package com.example.cdc.common.transform;

import com.example.cdc.common.event.CdcEvent;
import org.springframework.stereotype.Component;
import org.yaml.snakeyaml.Yaml;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Decompose TUSUARIO PG into the corresponding Oracle child table
 * (TESTUDIANTE / TFUNCIONARIO / TPADRE) based on the row's tipo_usuario.
 *
 * <p>Reverse of {@code tusuario/builder.py} (migration phase 1): where phase 1
 * consolidated three Oracle sources into one TUSUARIO row carrying the personal
 * data fields, this decomposer re-emits each TUSUARIO row into the Oracle child
 * table it originated from.
 *
 * <p>Routing driven by {@code tipo_usuario} (string: ESTUDIANTE / FUNCIONARIO /
 * PADRE). The YAML config ({@code tusuario-decompose.yaml}) declares the
 * {@code oracle_table}, {@code pk_column} and the list of personal data fields
 * to copy for each tipo.
 *
 * <p>The output map carries marker keys {@code ORACLE_TABLE}, {@code PK_COLUMN}
 * and {@code FK_TO_PARENT} so {@link com.example.cdc.worker.pipeline.OracleReverseStage}
 * can route the MERGE/DELETE to the correct child table keyed by the parent PK
 * (FK_TUSUARIO), since the child Oracle PK is generated by IDENTITY.
 */
@Component
public class TUsuarioDecomposer implements Transformer {

    private final Map<String, Decomposition> decompositions;

    public TUsuarioDecomposer() {
        try (InputStream in = getClass().getResourceAsStream("/transforms/tusuario-decompose.yaml")) {
            Map<String, Object> root = new Yaml().load(in);
            Map<String, Map<String, Object>> raw = (Map<String, Map<String, Object>>) root.get("decompositions");
            Map<String, Decomposition> parsed = new HashMap<>();
            for (Map.Entry<String, Map<String, Object>> e : raw.entrySet()) {
                Map<String, Object> cfg = e.getValue();
                parsed.put(e.getKey(), new Decomposition(
                        (String) cfg.get("oracle_table"),
                        (String) cfg.get("pk_column"),
                        (List<String>) cfg.get("copy_fields")
                ));
            }
            this.decompositions = parsed;
        } catch (Exception e) {
            throw new RuntimeException("Error cargando tusuario-decompose.yaml", e);
        }
    }

    /** Routing target for one {@code tipo_usuario} value. */
    public record Decomposition(String oracleTable, String pkColumn, List<String> copyFields) {}

    @Override
    public Optional<Map<String, Object>> apply(CdcEvent event, OperationContext ctx) {
        Map<String, Object> row = event.after() != null ? event.after() : event.before();
        if (row == null) return Optional.empty();

        Object tipoObj = row.get("tipo_usuario");
        if (tipoObj == null) return Optional.empty();
        String tipo = tipoObj.toString();
        Decomposition dec = decompositions.get(tipo);
        if (dec == null) {
            // Tipo desconocido → omitir
            return Optional.empty();
        }

        Map<String, Object> result = new HashMap<>();
        result.put("ORACLE_TABLE", dec.oracleTable());
        result.put("PK_COLUMN", dec.pkColumn());
        // FK_TO_PARENT indica la columna FK en la tabla hija Oracle que apunta
        // al PK de TUSUARIO. El reverse-stage hace MERGE/DELETE usando esta
        // columna como clave de match, porque el PK hijo es generado por
        // IDENTITY al INSERT y no se conoce de antemano.
        result.put("FK_TO_PARENT", "FK_TUSUARIO");
        // PK_TUSUARIO sirve como FK hacia la tabla hija Oracle; el PK hijo se
        // asignará por la secuencia IDENTITY correspondiente.
        for (String field : dec.copyFields()) {
            String keyLower = field.toLowerCase();
            if (row.containsKey(keyLower)) {
                result.put(field, row.get(keyLower));
            }
        }
        return Optional.of(result);
    }
}