-- ===========================================================================
-- 02_tests - Flujo de calificacion por instrumento (V227/V240/V241/V450/V469).
-- Requiere 01_seed.sql sobre el fixture de informes. Reutiliza los helpers
-- tstinf_assert / tstinf_sqlstate y la tabla informes_test_result.
--
-- Secciones:
--   A  calculo y persistencia por instrumento
--   B  lectura: listado de la actividad, detalle y resultado del instrumento
--   C  planilla del Planeador: homologacion, periodo, registrada, tendencia
--   D  planilla de informes: homologacion y resultado en celdas
--   E  proyeccion: cambia al re-calificar, antes y despues de consolidar
--   F  gates: asistencia, asignacion, rubrica incompleta, rango, bulk
--   G  instrumento OTRO: requiereArchivo / requiereTexto
-- ===========================================================================
\set ON_ERROR_STOP on

DROP TABLE IF EXISTS public.informes_test_result;
CREATE TABLE public.informes_test_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seccion TEXT, nombre TEXT, estado TEXT, esperado TEXT, obtenido TEXT, ref TEXT);

CREATE OR REPLACE FUNCTION public.tstinf_assert(
    p_sec TEXT, p_nom TEXT, p_ok BOOLEAN, p_esp TEXT DEFAULT NULL, p_obt TEXT DEFAULT NULL)
RETURNS VOID LANGUAGE SQL AS $$
    INSERT INTO public.informes_test_result (seccion, nombre, estado, esperado, obtenido)
    VALUES (p_sec, p_nom, CASE WHEN COALESCE(p_ok, FALSE) THEN 'PASS' ELSE 'FAIL' END, p_esp, p_obt);
$$;

CREATE OR REPLACE FUNCTION public.tstinf_sqlstate(p_sql TEXT)
RETURNS TEXT LANGUAGE plpgsql AS $$
BEGIN
    EXECUTE p_sql;
    RETURN 'OK';
EXCEPTION WHEN OTHERS THEN
    RETURN SQLSTATE;
END;
$$;

DO $t$
DECLARE
    fx JSONB; ids JSONB;
    gr BIGINT; asg BIGINT; pe1 BIGINT; pe2 BIGINT; m1 BIGINT; m2 BIGINT;
    a_rub BIGINT; a_cot BIGINT; a_escq BIGINT; a_escn BIGINT;
    ae BIGINT; n NUMERIC; t TEXT; b BOOLEAN; j JSONB; r RECORD;
    v_before NUMERIC; v_after NUMERIC; v_guardada NUMERIC;
    nsup BIGINT; a_otro BIGINT; tev BIGINT; m_cot BIGINT;
BEGIN
    SELECT JSONB_OBJECT_AGG(clave, valor) INTO fx  FROM public.informes_test_fixture;
    SELECT JSONB_OBJECT_AGG(clave, valor) INTO ids FROM public.calif_test_ids;
    gr := (fx->>'gr_601')::BIGINT; asg := (fx->>'asg_mat')::BIGINT;
    pe1 := (fx->>'pe1')::BIGINT; pe2 := (fx->>'pe2')::BIGINT;
    m1 := (fx->>'mat_e1')::BIGINT; m2 := (fx->>'mat_e2')::BIGINT;
    a_rub := (ids->>'TSTCAL RUBRICA')::BIGINT; a_cot := (ids->>'TSTCAL COTEJO')::BIGINT;
    a_escq := (ids->>'TSTCAL ESC CUAL')::BIGINT; a_escn := (ids->>'TSTCAL ESC NUM')::BIGINT;

    -- A ------------------------------------------------------------------
    FOR r IN SELECT * FROM (VALUES
        ('ae_rub_e1', 80.00), ('ae_rub_e2', 75.00), ('ae_cot_e1', 75.00), ('ae_cot_e2', 25.00),
        ('ae_escq_e1', 80.00), ('ae_escq_e2', 60.00),
        ('ae_escn_e1', 60.00), ('ae_escn_e2', 100.00), ('ae_escn_e3', 20.00)) v(k, esp)
    LOOP
        SELECT CALIFICACION INTO n FROM academico_test.TACTIVIDAD_NOTA
         WHERE FK_TACTIVIDAD_ESTUDIANTE = (ids->>r.k)::BIGINT AND ACTIVE;
        PERFORM public.tstinf_assert('A', r.k || ' guardada como % ' || r.esp, n = r.esp, r.esp::TEXT, n::TEXT);
    END LOOP;
    -- Escala numerica 1-5: 3.0 = 60 %, nunca 50 (V469).
    n := academico_test.fn_actividad_nota_calificar(1, (ids->>'ae_escn_e1')::BIGINT, '{"valorNumerico":4.5}', CURRENT_DATE);
    PERFORM public.tstinf_assert('A', 'escala numerica 4.5 en 1-5 -> 90 %', n = 90, '90', n::TEXT);
    SELECT COUNT(*) INTO n FROM academico_test.TACTIVIDAD_ESCALA_EVALUACION WHERE FK_TACTIVIDAD_ESTUDIANTE = (ids->>'ae_escn_e1')::BIGINT AND ACTIVE;
    PERFORM public.tstinf_assert('A', 're-calificar reemplaza la captura (1 fila activa)', n = 1, '1', n::TEXT);

    -- B ------------------------------------------------------------------
    SELECT nota_homologada, valoracion, formato_valor, resultado_instrumento INTO r
      FROM academico_test.fn_actividad_estudiantes_calificaciones_listar(1, a_escn, CURRENT_DATE, 'Sexto1');
    PERFORM public.tstinf_assert('B', 'listado: 90 % homologa a 4.50 en CINCO', r.nota_homologada = 4.50 AND r.formato_valor = 'CINCO', '4.50 CINCO', r.nota_homologada || ' ' || r.formato_valor);
    PERFORM public.tstinf_assert('B', 'listado: resultado numerico = valor digitado', r.resultado_instrumento->>'resumen' = '4.5', '4.5', r.resultado_instrumento->>'resumen');
    SELECT resultado_instrumento INTO j FROM academico_test.fn_actividad_estudiantes_calificaciones_listar(1, a_rub, CURRENT_DATE, 'Sexto1');
    PERFORM public.tstinf_assert('B', 'listado: rubrica con criterio: nivel', j->>'resumen' = 'Argumenta: Excelente · Presenta: Basico', 'Argumenta: Excelente · Presenta: Basico', j->>'resumen');
    SELECT resultado_instrumento INTO j FROM academico_test.fn_actividad_estudiantes_calificaciones_listar(1, a_cot, CURRENT_DATE, 'Sexto1');
    PERFORM public.tstinf_assert('B', 'listado: cotejo 2/3 items', (j->>'cumplidos')::INT = 2 AND (j->>'total')::INT = 3, '2/3', j->>'resumen');
    SELECT resultado_instrumento INTO j FROM academico_test.fn_actividad_estudiantes_calificaciones_listar(1, a_rub, CURRENT_DATE, 'Sexto3');
    PERFORM public.tstinf_assert('B', 'listado: sin captura -> resultado NULL', j IS NULL, 'NULL', j::TEXT);
    SELECT nota_homologada, valoracion, resultado_instrumento INTO r FROM academico_test.fn_actividad_nota_obtener(1, (ids->>'ae_escq_e1')::BIGINT);
    PERFORM public.tstinf_assert('B', 'detalle: escala cualitativa trae el nivel elegido', r.resultado_instrumento->>'nivel' = 'Sobresaliente' AND r.nota_homologada = 4.00, 'Sobresaliente 4.00', (r.resultado_instrumento->>'nivel') || ' ' || r.nota_homologada);

    -- C ------------------------------------------------------------------
    SELECT * INTO r FROM academico_test.fn_planilla_calificaciones_listar(1, gr, asg, NULL, NULL, NULL, NULL, 'Sexto1', 50, 0, NULL);
    PERFORM public.tstinf_assert('C', 'planilla planeador: periodo por defecto = el que contiene hoy (P2)', r.pk_tperiodo_evaluacion = pe2, pe2::TEXT, r.pk_tperiodo_evaluacion::TEXT);
    -- P2 de E1: A1 100 (pond 100) + 80/75/80/90 (pond 25) = (10000+8125)/200
    PERFORM public.tstinf_assert('C', 'planilla planeador: proyectada acotada a P2 (90.63), no mezcla P1/P3', r.definitiva_proyectada = 90.63, '90.63', r.definitiva_proyectada::TEXT);
    PERFORM public.tstinf_assert('C', 'planilla planeador: proyectada homologada 4.53 CINCO', r.definitiva_proyectada_homologada = 4.53 AND r.es_numerico, '4.53', r.definitiva_proyectada_homologada::TEXT);
    SELECT c INTO j FROM jsonb_array_elements(r.celdas) c WHERE (c->>'pkTactividad')::BIGINT = a_escq;
    PERFORM public.tstinf_assert('C', 'celda: notaHomologada + valoracion + resultadoInstrumento', (j->>'notaHomologada')::NUMERIC = 4.00 AND j->>'valoracion' IS NOT NULL AND j->'resultadoInstrumento'->>'resumen' = 'Sobresaliente', '4.00 / Sobresaliente', (j->>'notaHomologada') || ' / ' || (j->'resultadoInstrumento'->>'resumen'));
    SELECT definitiva_proyectada INTO n FROM academico_test.fn_planilla_calificaciones_listar(1, gr, asg, NULL, NULL, NULL, NULL, 'Sexto1', 50, 0, pe1);
    PERFORM public.tstinf_assert('C', 'planilla planeador: ?PERIODO=P1 -> 87 (cerrado)', n = 87, '87', n::TEXT);
    SELECT string_agg(c->>'estado', ',') INTO t FROM academico_test.fn_planilla_calificaciones_listar(1, gr, asg, NULL, NULL, NULL, NULL, 'Sexto4', 50, 0, NULL) p, jsonb_array_elements(p.celdas) c WHERE (c->>'pkTactividad')::BIGINT IN (a_rub, a_cot, a_escq, a_escn);
    PERFORM public.tstinf_assert('C', 'E4 no asignado -> NO_ASIGNADA en las 4', t = 'NO_ASIGNADA,NO_ASIGNADA,NO_ASIGNADA,NO_ASIGNADA', 'x4', t);

    -- D ------------------------------------------------------------------
    SELECT * INTO r FROM academico_test.fn_informe_planilla_listar(1, gr, asg, pe2, 'Sexto1');
    PERFORM public.tstinf_assert('D', 'planilla informes: proyectada = planeador (90.63)', r.definitiva_proyectada = 90.63, '90.63', r.definitiva_proyectada::TEXT);
    SELECT c INTO j FROM jsonb_array_elements(r.actividades) c WHERE (c->>'pkTactividad')::BIGINT = a_rub;
    PERFORM public.tstinf_assert('D', 'celda informes: nota 4.00 + resultadoInstrumento', (j->>'nota')::NUMERIC = 4.00 AND j->'resultadoInstrumento'->>'tipo' = 'RUBRICA', '4.00 RUBRICA', (j->>'nota') || ' ' || (j->'resultadoInstrumento'->>'tipo'));

    -- E ------------------------------------------------------------------
    SELECT n2.PK_TACTIVIDAD_ESCALA_NIVEL INTO nsup FROM academico_test.TACTIVIDAD_ESCALA_NIVEL n2 JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = n2.FK_TACTIVIDAD_ESCALA WHERE e.FK_TACTIVIDAD = a_escq AND n2.PONDERACION = 100;
    v_before := 90.63;
    PERFORM academico_test.fn_actividad_nota_calificar(1, (ids->>'ae_escq_e1')::BIGINT, jsonb_build_object('pkNivel', nsup), CURRENT_DATE);
    SELECT definitiva_proyectada INTO v_after FROM academico_test.fn_planilla_calificaciones_listar(1, gr, asg, NULL, NULL, NULL, NULL, 'Sexto1', 50, 0, NULL);
    PERFORM public.tstinf_assert('E', 'proyeccion sube al subir una nota (80->100 en ESC CUAL): 93.13', v_after = 93.13, '93.13', v_after::TEXT);
    SELECT nota_guardada INTO v_guardada FROM academico_test.fn_informe_planilla_guardar(1, gr, asg, pe2, ARRAY[m1]);
    PERFORM public.tstinf_assert('E', 'consolidar guarda la proyectada', v_guardada = 93.13, '93.13', v_guardada::TEXT);
    PERFORM academico_test.fn_actividad_nota_calificar(1, (ids->>'ae_escq_e1')::BIGINT, jsonb_build_object('pkNivel', (ids->>'nq_bas')::BIGINT), CURRENT_DATE);
    SELECT definitiva_proyectada, definitiva_registrada, tendencia INTO r FROM academico_test.fn_planilla_calificaciones_listar(1, gr, asg, NULL, NULL, NULL, NULL, 'Sexto1', 50, 0, NULL);
    PERFORM public.tstinf_assert('E', 'tras consolidar, la proyeccion sigue moviendose (88.13) y la registrada queda (93.13)', r.definitiva_proyectada = 88.13 AND r.definitiva_registrada = 93.13, '88.13 / 93.13', r.definitiva_proyectada || ' / ' || r.definitiva_registrada);
    PERFORM public.tstinf_assert('E', 'tendencia BAJA', r.tendencia = 'BAJA', 'BAJA', r.tendencia);
    SELECT estado_nota INTO t FROM academico_test.fn_informe_planilla_listar(1, gr, asg, pe2, 'Sexto1');
    PERFORM public.tstinf_assert('E', 'informes: estado cambio_propuesto', t = 'cambio_propuesto', 'cambio_propuesto', t);

    -- F ------------------------------------------------------------------
    ae := (ids->>'ae_escn_e2')::BIGINT;
    t := public.tstinf_sqlstate(format('SELECT academico_test.fn_actividad_nota_calificar(1,%s,''{"valorNumerico":4}'',CURRENT_DATE+1)', ae));
    PERFORM public.tstinf_assert('F', 'sin asistencia ese dia -> 22023', t = '22023', '22023', t);
    INSERT INTO academico_test.TASISTENCIA (FECHA, FK_TLV_TIPO_ASISTENCIA, FK_TASIGNATURA, FK_TPERIODO_EVALUACION, FK_TMATRICULA, CREATED_BY, CREATED_AT, ACTIVE)
    VALUES (CURRENT_DATE - 1, academico_test.fn_asistencia_tipo_pk(2), asg, pe2, m2, 'TSTCAL', CURRENT_TIMESTAMP, TRUE);
    t := public.tstinf_sqlstate(format('SELECT academico_test.fn_actividad_nota_calificar(1,%s,''{"valorNumerico":4}'',CURRENT_DATE-1)', ae));
    PERFORM public.tstinf_assert('F', 'inasistencia injustificada -> 22023', t = '22023', '22023', t);
    t := public.tstinf_sqlstate(format('SELECT academico_test.fn_actividad_nota_calificar(1,%s,''{"valorNumerico":6}'',CURRENT_DATE)', ae));
    PERFORM public.tstinf_assert('F', 'numerica fuera de rango -> 22023', t = '22023', '22023', t);
    t := public.tstinf_sqlstate(format('SELECT academico_test.fn_actividad_nota_calificar(1,%s,''{"niveles":[{"pkCriterio":%s,"pkNivel":%s}]}'',CURRENT_DATE)', (ids->>'ae_rub_e2')::BIGINT, (ids->>'crit1')::BIGINT, (ids->>'n1_alto')::BIGINT));
    PERFORM public.tstinf_assert('F', 'rubrica incompleta -> 22023', t = '22023', '22023', t);
    t := public.tstinf_sqlstate(format('SELECT academico_test.fn_actividad_nota_calificar_cotejo_bulk(1,%s,%s,''S'',ARRAY[%s]::BIGINT[],CURRENT_DATE)', a_cot, (ids->>'it1')::BIGINT, (ids->>'ae_rub_e1')::BIGINT));
    PERFORM public.tstinf_assert('F', 'bulk con estudiante de otra actividad -> 22023', t = '22023', '22023', t);
    SELECT COUNT(*) FILTER (WHERE calificacion_actualizada) AS act, COUNT(*) FILTER (WHERE calificacion IS NULL) AS nulos INTO r
      FROM academico_test.fn_actividad_nota_calificar_rubrica_bulk(1, a_rub, (ids->>'crit1')::BIGINT, (ids->>'n1_alto')::BIGINT,
           ARRAY(SELECT PK_TACTIVIDAD_ESTUDIANTE FROM academico_test.TACTIVIDAD_ESTUDIANTE WHERE FK_TACTIVIDAD = a_rub AND ACTIVE), CURRENT_DATE);
    PERFORM public.tstinf_assert('F', 'bulk rubrica: 2 actualizados, 1 incompleto en NULL', r.act = 2 AND r.nulos = 1, '2 / 1', r.act || ' / ' || r.nulos);

    -- G ------------------------------------------------------------------
    SELECT PK_LISTA_VALOR INTO m_cot FROM academico_test.TLISTA_VALOR WHERE CATEGORIA = 'INSTRUMENTO_EVALUACION' AND VALOR = 'LISTA_COTEJO' AND ACTIVE LIMIT 1;
    SELECT PK_LISTA_VALOR INTO tev   FROM academico_test.TLISTA_VALOR WHERE CATEGORIA = 'TIPO_EVIDENCIA_OTRO' AND ACTIVE ORDER BY 1 LIMIT 1;
    INSERT INTO academico_test.TACTIVIDAD (TITULO, FK_TASIGNATURA, FK_TGRUPO, FK_TLV_TIPO_ACTIVIDAD, FK_TLV_JERARQUIA, FK_TLV_INSTRUMENTO_EVALUACION, ES_EVALUATIVA, PONDERACION, FECHA_INICIO, FECHA_CIERRE, FECHA_CREACION, NOTA_MAXIMA, REQUIERE_ARCHIVO, REQUIERE_TEXTO, CREATED_BY, CREATED_AT, ACTIVE)
    SELECT 'TSTCAL OTRO', asg, gr, (fx->>'tipo_act')::BIGINT, (fx->>'jerarquia')::BIGINT, PK_LISTA_VALOR, 'S', 10, CURRENT_DATE, CURRENT_DATE, CURRENT_TIMESTAMP, 100, 'S', 'N', 'TSTCAL', CURRENT_TIMESTAMP, TRUE
      FROM academico_test.TLISTA_VALOR WHERE CATEGORIA = 'INSTRUMENTO_EVALUACION' AND VALOR = 'OTRO' AND ACTIVE LIMIT 1
    RETURNING PK_TACTIVIDAD INTO a_otro;
    SELECT definicion INTO j FROM academico_test.fn_actividad_instrumento_obtener(1, a_otro);
    PERFORM public.tstinf_assert('G', 'OTRO sin configurar ya devuelve requiereArchivo/requiereTexto', (j->>'requiereArchivo')::BOOLEAN AND NOT (j->>'requiereTexto')::BOOLEAN, 'true/false', (j->>'requiereArchivo') || '/' || (j->>'requiereTexto'));
    PERFORM academico_test.fn_actividad_instrumento_definir(1, a_otro, jsonb_build_object('tipoEvidencia', tev, 'metodoValoracion', m_cot, 'requiereArchivo', false, 'requiereTexto', true, 'definicion', jsonb_build_array(jsonb_build_object('descripcion', 'Entrega'))));
    SELECT definicion INTO j FROM academico_test.fn_actividad_instrumento_obtener(1, a_otro);
    PERFORM public.tstinf_assert('G', 'PUT booleanos -> GET los devuelve', NOT (j->>'requiereArchivo')::BOOLEAN AND (j->>'requiereTexto')::BOOLEAN, 'false/true', (j->>'requiereArchivo') || '/' || (j->>'requiereTexto'));
    PERFORM academico_test.fn_actividad_instrumento_definir(1, a_otro, jsonb_build_object('tipoEvidencia', tev, 'metodoValoracion', m_cot, 'requiereArchivo', 'S', 'definicion', jsonb_build_array(jsonb_build_object('descripcion', 'Entrega'))));
    SELECT REQUIERE_ARCHIVO || REQUIERE_TEXTO INTO t FROM academico_test.TACTIVIDAD WHERE PK_TACTIVIDAD = a_otro;
    PERFORM public.tstinf_assert('G', 'PUT con S y sin requiereTexto -> el ausente no se toca', t = 'SS', 'SS', t);
END
$t$;
