package com.co.eurekatic.auth.init;

import com.co.eurekatic.common.entity.User;
import com.co.eurekatic.common.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Da al seed admin su identidad en el módulo académico. El gate
 * {@code fn_puede_afectar_usuarios} ({@code fn_puede_afectar_sede} OR rol 9)
 * evalúa {@code academico_test.tsede_usuario.fk_tusuario} contra el
 * {@code public.users.id_user} que {@code FuncionarioRegistrationService}
 * propaga como {@code p_pk_usuario_solicitante}: sin esa fila el gate
 * devuelve FALSE y cada {@code /register/*} responde 403.
 *
 * <p>Por eso {@code pk_tusuario} se inserta explícitamente con el
 * {@code id_user} del admin ({@code GENERATED BY DEFAULT AS IDENTITY} lo
 * permite): son los dos extremos del mismo puente y la identity los
 * separaría.
 *
 * <p>Insertamos por JDBC directo (saltamos {@code fn_usu_crear} y
 * {@code fn_sede_usuario_crear}) porque el seed es bootstrap del sistema,
 * no una acción de usuario: no tiene sentido exigirle permisos a sí mismo
 * para existir.
 */
@Service
public class AdminAcademicIdentityBootstrap {

    private static final Logger log = LoggerFactory.getLogger(AdminAcademicIdentityBootstrap.class);

    /** Rol exclusivo de usuarios; el único que pasa el gate sin vínculo de sede. */
    private static final long ROL_USUARIOS = 9L;

    private static final String IDENTIFICACION_SEED = "ADMIN-SEED";
    private static final String CREATED_BY_SEED = "SEED";

    private final JdbcTemplate jdbc;
    private final UserRepository userRepository;

    public AdminAcademicIdentityBootstrap(JdbcTemplate jdbc, UserRepository userRepository) {
        this.jdbc = jdbc;
        this.userRepository = userRepository;
    }

    /**
     * Idempotente y reintentable: si una corrida anterior dejó la fila de
     * {@code public.users} sin su mitad académica, la siguiente la repara.
     * Nunca propaga fallos de seed faltante — el admin debe poder
     * autenticarse aunque el módulo académico esté vacío.
     */
    @Transactional
    public void bootstrapForSeedAdmin(String adminEmail) {
        Optional<User> admin = userRepository.findByEmail(adminEmail);
        if (admin.isEmpty()) {
            log.warn("Bootstrap académico: '{}' no tiene fila en public.users — nada que vincular", adminEmail);
            return;
        }
        long pkTusuario = admin.get().getId();

        if (gatePasses(pkTusuario)) {
            log.debug("Bootstrap académico: '{}' ya pasa fn_puede_afectar_usuarios — omitido", adminEmail);
            return;
        }

        Optional<String> occupant = firstResult(
                "SELECT cuenta FROM academico_test.tusuario WHERE pk_tusuario = ?",
                String.class, pkTusuario);
        if (occupant.isPresent() && !occupant.get().equalsIgnoreCase(adminEmail)) {
            log.error("Bootstrap académico omitido: pk_tusuario={} ya pertenece a la cuenta '{}', "
                            + "no a '{}'. Reconciliar manualmente antes de usar /register/*",
                    pkTusuario, occupant.get(), adminEmail);
            return;
        }

        Optional<Long> pkDeLaCuenta = firstResult(
                "SELECT pk_tusuario FROM academico_test.tusuario WHERE UPPER(cuenta) = UPPER(?)",
                Long.class, adminEmail);
        if (pkDeLaCuenta.isPresent() && pkDeLaCuenta.get().longValue() != pkTusuario) {
            log.error("Bootstrap académico omitido: la cuenta '{}' es pk_tusuario={} pero "
                            + "public.users.id_user={}. El gate exige que coincidan; reconciliar manualmente",
                    adminEmail, pkDeLaCuenta.get(), pkTusuario);
            return;
        }

        Optional<Long> tipoDocumento = firstActiveTlv("TIPO_DOCUMENTO");
        Optional<Long> genero = firstActiveTlv("GENERO");
        Optional<Long> jornada = firstActiveTlv("JORNADA");
        Optional<Long> sede = firstResult(
                "SELECT pk_tsede FROM academico_test.tsede WHERE active = TRUE "
                        + "ORDER BY pk_tsede LIMIT 1", Long.class);
        boolean rolExiste = !jdbc.queryForList(
                "SELECT 1 FROM academico_test.trol WHERE pk_trol = ? AND active = TRUE",
                Integer.class, ROL_USUARIOS).isEmpty();

        List<String> faltantes = new ArrayList<>();
        if (tipoDocumento.isEmpty()) faltantes.add("TLISTA_VALOR categoría TIPO_DOCUMENTO");
        if (genero.isEmpty()) faltantes.add("TLISTA_VALOR categoría GENERO");
        if (jornada.isEmpty()) faltantes.add("TLISTA_VALOR categoría JORNADA");
        if (sede.isEmpty()) faltantes.add("TSEDE activa");
        if (!rolExiste) faltantes.add("TROL " + ROL_USUARIOS);
        if (!faltantes.isEmpty()) {
            log.error("Bootstrap académico omitido para '{}': falta seed en academico_test -> {}. "
                            + "El admin puede autenticarse, pero /register/* responderá 403 hasta "
                            + "que se pueblen esas filas", adminEmail, faltantes);
            return;
        }

        jdbc.update("""
                INSERT INTO academico_test.tusuario (
                    pk_tusuario, cuenta, contrasena, estado, identificacion,
                    fk_tlv_tipo_documento, primer_nombre, primer_apellido,
                    fecha_nacimiento, fk_tlv_genero, correo_electronico,
                    created_by, active)
                VALUES (?, ?, 'N/A', 'A', ?, ?, 'Admin', 'Sistema',
                        DATE '1970-01-01', ?, ?, ?, TRUE)
                ON CONFLICT DO NOTHING
                """,
                pkTusuario, adminEmail, IDENTIFICACION_SEED, tipoDocumento.get(),
                genero.get(), adminEmail, CREATED_BY_SEED);

        jdbc.execute("""
                SELECT setval(
                    pg_get_serial_sequence('academico_test.tusuario', 'pk_tusuario'),
                    GREATEST(COALESCE((SELECT MAX(pk_tusuario) FROM academico_test.tusuario), 1), 1))
                """);

        jdbc.update("""
                INSERT INTO academico_test.tsede_usuario (
                    fk_tsede, fk_trol, fk_tusuario, fk_tlv_jornada,
                    orden, tlv_estado, predeterminado,
                    created_by, created_at, active)
                VALUES (?, ?, ?, ?, 1, 'ACTIVO', 1, ?, CURRENT_TIMESTAMP, TRUE)
                ON CONFLICT DO NOTHING
                """,
                sede.get(), ROL_USUARIOS, pkTusuario, jornada.get(), CREATED_BY_SEED);

        if (gatePasses(pkTusuario)) {
            log.info("Bootstrap académico: '{}' vinculado a TSEDE {} con rol {} (pk_tusuario={})",
                    adminEmail, sede.get(), ROL_USUARIOS, pkTusuario);
        } else {
            log.error("Bootstrap académico: '{}' sigue sin pasar fn_puede_afectar_usuarios "
                    + "tras insertar (pk_tusuario={}) — /register/* responderá 403", adminEmail, pkTusuario);
        }
    }

    private boolean gatePasses(long pkTusuario) {
        return Boolean.TRUE.equals(jdbc.queryForObject(
                "SELECT academico_test.fn_puede_afectar_usuarios(?)", Boolean.class, pkTusuario));
    }

    private Optional<Long> firstActiveTlv(String categoria) {
        return firstResult("SELECT pk_lista_valor FROM academico_test.tlista_valor "
                        + "WHERE categoria = ? AND active = TRUE ORDER BY pk_lista_valor LIMIT 1",
                Long.class, categoria);
    }

    private <T> Optional<T> firstResult(String sql, Class<T> type, Object... args) {
        List<T> rows = jdbc.queryForList(sql, type, args);
        return rows.isEmpty() ? Optional.empty() : Optional.ofNullable(rows.get(0));
    }
}
