-- file-service dejaba de poder escribir la referencia del archivo (pk) en
-- ningún otro sitio que academico_test.tarchivo -- el schema era
-- configurable por despliegue (files.schema) pero la TABLA siempre era
-- "tarchivo", igual para toda subida sin importar qué query-service la
-- sirviera.
--
-- Esta migración deja que cada instancia de query-service (una fila
-- MICROSERVICE con kind='QUERY' -- la misma que ya declara su propia
-- conexión: DIALECT/JDBCURL/DBUSERNAME/INSTANCENAME) declare, opcionalmente,
-- su propio schema.tabla para guardar esa referencia -- con el mismo
-- formato de columnas que academico_test.tarchivo (ver
-- fn_validar_tabla_archivo). Vive en MICROSERVICE y no en QUERY a propósito:
-- el destino tiene que ver con la CONEXIÓN que ese query-service ya
-- declara, no con cada fila de query individual -- se configura una sola
-- vez al dar de alta el query-service y todas sus queries lo heredan. Los
-- endpoints (auth-center, etc.) no se tocan: siguen siempre en
-- academico_test.tarchivo.
--
-- pk_tarchivo puede terminar en cualquiera de esas tablas, pero
-- DownloadController y compañía sólo reciben el id (nunca el destino) para
-- servir/consultar un archivo -- por eso hace falta un registro GLOBAL de
-- "este pk vive en esta tabla" (file_reference_location) y una secuencia
-- COMPARTIDA (seq_pk_tarchivo) para que el id siga siendo único sin
-- importar en qué tabla haya terminado la fila.

-- 1. Secuencia compartida. Arranca después del máximo pk_tarchivo actual
--    para no colisionar con las filas que ya existen.
CREATE SEQUENCE IF NOT EXISTS public.seq_pk_tarchivo;
SELECT setval('public.seq_pk_tarchivo',
              GREATEST((SELECT COALESCE(MAX(pk_tarchivo), 0) FROM academico_test.tarchivo), 1));

-- TARCHIVO.pk_tarchivo era "GENERATED BY DEFAULT AS IDENTITY" (V22): un
-- identity BY DEFAULT ya admite valores explícitos en el INSERT sin
-- OVERRIDING SYSTEM VALUE, así que file-service podría seguir insertando
-- pk_tarchivo a mano sin tocar esto. Pero dejar el identity original
-- generando en paralelo es una fuga de colisión esperando a pasar -- el
-- día que alguien inserte sin pk explícito (una migración, un backfill
-- manual), su identity puede repetir un valor que la secuencia
-- compartida ya entregó a OTRA tabla. Se reemplaza por un DEFAULT sobre
-- la misma secuencia compartida: mismo comportamiento para quien no
-- manda pk_tarchivo, mismo espacio de ids que todo lo demás.
ALTER TABLE academico_test.tarchivo ALTER COLUMN pk_tarchivo DROP IDENTITY IF EXISTS;
ALTER TABLE academico_test.tarchivo ALTER COLUMN pk_tarchivo SET DEFAULT nextval('public.seq_pk_tarchivo');

-- 2. Registro global: en qué tabla vive cada pk_tarchivo. file-service lo
--    escribe en el mismo INSERT que reserva la fila real (ver
--    ArchivoRepository#reservar) y lo consulta en cada operación
--    posterior (registrarUrl/activar/descartar/buscarActivo...) para
--    saber a qué tabla apuntar sin que el llamante tenga que volver a
--    decírselo.
CREATE TABLE IF NOT EXISTS public.file_reference_location (
    pk_tarchivo  bigint PRIMARY KEY,
    schema_name  text NOT NULL,
    table_name   text NOT NULL,
    urls3        text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.file_reference_location IS
    'file-service: en qué schema.tabla vive cada pk_tarchivo -- necesario '
    'porque distintos query-services pueden declarar distintas tablas de '
    'destino (microservice.file_storage_schema/table) y los endpoints de '
    'descarga sólo reciben el id, nunca el destino.';

-- Backfill: todo lo que ya existía en academico_test.tarchivo vivía (y
-- sigue viviendo) ahí.
INSERT INTO public.file_reference_location (pk_tarchivo, schema_name, table_name, urls3)
SELECT pk_tarchivo, 'academico_test', 'tarchivo', urls3
  FROM academico_test.tarchivo
ON CONFLICT (pk_tarchivo) DO NOTHING;

-- 3. Catálogo: dónde debe guardar file-service la referencia para las
--    queries de ESTE query-service. NULL en ambas (el default) =
--    comportamiento de siempre (academico_test.tarchivo -- ver
--    files.schema en file-service).
ALTER TABLE MICROSERVICE ADD COLUMN IF NOT EXISTS FILE_STORAGE_SCHEMA text;
ALTER TABLE MICROSERVICE ADD COLUMN IF NOT EXISTS FILE_STORAGE_TABLE  text;

ALTER TABLE MICROSERVICE DROP CONSTRAINT IF EXISTS microservice_file_storage_ambos_o_ninguno;
ALTER TABLE MICROSERVICE ADD CONSTRAINT microservice_file_storage_ambos_o_ninguno
    CHECK ((FILE_STORAGE_SCHEMA IS NULL) = (FILE_STORAGE_TABLE IS NULL));

-- Sólo tiene sentido para una fila con conexión propia (kind=QUERY) --
-- una fila REST no tiene ni base de datos que file-service pudiera usar.
ALTER TABLE MICROSERVICE DROP CONSTRAINT IF EXISTS microservice_file_storage_solo_query;
ALTER TABLE MICROSERVICE ADD CONSTRAINT microservice_file_storage_solo_query
    CHECK (FILE_STORAGE_SCHEMA IS NULL OR KIND = 'QUERY');

COMMENT ON COLUMN MICROSERVICE.FILE_STORAGE_SCHEMA IS
    'Override opcional (sólo kind=QUERY): schema donde file-service debe '
    'guardar la referencia (pk) de los archivos subidos por las queries de '
    'este query-service. NULL = usa el default del servicio '
    '(academico_test.tarchivo).';
COMMENT ON COLUMN MICROSERVICE.FILE_STORAGE_TABLE IS
    'Tabla del override anterior. Debe tener el mismo formato de columnas '
    'que academico_test.tarchivo -- ver fn_validar_tabla_archivo, que lo '
    'exige antes de dejar guardar la fila.';

-- 4. Validación de forma: si alguien declara un schema.tabla que no
--    tiene las columnas que ArchivoRepository necesita, mejor fallar al
--    guardar el microservicio que al primer intento de subida -- ese
--    error llegaría mucho después, como un 500 confuso de columna
--    inexistente.
CREATE OR REPLACE FUNCTION public.fn_validar_tabla_archivo(p_schema text, p_tabla text)
RETURNS void AS $$
DECLARE
    v_faltantes text;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables t
         WHERE t.table_schema = p_schema AND t.table_name = p_tabla
    ) THEN
        RAISE EXCEPTION 'file_storage: la tabla %.% no existe', p_schema, p_tabla;
    END IF;

    SELECT string_agg(col, ', ')
      INTO v_faltantes
      FROM unnest(ARRAY['pk_tarchivo', 'nombre', 'peso', 'etiqueta', 'fecha',
                         'created_by', 'created_at', 'modified_at', 'active',
                         'urls3']) AS col
     WHERE NOT EXISTS (
         SELECT 1 FROM information_schema.columns c
          WHERE c.table_schema = p_schema AND c.table_name = p_tabla
            AND c.column_name = col
     );

    IF v_faltantes IS NOT NULL THEN
        RAISE EXCEPTION 'file_storage: %.% no tiene el formato de academico_test.tarchivo -- faltan columnas: %',
            p_schema, p_tabla, v_faltantes;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.fn_microservice_validar_file_storage()
RETURNS trigger AS $$
BEGIN
    IF NEW.file_storage_schema IS NOT NULL THEN
        PERFORM public.fn_validar_tabla_archivo(NEW.file_storage_schema, NEW.file_storage_table);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_microservice_validar_file_storage ON MICROSERVICE;
CREATE TRIGGER trg_microservice_validar_file_storage
    BEFORE INSERT OR UPDATE OF file_storage_schema, file_storage_table ON MICROSERVICE
    FOR EACH ROW EXECUTE FUNCTION public.fn_microservice_validar_file_storage();
