-- Implementa los endpoints de "PIGSE-Endpoints.postman_collection.json"
-- (Gestión Documental institucional + Monitoreo y Cumplimiento) contra
-- academico_test -- el microservicio pigse (V148) pasa a apuntar ahí en
-- vez de a su propio schema aislado.
--
-- Desviaciones deliberadas respecto a la colección:
--   * DELETE /documentos/:tipo -> PATCH. ck_query_http_method sólo admite
--     GET/POST/PUT/PATCH (Query.httpMethod excluye DELETE a propósito,
--     ver su javadoc: "evita que una URL sugiera un borrado directo
--     sobre tablas"). El front tiene que pedir PATCH, no DELETE.
--   * :tipo en minúscula -> :TIPO. ParamNamespace exige
--     [A-Z][A-Z0-9_]* para cualquier variable de ruta.
--
-- Regla de negocio PEI/PEC/PMI (confirmada por el usuario):
--   * PEI y PEC son EXCLUYENTES -- un EE necesita uno u otro, nunca los
--     dos. Se resuelve por TESTABLECIMIENTO.ETNIAS: 'S' (etnoeducativo)
--     -> aplica PEC, PEI queda NO_APLICA; 'N' -> aplica PEI, PEC queda
--     NO_APLICA.
--   * PMI siempre aplica, para cualquier EE.
--   * globalProgress excluye del denominador los documentos NO_APLICA.

-- 1. Tablas -- mismo formato TXXX de siempre, FK a TESTABLECIMIENTO y
--    al TARCHIVO real de academico_test (no al pigse.tarchivo de V148:
--    ver el punto 2 más abajo, el bind pasa a apuntar acá).
CREATE TABLE IF NOT EXISTS academico_test.tdocumento_institucional (
    pk_documento_institucional BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_testablecimiento        BIGINT NOT NULL,
    tipo                       VARCHAR(10) NOT NULL,
    fk_tarchivo                BIGINT,
    created_by                 VARCHAR(120) NOT NULL,
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_by                VARCHAR(120),
    modified_at                TIMESTAMP,
    active                     BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT tdocumento_institucional_pk PRIMARY KEY (pk_documento_institucional),
    CONSTRAINT tdocumento_institucional_tipo_chk CHECK (tipo IN ('PEI', 'PEC', 'PMI')),
    CONSTRAINT fk_tdocumento_inst_testablec FOREIGN KEY (fk_testablecimiento)
        REFERENCES academico_test.testablecimiento (pk_establecimiento),
    CONSTRAINT fk_tdocumento_inst_tarchivo FOREIGN KEY (fk_tarchivo)
        REFERENCES academico_test.tarchivo (pk_tarchivo)
);

-- Un documento VIGENTE por EE+tipo -- reemplazar es UPDATE, no un
-- segundo INSERT (ver fn_pigse_documento_guardar).
CREATE UNIQUE INDEX IF NOT EXISTS uq_tdocumento_inst_ee_tipo
    ON academico_test.tdocumento_institucional (fk_testablecimiento, tipo)
    WHERE active = true;

CREATE TABLE IF NOT EXISTS academico_test.tdocumento_institucional_hist (
    pk_documento_institucional_hist BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_documento_institucional       BIGINT NOT NULL,
    fk_tarchivo                      BIGINT NOT NULL,
    reemplazado_by                   VARCHAR(120) NOT NULL,
    reemplazado_at                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT tdoc_inst_hist_pk PRIMARY KEY (pk_documento_institucional_hist),
    CONSTRAINT fk_tdoc_inst_hist_doc FOREIGN KEY (fk_documento_institucional)
        REFERENCES academico_test.tdocumento_institucional (pk_documento_institucional),
    CONSTRAINT fk_tdoc_inst_hist_archivo FOREIGN KEY (fk_tarchivo)
        REFERENCES academico_test.tarchivo (pk_tarchivo)
);

COMMENT ON TABLE academico_test.tdocumento_institucional IS
    'PIGSE — documento institucional vigente por establecimiento y tipo (PEI/PEC/PMI). fk_tarchivo NULL = PENDIENTE.';
COMMENT ON TABLE academico_test.tdocumento_institucional_hist IS
    'PIGSE — versiones reemplazadas (upload nuevo) o retiradas (PATCH .../:TIPO) de un documento institucional.';

-- 2. El bind de pigse pasa a apuntar a la BD normal del SSO, schema
--    academico_test -- no al schema pigse aislado de V148 (que queda
--    sin usar; academico_test.tarchivo es donde termina la referencia
--    real de cada archivo subido por estas queries).
UPDATE microservice
   SET file_storage_schema = 'academico_test',
       file_storage_table  = 'tarchivo',
       requesturi          = '/api/pigse/**'
 WHERE serviceid = 'pigse';

-- 3. Roles que faltan del catálogo de la colección Postman (id 1..4).
--    PIGSE-RECTOR ya existía (V148); Administrador/Secretario/a/
--    Secretaria Territorial son nuevos.
INSERT INTO role (name, description)
SELECT v.name, v.description
  FROM (VALUES
    ('PIGSE-ADMINISTRADOR',          'Administrador (PIGSE)'),
    ('PIGSE-SECRETARIO',             'Secretario/a (PIGSE)'),
    ('PIGSE-SECRETARIA_TERRITORIAL', 'Secretaria Territorial (PIGSE)')
  ) AS v(name, description)
 WHERE NOT EXISTS (SELECT 1 FROM role r WHERE r.name = v.name);

INSERT INTO role_app (id_app, id_role)
SELECT a.id_app, r.id_role
  FROM app a
  JOIN role r ON r.name IN (
       'PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIO', 'PIGSE-SECRETARIA_TERRITORIAL')
 WHERE a.name = 'PIGSE'
   AND NOT EXISTS (SELECT 1 FROM role_app ra WHERE ra.id_app = a.id_app AND ra.id_role = r.id_role);

-- 4. Rutas del menú (para GET /api/pigse/my-menus, ver punto 6) --
--    visibilidad por rol según la cabecera de la colección.
INSERT INTO route (name, icon, path, menuorder, type)
SELECT v.name, v.icon, v.path, v.menuorder, v.type
  FROM (VALUES
    ('Gestión Documental',        'folder',  '/gestion-documental',     1, NULL),
    ('Monitoreo y Cumplimiento',  'chart',   '/monitoreo-cumplimiento', 2, NULL)
  ) AS v(name, icon, path, menuorder, type)
 WHERE NOT EXISTS (SELECT 1 FROM route WHERE name = v.name AND path = v.path);

INSERT INTO app_route (id_app, id_route)
SELECT a.id_app, r.id_route
  FROM app a
  JOIN route r ON r.path IN ('/gestion-documental', '/monitoreo-cumplimiento')
 WHERE a.name = 'PIGSE'
   AND NOT EXISTS (SELECT 1 FROM app_route ar WHERE ar.id_app = a.id_app AND ar.id_route = r.id_route);

-- Gestión Documental: Administrador, Rector, Secretario/a (NO Secretaria Territorial).
INSERT INTO role_route (route_id, role_id)
SELECT r.id_route, ro.id_role
  FROM route r
 CROSS JOIN role ro
 WHERE r.path = '/gestion-documental'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-RECTOR', 'PIGSE-SECRETARIO')
   AND NOT EXISTS (SELECT 1 FROM role_route rr WHERE rr.route_id = r.id_route AND rr.role_id = ro.id_role);

-- Monitoreo y Cumplimiento: Administrador, Secretaria Territorial (NO Rector/Secretario).
INSERT INTO role_route (route_id, role_id)
SELECT r.id_route, ro.id_role
  FROM route r
 CROSS JOIN role ro
 WHERE r.path = '/monitoreo-cumplimiento'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIA_TERRITORIAL')
   AND NOT EXISTS (SELECT 1 FROM role_route rr WHERE rr.route_id = r.id_route AND rr.role_id = ro.id_role);

-- 5. Funciones PL/pgSQL -- mismo patrón que fn_est_crear (V53):
--    "SELECT schema.fn_x(...)" es la query que se guarda en el
--    catálogo; la función hace el trabajo real (incluida cualquier
--    escritura) y el statement que ve query-service sigue siendo un
--    SELECT.

-- Establecimiento del usuario autenticado -- mismo join que
-- FileDestinationAccessService#establecimientoDelUsuario (file-service,
-- V66), acá en SQL porque estas queries lo necesitan del lado del
-- catálogo, no de file-service. A diferencia de esa versión (que
-- devuelve Optional.empty() en la ambigüedad), acá se hace RAISE
-- EXCEPTION -- no hay "ruta feliz sin establecimiento" para un
-- endpoint de negocio como éste.
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_mi_establecimiento(p_email TEXT)
RETURNS BIGINT AS $$
DECLARE
    v_pk    BIGINT;
    v_count INT;
BEGIN
    SELECT COUNT(DISTINCT te.pk_establecimiento), MIN(te.pk_establecimiento)
      INTO v_count, v_pk
      FROM academico_test.tusuario t
      JOIN academico_test.tsede_usuario su ON su.fk_tusuario = t.pk_tusuario
      JOIN academico_test.tsede s ON s.pk_tsede = su.fk_tsede
      JOIN academico_test.testablecimiento te ON te.pk_establecimiento = s.fk_testablecimiento
     WHERE upper(t.cuenta) = upper(p_email)
       AND t.active AND su.active AND su.tlv_estado = 'ACTIVO' AND s.active AND te.active;

    IF v_count IS NULL OR v_count <> 1 THEN
        RAISE EXCEPTION 'pigse: % no está vinculado a exactamente un establecimiento (encontrados: %)',
            p_email, COALESCE(v_count, 0);
    END IF;
    RETURN v_pk;
END;
$$ LANGUAGE plpgsql STABLE;

-- Documentos (PEI/PEC/PMI) de un EE, con status COMPLETO/PENDIENTE/
-- NO_APLICA -- ver la regla de exclusión PEI<->PEC al inicio del
-- archivo. Reusada por "documentos" (GET) y por cumplimiento/listar.
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_documentos_listar(p_fk_establecimiento BIGINT)
RETURNS TABLE (
    id           TEXT,
    "type"       TEXT,
    "typeName"   TEXT,
    status       TEXT,
    "fileName"   TEXT,
    "uploadedAt" TIMESTAMP,
    "sizeBytes"  BIGINT
) AS $$
    SELECT
        tipos.tipo AS id,
        tipos.tipo AS "type",
        tipos.nombre AS "typeName",
        CASE
            WHEN tipos.tipo = 'PEI' AND te.etnias = 'S' THEN 'NO_APLICA'
            WHEN tipos.tipo = 'PEC' AND te.etnias = 'N' THEN 'NO_APLICA'
            WHEN d.fk_tarchivo IS NOT NULL THEN 'COMPLETO'
            ELSE 'PENDIENTE'
        END AS status,
        ta.nombre AS "fileName",
        ta.created_at AS "uploadedAt",
        ta.peso AS "sizeBytes"
      FROM academico_test.testablecimiento te
     CROSS JOIN (VALUES
                    ('PEI', 'Proyecto Educativo Institucional (PEI)'),
                    ('PEC', 'Proyecto Educativo Comunitario (PEC)'),
                    ('PMI', 'Plan de Mejoramiento Institucional (PMI)')
                ) AS tipos(tipo, nombre)
      LEFT JOIN academico_test.tdocumento_institucional d
             ON d.fk_testablecimiento = te.pk_establecimiento
            AND d.tipo = tipos.tipo
            AND d.active
      LEFT JOIN academico_test.tarchivo ta ON ta.pk_tarchivo = d.fk_tarchivo
     WHERE te.pk_establecimiento = p_fk_establecimiento
     ORDER BY tipos.tipo;
$$ LANGUAGE sql STABLE;

-- Sube (o reemplaza) el documento vigente de un EE+tipo. Reemplazar
-- es UPDATE de la fila vigente + INSERT en el histórico con el
-- fk_tarchivo saliente -- nunca un segundo INSERT en
-- tdocumento_institucional (el índice único ee+tipo activo lo
-- impediría igual).
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_documento_guardar(
    p_pk_usuario   BIGINT,
    p_email        VARCHAR,
    p_tipo         VARCHAR,
    p_fk_tarchivo  BIGINT
)
RETURNS TABLE (
    id           TEXT,
    "type"       TEXT,
    "typeName"   TEXT,
    status       TEXT,
    "fileName"   TEXT,
    "uploadedAt" TIMESTAMP,
    "sizeBytes"  BIGINT
) AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo  BIGINT;
BEGIN
    IF p_fk_tarchivo IS NULL THEN
        RAISE EXCEPTION 'pigse: p_fk_tarchivo es obligatorio (archivo no subido)';
    END IF;

    v_fk_establecimiento := academico_test.fn_pigse_mi_establecimiento(p_email);

    SELECT pk_documento_institucional, fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM academico_test.tdocumento_institucional
     WHERE fk_testablecimiento = v_fk_establecimiento AND tipo = p_tipo AND active;

    IF v_pk_doc IS NULL THEN
        INSERT INTO academico_test.tdocumento_institucional
            (fk_testablecimiento, tipo, fk_tarchivo, created_by)
        VALUES (v_fk_establecimiento, p_tipo, p_fk_tarchivo, p_email)
        RETURNING pk_documento_institucional INTO v_pk_doc;
    ELSE
        UPDATE academico_test.tdocumento_institucional
           SET fk_tarchivo = p_fk_tarchivo, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
         WHERE pk_documento_institucional = v_pk_doc;

        IF v_fk_tarchivo_previo IS NOT NULL THEN
            INSERT INTO academico_test.tdocumento_institucional_hist
                (fk_documento_institucional, fk_tarchivo, reemplazado_by)
            VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);
        END IF;
    END IF;

    RETURN QUERY
    SELECT * FROM academico_test.fn_pigse_documentos_listar(v_fk_establecimiento)
     WHERE fn_pigse_documentos_listar.id = p_tipo;
END;
$$ LANGUAGE plpgsql;

-- Retira la versión vigente (vuelve a PENDIENTE) -- NO borra el
-- archivo físico ni la fila de TARCHIVO, sólo desvincula y deja
-- rastro en el histórico (misma tabla que usa un reemplazo por
-- upload). Ver javadoc de ArchivoRepository#descartar en file-service
-- para el motivo equivalente del lado de S3: nunca borrar en el
-- camino feliz, sólo dejar de referenciar.
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_documento_eliminar(
    p_pk_usuario BIGINT,
    p_email      VARCHAR,
    p_tipo       VARCHAR
)
RETURNS TABLE (
    id           TEXT,
    "type"       TEXT,
    "typeName"   TEXT,
    status       TEXT,
    "fileName"   TEXT,
    "uploadedAt" TIMESTAMP,
    "sizeBytes"  BIGINT
) AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo BIGINT;
BEGIN
    v_fk_establecimiento := academico_test.fn_pigse_mi_establecimiento(p_email);

    SELECT pk_documento_institucional, fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM academico_test.tdocumento_institucional
     WHERE fk_testablecimiento = v_fk_establecimiento AND tipo = p_tipo AND active;

    IF v_pk_doc IS NULL OR v_fk_tarchivo_previo IS NULL THEN
        RAISE EXCEPTION 'pigse: tipo % desconocido o ya está PENDIENTE para este establecimiento', p_tipo
            USING ERRCODE = 'P0002';
    END IF;

    UPDATE academico_test.tdocumento_institucional
       SET fk_tarchivo = NULL, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
     WHERE pk_documento_institucional = v_pk_doc;

    INSERT INTO academico_test.tdocumento_institucional_hist
        (fk_documento_institucional, fk_tarchivo, reemplazado_by)
    VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);

    RETURN QUERY
    SELECT * FROM academico_test.fn_pigse_documentos_listar(v_fk_establecimiento)
     WHERE fn_pigse_documentos_listar.id = p_tipo;
END;
$$ LANGUAGE plpgsql;

-- Métricas globales del tablero de cumplimiento -- una sola fila,
-- cada tipo como sub-objeto JSON (mismo shape que espera el front).
-- Denominador de "total" excluye NO_APLICA por tipo (regla PEI<->PEC).
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_cumplimiento_metricas()
RETURNS TABLE (
    "totalEstablishments" BIGINT,
    pei                   JSONB,
    pec                   JSONB,
    pmi                   JSONB
) AS $$
    WITH ee AS (
        SELECT pk_establecimiento, etnias FROM academico_test.testablecimiento WHERE active
    ),
    docs AS (
        SELECT ee.pk_establecimiento,
               d.tipo,
               d.fk_tarchivo IS NOT NULL AS completo
          FROM ee
          LEFT JOIN academico_test.tdocumento_institucional d
                 ON d.fk_testablecimiento = ee.pk_establecimiento AND d.active
    )
    SELECT
        (SELECT count(*) FROM ee) AS "totalEstablishments",
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PEI' AND docs.completo),
            'total',     count(*) FILTER (WHERE ee.etnias = 'N'),
            'percent',   CASE WHEN count(*) FILTER (WHERE ee.etnias = 'N') = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PEI' AND docs.completo)
                                         / count(*) FILTER (WHERE ee.etnias = 'N'))
                          END
        ) AS pei,
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PEC' AND docs.completo),
            'total',     count(*) FILTER (WHERE ee.etnias = 'S'),
            'percent',   CASE WHEN count(*) FILTER (WHERE ee.etnias = 'S') = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PEC' AND docs.completo)
                                         / count(*) FILTER (WHERE ee.etnias = 'S'))
                          END
        ) AS pec,
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PMI' AND docs.completo),
            'total',     (SELECT count(*) FROM ee),
            'percent',   CASE WHEN (SELECT count(*) FROM ee) = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PMI' AND docs.completo)
                                         / (SELECT count(*) FROM ee))
                          END
        ) AS pmi
      FROM ee
      LEFT JOIN docs ON docs.pk_establecimiento = ee.pk_establecimiento;
$$ LANGUAGE sql STABLE;

-- Detalle por establecimiento -- mismos status que fn_pigse_documentos_listar,
-- pivotados de 3 filas (PEI/PEC/PMI) a 3 columnas JSON.
-- globalProgress excluye NO_APLICA del denominador (PMI siempre cuenta;
-- de PEI/PEC sólo el que aplica para ese EE, ver la regla de exclusión
-- al inicio del archivo).
CREATE OR REPLACE FUNCTION academico_test.fn_pigse_cumplimiento_listar()
RETURNS TABLE (
    id                  BIGINT,
    "establishmentName" TEXT,
    pei                 JSONB,
    pec                 JSONB,
    pmi                 JSONB,
    "globalProgress"    INT
) AS $$
    SELECT
        te.pk_establecimiento AS id,
        te.nombre AS "establishmentName",
        jsonb_build_object('status', d_pei.status, 'fileName', d_pei."fileName") AS pei,
        jsonb_build_object('status', d_pec.status, 'fileName', d_pec."fileName") AS pec,
        jsonb_build_object('status', d_pmi.status, 'fileName', d_pmi."fileName") AS pmi,
        CASE
            WHEN (CASE WHEN d_pei.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                  + CASE WHEN d_pec.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                  + CASE WHEN d_pmi.status <> 'NO_APLICA' THEN 1 ELSE 0 END) = 0 THEN 0
            ELSE round(
                100.0 * (
                    CASE WHEN d_pei.status = 'COMPLETO' THEN 1 ELSE 0 END
                    + CASE WHEN d_pec.status = 'COMPLETO' THEN 1 ELSE 0 END
                    + CASE WHEN d_pmi.status = 'COMPLETO' THEN 1 ELSE 0 END
                ) / (
                    CASE WHEN d_pei.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                    + CASE WHEN d_pec.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                    + CASE WHEN d_pmi.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                )
            )
        END AS "globalProgress"
      FROM academico_test.testablecimiento te
      JOIN LATERAL (
              SELECT * FROM academico_test.fn_pigse_documentos_listar(te.pk_establecimiento) WHERE id = 'PEI'
          ) d_pei ON true
      JOIN LATERAL (
              SELECT * FROM academico_test.fn_pigse_documentos_listar(te.pk_establecimiento) WHERE id = 'PEC'
          ) d_pec ON true
      JOIN LATERAL (
              SELECT * FROM academico_test.fn_pigse_documentos_listar(te.pk_establecimiento) WHERE id = 'PMI'
          ) d_pmi ON true
     WHERE te.active
     ORDER BY te.nombre;
$$ LANGUAGE sql STABLE;

-- 6. Catálogo -- una fila `query` por endpoint de la colección,
--    atada al microservicio pigse. execution_mode SELECT en todas
--    (incluidas las que escriben): "SELECT schema.fn_x(...)" es un
--    SELECT statement aunque fn_x haga INSERT/UPDATE por dentro --
--    mismo patrón que fn_est_crear/fn_est_actualizar (V64).
--
--    :CONTEXT.EMAIL / :CONTEXT.USER_ID son system-bound (vienen del
--    JWT verificado, ver ParamNamespace) -- no necesitan entrada en
--    param_types.
INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-documentos-listar',
       $q$SELECT * FROM academico_test.fn_pigse_documentos_listar(
              academico_test.fn_pigse_mi_establecimiento(:CONTEXT.EMAIL))$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos', 'SELECT', 'GET', '{}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-documentos-listar');

INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-documentos-upload',
       $q$SELECT * FROM academico_test.fn_pigse_documento_guardar(
              p_pk_usuario   => public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
              p_email        => CAST(:CONTEXT.EMAIL AS VARCHAR),
              p_tipo         => CAST(:BODY.TIPO AS VARCHAR),
              p_fk_tarchivo  => CAST(:BODY.ARCHIVO AS BIGINT)
          )$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/upload', 'SELECT', 'POST',
       '{"BODY.TIPO": "TEXT!", "BODY.ARCHIVO": "FILE:documentoInstitucional!"}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-documentos-upload');

-- DELETE -> PATCH: ver la nota de desviaciones al inicio del archivo.
INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-documentos-eliminar',
       $q$SELECT * FROM academico_test.fn_pigse_documento_eliminar(
              p_pk_usuario => public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
              p_email      => CAST(:CONTEXT.EMAIL AS VARCHAR),
              p_tipo       => CAST(:PARAM.TIPO AS VARCHAR)
          )$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/:TIPO', 'SELECT', 'PATCH',
       '{"PARAM.TIPO": "TEXT"}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-documentos-eliminar');

INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-cumplimiento-metricas',
       $q$SELECT * FROM academico_test.fn_pigse_cumplimiento_metricas()$q$,
       'postgres', false, false, m.id_microservice,
       '/cumplimiento/metricas', 'SELECT', 'GET', '{}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-cumplimiento-metricas');

INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-cumplimiento-listar',
       $q$SELECT * FROM academico_test.fn_pigse_cumplimiento_listar()$q$,
       'postgres', false, false, m.id_microservice,
       '/cumplimiento/listar', 'SELECT', 'GET', '{}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-cumplimiento-listar');

INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-establecimientos',
       $q$SELECT pk_establecimiento AS id, nombre AS "establishmentName", codigo AS codigo
            FROM academico_test.testablecimiento
           WHERE active
           ORDER BY nombre$q$,
       'postgres', false, false, m.id_microservice,
       '/establecimientos', 'SELECT', 'GET', '{}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-establecimientos');

-- Menú del usuario -- misma fuente (route/role_route/app_route) que
-- MyMenuService en sso-admin, expuesta acá como SQL para que el front
-- de PIGSE no tenga que llamar a /api/sso-admin/myMenu. :CONTEXT.ROLES_ARRAY
-- es system-bound (texto[] derivado de los authorities del JWT).
INSERT INTO query (uuid, query, type, public_end, captcha, microservice_id,
                   path_template, execution_mode, http_method, param_types)
SELECT 'pigse-my-menus',
       $q$SELECT DISTINCT r.id_route AS id, r.name AS name, r.icon AS icon,
                 r.path AS path, r.menuorder AS "menuOrder", r.idparent AS "idParent"
            FROM public.route r
            JOIN public.role_route rr ON rr.route_id = r.id_route
            JOIN public.role ro ON ro.id_role = rr.role_id
            JOIN public.app_route ar ON ar.id_route = r.id_route
            JOIN public.app a ON a.id_app = ar.id_app
           WHERE ro.name = ANY(:CONTEXT.ROLES_ARRAY::text[]) AND a.name = 'PIGSE'
           ORDER BY r.menuorder, r.id_route$q$,
       'postgres', false, false, m.id_microservice,
       '/my-menus', 'SELECT', 'GET', '{}'::jsonb
  FROM microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM query WHERE uuid = 'pigse-my-menus');

-- 7. role_query -- qué rol puede invocar cada endpoint, según la
--    matriz de la cabecera de la colección Postman.
INSERT INTO role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM query q
 CROSS JOIN role ro
 WHERE q.uuid = 'pigse-documentos-listar'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-RECTOR', 'PIGSE-SECRETARIO')
   AND NOT EXISTS (SELECT 1 FROM role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

INSERT INTO role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM query q
 CROSS JOIN role ro
 WHERE q.uuid IN ('pigse-documentos-upload', 'pigse-documentos-eliminar')
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIO')
   AND NOT EXISTS (SELECT 1 FROM role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

INSERT INTO role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM query q
 CROSS JOIN role ro
 WHERE q.uuid IN ('pigse-cumplimiento-metricas', 'pigse-cumplimiento-listar')
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIA_TERRITORIAL')
   AND NOT EXISTS (SELECT 1 FROM role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

INSERT INTO role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM query q
 CROSS JOIN role ro
 WHERE q.uuid = 'pigse-establecimientos'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIO', 'PIGSE-RECTOR')
   AND NOT EXISTS (SELECT 1 FROM role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

-- my-menus: todos los autenticados de PIGSE.
INSERT INTO role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM query q
 CROSS JOIN role ro
 WHERE q.uuid = 'pigse-my-menus'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-RECTOR', 'PIGSE-SECRETARIO', 'PIGSE-SECRETARIA_TERRITORIAL')
   AND NOT EXISTS (SELECT 1 FROM role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);
