-- ===========================================================================
--  Cobertura Matricula: configuracion de parametros requeridos
--
--  Modelo (ver diagrama del CU-86e2z8aff):
--
--    TMATRICULA_CAMPO  -- catalogo GLOBAL de campos de matricula que se
--                         pueden pedir (nombre visible + tabla/columna
--                         destino donde el dato termina guardado).
--
--    TMATRICULA_CONFIG -- una configuracion de matricula POR
--                         ESTABLECIMIENTO (FK_TESTABLECIMIENTO). Es el
--                         contenedor que agrupa que campos exige ese EE.
--
--    TMATRICULA_VALOR  -- tabla puente CONFIG <-> CAMPO: por cada campo
--                         incluido en una config dice si es REQUERIDO y si
--                         es VISIBLE en el formulario de matricula.
--
--  Estructura y convenciones tomadas 1:1 de V22__academic-schema.sql:
--    * schema academico_test, search_path academico_test, public
--    * PK BIGINT GENERATED BY DEFAULT AS IDENTITY, constraint PK_<TABLA>
--    * dominio bool_sn ('S'/'N') para banderas
--    * columnas de auditoria CREATED_BY/CREATED_AT/MODIFIED_BY/MODIFIED_AT
--    * ACTIVE BOOLEAN DEFAULT TRUE NOT NULL + indice parcial WHERE ACTIVE
--    * FK con nombre explicito, indice por cada FK
-- ===========================================================================

SET client_min_messages TO WARNING;
SET search_path TO academico_test, public;

-- --------------------------------------------------------------------------
--  Tabla: TMATRICULA_CAMPO
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TMATRICULA_CAMPO (
  PK_MATRICULA_CAMPO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NOMBRE VARCHAR(130) NOT NULL,
  EDITABLE bool_sn DEFAULT 'S' NOT NULL,
  TABLA VARCHAR(130),
  CAMPO_DESTINO VARCHAR(130),
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TMATRICULA_CAMPO PRIMARY KEY (PK_MATRICULA_CAMPO),
  CONSTRAINT U_TMATRICULA_CAMPO_1 UNIQUE (TABLA, CAMPO_DESTINO)
);

--  Indices (1)
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_CAMPO_ACTIVE ON TMATRICULA_CAMPO (PK_MATRICULA_CAMPO) WHERE ACTIVE = true ;

--  Comentarios
COMMENT ON TABLE TMATRICULA_CAMPO IS 'Catalogo global de campos que se pueden solicitar en el proceso de matricula';
COMMENT ON COLUMN TMATRICULA_CAMPO.PK_MATRICULA_CAMPO IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TMATRICULA_CAMPO.NOMBRE IS 'Nombre del campo a presentar al usuario';
COMMENT ON COLUMN TMATRICULA_CAMPO.EDITABLE IS 'S/N: si el valor del campo puede ser editado durante la matricula';
COMMENT ON COLUMN TMATRICULA_CAMPO.TABLA IS 'Tabla destino donde se persiste el dato capturado';
COMMENT ON COLUMN TMATRICULA_CAMPO.CAMPO_DESTINO IS 'Columna destino dentro de TABLA donde se persiste el dato capturado';

-- --------------------------------------------------------------------------
--  Tabla: TMATRICULA_CONFIG
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TMATRICULA_CONFIG (
  PK_MATRICULA_CONFIG BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TESTABLECIMIENTO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TMATRICULA_CONFIG PRIMARY KEY (PK_MATRICULA_CONFIG),
  CONSTRAINT U_TMATRICULA_CONFIG_1 UNIQUE (FK_TESTABLECIMIENTO),
  CONSTRAINT FK_TMATRICULA_CONFIG_1 FOREIGN KEY (FK_TESTABLECIMIENTO) REFERENCES TESTABLECIMIENTO (PK_ESTABLECIMIENTO)
);

--  Indices (2)
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_CONFIG_1 ON TMATRICULA_CONFIG (FK_TESTABLECIMIENTO) ;
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_CONFIG_ACTIVE ON TMATRICULA_CONFIG (PK_MATRICULA_CONFIG) WHERE ACTIVE = true ;

--  Comentarios
COMMENT ON TABLE TMATRICULA_CONFIG IS 'Configuracion de parametros de matricula por establecimiento educativo';
COMMENT ON COLUMN TMATRICULA_CONFIG.PK_MATRICULA_CONFIG IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TMATRICULA_CONFIG.FK_TESTABLECIMIENTO IS 'Llave foranea a tabla TESTABLECIMIENTO: EE dueno de la configuracion';

-- --------------------------------------------------------------------------
--  Tabla: TMATRICULA_VALOR
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TMATRICULA_VALOR (
  PK_MATRICULA_VALOR BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  REQUERIDO bool_sn DEFAULT 'N' NOT NULL,
  VISIBLE bool_sn DEFAULT 'S' NOT NULL,
  FK_TMATRICULA_CONFIG BIGINT NOT NULL,
  FK_TMATRICULA_CAMPO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TMATRICULA_VALOR PRIMARY KEY (PK_MATRICULA_VALOR),
  CONSTRAINT U_TMATRICULA_VALOR_1 UNIQUE (FK_TMATRICULA_CONFIG, FK_TMATRICULA_CAMPO),
  CONSTRAINT FK_TMATRICULA_VALOR_1 FOREIGN KEY (FK_TMATRICULA_CONFIG) REFERENCES TMATRICULA_CONFIG (PK_MATRICULA_CONFIG) ON DELETE CASCADE,
  CONSTRAINT FK_TMATRICULA_VALOR_2 FOREIGN KEY (FK_TMATRICULA_CAMPO) REFERENCES TMATRICULA_CAMPO (PK_MATRICULA_CAMPO)
);

--  Indices (3)
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_VALOR_1 ON TMATRICULA_VALOR (FK_TMATRICULA_CONFIG) ;
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_VALOR_2 ON TMATRICULA_VALOR (FK_TMATRICULA_CAMPO) ;
CREATE INDEX IF NOT EXISTS IDX_TMATRICULA_VALOR_ACTIVE ON TMATRICULA_VALOR (PK_MATRICULA_VALOR) WHERE ACTIVE = true ;

--  Comentarios
COMMENT ON TABLE TMATRICULA_VALOR IS 'Puente configuracion<->campo: marca por campo si es requerido y visible en la matricula del EE';
COMMENT ON COLUMN TMATRICULA_VALOR.PK_MATRICULA_VALOR IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TMATRICULA_VALOR.REQUERIDO IS 'S/N: si el campo es obligatorio para completar la matricula';
COMMENT ON COLUMN TMATRICULA_VALOR.VISIBLE IS 'S/N: si el campo se muestra en el formulario de matricula';
COMMENT ON COLUMN TMATRICULA_VALOR.FK_TMATRICULA_CONFIG IS 'Llave foranea a TMATRICULA_CONFIG';
COMMENT ON COLUMN TMATRICULA_VALOR.FK_TMATRICULA_CAMPO IS 'Llave foranea a TMATRICULA_CAMPO';
