-- ===========================================================================
-- V214.1 — Planeador educativo: relaciones UNIDAD<->ENUNCIADO (referente
-- curricular) y ACTIVIDAD<->EVIDENCIA (CU-86e311xxp).
--
-- Contexto (diagrama de dependencias del Planeador):
--   * TUNIDAD ya se acoge opcionalmente a UN TREFERENTE_CURRICULAR
--     (FK_REFERENTE_CURRICULAR, V212/V216). Falta el detalle: cuales
--     ENUNCIADOS de ese arbol curricular aplican/se seleccionaron para
--     esa unidad concreta.
--   * TREFERENTE_ENUNCIADO (V212, rama CU-86e311xqh) es una UNICA tabla
--     auto-referenciada via FK_PADRE que modela tanto "enunciados"
--     (FK_PADRE IS NULL, nivel 1) como "evidencias" (FK_PADRE NOT NULL,
--     nivel 2, hijas de un enunciado) -- NO existen tablas separadas
--     ENUNCIADO/EVIDENCIA. Ver V212 para el detalle del modelo.
--   * TACTIVIDAD tiene FK_TUNIDAD (V22; se vuelve NULLABLE en V218,
--     rama CU-86e329pvq, no mergeada aqui todavia -- hoy en esta rama
--     sigue NOT NULL). Una actividad ligada a una unidad puede marcar
--     que EVIDENCIAS (nivel 2 de TREFERENTE_ENUNCIADO) sustenta, pero
--     solo las que cuelguen de un enunciado que YA fue relacionado con
--     esa unidad (tabla del punto 1).
--
-- Tablas nuevas:
--   1) TUNIDAD_ENUNCIADO         -- N:N TUNIDAD <-> TREFERENTE_ENUNCIADO
--                                    (solo nivel 1, FK_PADRE IS NULL).
--   2) TACTIVIDAD_EVIDENCIA      -- N:N TACTIVIDAD <-> TREFERENTE_ENUNCIADO
--                                    (solo nivel 2, FK_PADRE NOT NULL).
--   3) TACTIVIDAD_CRITERIO_UNIDAD -- N:N TACTIVIDAD <-> TCRITERIO_UNIDAD
--                                    (criterios de la rubrica de la unidad
--                                    de la actividad, V22).
--
-- Validacion de reglas de negocio: siguiendo el patron ya usado en el
-- repo (fn_unidad_crear V216, fn_actividad_crear V224 -- ver
-- fn_assert_permiso_seccion y validaciones de FKs "existe y esta activo"
-- dentro de la funcion, NO triggers de tabla), las reglas se validan en
-- fn_unidad_enunciado_relacionar, fn_actividad_evidencia_relacionar y
-- fn_actividad_criterio_relacionar:
--   * fn_unidad_enunciado_relacionar: el enunciado debe ser de nivel 1
--     (FK_PADRE IS NULL) y su referente curricular debe tener el MISMO
--     nivel de ensenanza que la unidad (nivel de la unidad = nivel del
--     TGRADO de la unidad, via TGRADO.FK_TNIVEL_ENSENANZA).
--   * fn_actividad_evidencia_relacionar: la evidencia debe ser de nivel 2
--     (FK_PADRE NOT NULL) y su padre (el enunciado) debe estar presente
--     en TUNIDAD_ENUNCIADO para la MISMA unidad de la actividad
--     (TACTIVIDAD.FK_TUNIDAD).
--   * fn_actividad_criterio_relacionar: el criterio (TCRITERIO_UNIDAD)
--     debe pertenecer a la rubrica (TRUBRICA_UNIDAD) de la MISMA unidad
--     que la actividad (TACTIVIDAD.FK_TUNIDAD).
--
-- Nomenclatura/estilo: sigue V22/V212/V216 (mayusculas, PK_/FK_ BIGINT
-- IDENTITY, auditoria CREATED_BY/CREATED_AT/MODIFIED_BY/MODIFIED_AT +
-- ACTIVE, indice parcial IDX_..._ACTIVE WHERE ACTIVE = true, unicidad
-- solo entre filas vivas via indice unico parcial -- patron V65) y
-- V216/V224 (gate fn_assert_permiso_seccion sobre la seccion PLANEADOR,
-- get-or-create/reactivar sobre UNIQUE parcial, RAISE EXCEPTION con
-- nombre legible + ERRCODE).
-- ===========================================================================

SET search_path TO academico_test, public;

-- ---------------------------------------------------------------------------
-- 1) Tabla: TUNIDAD_ENUNCIADO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TUNIDAD_ENUNCIADO (
  PK_TUNIDAD_ENUNCIADO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TUNIDAD BIGINT NOT NULL,
  FK_REFERENTE_ENUNCIADO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TUNIDAD_ENUNCIADO PRIMARY KEY (PK_TUNIDAD_ENUNCIADO),
  CONSTRAINT FK_TUNIDAD_ENUNCIADO_UNIDAD FOREIGN KEY (FK_TUNIDAD)
    REFERENCES TUNIDAD (PK_TUNIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TUNIDAD_ENUNCIADO_ENUNCIADO FOREIGN KEY (FK_REFERENTE_ENUNCIADO)
    REFERENCES TREFERENTE_ENUNCIADO (PK_REFERENTE_ENUNCIADO)
);

--  Indices
CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_UNIDAD ON TUNIDAD_ENUNCIADO (FK_TUNIDAD);
CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_ENUNCIADO ON TUNIDAD_ENUNCIADO (FK_REFERENTE_ENUNCIADO);
CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_ACTIVE ON TUNIDAD_ENUNCIADO (PK_TUNIDAD_ENUNCIADO) WHERE ACTIVE = true;

-- Unicidad solo entre filas vivas (patron V65): el mismo par unidad/enunciado
-- puede reinsertarse tras un borrado logico sin chocar con la fila inactiva.
CREATE UNIQUE INDEX IF NOT EXISTS U_TUNIDAD_ENUNCIADO_1
  ON TUNIDAD_ENUNCIADO (FK_TUNIDAD, FK_REFERENTE_ENUNCIADO)
  WHERE ACTIVE = true;

--  Comentarios de columna
COMMENT ON COLUMN TUNIDAD_ENUNCIADO.PK_TUNIDAD_ENUNCIADO IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TUNIDAD_ENUNCIADO.FK_TUNIDAD IS 'Llave foranea a tabla TUNIDAD';
COMMENT ON COLUMN TUNIDAD_ENUNCIADO.FK_REFERENTE_ENUNCIADO IS 'Llave foranea a TREFERENTE_ENUNCIADO (nivel 1, FK_PADRE IS NULL) del mismo nivel de ensenanza que la unidad; el enunciado marcado como aplicable/seleccionado para esa unidad';

--  Comentario de tabla
COMMENT ON TABLE TUNIDAD_ENUNCIADO IS 'Relacion N:N entre TUNIDAD y los enunciados (TREFERENTE_ENUNCIADO nivel 1) del referente curricular que aplican a esa unidad';

-- ---------------------------------------------------------------------------
-- 2) Tabla: TACTIVIDAD_EVIDENCIA
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TACTIVIDAD_EVIDENCIA (
  PK_TACTIVIDAD_EVIDENCIA BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD BIGINT NOT NULL,
  FK_REFERENTE_ENUNCIADO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TACTIVIDAD_EVIDENCIA PRIMARY KEY (PK_TACTIVIDAD_EVIDENCIA),
  CONSTRAINT FK_TACTIVIDAD_EVIDENCIA_ACTIVIDAD FOREIGN KEY (FK_TACTIVIDAD)
    REFERENCES TACTIVIDAD (PK_TACTIVIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TACTIVIDAD_EVIDENCIA_EVIDENCIA FOREIGN KEY (FK_REFERENTE_ENUNCIADO)
    REFERENCES TREFERENTE_ENUNCIADO (PK_REFERENTE_ENUNCIADO)
);

--  Indices
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_ACTIVIDAD ON TACTIVIDAD_EVIDENCIA (FK_TACTIVIDAD);
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_EVIDENCIA ON TACTIVIDAD_EVIDENCIA (FK_REFERENTE_ENUNCIADO);
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_ACTIVE ON TACTIVIDAD_EVIDENCIA (PK_TACTIVIDAD_EVIDENCIA) WHERE ACTIVE = true;

-- Unicidad solo entre filas vivas (patron V65).
CREATE UNIQUE INDEX IF NOT EXISTS U_TACTIVIDAD_EVIDENCIA_1
  ON TACTIVIDAD_EVIDENCIA (FK_TACTIVIDAD, FK_REFERENTE_ENUNCIADO)
  WHERE ACTIVE = true;

--  Comentarios de columna
COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.PK_TACTIVIDAD_EVIDENCIA IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.FK_TACTIVIDAD IS 'Llave foranea a tabla TACTIVIDAD (debe tener FK_TUNIDAD asignado)';
COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.FK_REFERENTE_ENUNCIADO IS 'Llave foranea a TREFERENTE_ENUNCIADO (nivel 2, FK_PADRE NOT NULL = evidencia) cuyo enunciado padre esta relacionado con la unidad de la actividad (TUNIDAD_ENUNCIADO)';

--  Comentario de tabla
COMMENT ON TABLE TACTIVIDAD_EVIDENCIA IS 'Relacion N:N entre TACTIVIDAD y las evidencias (TREFERENTE_ENUNCIADO nivel 2) del enunciado relacionado con la unidad de esa actividad';

-- ---------------------------------------------------------------------------
-- 3) Tabla: TACTIVIDAD_CRITERIO_UNIDAD
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TACTIVIDAD_CRITERIO_UNIDAD (
  PK_TACTIVIDAD_CRITERIO_UNIDAD BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD BIGINT NOT NULL,
  FK_TCRITERIO_UNIDAD BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TACTIVIDAD_CRITERIO_UNIDAD PRIMARY KEY (PK_TACTIVIDAD_CRITERIO_UNIDAD),
  CONSTRAINT FK_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVIDAD FOREIGN KEY (FK_TACTIVIDAD)
    REFERENCES TACTIVIDAD (PK_TACTIVIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TACTIVIDAD_CRITERIO_UNIDAD_CRITERIO FOREIGN KEY (FK_TCRITERIO_UNIDAD)
    REFERENCES TCRITERIO_UNIDAD (PK_TCRITERIO_UNIDAD)
);

--  Indices
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVIDAD ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TACTIVIDAD);
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_CRITERIO ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TCRITERIO_UNIDAD);
CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVE ON TACTIVIDAD_CRITERIO_UNIDAD (PK_TACTIVIDAD_CRITERIO_UNIDAD) WHERE ACTIVE = true;

-- Unicidad solo entre filas vivas (patron V65).
CREATE UNIQUE INDEX IF NOT EXISTS U_TACTIVIDAD_CRITERIO_UNIDAD_1
  ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TACTIVIDAD, FK_TCRITERIO_UNIDAD)
  WHERE ACTIVE = true;

--  Comentarios de columna
COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.PK_TACTIVIDAD_CRITERIO_UNIDAD IS 'Llave primaria de la tabla';
COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.FK_TACTIVIDAD IS 'Llave foranea a tabla TACTIVIDAD (debe tener FK_TUNIDAD asignado)';
COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.FK_TCRITERIO_UNIDAD IS 'Llave foranea a TCRITERIO_UNIDAD; debe pertenecer a la rubrica (TRUBRICA_UNIDAD) de la misma unidad de la actividad';

--  Comentario de tabla
COMMENT ON TABLE TACTIVIDAD_CRITERIO_UNIDAD IS 'Relacion N:N entre TACTIVIDAD y los criterios (TCRITERIO_UNIDAD) de la rubrica de la unidad de esa actividad que se seleccionaron para evaluarla';

-- ===========================================================================
-- fn_unidad_enunciado_relacionar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_unidad_enunciado_relacionar(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tunidad               BIGINT,
    p_fk_referente_enunciado   BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_nombre_unidad       VARCHAR;
    v_nivel_unidad        BIGINT;
    v_padre_enunciado     BIGINT;
    -- Referente de la unidad y del enunciado: con el modelo N:N la regla se
    -- comprueba por REFERENTE, no por un nivel unico (ver el paso 4).
    v_referente_unidad    BIGINT;
    v_referente_enunciado BIGINT;
    v_pk                  BIGINT;
BEGIN
    -- 0. Gate: capability EDITAR sobre PLANEADOR.
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, p_fk_tunidad
    );

    -- 1. Obligatorios.
    IF p_fk_tunidad IS NULL THEN
        RAISE EXCEPTION 'La unidad (FK_TUNIDAD) es obligatoria' USING ERRCODE = '22023';
    END IF;
    IF p_fk_referente_enunciado IS NULL THEN
        RAISE EXCEPTION 'El enunciado (FK_REFERENTE_ENUNCIADO) es obligatorio' USING ERRCODE = '22023';
    END IF;

    -- 2. Unidad existe/activa; su nivel de ensenanza (via grado) y el
    --    referente al que se acoge.
    SELECT u.NOMBRE, g.FK_TNIVEL_ENSENANZA, u.FK_REFERENTE_CURRICULAR
      INTO v_nombre_unidad, v_nivel_unidad, v_referente_unidad
      FROM academico_test.TUNIDAD u
      JOIN academico_test.TGRADO g ON g.PK_TGRADO = u.FK_TGRADO
     WHERE u.PK_TUNIDAD = p_fk_tunidad
       AND u.ACTIVE = TRUE;

    IF v_nombre_unidad IS NULL THEN
        RAISE EXCEPTION 'FK_TUNIDAD (%) no existe o no esta activa', p_fk_tunidad USING ERRCODE = '23503';
    END IF;

    -- 3. Enunciado existe/activo, es nivel 1 (FK_PADRE IS NULL) y de que
    --    referente es.
    --
    -- ESTABA ROTO. Aqui se leia `rc.FK_TNIVEL_ENSENANZA`, una columna DIRECTA
    -- de TREFERENTE_CURRICULAR que dejo de existir cuando la relacion
    -- referente <-> nivel paso a ser N:N por TREFERENTE_CURRICULAR_NIVEL
    -- (V212, editada en sitio en la rama CU-86e311xqh). Al ser plpgsql no
    -- fallaba al crear la funcion: fallaba al invocarla, con
    --     column rc.fk_tnivel_ensenanza does not exist (42703)
    -- y como esta funcion es la que relaciona los enunciados escogidos con la
    -- unidad -- tanto desde POST /planeador/unidades/:ID/enunciados como desde
    -- el parametro p_enunciados de fn_unidad_crear --, el paso "escoger los
    -- enunciados de la unidad" del flujo estaba MUERTO: POST /planeador/unidades
    -- con ENUNCIADOS respondia 500. Comprobado contra el servidor de test.
    SELECT e.FK_PADRE, e.FK_REFERENTE_CURRICULAR
      INTO v_padre_enunciado, v_referente_enunciado
      FROM academico_test.TREFERENTE_ENUNCIADO e
     WHERE e.PK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado
       AND e.ACTIVE = TRUE;

    IF v_referente_enunciado IS NULL THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) no existe o no esta activo', p_fk_referente_enunciado USING ERRCODE = '23503';
    END IF;
    IF v_padre_enunciado IS NOT NULL THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) es una evidencia (nivel 2), no un enunciado (nivel 1)', p_fk_referente_enunciado
            USING ERRCODE = '22023';
    END IF;

    -- 4. Regla de negocio. Con el modelo N:N la comprobacion cambia, y a algo
    --    mas estricto que "mismo nivel":
    --
    --    a) Si la unidad tiene referente (lo normal desde V216, que lo deriva
    --       del grado), el enunciado tiene que ser DE ESE referente. Es la
    --       misma invariante que V280 dejo en los datos al reparar las
    --       unidades: los enunciados de una unidad pertenecen a su referente.
    --       Comprobar solo el nivel seria mas laxo -- dejaria colgar de la
    --       unidad enunciados de OTRO referente del mismo nivel, que es
    --       exactamente el estado inconsistente que V280 tuvo que limpiar.
    --
    --    b) Si la unidad no tiene referente (su grado aun no tiene ninguno en
    --       el catalogo), se cae a la regla de nivel original, ahora resuelta
    --       por el puente: el referente del enunciado debe cubrir el nivel de
    --       la unidad. Sin este fallback no se podria marcar ningun enunciado
    --       en esas unidades.
    IF v_referente_unidad IS NOT NULL THEN
        IF v_referente_enunciado IS DISTINCT FROM v_referente_unidad THEN
            RAISE EXCEPTION 'El enunciado (%) es de otro referente curricular (%) que el de la unidad "%" (%)',
                p_fk_referente_enunciado, v_referente_enunciado, v_nombre_unidad, v_referente_unidad
                USING ERRCODE = '22023';
        END IF;
    ELSIF NOT EXISTS (
        SELECT 1
          FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
         WHERE rcn.FK_REFERENTE_CURRICULAR = v_referente_enunciado
           AND rcn.FK_TNIVEL_ENSENANZA = v_nivel_unidad
           AND rcn.ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'El enunciado (%) pertenece a un referente que no cubre el nivel de ensenanza de la unidad "%"', p_fk_referente_enunciado, v_nombre_unidad
            USING ERRCODE = '22023';
    END IF;

    -- 5. Get-or-create / reactivar sobre el indice unico parcial.
    SELECT PK_TUNIDAD_ENUNCIADO INTO v_pk
      FROM academico_test.TUNIDAD_ENUNCIADO
     WHERE FK_TUNIDAD = p_fk_tunidad
       AND FK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado;

    IF v_pk IS NULL THEN
        INSERT INTO academico_test.TUNIDAD_ENUNCIADO (
            FK_TUNIDAD, FK_REFERENTE_ENUNCIADO, CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_fk_tunidad, p_fk_referente_enunciado, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TUNIDAD_ENUNCIADO INTO v_pk;
    ELSE
        UPDATE academico_test.TUNIDAD_ENUNCIADO
           SET ACTIVE = TRUE,
               MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
               MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE PK_TUNIDAD_ENUNCIADO = v_pk;
    END IF;

    RETURN v_pk;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_unidad_enunciado_relacionar(BIGINT, BIGINT, BIGINT)
    IS 'Relaciona (o reactiva) un enunciado del referente curricular (TREFERENTE_ENUNCIADO nivel 1, FK_PADRE IS NULL) con una unidad (TUNIDAD_ENUNCIADO). ESTABA ROTA: validaba el nivel del enunciado leyendo TREFERENTE_CURRICULAR.FK_TNIVEL_ENSENANZA, columna directa que desaparecio al pasar la relacion referente<->nivel a N:N (TREFERENTE_CURRICULAR_NIVEL, V212 editada en sitio); siendo plpgsql fallaba en ejecucion con "column rc.fk_tnivel_ensenanza does not exist" (42703), asi que el paso "escoger los enunciados de la unidad" estaba muerto -- POST /planeador/unidades con ENUNCIADOS devolvia 500 y POST /planeador/unidades/:ID/enunciados tampoco funcionaba. Validacion actual, mas estricta que la original: si la unidad TIENE referente (lo normal desde V216, que lo deriva del grado) el enunciado debe ser DE ESE referente -- misma invariante que V280 dejo en los datos, y comprobar solo el nivel permitiria colgar enunciados de otro referente del mismo nivel, que es el estado inconsistente que V280 tuvo que limpiar; si la unidad no tiene referente se cae a la regla de nivel original, resuelta ahora por el puente (el referente del enunciado debe cubrir el nivel de la unidad), para que esas unidades no queden sin poder marcar nada. Gate EDITAR sobre PLANEADOR. Retorna PK_TUNIDAD_ENUNCIADO. V214.1.';

-- ===========================================================================
-- fn_unidad_enunciado_quitar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_unidad_enunciado_quitar(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tunidad_enunciado     BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, (SELECT ue.FK_TUNIDAD FROM academico_test.TUNIDAD_ENUNCIADO ue
                     WHERE ue.PK_TUNIDAD_ENUNCIADO = p_pk_tunidad_enunciado)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TUNIDAD_ENUNCIADO
         WHERE PK_TUNIDAD_ENUNCIADO = p_pk_tunidad_enunciado AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'PK_TUNIDAD_ENUNCIADO (%) no existe o ya esta inactivo', p_pk_tunidad_enunciado USING ERRCODE = '23503';
    END IF;

    -- Desactiva en cascada las evidencias de actividades ligadas a esa
    -- unidad que colgaban de este enunciado (regla del punto 2: solo
    -- pueden existir mientras el enunciado siga relacionado con la unidad).
    UPDATE academico_test.TACTIVIDAD_EVIDENCIA ae
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
      FROM academico_test.TUNIDAD_ENUNCIADO ue,
           academico_test.TREFERENTE_ENUNCIADO ev,
           academico_test.TACTIVIDAD a
     WHERE ue.PK_TUNIDAD_ENUNCIADO = p_pk_tunidad_enunciado
       AND ev.FK_PADRE = ue.FK_REFERENTE_ENUNCIADO
       AND ae.FK_REFERENTE_ENUNCIADO = ev.PK_REFERENTE_ENUNCIADO
       AND a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD
       AND a.FK_TUNIDAD = ue.FK_TUNIDAD
       AND ae.ACTIVE = TRUE;

    UPDATE academico_test.TUNIDAD_ENUNCIADO
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TUNIDAD_ENUNCIADO = p_pk_tunidad_enunciado;

    RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_unidad_enunciado_quitar(BIGINT, BIGINT)
    IS 'Borrado logico (ACTIVE=FALSE) de una relacion TUNIDAD_ENUNCIADO; arrastra la desactivacion de las TACTIVIDAD_EVIDENCIA de esa unidad cuyo enunciado padre era este. Gate EDITAR sobre PLANEADOR. V214.1.';

-- ===========================================================================
-- fn_actividad_evidencia_relacionar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_evidencia_relacionar(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tactividad            BIGINT,
    p_fk_referente_enunciado   BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_titulo_actividad    VARCHAR;
    v_fk_tunidad          BIGINT;
    v_padre_evidencia     BIGINT;
    v_pk                  BIGINT;
BEGIN
    -- 0. Gate: capability EDITAR sobre PLANEADOR.
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, p_fk_tactividad
    );

    -- 1. Obligatorios.
    IF p_fk_tactividad IS NULL THEN
        RAISE EXCEPTION 'La actividad (FK_TACTIVIDAD) es obligatoria' USING ERRCODE = '22023';
    END IF;
    IF p_fk_referente_enunciado IS NULL THEN
        RAISE EXCEPTION 'La evidencia (FK_REFERENTE_ENUNCIADO) es obligatoria' USING ERRCODE = '22023';
    END IF;

    -- 2. Actividad existe/activa y tiene unidad relacionada (FK_TUNIDAD
    --    NOT NULL).
    SELECT a.TITULO, a.FK_TUNIDAD
      INTO v_titulo_actividad, v_fk_tunidad
      FROM academico_test.TACTIVIDAD a
     WHERE a.PK_TACTIVIDAD = p_fk_tactividad
       AND a.ACTIVE = TRUE;

    IF v_titulo_actividad IS NULL THEN
        RAISE EXCEPTION 'FK_TACTIVIDAD (%) no existe o no esta activa', p_fk_tactividad USING ERRCODE = '23503';
    END IF;
    IF v_fk_tunidad IS NULL THEN
        RAISE EXCEPTION 'La actividad "%" no tiene una unidad relacionada (FK_TUNIDAD)', v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 3. Evidencia existe/activa y es nivel 2 (FK_PADRE NOT NULL).
    SELECT e.FK_PADRE INTO v_padre_evidencia
      FROM academico_test.TREFERENTE_ENUNCIADO e
     WHERE e.PK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado
       AND e.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) no existe o no esta activo', p_fk_referente_enunciado USING ERRCODE = '23503';
    END IF;
    IF v_padre_evidencia IS NULL THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) es un enunciado (nivel 1), no una evidencia (nivel 2)', p_fk_referente_enunciado
            USING ERRCODE = '22023';
    END IF;

    -- 4. Regla de negocio: el enunciado padre de la evidencia debe estar
    --    relacionado (activo) con la unidad de la actividad.
    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TUNIDAD_ENUNCIADO ue
         WHERE ue.FK_TUNIDAD = v_fk_tunidad
           AND ue.FK_REFERENTE_ENUNCIADO = v_padre_evidencia
           AND ue.ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'El enunciado padre de la evidencia (%) no esta relacionado con la unidad de la actividad "%"', p_fk_referente_enunciado, v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 5. Get-or-create / reactivar sobre el indice unico parcial.
    SELECT PK_TACTIVIDAD_EVIDENCIA INTO v_pk
      FROM academico_test.TACTIVIDAD_EVIDENCIA
     WHERE FK_TACTIVIDAD = p_fk_tactividad
       AND FK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado;

    IF v_pk IS NULL THEN
        INSERT INTO academico_test.TACTIVIDAD_EVIDENCIA (
            FK_TACTIVIDAD, FK_REFERENTE_ENUNCIADO, CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_fk_tactividad, p_fk_referente_enunciado, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TACTIVIDAD_EVIDENCIA INTO v_pk;
    ELSE
        UPDATE academico_test.TACTIVIDAD_EVIDENCIA
           SET ACTIVE = TRUE,
               MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
               MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE PK_TACTIVIDAD_EVIDENCIA = v_pk;
    END IF;

    RETURN v_pk;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_evidencia_relacionar(BIGINT, BIGINT, BIGINT)
    IS 'Relaciona (o reactiva) una evidencia del referente curricular (TREFERENTE_ENUNCIADO nivel 2, FK_PADRE NOT NULL) con una actividad (TACTIVIDAD_EVIDENCIA), exigiendo que la actividad tenga FK_TUNIDAD y que el enunciado padre de la evidencia ya este relacionado (TUNIDAD_ENUNCIADO, activo) con esa misma unidad. Gate EDITAR sobre PLANEADOR. Retorna PK_TACTIVIDAD_EVIDENCIA. V214.1.';

-- ===========================================================================
-- fn_actividad_evidencia_quitar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_evidencia_quitar(
    p_pk_usuario_solicitante     BIGINT,
    p_pk_tactividad_evidencia    BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, (SELECT ae.FK_TACTIVIDAD FROM academico_test.TACTIVIDAD_EVIDENCIA ae
                           WHERE ae.PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TACTIVIDAD_EVIDENCIA
         WHERE PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'PK_TACTIVIDAD_EVIDENCIA (%) no existe o ya esta inactivo', p_pk_tactividad_evidencia USING ERRCODE = '23503';
    END IF;

    UPDATE academico_test.TACTIVIDAD_EVIDENCIA
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia;

    RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_evidencia_quitar(BIGINT, BIGINT)
    IS 'Borrado logico (ACTIVE=FALSE) de una relacion TACTIVIDAD_EVIDENCIA. Gate EDITAR sobre PLANEADOR. V214.1.';

-- ===========================================================================
-- fn_actividad_criterio_relacionar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_criterio_relacionar(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tactividad            BIGINT,
    p_fk_tcriterio_unidad      BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_titulo_actividad    VARCHAR;
    v_fk_tunidad          BIGINT;
    v_descripcion_criterio VARCHAR;
    v_fk_tunidad_criterio  BIGINT;
    v_pk                  BIGINT;
BEGIN
    -- 0. Gate: capability EDITAR sobre PLANEADOR.
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, p_fk_tactividad
    );

    -- 1. Obligatorios.
    IF p_fk_tactividad IS NULL THEN
        RAISE EXCEPTION 'La actividad (FK_TACTIVIDAD) es obligatoria' USING ERRCODE = '22023';
    END IF;
    IF p_fk_tcriterio_unidad IS NULL THEN
        RAISE EXCEPTION 'El criterio (FK_TCRITERIO_UNIDAD) es obligatorio' USING ERRCODE = '22023';
    END IF;

    -- 2. Actividad existe/activa y tiene unidad relacionada (FK_TUNIDAD
    --    NOT NULL).
    SELECT a.TITULO, a.FK_TUNIDAD
      INTO v_titulo_actividad, v_fk_tunidad
      FROM academico_test.TACTIVIDAD a
     WHERE a.PK_TACTIVIDAD = p_fk_tactividad
       AND a.ACTIVE = TRUE;

    IF v_titulo_actividad IS NULL THEN
        RAISE EXCEPTION 'FK_TACTIVIDAD (%) no existe o no esta activa', p_fk_tactividad USING ERRCODE = '23503';
    END IF;
    IF v_fk_tunidad IS NULL THEN
        RAISE EXCEPTION 'La actividad "%" no tiene una unidad relacionada (FK_TUNIDAD)', v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 3. Criterio existe/activo; su unidad (via la rubrica).
    SELECT cu.DESCRIPCION, ru.FK_TUNIDAD
      INTO v_descripcion_criterio, v_fk_tunidad_criterio
      FROM academico_test.TCRITERIO_UNIDAD cu
      JOIN academico_test.TRUBRICA_UNIDAD ru ON ru.PK_TRUBRICA_UNIDAD = cu.FK_TRUBRICA_UNIDAD
     WHERE cu.PK_TCRITERIO_UNIDAD = p_fk_tcriterio_unidad
       AND cu.ACTIVE = TRUE;

    IF v_descripcion_criterio IS NULL THEN
        RAISE EXCEPTION 'FK_TCRITERIO_UNIDAD (%) no existe o no esta activo', p_fk_tcriterio_unidad USING ERRCODE = '23503';
    END IF;

    -- 4. Regla de negocio: el criterio debe pertenecer a la rubrica de la
    --    MISMA unidad de la actividad.
    IF v_fk_tunidad_criterio IS DISTINCT FROM v_fk_tunidad THEN
        RAISE EXCEPTION 'El criterio (%) pertenece a la rubrica de una unidad distinta a la de la actividad "%"', p_fk_tcriterio_unidad, v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 5. Get-or-create / reactivar sobre el indice unico parcial.
    SELECT PK_TACTIVIDAD_CRITERIO_UNIDAD INTO v_pk
      FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD
     WHERE FK_TACTIVIDAD = p_fk_tactividad
       AND FK_TCRITERIO_UNIDAD = p_fk_tcriterio_unidad;

    IF v_pk IS NULL THEN
        INSERT INTO academico_test.TACTIVIDAD_CRITERIO_UNIDAD (
            FK_TACTIVIDAD, FK_TCRITERIO_UNIDAD, CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_fk_tactividad, p_fk_tcriterio_unidad, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TACTIVIDAD_CRITERIO_UNIDAD INTO v_pk;
    ELSE
        UPDATE academico_test.TACTIVIDAD_CRITERIO_UNIDAD
           SET ACTIVE = TRUE,
               MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
               MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = v_pk;
    END IF;

    RETURN v_pk;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_criterio_relacionar(BIGINT, BIGINT, BIGINT)
    IS 'Relaciona (o reactiva) un criterio de la rubrica de la unidad (TCRITERIO_UNIDAD) con una actividad (TACTIVIDAD_CRITERIO_UNIDAD), exigiendo que la actividad tenga FK_TUNIDAD y que el criterio pertenezca a la rubrica (TRUBRICA_UNIDAD) de esa misma unidad. Gate EDITAR sobre PLANEADOR. Retorna PK_TACTIVIDAD_CRITERIO_UNIDAD. V214.1.';

-- ===========================================================================
-- fn_actividad_criterio_quitar
-- ===========================================================================
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_criterio_quitar(
    p_pk_usuario_solicitante          BIGINT,
    p_pk_tactividad_criterio_unidad   BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, (SELECT ac.FK_TACTIVIDAD FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD ac
                           WHERE ac.PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD
         WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'PK_TACTIVIDAD_CRITERIO_UNIDAD (%) no existe o ya esta inactivo', p_pk_tactividad_criterio_unidad USING ERRCODE = '23503';
    END IF;

    UPDATE academico_test.TACTIVIDAD_CRITERIO_UNIDAD
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad;

    RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_criterio_quitar(BIGINT, BIGINT)
    IS 'Borrado logico (ACTIVE=FALSE) de una relacion TACTIVIDAD_CRITERIO_UNIDAD. Gate EDITAR sobre PLANEADOR. V214.1.';
