-- ===========================================================================
-- V214.3 -- Referente curricular: CRUD en capas y rotulos  [CU-86e385egu]
-- ===========================================================================
-- QUE HACE: CRUD vivo del referente curricular en tres capas: validaciones
-- fn_refcurr_validar_* (Reglas 2, 6, 7, rotulos, niveles con grados en uso),
-- nucleos _interno sin permisos y wrappers (gate + etiqueta de auditoria). El
-- rotulo de area es una FK a TLISTA_VALOR PERSONALIZAR_ASIGNATURA con CRUD
-- propio; el de ejecucion (ROTULO_EJECUCION) y el de secuencia (INSTRUMENTO)
-- son texto. Suma GET .../grados y GET .../impacto.
-- POR QUE AQUI: out-of-order pegado a la familia del referente curricular
-- (V212 schema / V213 CRUD / V214 endpoints); es la duena de estas funciones.
-- DEPENDE DE: V22 (TLISTA_VALOR), V212, V213, V214, V29 (gates), V66 (auditoria).
-- ===========================================================================

SET search_path TO academico_test, public;

-- ---------------------------------------------------------------------------
-- 1) Catalogo PERSONALIZAR_ASIGNATURA + columna FK
-- ---------------------------------------------------------------------------
-- PK_LISTA_VALOR es GENERATED BY DEFAULT AS IDENTITY (V22) y las filas del
-- dump base entraron con pk explicito, asi que la secuencia se quedo detras
-- del maximo y el primer INSERT sin pk choca (misma trampa que documenta V147
-- para TARCHIVO). Resincronizarla antes de insertar; es idempotente.
SELECT setval(pg_get_serial_sequence('academico_test.tlista_valor', 'pk_lista_valor'),
              GREATEST((SELECT COALESCE(MAX(PK_LISTA_VALOR), 0)
                          FROM academico_test.TLISTA_VALOR), 1));

-- Los 3 valores semilla. ON CONFLICT DO NOTHING no bastaria para reconciliar
-- una edicion posterior, pero aqui solo se siembran: el nombre lo edita el
-- usuario por el CRUD, no la migracion.
INSERT INTO academico_test.TLISTA_VALOR (CATEGORIA, NOMBRE, VALOR, CREATED_BY, CREATED_AT, ACTIVE)
SELECT 'PERSONALIZAR_ASIGNATURA', v, v, '1', CURRENT_TIMESTAMP, TRUE
  FROM (VALUES ('Asignatura'), ('Dimension'), ('Area')) AS s(v)
 WHERE NOT EXISTS (
     SELECT 1 FROM academico_test.TLISTA_VALOR lv
      WHERE lv.CATEGORIA = 'PERSONALIZAR_ASIGNATURA' AND lv.VALOR = s.v AND lv.ACTIVE = TRUE
 );

-- Resolver por VALOR y no por pk: los pk de TLISTA_VALOR no coinciden entre
-- el servidor de test y un Postgres limpio.
CREATE OR REPLACE FUNCTION academico_test.fn_personalizar_asignatura_pk(p_valor VARCHAR)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT lv.PK_LISTA_VALOR
      FROM academico_test.TLISTA_VALOR lv
     WHERE lv.CATEGORIA = 'PERSONALIZAR_ASIGNATURA'
       AND UPPER(TRIM(lv.VALOR)) = UPPER(TRIM(p_valor))
       AND lv.ACTIVE = TRUE
     LIMIT 1;
$$;

COMMENT ON FUNCTION academico_test.fn_personalizar_asignatura_pk(VARCHAR)
    IS 'V214.3 -- PK de un valor de TLISTA_VALOR categoria PERSONALIZAR_ASIGNATURA resuelto por su VALOR (case-insensitive, con TRIM). NULL si no existe o esta inactivo. Existe porque los pk de TLISTA_VALOR no son estables entre entornos y todo lo que necesite ''Asignatura'' o ''Dimension'' tiene que llegar por texto.';

-- Defecto por nivel. Se CUENTA en vez de usar NOT EXISTS sobre el JOIN: un id
-- que no resuelve a ninguna fila se cae del join y con NOT EXISTS se leeria
-- como "no queda ningun no-preescolar" -> Dimension, al reves de lo correcto.
-- Preescolar se resuelve por NOMBRE ILIKE, no por CODIGO (igual que V214.2:
-- el CODIGO no es estable entre entornos).
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_nombre_asignatura_default(BIGINT[]);
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_nombre_asignatura_default(
    p_fk_tnivel_ensenanza_ids BIGINT[]
)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT academico_test.fn_personalizar_asignatura_pk(CASE
        WHEN COALESCE(array_length(p_fk_tnivel_ensenanza_ids, 1), 0) = 0 THEN 'Asignatura'
        WHEN (SELECT count(*) FROM unnest(p_fk_tnivel_ensenanza_ids) ne_id)
           = (SELECT count(*)
                FROM unnest(p_fk_tnivel_ensenanza_ids) ne_id
                JOIN academico_test.TNIVEL_ENSENANZA ne ON ne.PK_NIVEL_ENSENANZA = ne_id
               WHERE ne.NOMBRE ILIKE 'preescolar%')
        THEN 'Dimension'
        ELSE 'Asignatura'
    END::VARCHAR);
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_nombre_asignatura_default(BIGINT[])
    IS 'V214.3 -- PK del valor por defecto de PERSONALIZAR_ASIGNATURA para un conjunto de niveles educativos: ''Dimension'' si TODOS son preescolar (asi se llama alli a la asignatura), ''Asignatura'' en cualquier otro caso, incluido el conjunto vacio o NULL. Un id que no exista en TNIVEL_ENSENANZA basta para caer a ''Asignatura'': el CASE compara la cuenta de ids preescolar contra la de ids pedidos, asi que exige que TODOS resuelvan Y sean preescolar. Con NOT EXISTS sobre el JOIN daria ''Dimension'', que es al reves.';

ALTER TABLE academico_test.TREFERENTE_CURRICULAR
  ADD COLUMN IF NOT EXISTS FK_TLV_NOMBRE_ASIGNATURA BIGINT;

-- Migracion desde la version anterior de esta misma migracion, que guardaba
-- el rotulo como texto libre: cada valor distinto que hubiera quedado en
-- NOMBRE_ASIGNATURA entra al catalogo y la fila pasa a apuntarlo.
DO $mig$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'academico_test' AND table_name = 'treferente_curricular'
           AND column_name = 'nombre_asignatura'
    ) THEN
        INSERT INTO academico_test.TLISTA_VALOR (CATEGORIA, NOMBRE, VALOR, CREATED_BY, CREATED_AT, ACTIVE)
        SELECT DISTINCT 'PERSONALIZAR_ASIGNATURA', TRIM(rc.NOMBRE_ASIGNATURA), TRIM(rc.NOMBRE_ASIGNATURA),
               '1', CURRENT_TIMESTAMP, TRUE
          FROM academico_test.TREFERENTE_CURRICULAR rc
         WHERE NULLIF(TRIM(rc.NOMBRE_ASIGNATURA), '') IS NOT NULL
           AND academico_test.fn_personalizar_asignatura_pk(TRIM(rc.NOMBRE_ASIGNATURA)) IS NULL;

        UPDATE academico_test.TREFERENTE_CURRICULAR rc
           SET FK_TLV_NOMBRE_ASIGNATURA =
               academico_test.fn_personalizar_asignatura_pk(TRIM(rc.NOMBRE_ASIGNATURA))
         WHERE rc.FK_TLV_NOMBRE_ASIGNATURA IS NULL
           AND NULLIF(TRIM(rc.NOMBRE_ASIGNATURA), '') IS NOT NULL;

        ALTER TABLE academico_test.TREFERENTE_CURRICULAR DROP COLUMN NOMBRE_ASIGNATURA;
    END IF;
END;
$mig$;

-- Backfill: cada referente sin valor toma el defecto de sus niveles ACTIVE.
UPDATE academico_test.TREFERENTE_CURRICULAR rc
   SET FK_TLV_NOMBRE_ASIGNATURA = academico_test.fn_refcurr_nombre_asignatura_default((
           SELECT array_agg(rcn.FK_TNIVEL_ENSENANZA)
             FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
            WHERE rcn.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR
              AND rcn.ACTIVE = TRUE
       ))
 WHERE rc.FK_TLV_NOMBRE_ASIGNATURA IS NULL;

ALTER TABLE academico_test.TREFERENTE_CURRICULAR
  ALTER COLUMN FK_TLV_NOMBRE_ASIGNATURA SET NOT NULL;

DO $fk$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_treferente_curricular_nombre_asignatura'
    ) THEN
        ALTER TABLE academico_test.TREFERENTE_CURRICULAR
          ADD CONSTRAINT FK_TREFERENTE_CURRICULAR_NOMBRE_ASIGNATURA
          FOREIGN KEY (FK_TLV_NOMBRE_ASIGNATURA) REFERENCES academico_test.TLISTA_VALOR (PK_LISTA_VALOR);
    END IF;
END;
$fk$;

CREATE INDEX IF NOT EXISTS IDX_TREFCURR_NOMBRE_ASIGNATURA
    ON academico_test.TREFERENTE_CURRICULAR (FK_TLV_NOMBRE_ASIGNATURA);

COMMENT ON COLUMN academico_test.TREFERENTE_CURRICULAR.FK_TLV_NOMBRE_ASIGNATURA
    IS 'V214.3 -- Llave foranea a TLISTA_VALOR, CATEGORIA=PERSONALIZAR_ASIGNATURA: como se llama la asignatura de este referente en las pantallas que lo consumen (planeador, asistencias, periodos academicos). NOT NULL, pero el caller no esta obligado a enviarlo: si falta se resuelve con fn_refcurr_nombre_asignatura_default (''Asignatura'', o ''Dimension'' si el referente es solo de preescolar). El catalogo se amplia con fn_personalizar_asignatura_crear.';

-- ---------------------------------------------------------------------------
-- 2) Validaciones del referente (una regla por funcion; lanzan o no hacen nada)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_lista_valor(
    p_pk_lista_valor  BIGINT,
    p_categoria       VARCHAR,
    p_campo           VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF p_pk_lista_valor IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM academico_test.TLISTA_VALOR
         WHERE PK_LISTA_VALOR = p_pk_lista_valor AND CATEGORIA = p_categoria AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION '% (%) no existe, no esta activo o no es de la categoria %', p_campo, p_pk_lista_valor, p_categoria
            USING ERRCODE = '23503';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_lista_valor(BIGINT, VARCHAR, VARCHAR)
    IS 'INTERNO: 23503 si el pk no es un valor ACTIVO de esa categoria de TLISTA_VALOR. NULL pasa.';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_niveles(p_fk_tnivel_ensenanza_ids BIGINT[])
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF COALESCE(array_length(p_fk_tnivel_ensenanza_ids, 1), 0) = 0 THEN
        RAISE EXCEPTION 'Debe indicar al menos un nivel educativo'
            USING ERRCODE = '22023', HINT = 'la lista de niveles no puede ser NULL ni vacia';
    END IF;
    IF EXISTS (SELECT 1 FROM unnest(p_fk_tnivel_ensenanza_ids) n WHERE n IS NULL) THEN
        RAISE EXCEPTION 'La lista de niveles educativos no puede contener valores nulos'
            USING ERRCODE = '22023';
    END IF;
    IF EXISTS (
        SELECT 1 FROM unnest(p_fk_tnivel_ensenanza_ids) ne_id
         WHERE NOT EXISTS (SELECT 1 FROM academico_test.TNIVEL_ENSENANZA ne
                            WHERE ne.PK_NIVEL_ENSENANZA = ne_id AND ne.ACTIVE = TRUE)
    ) THEN
        RAISE EXCEPTION 'Uno o mas niveles educativos (TNIVEL_ENSENANZA) no existen o no estan activos'
            USING ERRCODE = '23503';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_niveles(BIGINT[])
    IS 'INTERNO: el set de niveles educativos no es vacio, no trae NULL (22023) y todos existen activos (23503).';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_areas(p_fk_tarea_asignatura_ids BIGINT[])
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM unnest(p_fk_tarea_asignatura_ids) ta_id
         WHERE NOT EXISTS (SELECT 1 FROM academico_test.TAREA_ASIGNATURA ta
                            WHERE ta.PK_TAREA_ASIGNATURA = ta_id AND ta.ACTIVE = TRUE)
    ) THEN
        RAISE EXCEPTION 'Una o mas areas/dimensiones (TAREA_ASIGNATURA) no existen o no estan activas'
            USING ERRCODE = '23503';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_areas(BIGINT[])
    IS 'INTERNO: 23503 si alguna area del catalogo no existe activa. NULL o vacio pasa (aplica a todas).';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_vigencia(p_desde INTEGER, p_hasta INTEGER)
RETURNS VOID
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF p_desde IS NULL THEN
        RAISE EXCEPTION 'Anio de vigencia (desde) es obligatorio' USING ERRCODE = '22023';
    END IF;
    IF p_hasta IS NOT NULL AND p_hasta < p_desde THEN
        RAISE EXCEPTION 'El anio de vigencia hasta (%) no puede ser anterior al anio desde (%)', p_hasta, p_desde
            USING ERRCODE = '22023';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_vigencia(INTEGER, INTEGER)
    IS 'INTERNO: 22023 si falta el anio desde o el hasta es anterior al desde.';

-- Regla 2. Por VALOR y no por pk: los pk de TLISTA_VALOR cambian por entorno.
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_enfoque_tipo(
    p_fk_tlv_enfoque_pedagogico  BIGINT,
    p_fk_tlv_tipo_evaluacion     BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM academico_test.TLISTA_VALOR
                WHERE PK_LISTA_VALOR = p_fk_tlv_enfoque_pedagogico AND VALOR = 'FORMATIVO')
       AND NOT EXISTS (SELECT 1 FROM academico_test.TLISTA_VALOR
                        WHERE PK_LISTA_VALOR = p_fk_tlv_tipo_evaluacion AND VALOR = 'CUALITATIVA') THEN
        RAISE EXCEPTION 'Los referentes de enfoque formativo requieren evaluacion cualitativa'
            USING ERRCODE = '22023';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_enfoque_tipo(BIGINT, BIGINT)
    IS 'INTERNO (Regla 2): 22023 si el enfoque es FORMATIVO y el tipo de evaluacion no es CUALITATIVA. Evaluativo admite cualquier tipo (Regla 3).';

-- Regla 6.
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_nombre_unico(
    p_pk_excluir               BIGINT,
    p_nombre                   VARCHAR,
    p_fk_tnivel_ensenanza_ids  BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM academico_test.TREFERENTE_CURRICULAR rc
          JOIN academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
            ON rcn.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR AND rcn.ACTIVE = TRUE
         WHERE UPPER(TRIM(rc.NOMBRE)) = UPPER(TRIM(p_nombre))
           AND rc.ACTIVE = TRUE
           AND rc.PK_REFERENTE_CURRICULAR IS DISTINCT FROM p_pk_excluir
           AND rcn.FK_TNIVEL_ENSENANZA = ANY(p_fk_tnivel_ensenanza_ids)
    ) THEN
        RAISE EXCEPTION 'Ya existe un referente curricular con el nombre "%" para al menos uno de esos niveles educativos', p_nombre
            USING ERRCODE = '23505';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_nombre_unico(BIGINT, VARCHAR, BIGINT[])
    IS 'INTERNO (Regla 6): 23505 si otro referente no dado de baja lleva el mismo nombre (sin distinguir mayusculas) y comparte al menos un nivel educativo. p_pk_excluir = el propio referente al editar.';

-- Regla 7: el conflicto se nombra (nivel + referente) para que la UI ofrezca
-- guardar como inactivo o abrir el otro referente.
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_nivel_unico_activo(
    p_pk_excluir               BIGINT,
    p_fk_tnivel_ensenanza_ids  BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_nivel     VARCHAR;
    v_otro      VARCHAR;
    v_otro_pk   BIGINT;
BEGIN
    SELECT ne.NOMBRE, rc.NOMBRE, rc.PK_REFERENTE_CURRICULAR
      INTO v_nivel, v_otro, v_otro_pk
      FROM academico_test.TREFERENTE_CURRICULAR rc
      JOIN academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
        ON rcn.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR AND rcn.ACTIVE = TRUE
      JOIN academico_test.TNIVEL_ENSENANZA ne ON ne.PK_NIVEL_ENSENANZA = rcn.FK_TNIVEL_ENSENANZA
     WHERE rc.ACTIVE = TRUE
       AND rc.ESTADO = 'A'
       AND rc.PK_REFERENTE_CURRICULAR IS DISTINCT FROM p_pk_excluir
       AND rcn.FK_TNIVEL_ENSENANZA = ANY(p_fk_tnivel_ensenanza_ids)
     ORDER BY ne.NOMBRE, rc.PK_REFERENTE_CURRICULAR
     LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'El nivel educativo "%" ya lo gobierna el referente activo "%"', v_nivel, v_otro
            USING ERRCODE = '23505',
                  HINT = format('Guarde este referente como inactivo o inactive primero el referente %s', v_otro_pk);
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_nivel_unico_activo(BIGINT, BIGINT[])
    IS 'INTERNO (Regla 7): 23505 si alguno de los niveles ya lo cubre otro referente con ESTADO = A y no dado de baja, sin importar el nombre. El mensaje nombra el primer nivel en conflicto y el referente; el HINT lleva su pk. Solo se invoca cuando el referente va a quedar activo.';

-- Quitar un nivel no puede dejar huerfano el grado de un enunciado vivo.
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_niveles_con_grados(
    p_pk_referente_curricular  BIGINT,
    p_fk_tnivel_ensenanza_ids  BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_grado  VARCHAR;
BEGIN
    SELECT lv.NOMBRE INTO v_grado
      FROM academico_test.TREFERENTE_ENUNCIADO e
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = e.FK_TLV_GRADO
     WHERE e.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
       AND e.ACTIVE = TRUE
       AND NOT EXISTS (
           SELECT 1 FROM academico_test.TNIVEL_ENSENANZA_GRADO ng
            WHERE ng.FK_TLV_GRADO = e.FK_TLV_GRADO AND ng.ACTIVE = TRUE
              AND ng.FK_TNIVEL_ENSENANZA = ANY(p_fk_tnivel_ensenanza_ids)
       )
     LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'No se puede quitar el nivel educativo del grado "%": todavia tiene enunciados asociados', v_grado
            USING ERRCODE = '23503',
                  HINT = 'Elimine o inactive esos enunciados, o conserve el nivel';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_niveles_con_grados(BIGINT, BIGINT[])
    IS 'INTERNO: 23503 si el nuevo set de niveles deja fuera el grado de algun enunciado activo del referente (simetrico a quitar un area con enunciados).';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_areas_sin_enunciados(
    p_pk_referente_curricular  BIGINT,
    p_fk_tarea_asignatura_ids  BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM academico_test.TREFERENTE_CURRICULAR_AREA rca
          JOIN academico_test.TREFERENTE_ENUNCIADO re
            ON re.FK_REFERENTE_CURRICULAR_AREA = rca.PK_REFERENTE_CURRICULAR_AREA AND re.ACTIVE = TRUE
         WHERE rca.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
           AND rca.ACTIVE = TRUE
           AND NOT (rca.FK_TAREA_ASIGNATURA = ANY(p_fk_tarea_asignatura_ids))
    ) THEN
        RAISE EXCEPTION 'No se puede quitar un area/dimension que todavia tiene enunciados asociados; reasigne o elimine esos enunciados primero'
            USING ERRCODE = '23503';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_areas_sin_enunciados(BIGINT, BIGINT[])
    IS 'INTERNO: 23503 si el nuevo set de areas quita una que tiene enunciados activos amarrados.';

-- Validaciones de formulario comunes a crear y actualizar. En actualizar los
-- NULL significan "no tocar", por eso aqui nada es obligatorio.
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_validar_campos(
    p_nombre                      VARCHAR,
    p_descripcion                 VARCHAR,
    p_nivel_1_etiqueta            VARCHAR,
    p_nivel_2_etiqueta            VARCHAR,
    p_instrumento                 VARCHAR,
    p_instrumento_info_adicional  VARCHAR,
    p_normatividad                VARCHAR,
    p_rotulo_ejecucion            VARCHAR,
    p_estado                      VARCHAR,
    p_fk_tlv_enfoque_pedagogico   BIGINT,
    p_fk_tlv_tipo_evaluacion      BIGINT,
    p_fk_tlv_nombre_asignatura    BIGINT,
    p_fk_tarea_asignatura_ids     BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_refcurr_validar_texto(p_nombre, 'Nombre del referente', 150);
    PERFORM academico_test.fn_refcurr_validar_texto(p_descripcion, 'Descripcion/finalidad', 400);
    PERFORM academico_test.fn_refcurr_validar_texto(p_nivel_1_etiqueta, 'Rotulo de nivel 1', 50);
    PERFORM academico_test.fn_refcurr_validar_texto(p_nivel_2_etiqueta, 'Rotulo de nivel 2', 50);
    PERFORM academico_test.fn_refcurr_validar_texto(p_instrumento, 'Rotulo de secuencia de actividades', 50);
    PERFORM academico_test.fn_refcurr_validar_texto(p_instrumento_info_adicional, 'Informacion adicional de la secuencia', 400);
    PERFORM academico_test.fn_refcurr_validar_texto(p_normatividad, 'Normatividad', 400);
    PERFORM academico_test.fn_refcurr_validar_texto(p_rotulo_ejecucion, 'Rotulo de ejecucion', 50);
    PERFORM academico_test.fn_refcurr_validar_estado(p_estado);
    PERFORM academico_test.fn_refcurr_validar_lista_valor(p_fk_tlv_enfoque_pedagogico, 'ENFOQUE_PEDAGOGICO', 'Enfoque pedagogico');
    PERFORM academico_test.fn_refcurr_validar_lista_valor(p_fk_tlv_tipo_evaluacion, 'TIPO_EVALUACION', 'Tipo de evaluacion');
    PERFORM academico_test.fn_refcurr_validar_lista_valor(p_fk_tlv_nombre_asignatura, 'PERSONALIZAR_ASIGNATURA', 'Rotulo de area');
    PERFORM academico_test.fn_refcurr_validar_areas(p_fk_tarea_asignatura_ids);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_validar_campos(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, BIGINT, BIGINT, BIGINT[])
    IS 'INTERNO: formato de cada campo del Formulario de Configuracion (longitudes de la seccion 2.1, estado, catalogos de TLISTA_VALOR, areas). NULL = no tocar; la obligatoriedad la comprueba fn_refcurr_crear_interno.';

-- ---------------------------------------------------------------------------
-- 3) fn_refcurr_crear
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_crear_interno(
    p_actor                         BIGINT,
    p_nombre                        VARCHAR,
    p_descripcion                   VARCHAR,
    p_fk_tnivel_ensenanza_ids       BIGINT[],
    p_fk_tlv_enfoque_pedagogico     BIGINT,
    p_fk_tlv_tipo_evaluacion        BIGINT,
    p_instrumento                   VARCHAR,
    p_normatividad                  VARCHAR,
    p_anio_vigencia_desde           INTEGER,
    p_nivel_1_etiqueta              VARCHAR  DEFAULT 'Enunciado',
    p_nivel_2_etiqueta              VARCHAR  DEFAULT 'Evidencia',
    p_instrumento_info_adicional    VARCHAR  DEFAULT NULL,
    p_anio_vigencia_hasta           INTEGER  DEFAULT NULL,
    p_estado                        VARCHAR  DEFAULT 'A',
    p_fk_tarea_asignatura_ids       BIGINT[] DEFAULT NULL,
    p_fk_tlv_nombre_asignatura      BIGINT   DEFAULT NULL,
    p_rotulo_ejecucion              VARCHAR  DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_creado  BIGINT;
    v_estado     VARCHAR := UPPER(TRIM(COALESCE(p_estado, 'A')));
BEGIN
    PERFORM academico_test.fn_refcurr_validar_texto(p_nombre, 'Nombre del referente', 150, TRUE);
    PERFORM academico_test.fn_refcurr_validar_texto(p_descripcion, 'Descripcion/finalidad', 400, TRUE);
    PERFORM academico_test.fn_refcurr_validar_texto(p_instrumento, 'Rotulo de secuencia de actividades', 50, TRUE);
    PERFORM academico_test.fn_refcurr_validar_texto(p_normatividad, 'Normatividad', 400, TRUE);
    IF p_fk_tlv_enfoque_pedagogico IS NULL THEN
        RAISE EXCEPTION 'Enfoque pedagogico es obligatorio' USING ERRCODE = '22023';
    END IF;
    IF p_fk_tlv_tipo_evaluacion IS NULL THEN
        RAISE EXCEPTION 'Tipo de evaluacion es obligatorio' USING ERRCODE = '22023';
    END IF;
    PERFORM academico_test.fn_refcurr_validar_niveles(p_fk_tnivel_ensenanza_ids);
    PERFORM academico_test.fn_refcurr_validar_campos(
        p_nombre, p_descripcion, p_nivel_1_etiqueta, p_nivel_2_etiqueta, p_instrumento,
        p_instrumento_info_adicional, p_normatividad, p_rotulo_ejecucion, v_estado,
        p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion, p_fk_tlv_nombre_asignatura,
        p_fk_tarea_asignatura_ids);
    PERFORM academico_test.fn_refcurr_validar_vigencia(p_anio_vigencia_desde, p_anio_vigencia_hasta);
    PERFORM academico_test.fn_refcurr_validar_enfoque_tipo(p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion);
    PERFORM academico_test.fn_refcurr_validar_nombre_unico(NULL, p_nombre, p_fk_tnivel_ensenanza_ids);
    IF v_estado = 'A' THEN
        PERFORM academico_test.fn_refcurr_validar_nivel_unico_activo(NULL, p_fk_tnivel_ensenanza_ids);
    END IF;

    INSERT INTO academico_test.TREFERENTE_CURRICULAR (
        NOMBRE, FK_TLV_NOMBRE_ASIGNATURA, DESCRIPCION, FK_TLV_ENFOQUE_PEDAGOGICO,
        FK_TLV_TIPO_EVALUACION, NIVEL_1_ETIQUETA, NIVEL_2_ETIQUETA, ROTULO_EJECUCION,
        INSTRUMENTO, INSTRUMENTO_INFO_ADICIONAL, NORMATIVIDAD, ANIO_VIGENCIA_DESDE,
        ANIO_VIGENCIA_HASTA, ESTADO, CREATED_BY, CREATED_AT, ACTIVE
    ) VALUES (
        TRIM(p_nombre),
        COALESCE(p_fk_tlv_nombre_asignatura,
                 academico_test.fn_refcurr_nombre_asignatura_default(p_fk_tnivel_ensenanza_ids)),
        p_descripcion, p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion,
        COALESCE(NULLIF(TRIM(p_nivel_1_etiqueta), ''), 'Enunciado'),
        COALESCE(NULLIF(TRIM(p_nivel_2_etiqueta), ''), 'Evidencia'),
        COALESCE(NULLIF(TRIM(p_rotulo_ejecucion), ''), 'Actividad'),
        TRIM(p_instrumento), p_instrumento_info_adicional, p_normatividad,
        p_anio_vigencia_desde, p_anio_vigencia_hasta, v_estado,
        p_actor::VARCHAR, CURRENT_TIMESTAMP, TRUE
    )
    RETURNING PK_REFERENTE_CURRICULAR INTO v_id_creado;

    INSERT INTO academico_test.TREFERENTE_CURRICULAR_NIVEL (
        FK_REFERENTE_CURRICULAR, FK_TNIVEL_ENSENANZA, CREATED_BY, CREATED_AT, ACTIVE
    )
    SELECT DISTINCT v_id_creado, ne_id, p_actor::VARCHAR, CURRENT_TIMESTAMP, TRUE
      FROM unnest(p_fk_tnivel_ensenanza_ids) ne_id;

    INSERT INTO academico_test.TREFERENTE_CURRICULAR_AREA (
        FK_REFERENTE_CURRICULAR, FK_TAREA_ASIGNATURA, CREATED_BY, CREATED_AT, ACTIVE
    )
    SELECT DISTINCT v_id_creado, ta_id, p_actor::VARCHAR, CURRENT_TIMESTAMP, TRUE
      FROM unnest(COALESCE(p_fk_tarea_asignatura_ids, ARRAY[]::BIGINT[])) ta_id;

    RETURN v_id_creado;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_crear_interno(BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, BIGINT[], BIGINT, VARCHAR)
    IS 'INTERNO: crea un referente curricular con sus niveles y areas, sin permisos. Valida obligatorios, longitudes, catalogos, vigencia, Regla 2 (formativo => cualitativa), Regla 6 (nombre por nivel) y, si nace activo, Regla 7 (un solo referente activo por nivel). Rotulos por defecto: Enunciado / Evidencia / Actividad; rotulo de area por nivel (fn_refcurr_nombre_asignatura_default). Lo usa fn_refcurr_crear.';

DROP FUNCTION IF EXISTS academico_test.fn_refcurr_crear(
    BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR,
    INTEGER, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, BIGINT[]);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_crear(
    BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR,
    INTEGER, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, BIGINT[], VARCHAR);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_crear(
    BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR,
    INTEGER, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, BIGINT[], BIGINT);

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_crear(
    p_pk_usuario_solicitante        BIGINT,
    p_nombre                        VARCHAR(150),
    p_descripcion                   VARCHAR(400),
    p_fk_tnivel_ensenanza_ids       BIGINT[],
    p_fk_tlv_enfoque_pedagogico     BIGINT,
    p_fk_tlv_tipo_evaluacion        BIGINT,
    p_instrumento                   VARCHAR(400),
    p_normatividad                  VARCHAR(400),
    p_anio_vigencia_desde           INTEGER,
    p_nivel_1_etiqueta              VARCHAR(60)  DEFAULT 'Enunciado',
    p_nivel_2_etiqueta              VARCHAR(60)  DEFAULT 'Evidencia',
    p_instrumento_info_adicional    VARCHAR(400) DEFAULT NULL,
    p_anio_vigencia_hasta           INTEGER      DEFAULT NULL,
    p_estado                        VARCHAR(1)   DEFAULT 'A',
    p_fk_tarea_asignatura_ids       BIGINT[]     DEFAULT NULL,
    p_fk_tlv_nombre_asignatura      BIGINT       DEFAULT NULL,
    -- Nuevos al final para no reordenar los que ya existian.
    p_rotulo_ejecucion              VARCHAR(60)  DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'CREAR'
    );
    PERFORM academico_test.fn_audit_declarar(
        p_pk_usuario_solicitante,
        'Creacion del referente curricular "' || COALESCE(TRIM(p_nombre), '') || '"',
        NULL, NULL, ARRAY['REFERENTES_CURRICULARES', 'CREACION']);

    RETURN academico_test.fn_refcurr_crear_interno(
        p_pk_usuario_solicitante, p_nombre, p_descripcion, p_fk_tnivel_ensenanza_ids,
        p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion, p_instrumento,
        p_normatividad, p_anio_vigencia_desde, p_nivel_1_etiqueta, p_nivel_2_etiqueta,
        p_instrumento_info_adicional, p_anio_vigencia_hasta, p_estado,
        p_fk_tarea_asignatura_ids, p_fk_tlv_nombre_asignatura, p_rotulo_ejecucion);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_crear(BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, BIGINT[], BIGINT, VARCHAR)
    IS 'POST /referentes-curriculares: gate CREAR sobre REFERENTES_CURRICULARES + etiqueta de auditoria; logica en fn_refcurr_crear_interno. p_instrumento es el Rotulo de Secuencia de Actividades, p_rotulo_ejecucion el Rotulo de Ejecucion (defecto Actividad) y p_fk_tlv_nombre_asignatura el Rotulo de Area (PERSONALIZAR_ASIGNATURA). 23505 por nombre repetido en un nivel o por nivel ya gobernado por otro referente activo.';

-- ---------------------------------------------------------------------------
-- 4) fn_refcurr_actualizar -- PATCH: cada NULL conserva el valor actual.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_actualizar_interno(
    p_actor                         BIGINT,
    p_pk_referente_curricular       BIGINT,
    p_nombre                        VARCHAR  DEFAULT NULL,
    p_descripcion                   VARCHAR  DEFAULT NULL,
    p_fk_tnivel_ensenanza_ids       BIGINT[] DEFAULT NULL,
    p_fk_tlv_enfoque_pedagogico     BIGINT   DEFAULT NULL,
    p_fk_tlv_tipo_evaluacion        BIGINT   DEFAULT NULL,
    p_nivel_1_etiqueta              VARCHAR  DEFAULT NULL,
    p_nivel_2_etiqueta              VARCHAR  DEFAULT NULL,
    p_instrumento                   VARCHAR  DEFAULT NULL,
    p_instrumento_info_adicional    VARCHAR  DEFAULT NULL,
    p_normatividad                  VARCHAR  DEFAULT NULL,
    p_anio_vigencia_desde           INTEGER  DEFAULT NULL,
    p_anio_vigencia_hasta           INTEGER  DEFAULT NULL,
    p_estado                        VARCHAR  DEFAULT NULL,
    p_fk_tarea_asignatura_ids       BIGINT[] DEFAULT NULL,
    p_fk_tlv_nombre_asignatura      BIGINT   DEFAULT NULL,
    p_rotulo_ejecucion              VARCHAR  DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_actual   academico_test.TREFERENTE_CURRICULAR%ROWTYPE;
    v_niveles  BIGINT[];
    v_enfoque  BIGINT;
    v_tipo     BIGINT;
    v_estado   VARCHAR;
BEGIN
    SELECT * INTO v_actual
      FROM academico_test.TREFERENTE_CURRICULAR
     WHERE PK_REFERENTE_CURRICULAR = p_pk_referente_curricular;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el referente curricular solicitado'
            USING ERRCODE = 'P0002';
    END IF;
    IF v_actual.ACTIVE = FALSE THEN
        RAISE EXCEPTION 'El referente curricular "%" esta inactivo (borrado logico); no se puede editar', v_actual.NOMBRE
            USING ERRCODE = '22023';
    END IF;

    PERFORM academico_test.fn_refcurr_validar_campos(
        p_nombre, p_descripcion, p_nivel_1_etiqueta, p_nivel_2_etiqueta, p_instrumento,
        p_instrumento_info_adicional, p_normatividad, p_rotulo_ejecucion, p_estado,
        p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion, p_fk_tlv_nombre_asignatura,
        p_fk_tarea_asignatura_ids);

    -- Niveles efectivos: un array vacio no es "vaciar" (el nivel es obligatorio).
    IF p_fk_tnivel_ensenanza_ids IS NOT NULL THEN
        PERFORM academico_test.fn_refcurr_validar_niveles(p_fk_tnivel_ensenanza_ids);
        PERFORM academico_test.fn_refcurr_validar_niveles_con_grados(p_pk_referente_curricular, p_fk_tnivel_ensenanza_ids);
        v_niveles := p_fk_tnivel_ensenanza_ids;
    ELSE
        SELECT array_agg(rcn.FK_TNIVEL_ENSENANZA) INTO v_niveles
          FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
         WHERE rcn.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular AND rcn.ACTIVE = TRUE;
    END IF;

    -- Regla 2: si el referente queda formativo y el caller no mando tipo, el
    -- tipo se fija en Cualitativa (como hace el formulario); si lo mando
    -- distinto, 22023.
    v_enfoque := COALESCE(p_fk_tlv_enfoque_pedagogico, v_actual.FK_TLV_ENFOQUE_PEDAGOGICO);
    v_tipo    := COALESCE(p_fk_tlv_tipo_evaluacion, v_actual.FK_TLV_TIPO_EVALUACION);
    IF p_fk_tlv_tipo_evaluacion IS NULL
       AND EXISTS (SELECT 1 FROM academico_test.TLISTA_VALOR
                    WHERE PK_LISTA_VALOR = v_enfoque AND VALOR = 'FORMATIVO') THEN
        v_tipo := COALESCE((SELECT PK_LISTA_VALOR FROM academico_test.TLISTA_VALOR
                             WHERE CATEGORIA = 'TIPO_EVALUACION' AND VALOR = 'CUALITATIVA' AND ACTIVE = TRUE
                             LIMIT 1), v_tipo);
    END IF;
    PERFORM academico_test.fn_refcurr_validar_enfoque_tipo(v_enfoque, v_tipo);

    PERFORM academico_test.fn_refcurr_validar_vigencia(
        COALESCE(p_anio_vigencia_desde, v_actual.ANIO_VIGENCIA_DESDE),
        COALESCE(p_anio_vigencia_hasta, v_actual.ANIO_VIGENCIA_HASTA));

    IF v_niveles IS NOT NULL THEN
        PERFORM academico_test.fn_refcurr_validar_nombre_unico(
            p_pk_referente_curricular, COALESCE(p_nombre, v_actual.NOMBRE), v_niveles);
    END IF;

    -- Regla 7 solo cuando lo que llega puede crear el solape (estado o
    -- niveles): editar el nombre de un referente que ya choca por datos
    -- anteriores a la regla no debe quedar bloqueado.
    v_estado := COALESCE(UPPER(TRIM(p_estado)), v_actual.ESTADO::VARCHAR);
    IF v_estado = 'A' AND (p_estado IS NOT NULL OR p_fk_tnivel_ensenanza_ids IS NOT NULL) THEN
        PERFORM academico_test.fn_refcurr_validar_nivel_unico_activo(p_pk_referente_curricular, v_niveles);
    END IF;

    IF p_fk_tarea_asignatura_ids IS NOT NULL THEN
        PERFORM academico_test.fn_refcurr_validar_areas_sin_enunciados(p_pk_referente_curricular, p_fk_tarea_asignatura_ids);
    END IF;

    UPDATE academico_test.TREFERENTE_CURRICULAR
       SET NOMBRE                       = COALESCE(TRIM(p_nombre), NOMBRE),
           FK_TLV_NOMBRE_ASIGNATURA     = COALESCE(p_fk_tlv_nombre_asignatura, FK_TLV_NOMBRE_ASIGNATURA),
           DESCRIPCION                  = COALESCE(p_descripcion, DESCRIPCION),
           FK_TLV_ENFOQUE_PEDAGOGICO    = v_enfoque,
           FK_TLV_TIPO_EVALUACION       = v_tipo,
           NIVEL_1_ETIQUETA             = COALESCE(NULLIF(TRIM(p_nivel_1_etiqueta), ''), NIVEL_1_ETIQUETA),
           NIVEL_2_ETIQUETA             = COALESCE(NULLIF(TRIM(p_nivel_2_etiqueta), ''), NIVEL_2_ETIQUETA),
           ROTULO_EJECUCION             = COALESCE(NULLIF(TRIM(p_rotulo_ejecucion), ''), ROTULO_EJECUCION),
           INSTRUMENTO                  = COALESCE(TRIM(p_instrumento), INSTRUMENTO),
           INSTRUMENTO_INFO_ADICIONAL   = COALESCE(p_instrumento_info_adicional, INSTRUMENTO_INFO_ADICIONAL),
           NORMATIVIDAD                 = COALESCE(p_normatividad, NORMATIVIDAD),
           ANIO_VIGENCIA_DESDE          = COALESCE(p_anio_vigencia_desde, ANIO_VIGENCIA_DESDE),
           ANIO_VIGENCIA_HASTA          = COALESCE(p_anio_vigencia_hasta, ANIO_VIGENCIA_HASTA),
           ESTADO                       = v_estado,
           MODIFIED_BY                  = p_actor::VARCHAR,
           MODIFIED_AT                  = CURRENT_TIMESTAMP
     WHERE PK_REFERENTE_CURRICULAR = p_pk_referente_curricular;

    IF p_fk_tnivel_ensenanza_ids IS NOT NULL THEN
        UPDATE academico_test.TREFERENTE_CURRICULAR_NIVEL
           SET ACTIVE = FALSE, MODIFIED_BY = p_actor::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
           AND ACTIVE = TRUE
           AND NOT (FK_TNIVEL_ENSENANZA = ANY(p_fk_tnivel_ensenanza_ids));

        INSERT INTO academico_test.TREFERENTE_CURRICULAR_NIVEL (
            FK_REFERENTE_CURRICULAR, FK_TNIVEL_ENSENANZA, CREATED_BY, CREATED_AT, ACTIVE
        )
        SELECT DISTINCT p_pk_referente_curricular, ne_id, p_actor::VARCHAR, CURRENT_TIMESTAMP, TRUE
          FROM unnest(p_fk_tnivel_ensenanza_ids) ne_id
         WHERE NOT EXISTS (
             SELECT 1 FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
              WHERE rcn.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
                AND rcn.FK_TNIVEL_ENSENANZA = ne_id AND rcn.ACTIVE = TRUE
         );
    END IF;

    -- NULL = no tocar areas; ARRAY[]::BIGINT[] = vaciarlas (aplica a todas).
    IF p_fk_tarea_asignatura_ids IS NOT NULL THEN
        UPDATE academico_test.TREFERENTE_CURRICULAR_AREA
           SET ACTIVE = FALSE, MODIFIED_BY = p_actor::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
           AND ACTIVE = TRUE
           AND NOT (FK_TAREA_ASIGNATURA = ANY(p_fk_tarea_asignatura_ids));

        INSERT INTO academico_test.TREFERENTE_CURRICULAR_AREA (
            FK_REFERENTE_CURRICULAR, FK_TAREA_ASIGNATURA, CREATED_BY, CREATED_AT, ACTIVE
        )
        SELECT DISTINCT p_pk_referente_curricular, ta_id, p_actor::VARCHAR, CURRENT_TIMESTAMP, TRUE
          FROM unnest(p_fk_tarea_asignatura_ids) ta_id
         WHERE NOT EXISTS (
             SELECT 1 FROM academico_test.TREFERENTE_CURRICULAR_AREA rca
              WHERE rca.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
                AND rca.FK_TAREA_ASIGNATURA = ta_id AND rca.ACTIVE = TRUE
         );
    END IF;

    RETURN p_pk_referente_curricular;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_actualizar_interno(BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, INTEGER, VARCHAR, BIGINT[], BIGINT, VARCHAR)
    IS 'INTERNO: PATCH parcial de un referente sin permisos (NULL = no tocar). Niveles: array = reemplazo completo, nunca vacio, y no puede dejar fuera el grado de un enunciado vivo (23503). Areas: [] = vaciar, bloqueado si quita una con enunciados (23503). Regla 2 sobre el enfoque/tipo resultantes (formativo sin tipo explicito fija Cualitativa). Regla 7 cuando llegan estado o niveles y el referente queda activo. Lo usa fn_refcurr_actualizar.';

DROP FUNCTION IF EXISTS academico_test.fn_refcurr_actualizar(
    BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, INTEGER, VARCHAR, BIGINT[]);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_actualizar(
    BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, INTEGER, VARCHAR, BIGINT[], VARCHAR);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_actualizar(
    BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, INTEGER, VARCHAR, BIGINT[], BIGINT);

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_actualizar(
    p_pk_usuario_solicitante        BIGINT,
    p_pk_referente_curricular       BIGINT,
    p_nombre                        VARCHAR(150) DEFAULT NULL,
    p_descripcion                   VARCHAR(400) DEFAULT NULL,
    p_fk_tnivel_ensenanza_ids       BIGINT[]     DEFAULT NULL,
    p_fk_tlv_enfoque_pedagogico     BIGINT       DEFAULT NULL,
    p_fk_tlv_tipo_evaluacion        BIGINT       DEFAULT NULL,
    p_nivel_1_etiqueta              VARCHAR(60)  DEFAULT NULL,
    p_nivel_2_etiqueta              VARCHAR(60)  DEFAULT NULL,
    p_instrumento                   VARCHAR(400) DEFAULT NULL,
    p_instrumento_info_adicional    VARCHAR(400) DEFAULT NULL,
    p_normatividad                  VARCHAR(400) DEFAULT NULL,
    p_anio_vigencia_desde           INTEGER      DEFAULT NULL,
    p_anio_vigencia_hasta           INTEGER      DEFAULT NULL,
    p_estado                        VARCHAR(1)   DEFAULT NULL,
    p_fk_tarea_asignatura_ids       BIGINT[]     DEFAULT NULL,
    p_fk_tlv_nombre_asignatura      BIGINT       DEFAULT NULL,
    p_rotulo_ejecucion              VARCHAR(60)  DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_actual     academico_test.TREFERENTE_CURRICULAR%ROWTYPE;
    v_etiquetas  TEXT[] := ARRAY['REFERENTES_CURRICULARES', 'EDICION'];
BEGIN
    PERFORM academico_test.fn_refcurr_validar_existe(p_pk_referente_curricular);
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'EDITAR'
    );

    -- Las cuatro alertas de alto impacto y el cambio de estado se auditan
    -- como eventos propios (Mapeo de Auditoria, seccion 2.1).
    SELECT * INTO v_actual FROM academico_test.TREFERENTE_CURRICULAR
     WHERE PK_REFERENTE_CURRICULAR = p_pk_referente_curricular;
    IF p_fk_tlv_enfoque_pedagogico IS DISTINCT FROM NULL
       AND p_fk_tlv_enfoque_pedagogico IS DISTINCT FROM v_actual.FK_TLV_ENFOQUE_PEDAGOGICO THEN
        v_etiquetas := v_etiquetas || 'CAMBIO_ENFOQUE_PEDAGOGICO'::TEXT;
    END IF;
    IF p_instrumento IS NOT NULL AND TRIM(p_instrumento) IS DISTINCT FROM v_actual.INSTRUMENTO THEN
        v_etiquetas := v_etiquetas || 'CAMBIO_ROTULO_SECUENCIA'::TEXT;
    END IF;
    IF p_rotulo_ejecucion IS NOT NULL AND TRIM(p_rotulo_ejecucion) IS DISTINCT FROM v_actual.ROTULO_EJECUCION THEN
        v_etiquetas := v_etiquetas || 'CAMBIO_ROTULO_EJECUCION'::TEXT;
    END IF;
    IF p_fk_tlv_nombre_asignatura IS NOT NULL
       AND p_fk_tlv_nombre_asignatura IS DISTINCT FROM v_actual.FK_TLV_NOMBRE_ASIGNATURA THEN
        v_etiquetas := v_etiquetas || 'CAMBIO_ROTULO_AREA'::TEXT;
    END IF;
    IF p_estado IS NOT NULL AND UPPER(TRIM(p_estado)) IS DISTINCT FROM v_actual.ESTADO::VARCHAR THEN
        v_etiquetas := v_etiquetas || 'CAMBIO_ESTADO'::TEXT;
    END IF;
    PERFORM academico_test.fn_audit_declarar(
        p_pk_usuario_solicitante,
        'Edicion del referente curricular "' || v_actual.NOMBRE || '"',
        NULL, NULL, v_etiquetas);

    RETURN academico_test.fn_refcurr_actualizar_interno(
        p_pk_usuario_solicitante, p_pk_referente_curricular, p_nombre, p_descripcion,
        p_fk_tnivel_ensenanza_ids, p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion,
        p_nivel_1_etiqueta, p_nivel_2_etiqueta, p_instrumento, p_instrumento_info_adicional,
        p_normatividad, p_anio_vigencia_desde, p_anio_vigencia_hasta, p_estado,
        p_fk_tarea_asignatura_ids, p_fk_tlv_nombre_asignatura, p_rotulo_ejecucion);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_actualizar(BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT[], BIGINT, BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, INTEGER, VARCHAR, BIGINT[], BIGINT, VARCHAR)
    IS 'PATCH /referentes-curriculares/:ID: existencia (P0002) -> gate EDITAR sobre REFERENTES_CURRICULARES -> etiqueta de auditoria con un evento por alerta de alto impacto (CAMBIO_ENFOQUE_PEDAGOGICO, CAMBIO_ROTULO_SECUENCIA, CAMBIO_ROTULO_EJECUCION, CAMBIO_ROTULO_AREA) y CAMBIO_ESTADO -> fn_refcurr_actualizar_interno. El modal de confirmacion lo decide la UI con GET /referentes-curriculares/:ID/impacto.';

-- ---------------------------------------------------------------------------
-- 5) Grados vinculados (Regla 12): agregado de los grados que declararon los
--    enunciados de nivel 1. [] = ningun enunciado tiene grado ("Todos").
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_grados_vinculados_interno(p_pk_referente_curricular BIGINT)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(jsonb_agg(jsonb_build_object('id', g.fk_tlv_grado, 'codigo', g.codigo, 'nombre', g.nombre)
                              ORDER BY g.orden), '[]'::jsonb)
      FROM (SELECT DISTINCT d.fk_tlv_grado, d.codigo, d.nombre,
                   CASE WHEN d.codigo ~ '^-?\d+$' THEN d.codigo::INTEGER END AS orden
              FROM academico_test.fn_refcurr_grados_disponibles_interno(p_pk_referente_curricular) d
             WHERE EXISTS (SELECT 1 FROM academico_test.TREFERENTE_ENUNCIADO e
                            WHERE e.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
                              AND e.FK_TLV_GRADO = d.fk_tlv_grado
                              AND e.FK_PADRE IS NULL
                              AND e.ACTIVE = TRUE)) g;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_grados_vinculados_interno(BIGINT)
    IS 'INTERNO: [{id, codigo, nombre}] de los grados que usan los enunciados activos de nivel 1 del referente, acotado a sus niveles educativos. [] significa "Todos" (ningun enunciado declara grado). Lo usan fn_refcurr_listar_interno y fn_refcurr_buscar_por_pk_interno.';

-- ---------------------------------------------------------------------------
-- 6) fn_refcurr_listar -- Vista Maestra.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_listar(
    BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN, INT, INT);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_listar_interno(
    VARCHAR, BIGINT, BIGINT, BIGINT, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN, INT, INT);

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_listar_interno(
    p_search                      VARCHAR   DEFAULT NULL,
    p_fk_tnivel_ensenanza         BIGINT    DEFAULT NULL,
    p_fk_tlv_enfoque_pedagogico   BIGINT    DEFAULT NULL,
    p_fk_tlv_tipo_evaluacion      BIGINT    DEFAULT NULL,
    p_estado                      VARCHAR   DEFAULT NULL,
    p_incluir_inactivos           BOOLEAN   DEFAULT FALSE,
    p_orden_por                   VARCHAR   DEFAULT 'nombre',
    p_orden_asc                   BOOLEAN   DEFAULT TRUE,
    p_limite                      INT       DEFAULT 20,
    p_offset                      INT       DEFAULT 0
)
RETURNS TABLE (
    pk_referente_curricular    BIGINT,
    nombre                     VARCHAR,
    descripcion                VARCHAR,
    fk_tlv_nombre_asignatura   BIGINT,
    nombre_asignatura          VARCHAR,
    niveles_educativos         VARCHAR,
    niveles                    JSONB,
    instrumento                VARCHAR,
    instrumento_info_adicional VARCHAR,
    rotulo_ejecucion           VARCHAR,
    enfoque_pedagogico         VARCHAR,
    tipo_evaluacion            VARCHAR,
    grados_vinculados          JSONB,
    estado                     VARCHAR,
    anio_vigencia_desde        INTEGER,
    anio_vigencia_hasta        INTEGER,
    modificado_por             VARCHAR,
    modificado_en              TIMESTAMP,
    active                     BOOLEAN,
    total_count                BIGINT
)
LANGUAGE sql
STABLE
AS $$
    SELECT rc.PK_REFERENTE_CURRICULAR,
           rc.NOMBRE,
           rc.DESCRIPCION,
           rc.FK_TLV_NOMBRE_ASIGNATURA,
           lvna.VALOR,
           niv.niveles_texto,
           niv.niveles_json,
           rc.INSTRUMENTO,
           rc.INSTRUMENTO_INFO_ADICIONAL,
           rc.ROTULO_EJECUCION,
           lve.NOMBRE,
           lvt.NOMBRE,
           academico_test.fn_refcurr_grados_vinculados_interno(rc.PK_REFERENTE_CURRICULAR),
           rc.ESTADO::VARCHAR,
           rc.ANIO_VIGENCIA_DESDE,
           rc.ANIO_VIGENCIA_HASTA,
           -- CREATED_BY/MODIFIED_BY guardan el pk de TUSUARIO como texto.
           COALESCE(CASE WHEN COALESCE(rc.MODIFIED_BY, rc.CREATED_BY) ~ '^\d+$'
                         THEN academico_test.fn_resolver_actor(COALESCE(rc.MODIFIED_BY, rc.CREATED_BY)::BIGINT) END,
                    COALESCE(rc.MODIFIED_BY, rc.CREATED_BY))::VARCHAR,
           COALESCE(rc.MODIFIED_AT, rc.CREATED_AT),
           rc.ACTIVE,
           COUNT(*) OVER()
      FROM academico_test.TREFERENTE_CURRICULAR rc
      -- LATERAL y no JOIN + GROUP BY: agrupar romperia el COUNT(*) OVER().
      LEFT JOIN LATERAL (
          SELECT COALESCE(string_agg(ne.NOMBRE, ', ' ORDER BY ne.NOMBRE), '')::VARCHAR AS niveles_texto,
                 COALESCE(jsonb_agg(jsonb_build_object(
                     'id', ne.PK_NIVEL_ENSENANZA, 'codigo', ne.CODIGO, 'nombre', ne.NOMBRE
                 ) ORDER BY ne.NOMBRE), '[]'::jsonb) AS niveles_json
            FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
            JOIN academico_test.TNIVEL_ENSENANZA ne ON ne.PK_NIVEL_ENSENANZA = rcn.FK_TNIVEL_ENSENANZA
           WHERE rcn.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR
             AND rcn.ACTIVE = TRUE
      ) niv ON TRUE
      JOIN academico_test.TLISTA_VALOR lve ON lve.PK_LISTA_VALOR = rc.FK_TLV_ENFOQUE_PEDAGOGICO
      JOIN academico_test.TLISTA_VALOR lvt ON lvt.PK_LISTA_VALOR = rc.FK_TLV_TIPO_EVALUACION
      JOIN academico_test.TLISTA_VALOR lvna ON lvna.PK_LISTA_VALOR = rc.FK_TLV_NOMBRE_ASIGNATURA
     WHERE (p_incluir_inactivos OR rc.ACTIVE = TRUE)
       AND (p_search IS NULL OR rc.NOMBRE ILIKE '%' || p_search || '%' OR rc.DESCRIPCION ILIKE '%' || p_search || '%' OR lvna.VALOR ILIKE '%' || p_search || '%')
       AND (p_fk_tnivel_ensenanza IS NULL OR EXISTS (
               SELECT 1 FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn_f
                WHERE rcn_f.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR
                  AND rcn_f.FK_TNIVEL_ENSENANZA = p_fk_tnivel_ensenanza
                  AND rcn_f.ACTIVE = TRUE
           ))
       AND (p_fk_tlv_enfoque_pedagogico IS NULL OR rc.FK_TLV_ENFOQUE_PEDAGOGICO = p_fk_tlv_enfoque_pedagogico)
       AND (p_fk_tlv_tipo_evaluacion IS NULL OR rc.FK_TLV_TIPO_EVALUACION = p_fk_tlv_tipo_evaluacion)
       AND (p_estado IS NULL OR rc.ESTADO = UPPER(TRIM(p_estado)))
     ORDER BY
       CASE WHEN p_orden_asc THEN
           CASE LOWER(TRIM(COALESCE(p_orden_por, 'nombre')))
               WHEN 'nombre'          THEN rc.NOMBRE
               WHEN 'nivel_educativo' THEN niv.niveles_texto
               WHEN 'instrumento'     THEN rc.INSTRUMENTO
               WHEN 'estado'          THEN rc.ESTADO::VARCHAR
               ELSE rc.NOMBRE
           END
       END ASC,
       CASE WHEN NOT p_orden_asc THEN
           CASE LOWER(TRIM(COALESCE(p_orden_por, 'nombre')))
               WHEN 'nombre'          THEN rc.NOMBRE
               WHEN 'nivel_educativo' THEN niv.niveles_texto
               WHEN 'instrumento'     THEN rc.INSTRUMENTO
               WHEN 'estado'          THEN rc.ESTADO::VARCHAR
               ELSE rc.NOMBRE
           END
       END DESC
     LIMIT GREATEST(p_limite, 1)
    OFFSET GREATEST(p_offset, 0);
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_listar_interno(VARCHAR, BIGINT, BIGINT, BIGINT, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN, INT, INT)
    IS 'INTERNO: pagina de la Vista Maestra de referentes -- niveles, los tres rotulos (instrumento = secuencia, rotulo_ejecucion, nombre_asignatura = area), grados_vinculados ([] = Todos), ultima modificacion (usuario legible + fecha) y total_count. Filtros: search, nivel, enfoque, tipo, estado. Lo usa fn_refcurr_listar.';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_listar(
    p_pk_usuario_solicitante      BIGINT,
    p_search                      VARCHAR   DEFAULT NULL,
    p_fk_tnivel_ensenanza         BIGINT    DEFAULT NULL,
    p_fk_tlv_enfoque_pedagogico   BIGINT    DEFAULT NULL,
    p_fk_tlv_tipo_evaluacion      BIGINT    DEFAULT NULL,
    p_estado                      VARCHAR   DEFAULT NULL,
    p_incluir_inactivos           BOOLEAN   DEFAULT FALSE,
    p_orden_por                   VARCHAR   DEFAULT 'nombre',
    p_orden_asc                   BOOLEAN   DEFAULT TRUE,
    p_limite                      INT       DEFAULT 20,
    p_offset                      INT       DEFAULT 0
)
RETURNS TABLE (
    pk_referente_curricular    BIGINT,
    nombre                     VARCHAR,
    descripcion                VARCHAR,
    fk_tlv_nombre_asignatura   BIGINT,
    nombre_asignatura          VARCHAR,
    niveles_educativos         VARCHAR,
    niveles                    JSONB,
    instrumento                VARCHAR,
    instrumento_info_adicional VARCHAR,
    rotulo_ejecucion           VARCHAR,
    enfoque_pedagogico         VARCHAR,
    tipo_evaluacion            VARCHAR,
    grados_vinculados          JSONB,
    estado                     VARCHAR,
    anio_vigencia_desde        INTEGER,
    anio_vigencia_hasta        INTEGER,
    modificado_por             VARCHAR,
    modificado_en              TIMESTAMP,
    active                     BOOLEAN,
    total_count                BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'VER'
    );

    RETURN QUERY
    SELECT * FROM academico_test.fn_refcurr_listar_interno(
        p_search, p_fk_tnivel_ensenanza, p_fk_tlv_enfoque_pedagogico, p_fk_tlv_tipo_evaluacion,
        p_estado, p_incluir_inactivos, p_orden_por, p_orden_asc, p_limite, p_offset);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_listar(BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN, INT, INT)
    IS 'POST /referentes-curriculares/query: Vista Maestra. Gate VER sobre REFERENTES_CURRICULARES; logica en fn_refcurr_listar_interno.';

-- ---------------------------------------------------------------------------
-- 7) fn_refcurr_buscar_por_pk -- Formulario de Configuracion / cabecera del Gestor.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_buscar_por_pk(BIGINT, BIGINT);
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_buscar_por_pk_interno(BIGINT);

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_buscar_por_pk_interno(p_pk_referente_curricular BIGINT)
RETURNS TABLE (
    pk_referente_curricular    BIGINT,
    nombre                     VARCHAR,
    descripcion                VARCHAR,
    fk_tlv_nombre_asignatura   BIGINT,
    nombre_asignatura          VARCHAR,
    niveles                    JSONB,
    fk_tlv_enfoque_pedagogico  BIGINT,
    enfoque_pedagogico         VARCHAR,
    fk_tlv_tipo_evaluacion     BIGINT,
    tipo_evaluacion            VARCHAR,
    nivel_1_etiqueta           VARCHAR,
    nivel_2_etiqueta           VARCHAR,
    instrumento                VARCHAR,
    instrumento_info_adicional VARCHAR,
    rotulo_ejecucion           VARCHAR,
    normatividad               VARCHAR,
    grados_vinculados          JSONB,
    anio_vigencia_desde        INTEGER,
    anio_vigencia_hasta        INTEGER,
    estado                     VARCHAR,
    active                     BOOLEAN
)
LANGUAGE sql
STABLE
AS $$
    SELECT rc.PK_REFERENTE_CURRICULAR, rc.NOMBRE, rc.DESCRIPCION,
           rc.FK_TLV_NOMBRE_ASIGNATURA, lvna.VALOR,
           COALESCE((
               SELECT jsonb_agg(jsonb_build_object(
                          'id', ne.PK_NIVEL_ENSENANZA, 'codigo', ne.CODIGO, 'nombre', ne.NOMBRE
                      ) ORDER BY ne.NOMBRE)
                 FROM academico_test.TREFERENTE_CURRICULAR_NIVEL rcn
                 JOIN academico_test.TNIVEL_ENSENANZA ne ON ne.PK_NIVEL_ENSENANZA = rcn.FK_TNIVEL_ENSENANZA
                WHERE rcn.FK_REFERENTE_CURRICULAR = rc.PK_REFERENTE_CURRICULAR
                  AND rcn.ACTIVE = TRUE
           ), '[]'::jsonb),
           rc.FK_TLV_ENFOQUE_PEDAGOGICO, lve.NOMBRE,
           rc.FK_TLV_TIPO_EVALUACION, lvt.NOMBRE,
           rc.NIVEL_1_ETIQUETA, rc.NIVEL_2_ETIQUETA,
           rc.INSTRUMENTO, rc.INSTRUMENTO_INFO_ADICIONAL, rc.ROTULO_EJECUCION, rc.NORMATIVIDAD,
           academico_test.fn_refcurr_grados_vinculados_interno(rc.PK_REFERENTE_CURRICULAR),
           rc.ANIO_VIGENCIA_DESDE, rc.ANIO_VIGENCIA_HASTA,
           rc.ESTADO::VARCHAR, rc.ACTIVE
      FROM academico_test.TREFERENTE_CURRICULAR rc
      JOIN academico_test.TLISTA_VALOR lve ON lve.PK_LISTA_VALOR = rc.FK_TLV_ENFOQUE_PEDAGOGICO
      JOIN academico_test.TLISTA_VALOR lvt ON lvt.PK_LISTA_VALOR = rc.FK_TLV_TIPO_EVALUACION
      JOIN academico_test.TLISTA_VALOR lvna ON lvna.PK_LISTA_VALOR = rc.FK_TLV_NOMBRE_ASIGNATURA
     WHERE rc.PK_REFERENTE_CURRICULAR = p_pk_referente_curricular;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_buscar_por_pk_interno(BIGINT)
    IS 'INTERNO: detalle de un referente (0 o 1 fila, incluye dados de baja) con niveles, los tres rotulos, los rotulos de nivel 1/2 y grados_vinculados. Lo usa fn_refcurr_buscar_por_pk.';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_buscar_por_pk(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_referente_curricular  BIGINT
)
RETURNS TABLE (
    pk_referente_curricular    BIGINT,
    nombre                     VARCHAR,
    descripcion                VARCHAR,
    fk_tlv_nombre_asignatura   BIGINT,
    nombre_asignatura          VARCHAR,
    niveles                    JSONB,
    fk_tlv_enfoque_pedagogico  BIGINT,
    enfoque_pedagogico         VARCHAR,
    fk_tlv_tipo_evaluacion     BIGINT,
    tipo_evaluacion            VARCHAR,
    nivel_1_etiqueta           VARCHAR,
    nivel_2_etiqueta           VARCHAR,
    instrumento                VARCHAR,
    instrumento_info_adicional VARCHAR,
    rotulo_ejecucion           VARCHAR,
    normatividad               VARCHAR,
    grados_vinculados          JSONB,
    anio_vigencia_desde        INTEGER,
    anio_vigencia_hasta        INTEGER,
    estado                     VARCHAR,
    active                     BOOLEAN
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'VER'
    );

    RETURN QUERY SELECT * FROM academico_test.fn_refcurr_buscar_por_pk_interno(p_pk_referente_curricular);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_buscar_por_pk(BIGINT, BIGINT)
    IS 'GET /referentes-curriculares/:ID: detalle del referente. Gate VER sobre REFERENTES_CURRICULARES; logica en fn_refcurr_buscar_por_pk_interno.';

-- ---------------------------------------------------------------------------
-- 7.1) fn_refcurr_grados_listar -- selector "Grado" del Gestor de Contenido.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_grados_listar(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_referente_curricular  BIGINT
)
RETURNS TABLE (
    fk_tlv_grado          BIGINT,
    codigo                VARCHAR,
    nombre                VARCHAR,
    fk_tnivel_ensenanza   BIGINT,
    nivel_ensenanza       VARCHAR,
    total_enunciados      BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_refcurr_validar_existe(p_pk_referente_curricular);
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'VER'
    );

    RETURN QUERY
    SELECT d.fk_tlv_grado, d.codigo, d.nombre, d.fk_tnivel_ensenanza, d.nivel_ensenanza,
           (SELECT COUNT(*) FROM academico_test.TREFERENTE_ENUNCIADO e
             WHERE e.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular
               AND e.FK_TLV_GRADO = d.fk_tlv_grado
               AND e.FK_PADRE IS NULL AND e.ACTIVE = TRUE)
      FROM academico_test.fn_refcurr_grados_disponibles_interno(p_pk_referente_curricular) d;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_grados_listar(BIGINT, BIGINT)
    IS 'GET /referentes-curriculares/:ID/grados: grados que el referente ofrece segun sus niveles educativos (fn_refcurr_grados_disponibles_interno), con cuantos enunciados activos declara cada uno. Lista vacia = el selector Grado no se muestra. P0002 si el referente no existe; gate VER sobre REFERENTES_CURRICULARES.';

-- ---------------------------------------------------------------------------
-- 7.2) fn_refcurr_impacto -- conteos para los modales de alto impacto.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_impacto_interno(p_pk_referente_curricular BIGINT)
RETURNS TABLE (unidades BIGINT, actividades BIGINT)
LANGUAGE sql
STABLE
AS $$
    WITH u AS (
        SELECT un.PK_TUNIDAD
          FROM academico_test.TUNIDAD un
         WHERE un.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular AND un.ACTIVE = TRUE
    )
    SELECT (SELECT COUNT(*) FROM u),
           (SELECT COUNT(DISTINCT a.PK_TACTIVIDAD)
              FROM academico_test.TACTIVIDAD a
             WHERE a.ACTIVE = TRUE
               AND (a.FK_TUNIDAD IN (SELECT PK_TUNIDAD FROM u)
                    OR EXISTS (SELECT 1
                                 FROM academico_test.TACTIVIDAD_EVIDENCIA ae
                                 JOIN academico_test.TREFERENTE_ENUNCIADO e
                                   ON e.PK_REFERENTE_ENUNCIADO = ae.FK_REFERENTE_ENUNCIADO
                                WHERE ae.FK_TACTIVIDAD = a.PK_TACTIVIDAD AND ae.ACTIVE = TRUE
                                  AND e.FK_REFERENTE_CURRICULAR = p_pk_referente_curricular)));
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_impacto_interno(BIGINT)
    IS 'INTERNO: unidades activas bajo el referente y actividades activas que cuelgan de ellas o citan alguna de sus evidencias. Alimenta los cuatro modales de alto impacto (enfoque y los tres rotulos). Lo usa fn_refcurr_impacto.';

CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_impacto(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_referente_curricular  BIGINT
)
RETURNS TABLE (unidades BIGINT, actividades BIGINT)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_refcurr_validar_existe(p_pk_referente_curricular);
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'VER'
    );

    RETURN QUERY SELECT * FROM academico_test.fn_refcurr_impacto_interno(p_pk_referente_curricular);
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_impacto(BIGINT, BIGINT)
    IS 'GET /referentes-curriculares/:ID/impacto: {unidades, actividades} afectadas por un cambio de enfoque o de rotulo; con ambos en 0 la UI guarda sin modal. P0002 si el referente no existe; gate VER sobre REFERENTES_CURRICULARES.';

-- ---------------------------------------------------------------------------
-- 8) fn_refcurr_nombre_asignatura -- resolucion de UN nombre de asignatura.
-- ---------------------------------------------------------------------------
-- Gate distinto al del CRUD a proposito: el CRUD del catalogo exige
-- capability sobre REFERENTES_CURRICULARES, pero LEER como se llama la
-- asignatura lo necesita cualquiera que tenga la ventana de gestion
-- academica (PLANEADOR / ASISTENCIAS) o la de PERIODOS_ACADEMICOS.
-- Basta VER en CUALQUIERA de los tres menus (OR, no AND).
--
-- Sin scope territorial: TREFERENTE_CURRICULAR es catalogo global, no cuelga
-- de establecimiento ni de sede, asi que no hay nada que recortar con
-- fn_planeador_assert_alcance.
--
-- fn_usuario_puede_en_menu (V29) envuelve fn_usuario_permisos_menu (V185),
-- asi que hereda "TROL_MENU concede / TUSUARIO_ROL_PERMISO recorta" y es
-- fail-closed ante menu no concedido.
DROP FUNCTION IF EXISTS academico_test.fn_refcurr_nombre_asignatura(BIGINT, BIGINT);
CREATE OR REPLACE FUNCTION academico_test.fn_refcurr_nombre_asignatura(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_referente_curricular  BIGINT
)
RETURNS TABLE (
    pk_referente_curricular    BIGINT,
    nombre                     VARCHAR,
    fk_tlv_nombre_asignatura   BIGINT,
    nombre_asignatura          VARCHAR,
    active                     BOOLEAN
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF NOT (
           academico_test.fn_usuario_puede_en_menu(p_pk_usuario_solicitante, 'PLANEADOR', 'VER')
        OR academico_test.fn_usuario_puede_en_menu(p_pk_usuario_solicitante, 'ASISTENCIAS', 'VER')
        OR academico_test.fn_usuario_puede_en_menu(p_pk_usuario_solicitante, 'PERIODOS_ACADEMICOS', 'VER')
    ) THEN
        RAISE EXCEPTION 'No tiene permiso para consultar el nombre de la asignatura del referente curricular'
            USING ERRCODE = '42501',
                  HINT = 'requiere VER en alguno de los menus PLANEADOR, ASISTENCIAS o PERIODOS_ACADEMICOS';
    END IF;

    RETURN QUERY
    SELECT rc.PK_REFERENTE_CURRICULAR,
           rc.NOMBRE,
           rc.FK_TLV_NOMBRE_ASIGNATURA,
           lvna.VALOR,
           rc.ACTIVE
      FROM academico_test.TREFERENTE_CURRICULAR rc
      JOIN academico_test.TLISTA_VALOR lvna ON lvna.PK_LISTA_VALOR = rc.FK_TLV_NOMBRE_ASIGNATURA
     WHERE rc.PK_REFERENTE_CURRICULAR = p_pk_referente_curricular
       AND rc.ACTIVE = TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_refcurr_nombre_asignatura(BIGINT, BIGINT)
    IS 'Resuelve el nombre con el que se debe rotular la asignatura de UN referente curricular, leyendo el VALOR de TLISTA_VALOR al que apunta. Gate por CAPABILITY de menu, no por el gate del catalogo: basta VER en PLANEADOR, ASISTENCIAS o PERIODOS_ACADEMICOS (OR). Sin scope territorial (catalogo global). Devuelve 0 filas si el referente no existe o esta inactivo -- el front lo trata como 404. 42501 -> HTTP 403.';


-- ---------------------------------------------------------------------------
-- 9) CRUD del catalogo PERSONALIZAR_ASIGNATURA
-- ---------------------------------------------------------------------------
-- Mismo gate que el catalogo de referentes (CREAR / VER / ELIMINAR sobre
-- REFERENTES_CURRICULARES): quien administra referentes administra los
-- rotulos con los que se nombran sus asignaturas.
CREATE OR REPLACE FUNCTION academico_test.fn_personalizar_asignatura_crear(
    p_pk_usuario_solicitante  BIGINT,
    p_valor                   VARCHAR
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_valor       VARCHAR;
    v_id_creado   BIGINT;
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'CREAR'
    );

    v_valor := NULLIF(TRIM(p_valor), '');
    IF v_valor IS NULL THEN
        RAISE EXCEPTION 'El nombre del valor es obligatorio'
            USING ERRCODE = '22023', HINT = 'p_valor no puede ser NULL ni vacio';
    END IF;
    IF length(v_valor) > 120 THEN
        RAISE EXCEPTION 'El nombre "%" supera los 120 caracteres', v_valor
            USING ERRCODE = '22023';
    END IF;

    -- Case-insensitive: la UNIQUE parcial de TLISTA_VALOR distingue mayusculas
    -- y dejaria pasar "Area" y "AREA" como dos valores distintos.
    IF academico_test.fn_personalizar_asignatura_pk(v_valor) IS NOT NULL THEN
        RAISE EXCEPTION 'Ya existe un valor activo llamado "%"', v_valor
            USING ERRCODE = '23505';
    END IF;

    -- El duplicado por VALOR ya se descarto arriba, asi que un unique_violation
    -- aqui solo puede ser la pkey: la secuencia de identidad detras del maximo
    -- porque alguien inserto con pk explicito (un dump). Se resincroniza y se
    -- reintenta una vez; si vuelve a fallar, que suba.
    BEGIN
        INSERT INTO academico_test.TLISTA_VALOR
            (CATEGORIA, NOMBRE, VALOR, CREATED_BY, CREATED_AT, ACTIVE)
        VALUES
            ('PERSONALIZAR_ASIGNATURA', v_valor, v_valor,
             p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE)
        RETURNING PK_LISTA_VALOR INTO v_id_creado;
    EXCEPTION WHEN unique_violation THEN
        PERFORM setval(pg_get_serial_sequence('academico_test.tlista_valor', 'pk_lista_valor'),
                       GREATEST((SELECT COALESCE(MAX(PK_LISTA_VALOR), 0)
                                   FROM academico_test.TLISTA_VALOR), 1));
        INSERT INTO academico_test.TLISTA_VALOR
            (CATEGORIA, NOMBRE, VALOR, CREATED_BY, CREATED_AT, ACTIVE)
        VALUES
            ('PERSONALIZAR_ASIGNATURA', v_valor, v_valor,
             p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE)
        RETURNING PK_LISTA_VALOR INTO v_id_creado;
    END;

    RETURN v_id_creado;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_personalizar_asignatura_crear(BIGINT, VARCHAR)
    IS 'Agrega un valor a TLISTA_VALOR categoria PERSONALIZAR_ASIGNATURA (los rotulos con los que un referente curricular puede nombrar su asignatura: Asignatura, Dimension, Area y los que se anadan). Guarda el mismo texto en NOMBRE y en VALOR, con TRIM. Rechaza vacio o mas de 120 caracteres (22023) y duplicados comparando sin distinguir mayusculas (23505), que es mas estricto que la UNIQUE parcial de la tabla. Gate CREAR sobre REFERENTES_CURRICULARES.';

CREATE OR REPLACE FUNCTION academico_test.fn_personalizar_asignatura_listar(
    p_pk_usuario_solicitante  BIGINT,
    p_search                  VARCHAR DEFAULT NULL,
    p_incluir_inactivos       BOOLEAN DEFAULT FALSE
)
RETURNS TABLE (
    pk_lista_valor   BIGINT,
    valor            VARCHAR,
    es_semilla       BOOLEAN,
    en_uso           BIGINT,
    active           BOOLEAN,
    total_count      BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'VER'
    );

    RETURN QUERY
    SELECT lv.PK_LISTA_VALOR,
           lv.VALOR,
           UPPER(TRIM(lv.VALOR)) IN ('ASIGNATURA', 'DIMENSION', 'AREA'),
           (SELECT count(*)
              FROM academico_test.TREFERENTE_CURRICULAR rc
             WHERE rc.FK_TLV_NOMBRE_ASIGNATURA = lv.PK_LISTA_VALOR
               AND rc.ACTIVE = TRUE),
           lv.ACTIVE,
           COUNT(*) OVER()
      FROM academico_test.TLISTA_VALOR lv
     WHERE lv.CATEGORIA = 'PERSONALIZAR_ASIGNATURA'
       AND (p_incluir_inactivos OR lv.ACTIVE = TRUE)
       AND (p_search IS NULL OR lv.VALOR ILIKE '%' || p_search || '%')
     ORDER BY lv.VALOR;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_personalizar_asignatura_listar(BIGINT, VARCHAR, BOOLEAN)
    IS 'Valores de TLISTA_VALOR categoria PERSONALIZAR_ASIGNATURA, para el select "como se llama la asignatura" del referente curricular. es_semilla marca los tres que trae la migracion (Asignatura, Dimension, Area), que no se pueden borrar; en_uso cuenta los referentes ACTIVE que apuntan a cada valor, para que la UI sepa de antemano cuales fallarian al eliminar. p_incluir_inactivos=FALSE por defecto. Gate VER sobre REFERENTES_CURRICULARES.';

CREATE OR REPLACE FUNCTION academico_test.fn_personalizar_asignatura_eliminar(
    p_pk_usuario_solicitante  BIGINT,
    p_pk_lista_valor          BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_actual   academico_test.TLISTA_VALOR%ROWTYPE;
    v_en_uso   BIGINT;
BEGIN
    SELECT * INTO v_actual
      FROM academico_test.TLISTA_VALOR
     WHERE PK_LISTA_VALOR = p_pk_lista_valor
       AND CATEGORIA = 'PERSONALIZAR_ASIGNATURA';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el valor solicitado en PERSONALIZAR_ASIGNATURA'
            USING ERRCODE = 'P0002';
    END IF;

    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'REFERENTES_CURRICULARES', 'ELIMINAR'
    );

    IF UPPER(TRIM(v_actual.VALOR)) IN ('ASIGNATURA', 'DIMENSION', 'AREA') THEN
        RAISE EXCEPTION 'El valor "%" es uno de los tres basicos y no se puede eliminar', v_actual.VALOR
            USING ERRCODE = '22023',
                  HINT = 'Asignatura, Dimension y Area sostienen el valor por defecto de los referentes';
    END IF;

    SELECT count(*) INTO v_en_uso
      FROM academico_test.TREFERENTE_CURRICULAR rc
     WHERE rc.FK_TLV_NOMBRE_ASIGNATURA = p_pk_lista_valor
       AND rc.ACTIVE = TRUE;

    IF v_en_uso > 0 THEN
        RAISE EXCEPTION 'El valor "%" lo usan % referente(s) curricular(es) vigente(s); cambieles el nombre de asignatura antes de eliminarlo', v_actual.VALOR, v_en_uso
            USING ERRCODE = '23503';
    END IF;

    IF v_actual.ACTIVE = FALSE THEN
        RETURN p_pk_lista_valor;
    END IF;

    UPDATE academico_test.TLISTA_VALOR
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_LISTA_VALOR = p_pk_lista_valor;

    RETURN p_pk_lista_valor;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_personalizar_asignatura_eliminar(BIGINT, BIGINT)
    IS 'Baja logica (ACTIVE=FALSE) de un valor de PERSONALIZAR_ASIGNATURA. Rechaza los tres basicos -- Asignatura, Dimension, Area -- con 22023, porque fn_refcurr_nombre_asignatura_default los resuelve por texto y sin ellos los referentes nuevos se quedarian sin valor por defecto. Rechaza con 23503, nombrando el valor y cuantos lo usan, si algun referente ACTIVE apunta a el. Idempotente: sobre un valor ya inactivo devuelve su pk sin tocar nada. Un pk de otra categoria responde P0002, no lo borra. Gate ELIMINAR sobre REFERENTES_CURRICULARES.';

-- ===========================================================================
-- 10) public.query -- filas del gateway (serviceid eval-col).
-- ===========================================================================
-- Las de crear/actualizar se REEMPLAZAN con UPDATE y no editando V214: esa
-- migracion ya corrio y su ON CONFLICT no se reejecuta.

-- 10.1 refcurr-crear -- + BODY.NOMBRE_ASIGNATURA (opcional, cae al defecto).
UPDATE public.query
   SET query = $q$SELECT academico_test.fn_refcurr_crear(
    p_pk_usuario_solicitante     => public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    p_nombre                     => CAST(:BODY.NOMBRE AS VARCHAR),
    p_descripcion                => CAST(:BODY.DESCRIPCION AS VARCHAR),
    p_fk_tnivel_ensenanza_ids    => CAST(:BODY.NIVELES_IDS AS BIGINT[]),
    p_fk_tlv_enfoque_pedagogico  => CAST(:BODY.ENFOQUE_PEDAGOGICO AS BIGINT),
    p_fk_tlv_tipo_evaluacion     => CAST(:BODY.TIPO_EVALUACION AS BIGINT),
    p_instrumento                => CAST(:BODY.INSTRUMENTO AS VARCHAR),
    p_normatividad               => CAST(:BODY.NORMATIVIDAD AS VARCHAR),
    p_anio_vigencia_desde        => CAST(:BODY.ANIO_DESDE AS INTEGER),
    p_nivel_1_etiqueta           => CAST(:BODY.NIVEL_1_ETIQUETA AS VARCHAR),
    p_nivel_2_etiqueta           => CAST(:BODY.NIVEL_2_ETIQUETA AS VARCHAR),
    p_instrumento_info_adicional => CAST(:BODY.INSTRUMENTO_INFO AS VARCHAR),
    p_anio_vigencia_hasta        => CAST(:BODY.ANIO_HASTA AS INTEGER),
    p_estado                     => COALESCE(CAST(:BODY.ESTADO AS VARCHAR), 'A'),
    p_fk_tarea_asignatura_ids    => CAST(:BODY.AREAS_IDS AS BIGINT[]),
    p_fk_tlv_nombre_asignatura   => CAST(:BODY.NOMBRE_ASIGNATURA AS BIGINT),
    p_rotulo_ejecucion           => CAST(:BODY.ROTULO_EJECUCION AS VARCHAR)
) AS pk_referente_curricular_creado$q$,
       param_types = '{
       "BODY.NOMBRE":             "VARCHAR",
       "BODY.NOMBRE_ASIGNATURA":  "BIGINT",
       "BODY.ROTULO_EJECUCION":   "VARCHAR",
       "BODY.DESCRIPCION":        "VARCHAR",
       "BODY.NIVELES_IDS":        "BIGINT[]",
       "BODY.ENFOQUE_PEDAGOGICO": "BIGINT",
       "BODY.TIPO_EVALUACION":    "BIGINT",
       "BODY.INSTRUMENTO":        "VARCHAR",
       "BODY.NORMATIVIDAD":       "VARCHAR",
       "BODY.ANIO_DESDE":         "INTEGER",
       "BODY.NIVEL_1_ETIQUETA":   "VARCHAR",
       "BODY.NIVEL_2_ETIQUETA":   "VARCHAR",
       "BODY.INSTRUMENTO_INFO":   "VARCHAR",
       "BODY.ANIO_HASTA":         "INTEGER",
       "BODY.ESTADO":             "VARCHAR",
       "BODY.AREAS_IDS":          "BIGINT[]"
     }'::jsonb,
       detail = 'Crea un referente curricular. BODY.INSTRUMENTO es el Rotulo de Secuencia de Actividades y BODY.ROTULO_EJECUCION el Rotulo de Ejecucion (max 50, defecto Actividad). Formativo exige Cualitativa (22023); un nivel ya gobernado por otro referente activo da 23505. BODY.NOMBRE_ASIGNATURA es el PK_LISTA_VALOR de un valor de la categoria PERSONALIZAR_ASIGNATURA (GET /referentes-curriculares/personalizar-asignatura lo lista), no texto libre; es OPCIONAL: si no viene se resuelve por nivel -- Asignatura, o Dimension si el referente es SOLO de preescolar. Un id que no sea de esa categoria da 23503. BODY.NIVELES_IDS obligatorio con al menos un nivel; BODY.AREAS_IDS vacio/ausente = aplica a todas las areas'
 WHERE uuid = 'refcurr-crear';

-- 10.2 refcurr-actualizar -- + BODY.NOMBRE_ASIGNATURA (ausente = no tocar).
UPDATE public.query
   SET query = $q$SELECT academico_test.fn_refcurr_actualizar(
    p_pk_usuario_solicitante     => public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    p_pk_referente_curricular    => CAST(:PARAM.ID AS BIGINT),
    p_nombre                     => CAST(:BODY.NOMBRE AS VARCHAR),
    p_descripcion                => CAST(:BODY.DESCRIPCION AS VARCHAR),
    p_fk_tnivel_ensenanza_ids    => CAST(:BODY.NIVELES_IDS AS BIGINT[]),
    p_fk_tlv_enfoque_pedagogico  => CAST(:BODY.ENFOQUE_PEDAGOGICO AS BIGINT),
    p_fk_tlv_tipo_evaluacion     => CAST(:BODY.TIPO_EVALUACION AS BIGINT),
    p_nivel_1_etiqueta           => CAST(:BODY.NIVEL_1_ETIQUETA AS VARCHAR),
    p_nivel_2_etiqueta           => CAST(:BODY.NIVEL_2_ETIQUETA AS VARCHAR),
    p_instrumento                => CAST(:BODY.INSTRUMENTO AS VARCHAR),
    p_instrumento_info_adicional => CAST(:BODY.INSTRUMENTO_INFO AS VARCHAR),
    p_normatividad               => CAST(:BODY.NORMATIVIDAD AS VARCHAR),
    p_anio_vigencia_desde        => CAST(:BODY.ANIO_DESDE AS INTEGER),
    p_anio_vigencia_hasta        => CAST(:BODY.ANIO_HASTA AS INTEGER),
    p_estado                     => CAST(:BODY.ESTADO AS VARCHAR),
    p_fk_tarea_asignatura_ids    => CAST(:BODY.AREAS_IDS AS BIGINT[]),
    p_fk_tlv_nombre_asignatura   => CAST(:BODY.NOMBRE_ASIGNATURA AS BIGINT),
    p_rotulo_ejecucion           => CAST(:BODY.ROTULO_EJECUCION AS VARCHAR)
) AS pk_referente_curricular$q$,
       param_types = '{
       "PARAM.ID":                "BIGINT",
       "BODY.NOMBRE":             "VARCHAR",
       "BODY.NOMBRE_ASIGNATURA":  "BIGINT",
       "BODY.ROTULO_EJECUCION":   "VARCHAR",
       "BODY.DESCRIPCION":        "VARCHAR",
       "BODY.NIVELES_IDS":        "BIGINT[]",
       "BODY.ENFOQUE_PEDAGOGICO": "BIGINT",
       "BODY.TIPO_EVALUACION":    "BIGINT",
       "BODY.NIVEL_1_ETIQUETA":   "VARCHAR",
       "BODY.NIVEL_2_ETIQUETA":   "VARCHAR",
       "BODY.INSTRUMENTO":        "VARCHAR",
       "BODY.INSTRUMENTO_INFO":   "VARCHAR",
       "BODY.NORMATIVIDAD":       "VARCHAR",
       "BODY.ANIO_DESDE":         "INTEGER",
       "BODY.ANIO_HASTA":         "INTEGER",
       "BODY.ESTADO":             "VARCHAR",
       "BODY.AREAS_IDS":          "BIGINT[]"
     }'::jsonb,
       detail = 'PATCH parcial de un referente curricular; BODY.ROTULO_EJECUCION ausente = no tocar. cada campo ausente preserva su valor actual. BODY.NOMBRE_ASIGNATURA es el PK_LISTA_VALOR de un valor de PERSONALIZAR_ASIGNATURA: ausente = no tocar, id = lo reemplaza, id que no sea de esa categoria = 23503. BODY.NIVELES_IDS ausente = no tocar los niveles, array = reemplazo completo del set. BODY.AREAS_IDS ausente = no tocar areas, [] = vaciarlas'
 WHERE uuid = 'refcurr-actualizar';

-- 10.3 refcurr-nombre-asignatura -- endpoint nuevo.
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'refcurr-nombre-asignatura',
    $q$SELECT * FROM academico_test.fn_refcurr_nombre_asignatura(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:PARAM.ID AS BIGINT)
);$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/:ID/nombre-asignatura', 'SELECT', 'GET',
    '{"PARAM.ID": "BIGINT"}'::jsonb,
    'Nombre con el que se debe rotular la asignatura de este referente, segun el acceso del usuario. Gate por capability de menu: basta VER en PLANEADOR, ASISTENCIAS o PERIODOS_ACADEMICOS (403 si no tiene ninguno). 0 filas si el referente no existe o esta inactivo'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- 10.4 personalizar-asignatura -- LISTAR
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'personalizar-asignatura-listar',
    $q$SELECT * FROM academico_test.fn_personalizar_asignatura_listar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:QUERY.SEARCH AS VARCHAR),
    COALESCE(CAST(:QUERY.INCLUIR_INACTIVOS AS BOOLEAN), FALSE)
);$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/personalizar-asignatura', 'SELECT', 'GET',
    '{"QUERY.SEARCH": "VARCHAR", "QUERY.INCLUIR_INACTIVOS": "BOOLEAN"}'::jsonb,
    'Valores con los que un referente curricular puede nombrar su asignatura (TLISTA_VALOR categoria PERSONALIZAR_ASIGNATURA). Alimenta el select del formulario de referentes. es_semilla marca los tres basicos, que no se pueden eliminar; en_uso cuenta los referentes vigentes que apuntan a cada valor. Gate VER sobre REFERENTES_CURRICULARES'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- 10.5 personalizar-asignatura -- CREAR
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'personalizar-asignatura-crear',
    $q$SELECT academico_test.fn_personalizar_asignatura_crear(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:BODY.VALOR AS VARCHAR)
) AS pk_lista_valor_creado$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/personalizar-asignatura', 'SELECT', 'POST',
    '{"BODY.VALOR": "VARCHAR"}'::jsonb,
    'Agrega un valor a PERSONALIZAR_ASIGNATURA. BODY.VALOR obligatorio, maximo 120 caracteres (22023) y sin duplicar uno activo comparando sin distinguir mayusculas (23505). Gate CREAR sobre REFERENTES_CURRICULARES'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- 10.6 personalizar-asignatura -- ELIMINAR
-- PATCH sobre un sub-path .../eliminar, igual que el resto del dominio (V214).
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'personalizar-asignatura-eliminar',
    $q$SELECT academico_test.fn_personalizar_asignatura_eliminar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:PARAM.ID AS BIGINT)
) AS pk_lista_valor$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/personalizar-asignatura/:ID/eliminar', 'SELECT', 'PATCH',
    '{"PARAM.ID": "BIGINT"}'::jsonb,
    'Baja logica de un valor de PERSONALIZAR_ASIGNATURA. Responde 22023 sobre los tres basicos (Asignatura, Dimension, Area) y 23503 si algun referente vigente lo usa, diciendo cuantos. Gate ELIMINAR sobre REFERENTES_CURRICULARES'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- 10.7 refcurr-grados -- selector "Grado" del Gestor de Contenido.
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'refcurr-grados',
    $q$SELECT * FROM academico_test.fn_refcurr_grados_listar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:PARAM.ID AS BIGINT)
);$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/:ID/grados', 'SELECT', 'GET',
    '{"PARAM.ID": "BIGINT"}'::jsonb,
    'Grados (catalogo GRADOS) que ofrece el referente segun sus niveles educativos, con total_enunciados por grado. Lista vacia = no mostrar el selector Grado. El fk_tlv_grado es el BODY.GRADO_ID de POST /referentes-curriculares/:ID/enunciados y el ?grado= de su GET. Gate VER sobre REFERENTES_CURRICULARES'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- 10.8 refcurr-impacto -- conteos de los modales de alto impacto.
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                           path_template, execution_mode, http_method, param_types, detail)
SELECT
    'refcurr-impacto',
    $q$SELECT * FROM academico_test.fn_refcurr_impacto(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:PARAM.ID AS BIGINT)
);$q$,
    'postgres', false, false, m.id_microservice,
    '/referentes-curriculares/:ID/impacto', 'SELECT', 'GET',
    '{"PARAM.ID": "BIGINT"}'::jsonb,
    'Unidades y actividades activas que se verian afectadas al cambiar el enfoque pedagogico o alguno de los tres rotulos del referente; con ambos en 0 la UI guarda sin modal de confirmacion. Gate VER sobre REFERENTES_CURRICULARES'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (uuid) DO UPDATE
   SET query = EXCLUDED.query, param_types = EXCLUDED.param_types,
       path_template = EXCLUDED.path_template, http_method = EXCLUDED.http_method,
       execution_mode = EXCLUDED.execution_mode, microservice_id = EXCLUDED.microservice_id,
       detail = EXCLUDED.detail;

-- ---------------------------------------------------------------------------
-- 11) role_query -- sin fila aqui el gateway responde 403 y el gate de la
--    funcion no llega a ejecutarse. Los roles salen de TROL_MENU, para que el
--    gate del JWT y el de la base no queden desincronizados.
-- ---------------------------------------------------------------------------
-- 11.1 Catalogo: solo quien administra referentes (REFERENTES_CURRICULARES ->
--     SUPER_ADMINISTRADOR), el mismo conjunto que V214 dio al resto del dominio.
INSERT INTO public.role_query (role_id, query_id)
SELECT r.id_role, q.id_query
  FROM public.query q
  JOIN public.microservice m ON m.id_microservice = q.microservice_id AND m.serviceid = 'eval-col'
 CROSS JOIN public.role r
 WHERE r.name = 'CEVAL-SUPER_ADMINISTRADOR'
   AND q.uuid IN ('personalizar-asignatura-listar', 'personalizar-asignatura-crear',
                  'personalizar-asignatura-eliminar', 'refcurr-grados', 'refcurr-impacto')
   AND NOT EXISTS (
       SELECT 1 FROM public.role_query rq
        WHERE rq.query_id = q.id_query AND rq.role_id = r.id_role
   );

-- 11.2 Resolver del rotulo: quien tiene PLANEADOR, ASISTENCIAS o
--     PERIODOS_ACADEMICOS -- coordinador, docente, rector y super admin.
INSERT INTO public.role_query (role_id, query_id)
SELECT r.id_role, q.id_query
  FROM public.query q
  JOIN public.microservice m ON m.id_microservice = q.microservice_id AND m.serviceid = 'eval-col'
 CROSS JOIN public.role r
 WHERE r.name IN ('CEVAL-COORDINADOR', 'CEVAL-DOCENTE', 'CEVAL-RECTOR',
                  'CEVAL-SUPER_ADMINISTRADOR', 'SSO-ADMIN')
   AND q.uuid = 'refcurr-nombre-asignatura'
   AND NOT EXISTS (
       SELECT 1 FROM public.role_query rq
        WHERE rq.query_id = q.id_query AND rq.role_id = r.id_role
   );
