-- ===========================================================================
-- V214.1 - Planeador: tablas puente TUNIDAD_ENUNCIADO, TACTIVIDAD_EVIDENCIA y
-- TACTIVIDAD_CRITERIO_UNIDAD, y el CRUD de evidencias y criterios de actividad.
--
-- El CRUD de enunciados de la unidad (relacionar/quitar) vive en V492.1-V492.3.
-- Depende de: V212 (TREFERENTE_ENUNCIADO), V22 (TUNIDAD, TACTIVIDAD).
-- ===========================================================================


SET search_path TO academico_test, public;

CREATE TABLE IF NOT EXISTS TUNIDAD_ENUNCIADO (
  PK_TUNIDAD_ENUNCIADO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TUNIDAD BIGINT NOT NULL,
  FK_REFERENTE_ENUNCIADO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TUNIDAD_ENUNCIADO PRIMARY KEY (PK_TUNIDAD_ENUNCIADO),
  CONSTRAINT FK_TUNIDAD_ENUNCIADO_UNIDAD FOREIGN KEY (FK_TUNIDAD)
    REFERENCES TUNIDAD (PK_TUNIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TUNIDAD_ENUNCIADO_ENUNCIADO FOREIGN KEY (FK_REFERENTE_ENUNCIADO)
    REFERENCES TREFERENTE_ENUNCIADO (PK_REFERENTE_ENUNCIADO)
);

CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_UNIDAD ON TUNIDAD_ENUNCIADO (FK_TUNIDAD);

CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_ENUNCIADO ON TUNIDAD_ENUNCIADO (FK_REFERENTE_ENUNCIADO);

CREATE INDEX IF NOT EXISTS IDX_TUNIDAD_ENUNCIADO_ACTIVE ON TUNIDAD_ENUNCIADO (PK_TUNIDAD_ENUNCIADO) WHERE ACTIVE = true;

CREATE UNIQUE INDEX IF NOT EXISTS U_TUNIDAD_ENUNCIADO_1
  ON TUNIDAD_ENUNCIADO (FK_TUNIDAD, FK_REFERENTE_ENUNCIADO)
  WHERE ACTIVE = true;

COMMENT ON COLUMN TUNIDAD_ENUNCIADO.PK_TUNIDAD_ENUNCIADO IS 'Llave primaria de la tabla';

COMMENT ON COLUMN TUNIDAD_ENUNCIADO.FK_TUNIDAD IS 'Llave foranea a tabla TUNIDAD';

COMMENT ON COLUMN TUNIDAD_ENUNCIADO.FK_REFERENTE_ENUNCIADO IS 'Llave foranea a TREFERENTE_ENUNCIADO (nivel 1, FK_PADRE IS NULL) del mismo nivel de ensenanza que la unidad; el enunciado marcado como aplicable/seleccionado para esa unidad';

COMMENT ON TABLE TUNIDAD_ENUNCIADO IS 'Relacion N:N entre TUNIDAD y los enunciados (TREFERENTE_ENUNCIADO nivel 1) del referente curricular que aplican a esa unidad';

CREATE TABLE IF NOT EXISTS TACTIVIDAD_EVIDENCIA (
  PK_TACTIVIDAD_EVIDENCIA BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD BIGINT NOT NULL,
  FK_REFERENTE_ENUNCIADO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TACTIVIDAD_EVIDENCIA PRIMARY KEY (PK_TACTIVIDAD_EVIDENCIA),
  CONSTRAINT FK_TACTIVIDAD_EVIDENCIA_ACTIVIDAD FOREIGN KEY (FK_TACTIVIDAD)
    REFERENCES TACTIVIDAD (PK_TACTIVIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TACTIVIDAD_EVIDENCIA_EVIDENCIA FOREIGN KEY (FK_REFERENTE_ENUNCIADO)
    REFERENCES TREFERENTE_ENUNCIADO (PK_REFERENTE_ENUNCIADO)
);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_ACTIVIDAD ON TACTIVIDAD_EVIDENCIA (FK_TACTIVIDAD);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_EVIDENCIA ON TACTIVIDAD_EVIDENCIA (FK_REFERENTE_ENUNCIADO);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_EVIDENCIA_ACTIVE ON TACTIVIDAD_EVIDENCIA (PK_TACTIVIDAD_EVIDENCIA) WHERE ACTIVE = true;

CREATE UNIQUE INDEX IF NOT EXISTS U_TACTIVIDAD_EVIDENCIA_1
  ON TACTIVIDAD_EVIDENCIA (FK_TACTIVIDAD, FK_REFERENTE_ENUNCIADO)
  WHERE ACTIVE = true;

COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.PK_TACTIVIDAD_EVIDENCIA IS 'Llave primaria de la tabla';

COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.FK_TACTIVIDAD IS 'Llave foranea a tabla TACTIVIDAD (debe tener FK_TUNIDAD asignado)';

COMMENT ON COLUMN TACTIVIDAD_EVIDENCIA.FK_REFERENTE_ENUNCIADO IS 'Llave foranea a TREFERENTE_ENUNCIADO (nivel 2, FK_PADRE NOT NULL = evidencia) cuyo enunciado padre esta relacionado con la unidad de la actividad (TUNIDAD_ENUNCIADO)';

COMMENT ON TABLE TACTIVIDAD_EVIDENCIA IS 'Relacion N:N entre TACTIVIDAD y las evidencias (TREFERENTE_ENUNCIADO nivel 2) del enunciado relacionado con la unidad de esa actividad';

CREATE TABLE IF NOT EXISTS TACTIVIDAD_CRITERIO_UNIDAD (
  PK_TACTIVIDAD_CRITERIO_UNIDAD BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD BIGINT NOT NULL,
  FK_TCRITERIO_UNIDAD BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TACTIVIDAD_CRITERIO_UNIDAD PRIMARY KEY (PK_TACTIVIDAD_CRITERIO_UNIDAD),
  CONSTRAINT FK_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVIDAD FOREIGN KEY (FK_TACTIVIDAD)
    REFERENCES TACTIVIDAD (PK_TACTIVIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TACTIVIDAD_CRITERIO_UNIDAD_CRITERIO FOREIGN KEY (FK_TCRITERIO_UNIDAD)
    REFERENCES TCRITERIO_UNIDAD (PK_TCRITERIO_UNIDAD)
);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVIDAD ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TACTIVIDAD);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_CRITERIO ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TCRITERIO_UNIDAD);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_CRITERIO_UNIDAD_ACTIVE ON TACTIVIDAD_CRITERIO_UNIDAD (PK_TACTIVIDAD_CRITERIO_UNIDAD) WHERE ACTIVE = true;

CREATE UNIQUE INDEX IF NOT EXISTS U_TACTIVIDAD_CRITERIO_UNIDAD_1
  ON TACTIVIDAD_CRITERIO_UNIDAD (FK_TACTIVIDAD, FK_TCRITERIO_UNIDAD)
  WHERE ACTIVE = true;

COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.PK_TACTIVIDAD_CRITERIO_UNIDAD IS 'Llave primaria de la tabla';

COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.FK_TACTIVIDAD IS 'Llave foranea a tabla TACTIVIDAD (debe tener FK_TUNIDAD asignado)';

COMMENT ON COLUMN TACTIVIDAD_CRITERIO_UNIDAD.FK_TCRITERIO_UNIDAD IS 'Llave foranea a TCRITERIO_UNIDAD; debe pertenecer a la rubrica (TRUBRICA_UNIDAD) de la misma unidad de la actividad';

COMMENT ON TABLE TACTIVIDAD_CRITERIO_UNIDAD IS 'Relacion N:N entre TACTIVIDAD y los criterios (TCRITERIO_UNIDAD) de la rubrica de la unidad de esa actividad que se seleccionaron para evaluarla';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_evidencia_relacionar(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tactividad            BIGINT,
    p_fk_referente_enunciado   BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_titulo_actividad    VARCHAR;
    v_fk_tunidad          BIGINT;
    v_padre_evidencia     BIGINT;
    v_pk                  BIGINT;
BEGIN
    -- 0. Gate: capability EDITAR sobre PLANEADOR.
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, p_fk_tactividad
    );

    -- 1. Obligatorios.
    IF p_fk_tactividad IS NULL THEN
        RAISE EXCEPTION 'La actividad (FK_TACTIVIDAD) es obligatoria' USING ERRCODE = '22023';
    END IF;
    IF p_fk_referente_enunciado IS NULL THEN
        RAISE EXCEPTION 'La evidencia (FK_REFERENTE_ENUNCIADO) es obligatoria' USING ERRCODE = '22023';
    END IF;

    -- 2. Actividad existe/activa y tiene unidad relacionada (FK_TUNIDAD
    --    NOT NULL).
    SELECT a.TITULO, a.FK_TUNIDAD
      INTO v_titulo_actividad, v_fk_tunidad
      FROM academico_test.TACTIVIDAD a
     WHERE a.PK_TACTIVIDAD = p_fk_tactividad
       AND a.ACTIVE = TRUE;

    IF v_titulo_actividad IS NULL THEN
        RAISE EXCEPTION 'FK_TACTIVIDAD (%) no existe o no esta activa', p_fk_tactividad USING ERRCODE = '23503';
    END IF;
    IF v_fk_tunidad IS NULL THEN
        RAISE EXCEPTION 'La actividad "%" no tiene una unidad relacionada (FK_TUNIDAD)', v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 3. Evidencia existe/activa y es nivel 2 (FK_PADRE NOT NULL).
    SELECT e.FK_PADRE INTO v_padre_evidencia
      FROM academico_test.TREFERENTE_ENUNCIADO e
     WHERE e.PK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado
       AND e.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) no existe o no esta activo', p_fk_referente_enunciado USING ERRCODE = '23503';
    END IF;
    IF v_padre_evidencia IS NULL THEN
        RAISE EXCEPTION 'FK_REFERENTE_ENUNCIADO (%) es un enunciado (nivel 1), no una evidencia (nivel 2)', p_fk_referente_enunciado
            USING ERRCODE = '22023';
    END IF;

    -- 4. Regla de negocio: el enunciado padre de la evidencia debe estar
    --    relacionado (activo) con la unidad de la actividad.
    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TUNIDAD_ENUNCIADO ue
         WHERE ue.FK_TUNIDAD = v_fk_tunidad
           AND ue.FK_REFERENTE_ENUNCIADO = v_padre_evidencia
           AND ue.ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'El enunciado padre de la evidencia (%) no esta relacionado con la unidad de la actividad "%"', p_fk_referente_enunciado, v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 5. Get-or-create / reactivar sobre el indice unico parcial.
    SELECT PK_TACTIVIDAD_EVIDENCIA INTO v_pk
      FROM academico_test.TACTIVIDAD_EVIDENCIA
     WHERE FK_TACTIVIDAD = p_fk_tactividad
       AND FK_REFERENTE_ENUNCIADO = p_fk_referente_enunciado;

    IF v_pk IS NULL THEN
        INSERT INTO academico_test.TACTIVIDAD_EVIDENCIA (
            FK_TACTIVIDAD, FK_REFERENTE_ENUNCIADO, CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_fk_tactividad, p_fk_referente_enunciado, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TACTIVIDAD_EVIDENCIA INTO v_pk;
    ELSE
        UPDATE academico_test.TACTIVIDAD_EVIDENCIA
           SET ACTIVE = TRUE,
               MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
               MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE PK_TACTIVIDAD_EVIDENCIA = v_pk;
    END IF;

    RETURN v_pk;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_evidencia_relacionar(BIGINT, BIGINT, BIGINT)
    IS 'Relaciona (o reactiva) una evidencia del referente curricular (TREFERENTE_ENUNCIADO nivel 2, FK_PADRE NOT NULL) con una actividad (TACTIVIDAD_EVIDENCIA), exigiendo que la actividad tenga FK_TUNIDAD y que el enunciado padre de la evidencia ya este relacionado (TUNIDAD_ENUNCIADO, activo) con esa misma unidad. Gate EDITAR sobre PLANEADOR. Retorna PK_TACTIVIDAD_EVIDENCIA. V214.1.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_evidencia_quitar(
    p_pk_usuario_solicitante     BIGINT,
    p_pk_tactividad_evidencia    BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, (SELECT ae.FK_TACTIVIDAD FROM academico_test.TACTIVIDAD_EVIDENCIA ae
                           WHERE ae.PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TACTIVIDAD_EVIDENCIA
         WHERE PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'PK_TACTIVIDAD_EVIDENCIA (%) no existe o ya esta inactivo', p_pk_tactividad_evidencia USING ERRCODE = '23503';
    END IF;

    UPDATE academico_test.TACTIVIDAD_EVIDENCIA
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_EVIDENCIA = p_pk_tactividad_evidencia;

    RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_evidencia_quitar(BIGINT, BIGINT)
    IS 'Borrado logico (ACTIVE=FALSE) de una relacion TACTIVIDAD_EVIDENCIA. Gate EDITAR sobre PLANEADOR. V214.1.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_criterio_relacionar(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tactividad            BIGINT,
    p_fk_tcriterio_unidad      BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_titulo_actividad    VARCHAR;
    v_fk_tunidad          BIGINT;
    v_descripcion_criterio VARCHAR;
    v_fk_tunidad_criterio  BIGINT;
    v_pk                  BIGINT;
BEGIN
    -- 0. Gate: capability EDITAR sobre PLANEADOR.
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, p_fk_tactividad
    );

    -- 1. Obligatorios.
    IF p_fk_tactividad IS NULL THEN
        RAISE EXCEPTION 'La actividad (FK_TACTIVIDAD) es obligatoria' USING ERRCODE = '22023';
    END IF;
    IF p_fk_tcriterio_unidad IS NULL THEN
        RAISE EXCEPTION 'El criterio (FK_TCRITERIO_UNIDAD) es obligatorio' USING ERRCODE = '22023';
    END IF;

    -- 2. Actividad existe/activa y tiene unidad relacionada (FK_TUNIDAD
    --    NOT NULL).
    SELECT a.TITULO, a.FK_TUNIDAD
      INTO v_titulo_actividad, v_fk_tunidad
      FROM academico_test.TACTIVIDAD a
     WHERE a.PK_TACTIVIDAD = p_fk_tactividad
       AND a.ACTIVE = TRUE;

    IF v_titulo_actividad IS NULL THEN
        RAISE EXCEPTION 'FK_TACTIVIDAD (%) no existe o no esta activa', p_fk_tactividad USING ERRCODE = '23503';
    END IF;
    IF v_fk_tunidad IS NULL THEN
        RAISE EXCEPTION 'La actividad "%" no tiene una unidad relacionada (FK_TUNIDAD)', v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 3. Criterio existe/activo; su unidad (via la rubrica).
    SELECT cu.DESCRIPCION, ru.FK_TUNIDAD
      INTO v_descripcion_criterio, v_fk_tunidad_criterio
      FROM academico_test.TCRITERIO_UNIDAD cu
      JOIN academico_test.TRUBRICA_UNIDAD ru ON ru.PK_TRUBRICA_UNIDAD = cu.FK_TRUBRICA_UNIDAD
     WHERE cu.PK_TCRITERIO_UNIDAD = p_fk_tcriterio_unidad
       AND cu.ACTIVE = TRUE;

    IF v_descripcion_criterio IS NULL THEN
        RAISE EXCEPTION 'FK_TCRITERIO_UNIDAD (%) no existe o no esta activo', p_fk_tcriterio_unidad USING ERRCODE = '23503';
    END IF;

    -- 4. Regla de negocio: el criterio debe pertenecer a la rubrica de la
    --    MISMA unidad de la actividad.
    IF v_fk_tunidad_criterio IS DISTINCT FROM v_fk_tunidad THEN
        RAISE EXCEPTION 'El criterio (%) pertenece a la rubrica de una unidad distinta a la de la actividad "%"', p_fk_tcriterio_unidad, v_titulo_actividad
            USING ERRCODE = '22023';
    END IF;

    -- 5. Get-or-create / reactivar sobre el indice unico parcial.
    SELECT PK_TACTIVIDAD_CRITERIO_UNIDAD INTO v_pk
      FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD
     WHERE FK_TACTIVIDAD = p_fk_tactividad
       AND FK_TCRITERIO_UNIDAD = p_fk_tcriterio_unidad;

    IF v_pk IS NULL THEN
        INSERT INTO academico_test.TACTIVIDAD_CRITERIO_UNIDAD (
            FK_TACTIVIDAD, FK_TCRITERIO_UNIDAD, CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_fk_tactividad, p_fk_tcriterio_unidad, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TACTIVIDAD_CRITERIO_UNIDAD INTO v_pk;
    ELSE
        UPDATE academico_test.TACTIVIDAD_CRITERIO_UNIDAD
           SET ACTIVE = TRUE,
               MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
               MODIFIED_AT = CURRENT_TIMESTAMP
         WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = v_pk;
    END IF;

    RETURN v_pk;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_criterio_relacionar(BIGINT, BIGINT, BIGINT)
    IS 'Relaciona (o reactiva) un criterio de la rubrica de la unidad (TCRITERIO_UNIDAD) con una actividad (TACTIVIDAD_CRITERIO_UNIDAD), exigiendo que la actividad tenga FK_TUNIDAD y que el criterio pertenezca a la rubrica (TRUBRICA_UNIDAD) de esa misma unidad. Gate EDITAR sobre PLANEADOR. Retorna PK_TACTIVIDAD_CRITERIO_UNIDAD. V214.1.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_criterio_quitar(
    p_pk_usuario_solicitante          BIGINT,
    p_pk_tactividad_criterio_unidad   BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL, (SELECT ac.FK_TACTIVIDAD FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD ac
                           WHERE ac.PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TACTIVIDAD_CRITERIO_UNIDAD
         WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'PK_TACTIVIDAD_CRITERIO_UNIDAD (%) no existe o ya esta inactivo', p_pk_tactividad_criterio_unidad USING ERRCODE = '23503';
    END IF;

    UPDATE academico_test.TACTIVIDAD_CRITERIO_UNIDAD
       SET ACTIVE = FALSE,
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR,
           MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_CRITERIO_UNIDAD = p_pk_tactividad_criterio_unidad;

    RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_criterio_quitar(BIGINT, BIGINT)
    IS 'Borrado logico (ACTIVE=FALSE) de una relacion TACTIVIDAD_CRITERIO_UNIDAD. Gate EDITAR sobre PLANEADOR. V214.1.';
