-- ===========================================================================
-- V224 - Actividades: catalogos, TACTIVIDAD_ADAPTACION_ESTUDIANTE, indices,
-- helpers, reemplazo de materiales/adaptaciones, asignacion de estudiantes,
-- resumen de estados, finalizacion (triggers + backfill).
--
--   fn_actividad_listar se crea solo si falta: fn_planilla_actividades_universo
--   (V239, LANGUAGE sql) la necesita en una base limpia; la vigente es V454.
--   El CRUD, buscar, estado, recuperacion, listar_docente y calendario viven
--   en V251-V482.
-- ===========================================================================


SET search_path TO academico_test, public;

INSERT INTO academico_test.tlista_valor (categoria, nombre, valor, created_by)
SELECT v.categoria, v.nombre, v.valor, 'V224_seed'
  FROM (VALUES
    
    ('MODALIDAD'::VARCHAR,              'Presencial'::VARCHAR,                'PRESENCIAL'::VARCHAR),
    ('MODALIDAD',                       'Virtual',                            'VIRTUAL'),
    ('MODALIDAD',                       'Mixta',                              'MIXTA'),
    
    ('INSTRUMENTO_EVALUACION',          'Rúbrica',                            'RUBRICA'),
    ('INSTRUMENTO_EVALUACION',          'Lista de cotejo',                    'LISTA_COTEJO'),
    ('INSTRUMENTO_EVALUACION',          'Escala de valoración',               'ESCALA_VALORACION'),
    ('INSTRUMENTO_EVALUACION',          'Otro (personalizado)',               'OTRO'),
    
    
    ('DESTINO_RECUPERACION',            'Recuperar una actividad',            'ACTIVIDAD'),
    ('DESTINO_RECUPERACION',            'Recuperar la nota final',            'NOTA_FINAL'),
    ('TIPO_APLICACION_RECUPERACION',    'Computar con la nota anterior',      'COMPUTAR'),
    ('TIPO_APLICACION_RECUPERACION',    'Reemplazar la nota anterior',        'REEMPLAZAR'),
    ('TIPO_CALCULO_RECUPERACION',       'Promediado',                         'PROMEDIADO'),
    ('TIPO_CALCULO_RECUPERACION',       'Ponderado',                          'PONDERADO'),
    
    ('TIPO_EVIDENCIA',                  'Archivo',                            'ARCHIVO'),
    ('TIPO_EVIDENCIA',                  'Enlace',                             'ENLACE'),
    ('TIPO_EVIDENCIA',                  'Imagen',                             'IMAGEN'),
    ('TIPO_EVIDENCIA',                  'Video',                              'VIDEO'),
    ('TIPO_EVIDENCIA',                  'Observación',                        'OBSERVACION'),
    
    
    
    ('TIPO_RECURSO',                    'URL / Sitio web',                    'URL'),
    ('TIPO_RECURSO',                    'Archivo en PC',                      'ARCHIVO'),
    ('TIPO_RECURSO',                    'Unidad virtual / repositorio',       'REPOSITORIO'),
    
    
    ('TIPO_ADAPTACION',                 'Discapacidad visual',                             'DISCAPACIDAD_VISUAL'),
    ('TIPO_ADAPTACION',                 'Discapacidad auditiva',                           'DISCAPACIDAD_AUDITIVA'),
    ('TIPO_ADAPTACION',                 'Dificultades cognitivas',                         'DIFICULTADES_COGNITIVAS'),
    ('TIPO_ADAPTACION',                 'Estilo de aprendizaje (visual, kinestésico, auditivo)', 'ESTILO_APRENDIZAJE'),
    ('TIPO_ADAPTACION',                 'Modalidad (virtual, asincrónica, presencial)',    'MODALIDAD'),
    ('TIPO_ADAPTACION',                 'Nivel de desempeño (refuerzo, ampliación)',       'NIVEL_DESEMPENO'),
    ('TIPO_ADAPTACION',                 'Otro',                                            'OTRO'),
    
    
    
    
    ('FORMATO_ADAPTACION',              'Archivo',                            'ARCHIVO'),
    ('FORMATO_ADAPTACION',              'Enlace',                             'ENLACE'),
    ('FORMATO_ADAPTACION',              'Biblioteca',                         'BIBLIOTECA'),
    
    
    
    ('APLICA_A',                        'Todo el grupo',                      'TODO_EL_GRUPO'),
    ('APLICA_A',                        'Estudiantes seleccionados',          'ESTUDIANTES_SELECCIONADOS')
  ) AS v(categoria, nombre, valor)
 WHERE NOT EXISTS (
     SELECT 1 FROM academico_test.tlista_valor lv
      WHERE lv.categoria = v.categoria AND lv.valor = v.valor
 );

UPDATE academico_test.tlista_valor
   SET ACTIVE = FALSE, MODIFIED_BY = 'V224_seed_fix', MODIFIED_AT = CURRENT_TIMESTAMP
 WHERE CATEGORIA = 'TIPO_EVIDENCIA'
   AND VALOR IN ('TEXTO', 'OTRO')
   AND ACTIVE = TRUE;

CREATE TABLE IF NOT EXISTS TACTIVIDAD_ADAPTACION_ESTUDIANTE (
  PK_TACTIVIDAD_ADAPTACION_ESTUDIANTE BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD_ADAPTACION BIGINT NOT NULL,
  FK_TACTIVIDAD_ESTUDIANTE BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TAC_ADAPTACION_ESTUDIANTE PRIMARY KEY (PK_TACTIVIDAD_ADAPTACION_ESTUDIANTE),
  CONSTRAINT FK_TAC_ADAPT_EST_1 FOREIGN KEY (FK_TACTIVIDAD_ADAPTACION)
    REFERENCES TACTIVIDAD_ADAPTACION (PK_TACTIVIDAD_ADAPTACION) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_ADAPT_EST_2 FOREIGN KEY (FK_TACTIVIDAD_ESTUDIANTE)
    REFERENCES TACTIVIDAD_ESTUDIANTE (PK_TACTIVIDAD_ESTUDIANTE) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_TAC_ADAPT_EST_1
    ON TACTIVIDAD_ADAPTACION_ESTUDIANTE (FK_TACTIVIDAD_ADAPTACION) WHERE ACTIVE = TRUE;

CREATE INDEX IF NOT EXISTS IDX_TAC_ADAPT_EST_2
    ON TACTIVIDAD_ADAPTACION_ESTUDIANTE (FK_TACTIVIDAD_ESTUDIANTE) WHERE ACTIVE = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS U_TAC_ADAPTACION_ESTUDIANTE_1
    ON TACTIVIDAD_ADAPTACION_ESTUDIANTE (FK_TACTIVIDAD_ADAPTACION, FK_TACTIVIDAD_ESTUDIANTE)
 WHERE ACTIVE = TRUE;

COMMENT ON COLUMN TACTIVIDAD_ADAPTACION_ESTUDIANTE.FK_TACTIVIDAD_ADAPTACION IS 'Adaptacion curricular. ON DELETE CASCADE';

COMMENT ON COLUMN TACTIVIDAD_ADAPTACION_ESTUDIANTE.FK_TACTIVIDAD_ESTUDIANTE IS 'Asignacion actividad-estudiante a la que aplica la adaptacion (garantiza que el estudiante este asignado a esa actividad)';

COMMENT ON TABLE TACTIVIDAD_ADAPTACION_ESTUDIANTE IS 'Estudiantes concretos del grupo a los que aplica una adaptacion curricular. Solo tiene filas cuando TACTIVIDAD_ADAPTACION.FK_TLV_APLICA_A = ESTUDIANTES_SELECCIONADOS; con TODO_EL_GRUPO va vacia. V224.';

COMMENT ON COLUMN TACTIVIDAD_ADAPTACION.FK_TLV_APLICA_A IS 'Alcance de la adaptacion dentro del grupo. TLISTA_VALOR CATEGORIA=''APLICA_A'': TODO_EL_GRUPO o ESTUDIANTES_SELECCIONADOS. En el segundo caso, los estudiantes concretos van en TACTIVIDAD_ADAPTACION_ESTUDIANTE (V224).';

ALTER TABLE TACTIVIDAD_ADAPTACION ADD COLUMN IF NOT EXISTS URL VARCHAR(4000);

COMMENT ON COLUMN TACTIVIDAD_ADAPTACION.URL IS 'Enlace a la plantilla modificada del instrumento cuando FK_TLV_FORMATO_ADAPTACION = ENLACE. Para ARCHIVO/BIBLIOTECA se usa FK_TARCHIVO. V224.';

COMMENT ON COLUMN TACTIVIDAD_ADAPTACION.USA_VERSION_MODIFICADA IS 'Indica si se usa una version modificada del instrumento de evaluacion (S/N). Si es ''S'', FK_TLV_FORMATO_ADAPTACION dice de donde sale la plantilla (ARCHIVO/BIBLIOTECA -> FK_TARCHIVO; ENLACE -> URL). CHECK IN (S,N).';

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_tactividad_busqueda_trgm
    ON academico_test.TACTIVIDAD
 USING gin ((COALESCE(TITULO,'') || ' ' || COALESCE(DESCRIPCION,'')) gin_trgm_ops);

COMMENT ON INDEX academico_test.idx_tactividad_busqueda_trgm
    IS 'GIN trigram sobre TITULO+DESCRIPCION concatenados para que p_search (ILIKE %texto%) de fn_actividad_listar no haga Seq Scan. El texto de la expresion debe coincidir exacto con el del WHERE de esa funcion. V224.';

CREATE INDEX IF NOT EXISTS idx_tactividad_asignatura_fechas
    ON academico_test.TACTIVIDAD (FK_TASIGNATURA, FECHA_INICIO, FECHA_CIERRE, PK_TACTIVIDAD)
 WHERE ACTIVE = TRUE;

COMMENT ON INDEX academico_test.idx_tactividad_asignatura_fechas
    IS 'Listado de actividades por asignatura acotado por ventana de fechas (fn_actividad_listar, fn_actividad_calendario). Parcial WHERE ACTIVE para no indexar el historico borrado logicamente. V224.';

CREATE INDEX IF NOT EXISTS idx_tactividad_grupo_fechas
    ON academico_test.TACTIVIDAD (FK_TGRUPO, FECHA_INICIO, FECHA_CIERRE, PK_TACTIVIDAD)
 WHERE ACTIVE = TRUE;

COMMENT ON INDEX academico_test.idx_tactividad_grupo_fechas
    IS 'Grilla mensual y filtros por grupo (fn_actividad_calendario, fn_actividad_listar). V224.';

CREATE INDEX IF NOT EXISTS idx_tactividad_sin_calificar
    ON academico_test.TACTIVIDAD (FECHA_CIERRE, FK_TASIGNATURA, FK_TGRUPO)
 WHERE ACTIVE = TRUE AND FECHA_CALIFICADO IS NULL;

COMMENT ON INDEX academico_test.idx_tactividad_sin_calificar
    IS 'Soporta los contadores "Pendientes por evaluar" y "Vencidas (> N dias)" de fn_actividad_resumen_estados: parcial sobre las actividades vivas aun sin FECHA_CALIFICADO. V224.';

CREATE INDEX IF NOT EXISTS idx_tactividad_estudiante_actividad_activo
    ON academico_test.TACTIVIDAD_ESTUDIANTE (FK_TACTIVIDAD, PK_TACTIVIDAD_ESTUDIANTE)
 WHERE ACTIVE = TRUE;

COMMENT ON INDEX academico_test.idx_tactividad_estudiante_actividad_activo
    IS 'Conteo asignados/evaluados por actividad (LATERAL de fn_actividad_listar y fn_actividad_buscar_por_pk). V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_lv_assert(
    p_fk         BIGINT,
    p_categoria  VARCHAR,
    p_etiqueta   VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_categoria_existe BOOLEAN;
BEGIN
    IF p_fk IS NULL THEN
        RETURN;                     -- opcional: el caller ya exigio si aplica
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TLISTA_VALOR
         WHERE PK_LISTA_VALOR = p_fk AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION '% (%) no existe en TLISTA_VALOR o no esta activo', p_etiqueta, p_fk
            USING ERRCODE = '23503';
    END IF;

    -- La categoria se exige solo si esta seedeada. Tras el bloque (1) de
    -- esta misma migracion todas las categorias usadas aqui existen, asi
    -- que en la practica el chequeo es siempre estricto; el guard queda
    -- como red de seguridad para entornos donde el seed sea no-op.
    SELECT EXISTS (
        SELECT 1 FROM academico_test.TLISTA_VALOR
         WHERE CATEGORIA = p_categoria AND ACTIVE = TRUE
    ) INTO v_categoria_existe;

    IF v_categoria_existe AND NOT EXISTS (
        SELECT 1 FROM academico_test.TLISTA_VALOR
         WHERE PK_LISTA_VALOR = p_fk AND CATEGORIA = p_categoria AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION '% (%) no pertenece a la categoria % de TLISTA_VALOR', p_etiqueta, p_fk, p_categoria
            USING ERRCODE = '23503';
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_lv_assert(BIGINT, VARCHAR, VARCHAR)
    IS 'Valida una FK a TLISTA_VALOR: NULL pasa (opcional), si viene debe existir y estar ACTIVE, y debe ser de p_categoria (se exige solo si esa categoria esta seedeada; tras el seed de V224 siempre lo esta). Lanza 23503 con p_etiqueta en el mensaje. V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_grado_grupo_etiqueta(
    p_grado_nombre  VARCHAR,
    p_grado_codigo  VARCHAR,
    p_grupo_nombre  VARCHAR
)
RETURNS VARCHAR
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT CASE
        -- Sin grupo no hay etiqueta que componer (actividades sin grupo:
        -- criterios, huerfanas). Se devuelve el CODIGO del grado, que es la
        -- parte que aporta el grado a la etiqueta.
        WHEN NULLIF(TRIM(COALESCE(p_grupo_nombre, '')), '') IS NULL
            THEN NULLIF(TRIM(COALESCE(p_grado_codigo, '')), '')
        -- Sin codigo de grado no hay nada que anteponer: el grupo es la etiqueta.
        WHEN NULLIF(TRIM(COALESCE(p_grado_codigo, '')), '') IS NULL
            THEN TRIM(p_grupo_nombre)
        -- El nombre del grupo YA viene prefijado con el codigo del grado
        -- ('803M' para el grado '8'): concatenar daria '8803M'. Ya es la
        -- etiqueta, se devuelve tal cual. UNICA salvaguarda de la regla.
        WHEN TRIM(p_grupo_nombre) LIKE TRIM(p_grado_codigo) || '%'
            THEN TRIM(p_grupo_nombre)
        -- La regla: CODIGO del grado + nombre del grupo, sin separador.
        --   grado '6'  + grupo '01' -> '601'
        --   grado '-2' + grupo '01' -> '-201'  (Preescolar usa codigos negativos)
        ELSE TRIM(p_grado_codigo) || TRIM(p_grupo_nombre)
    END::VARCHAR;
$$;

COMMENT ON FUNCTION academico_test.fn_grado_grupo_etiqueta(VARCHAR, VARCHAR, VARCHAR)
    IS 'Etiqueta "grado-grupo" de una actividad -- el "601" de cada celda del calendario y de cada tarjeta del prototipo --, con UNA sola definicion para el listado, el tablero, el calendario y el detalle. Regla: CODIGO del grado + nombre del grupo, sin separador (grado ''6'' + grupo ''01'' -> ''601''). Se usa TGRADO.CODIGO y no TGRADO.NOMBRE porque el codigo es la parte corta que pinta el prototipo; en Preescolar los codigos son negativos (''-2'' Pre-Jardin) y la etiqueta sale ''-201'', que es el resultado de la regla y se acepta a proposito. UNICA salvaguarda: en los grupos cargados de verdad TGRUPO.NOMBRE ya incluye el codigo del grado (''803M'' para el grado ''8''), asi que concatenar daria ''8803M''; cuando el nombre del grupo ya empieza por el codigo se devuelve tal cual porque ya ES la etiqueta. En los grupos sembrados a mano el nombre es solo el consecutivo (''01'') y ahi la concatenacion si aplica. Sin grupo (criterios, huerfanas) devuelve el codigo del grado solo, o NULL; sin codigo de grado, el nombre del grupo. IMMUTABLE. V224.';

-- La version vigente es posterior; esta solo hace falta en una base limpia (fn_unidad_estado, LANGUAGE sql).
DO $guarda$
BEGIN
    IF to_regprocedure('academico_test.fn_actividad_estado(date,date,date,date,integer)') IS NULL THEN
        EXECUTE $crear$CREATE OR REPLACE FUNCTION academico_test.fn_actividad_estado(
    p_fecha_inicio      DATE,
    p_fecha_cierre      DATE,
    p_fecha_calificado  DATE,
    p_hoy               DATE,
    p_dias_gracia       INT DEFAULT 2
)
RETURNS VARCHAR
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT CASE
        WHEN p_fecha_calificado IS NOT NULL                                  THEN 'FINALIZADA'
        WHEN p_fecha_cierre IS NOT NULL
         AND p_hoy > p_fecha_cierre + COALESCE(p_dias_gracia, 2)             THEN 'VENCIDA'
        -- Vigente: hoy cae dentro de la ventana. Que falte UN extremo no
        -- invalida la vigencia (solo-inicio ya empezado, o solo-cierre aun no
        -- pasado); sin NINGUNA fecha no es vigente y cae a pendiente.
        WHEN (p_fecha_inicio IS NOT NULL OR p_fecha_cierre IS NOT NULL)
         AND (p_fecha_inicio IS NULL OR p_hoy >= p_fecha_inicio)
         AND (p_fecha_cierre IS NULL OR p_hoy <= p_fecha_cierre)             THEN 'EN_EVALUACION'
        ELSE 'PENDIENTE_POR_EVALUAR'
    END::VARCHAR;
$$$crear$;
    END IF;
END $guarda$;

CREATE OR REPLACE FUNCTION academico_test.fn_unidad_estado(
    p_pk_tunidad   BIGINT,
    p_hoy          DATE,
    p_dias_gracia  INT DEFAULT 2
)
RETURNS VARCHAR
LANGUAGE sql
STABLE
AS $$
    WITH estados AS (
        SELECT academico_test.fn_actividad_estado(
                   a.FECHA_INICIO, a.FECHA_CIERRE, a.FECHA_CALIFICADO,
                   p_hoy, p_dias_gracia) AS estado
          FROM academico_test.TACTIVIDAD a
         WHERE a.FK_TUNIDAD = p_pk_tunidad
           AND a.ACTIVE = TRUE
    )
    SELECT CASE
        WHEN COUNT(*) FILTER (WHERE estado = 'VENCIDA') > 0
            THEN 'VENCIDA'
        WHEN COUNT(*) FILTER (WHERE estado = 'PENDIENTE_POR_EVALUAR') > 0
            THEN 'PENDIENTE_POR_EVALUAR'
        WHEN COUNT(*) > 0
         AND COUNT(*) = COUNT(*) FILTER (WHERE estado = 'FINALIZADA')
            THEN 'FINALIZADA'
        ELSE 'EN_EVALUACION'
    END::VARCHAR
      FROM estados;
$$;

COMMENT ON FUNCTION academico_test.fn_unidad_estado(BIGINT, DATE, INT)
    IS 'Estado DERIVADO de una unidad (no hay columna de estado en TUNIDAD), agregando el estado de sus actividades ACTIVAS via fn_actividad_estado -- unica definicion del estado de actividad, no se duplica. El criterio NO es "el peor estado" ni una mayoria: es una cascada de prioridades de negocio, en este orden exacto: (1) UNA sola actividad VENCIDA -> VENCIDA; (2) sin vencidas pero alguna PENDIENTE_POR_EVALUAR -> PENDIENTE_POR_EVALUAR; (3) TODAS finalizadas -> FINALIZADA; (4) cualquier otro caso -> EN_EVALUACION. Devuelve exactamente los cuatro valores de fn_actividad_estado para que el front use la misma paleta en el chip de la unidad y en el de la actividad, sin traducir. CASO BORDE: una unidad SIN actividades activas cae en la rama 4 (EN_EVALUACION) -- es la lectura literal del criterio y evita un quinto estado que el front no tendria donde pintar; para distinguirla, el listado devuelve total_actividades = 0 en la misma fila. p_dias_gracia se propaga tal cual a fn_actividad_estado (default 2). V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_material_reemplazar(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad            BIGINT,
    p_materiales               JSONB
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_insertados INT := 0;
BEGIN
    IF p_materiales IS NULL THEN
        RETURN 0;                          -- NULL = no tocar la lista
    END IF;
    IF jsonb_typeof(p_materiales) <> 'array' THEN
        RAISE EXCEPTION 'p_materiales debe ser un arreglo JSON' USING ERRCODE = '22023';
    END IF;

    -- Cada elemento debe traer EXACTAMENTE uno de url / fkTarchivo
    -- (mismo criterio que el CHECK CK_TACTIVIDAD_MATERIAL_RECURSO de V22).
    IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(p_materiales) e
         WHERE (NULLIF(TRIM(e->>'url'), '') IS NULL) = ((e->>'fkTarchivo') IS NULL)
    ) THEN
        RAISE EXCEPTION 'Cada material debe traer url O fkTarchivo (exactamente uno)'
            USING ERRCODE = '22023';
    END IF;
    IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(p_materiales) e
         WHERE (e->>'tipoRecurso') IS NULL
    ) THEN
        RAISE EXCEPTION 'Cada material requiere tipoRecurso (FK a TLISTA_VALOR, categoria TIPO_RECURSO)'
            USING ERRCODE = '22023';
    END IF;

    PERFORM academico_test.fn_actividad_lv_assert(
                (e->>'tipoRecurso')::BIGINT, 'TIPO_RECURSO', 'tipoRecurso')
       FROM jsonb_array_elements(p_materiales) e;

    IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(p_materiales) e
         WHERE (e->>'fkTarchivo') IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM academico_test.TARCHIVO t
                            WHERE t.PK_TARCHIVO = (e->>'fkTarchivo')::BIGINT)
    ) THEN
        RAISE EXCEPTION 'Uno o mas fkTarchivo no existen en TARCHIVO' USING ERRCODE = '23503';
    END IF;

    UPDATE academico_test.TACTIVIDAD_MATERIAL
       SET ACTIVE = FALSE, MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE FK_TACTIVIDAD = p_pk_tactividad AND ACTIVE = TRUE;

    INSERT INTO academico_test.TACTIVIDAD_MATERIAL (
        FK_TACTIVIDAD, ORDEN, FK_TLV_TIPO_RECURSO, URL, FK_TARCHIVO, DESCRIPCION,
        CREATED_BY, CREATED_AT, ACTIVE
    )
    SELECT p_pk_tactividad,
           e.pos,
           (e.j->>'tipoRecurso')::BIGINT,
           NULLIF(TRIM(e.j->>'url'), ''),
           (e.j->>'fkTarchivo')::BIGINT,
           NULLIF(TRIM(e.j->>'descripcion'), ''),
           p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
      FROM (SELECT elem AS j, ord AS pos
              FROM jsonb_array_elements(p_materiales) WITH ORDINALITY AS t(elem, ord)) e;

    GET DIAGNOSTICS v_insertados = ROW_COUNT;
    RETURN v_insertados;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_material_reemplazar(BIGINT, BIGINT, JSONB)
    IS 'Reemplazo completo de los materiales de apoyo de una actividad (TACTIVIDAD_MATERIAL): desactiva los ACTIVE y re-inserta los del array con ORDEN por posicion. p_materiales NULL = no tocar; array vacio = dejarla sin materiales. Cada elemento {tipoRecurso, url|fkTarchivo, descripcion?} debe traer exactamente uno de url/fkTarchivo (CHECK de V22). Para REUTILIZAR un archivo ya usado en otra actividad, se pasa el mismo fkTarchivo (obtenido de fn_actividad_materiales_reutilizables_listar) con tipoRecurso=REPOSITORIO -- no hay restriccion que lo impida, un TARCHIVO puede estar referenciado por N filas TACTIVIDAD_MATERIAL de distintas actividades. Helper de fn_actividad_crear/_actualizar. Retorna cuantos quedaron. V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_adaptacion_reemplazar(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad            BIGINT,
    p_adaptaciones             JSONB
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_elem        JSONB;
    v_pk_adapt    BIGINT;
    v_formato_val VARCHAR;
    v_aplica_val  VARCHAR;
    v_usa         VARCHAR(1);
    v_insertadas  INT := 0;
BEGIN
    IF p_adaptaciones IS NULL THEN
        RETURN 0;                          -- NULL = no tocar la lista
    END IF;
    IF jsonb_typeof(p_adaptaciones) <> 'array' THEN
        RAISE EXCEPTION 'p_adaptaciones debe ser un arreglo JSON' USING ERRCODE = '22023';
    END IF;

    -- Soft delete de las actuales (el pivote de estudiantes cae con ellas).
    UPDATE academico_test.TACTIVIDAD_ADAPTACION_ESTUDIANTE ae
       SET ACTIVE = FALSE, MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
      FROM academico_test.TACTIVIDAD_ADAPTACION ad
     WHERE ae.FK_TACTIVIDAD_ADAPTACION = ad.PK_TACTIVIDAD_ADAPTACION
       AND ad.FK_TACTIVIDAD = p_pk_tactividad
       AND ae.ACTIVE = TRUE;

    UPDATE academico_test.TACTIVIDAD_ADAPTACION
       SET ACTIVE = FALSE, MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE FK_TACTIVIDAD = p_pk_tactividad AND ACTIVE = TRUE;

    FOR v_elem IN SELECT * FROM jsonb_array_elements(p_adaptaciones) LOOP
        -- 1. Obligatorios.
        IF (v_elem->>'tipoAdaptacion') IS NULL
           OR NULLIF(TRIM(v_elem->>'descripcion'), '') IS NULL THEN
            RAISE EXCEPTION 'Cada adaptacion requiere tipoAdaptacion y descripcion'
                USING ERRCODE = '22023';
        END IF;
        IF LENGTH(TRIM(v_elem->>'descripcion')) > 500 THEN
            RAISE EXCEPTION 'La descripcion de la adaptacion no puede pasar de 500 caracteres'
                USING ERRCODE = '22023';
        END IF;

        v_usa := UPPER(TRIM(COALESCE(v_elem->>'usaVersionModificada', 'N')));
        IF v_usa NOT IN ('S','N') THEN
            RAISE EXCEPTION 'usaVersionModificada solo acepta ''S'' o ''N''' USING ERRCODE = '22023';
        END IF;

        -- 2. Catalogos.
        PERFORM academico_test.fn_actividad_lv_assert((v_elem->>'tipoAdaptacion')::BIGINT,    'TIPO_ADAPTACION',    'tipoAdaptacion');
        PERFORM academico_test.fn_actividad_lv_assert((v_elem->>'formatoAdaptacion')::BIGINT, 'FORMATO_ADAPTACION', 'formatoAdaptacion');
        PERFORM academico_test.fn_actividad_lv_assert((v_elem->>'aplicaA')::BIGINT,           'APLICA_A',           'aplicaA');

        SELECT VALOR INTO v_formato_val FROM academico_test.TLISTA_VALOR
         WHERE PK_LISTA_VALOR = (v_elem->>'formatoAdaptacion')::BIGINT;
        SELECT VALOR INTO v_aplica_val  FROM academico_test.TLISTA_VALOR
         WHERE PK_LISTA_VALOR = (v_elem->>'aplicaA')::BIGINT;

        -- 3. Version modificada: el formato manda que se exige.
        IF v_usa = 'S' THEN
            IF v_formato_val IS NULL THEN
                RAISE EXCEPTION 'Con usaVersionModificada = ''S'' se debe indicar formatoAdaptacion (ARCHIVO, ENLACE o BIBLIOTECA)'
                    USING ERRCODE = '22023';
            END IF;
            IF v_formato_val IN ('ARCHIVO','BIBLIOTECA') AND (v_elem->>'fkTarchivo') IS NULL THEN
                RAISE EXCEPTION 'formatoAdaptacion = % exige fkTarchivo', v_formato_val USING ERRCODE = '22023';
            END IF;
            IF v_formato_val = 'ENLACE' AND NULLIF(TRIM(v_elem->>'url'), '') IS NULL THEN
                RAISE EXCEPTION 'formatoAdaptacion = ENLACE exige url' USING ERRCODE = '22023';
            END IF;
        ELSIF (v_elem->>'formatoAdaptacion') IS NOT NULL THEN
            RAISE EXCEPTION 'formatoAdaptacion solo aplica cuando usaVersionModificada = ''S'''
                USING ERRCODE = '22023';
        END IF;

        IF (v_elem->>'fkTarchivo') IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM academico_test.TARCHIVO t
             WHERE t.PK_TARCHIVO = (v_elem->>'fkTarchivo')::BIGINT
        ) THEN
            RAISE EXCEPTION 'fkTarchivo (%) no existe en TARCHIVO', (v_elem->>'fkTarchivo') USING ERRCODE = '23503';
        END IF;

        -- 4. Alcance.
        IF v_aplica_val = 'ESTUDIANTES_SELECCIONADOS'
           AND (v_elem->'estudiantes' IS NULL
                OR jsonb_typeof(v_elem->'estudiantes') <> 'array'
                OR jsonb_array_length(v_elem->'estudiantes') = 0) THEN
            RAISE EXCEPTION 'aplicaA = ESTUDIANTES_SELECCIONADOS exige la lista "estudiantes" (matriculas) no vacia'
                USING ERRCODE = '22023';
        END IF;
        IF v_aplica_val IS DISTINCT FROM 'ESTUDIANTES_SELECCIONADOS'
           AND jsonb_typeof(v_elem->'estudiantes') = 'array'
           AND jsonb_array_length(v_elem->'estudiantes') > 0 THEN
            RAISE EXCEPTION 'Solo se puede enviar "estudiantes" cuando aplicaA = ESTUDIANTES_SELECCIONADOS'
                USING ERRCODE = '22023';
        END IF;

        -- 5. INSERT de la adaptacion.
        INSERT INTO academico_test.TACTIVIDAD_ADAPTACION (
            FK_TACTIVIDAD, FK_TLV_TIPO_ADAPTACION, DESCRIPCION, USA_VERSION_MODIFICADA,
            FK_TARCHIVO, URL, FK_TLV_FORMATO_ADAPTACION, FK_TLV_APLICA_A,
            CREATED_BY, CREATED_AT, ACTIVE
        ) VALUES (
            p_pk_tactividad,
            (v_elem->>'tipoAdaptacion')::BIGINT,
            TRIM(v_elem->>'descripcion'),
            v_usa,
            (v_elem->>'fkTarchivo')::BIGINT,
            NULLIF(TRIM(v_elem->>'url'), ''),
            (v_elem->>'formatoAdaptacion')::BIGINT,
            (v_elem->>'aplicaA')::BIGINT,
            p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
        )
        RETURNING PK_TACTIVIDAD_ADAPTACION INTO v_pk_adapt;

        -- 6. Estudiantes concretos del grupo a los que aplica.
        IF v_aplica_val = 'ESTUDIANTES_SELECCIONADOS' THEN
            IF EXISTS (
                SELECT 1 FROM jsonb_array_elements_text(v_elem->'estudiantes') mid
                 WHERE NOT EXISTS (
                     SELECT 1 FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
                      WHERE ae.FK_TACTIVIDAD = p_pk_tactividad
                        AND ae.FK_TMATRICULA = mid::BIGINT
                        AND ae.ACTIVE = TRUE
                 )
            ) THEN
                RAISE EXCEPTION 'Una o mas matriculas de la adaptacion no estan asignadas a esta actividad; asigne primero los estudiantes'
                    USING ERRCODE = '23503';
            END IF;

            INSERT INTO academico_test.TACTIVIDAD_ADAPTACION_ESTUDIANTE (
                FK_TACTIVIDAD_ADAPTACION, FK_TACTIVIDAD_ESTUDIANTE,
                CREATED_BY, CREATED_AT, ACTIVE
            )
            SELECT DISTINCT v_pk_adapt, ae.PK_TACTIVIDAD_ESTUDIANTE,
                   p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
              FROM jsonb_array_elements_text(v_elem->'estudiantes') mid
              JOIN academico_test.TACTIVIDAD_ESTUDIANTE ae
                ON ae.FK_TACTIVIDAD = p_pk_tactividad
               AND ae.FK_TMATRICULA = mid::BIGINT
               AND ae.ACTIVE = TRUE;
        END IF;

        v_insertadas := v_insertadas + 1;
    END LOOP;

    RETURN v_insertadas;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_adaptacion_reemplazar(BIGINT, BIGINT, JSONB)
    IS 'Reemplazo completo de las adaptaciones curriculares de una actividad (TACTIVIDAD_ADAPTACION + TACTIVIDAD_ADAPTACION_ESTUDIANTE). p_adaptaciones NULL = no tocar; array vacio = dejarla sin adaptaciones. Sin gate contra unidad/referente: una actividad SIN unidad SI puede tener adaptaciones (confirmado con negocio -- la adaptacion es independiente de si la actividad se evalua formalmente). Elemento {tipoAdaptacion, descripcion(<=500), usaVersionModificada(S/N), formatoAdaptacion?, fkTarchivo?, url?, aplicaA?, estudiantes?[]}. Reglas del figma: con usaVersionModificada=''S'' el formato es obligatorio y ARCHIVO/BIBLIOTECA exigen fkTarchivo mientras ENLACE exige url; con ''N'' no se admite formato. aplicaA=ESTUDIANTES_SELECCIONADOS exige la lista de matriculas, que deben estar YA asignadas a la actividad (por eso se llama despues de fn_actividad_estudiantes_asignar); con TODO_EL_GRUPO la lista debe venir vacia. Retorna cuantas adaptaciones quedaron. V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_estudiantes_asignar(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad            BIGINT,
    
    
    p_fk_tmatriculas           BIGINT[] DEFAULT NULL,
    p_todo_el_grupo            BOOLEAN  DEFAULT FALSE
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_fk_grupo   BIGINT;
    v_set        BIGINT[];
    v_asignados  INT := 0;
BEGIN
    IF p_fk_tmatriculas IS NULL AND NOT p_todo_el_grupo THEN
        RETURN 0;                          -- nada que hacer
    END IF;

    SELECT FK_TGRUPO INTO v_fk_grupo
      FROM academico_test.TACTIVIDAD WHERE PK_TACTIVIDAD = p_pk_tactividad;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la actividad solicitada' USING ERRCODE = 'P0002';
    END IF;

    IF p_fk_tmatriculas IS NULL THEN
        IF v_fk_grupo IS NULL THEN
            RAISE EXCEPTION 'La actividad no tiene grupo (FK_TGRUPO); no se puede asignar "todo el grupo"'
                USING ERRCODE = '22023';
        END IF;
        SELECT COALESCE(array_agg(m.PK_TMATRICULA), ARRAY[]::BIGINT[])
          INTO v_set
          FROM academico_test.TMATRICULA m
         WHERE m.FK_TGRUPO = v_fk_grupo AND m.ACTIVE = TRUE;
    ELSE
        v_set := p_fk_tmatriculas;
        IF array_length(v_set, 1) > 0 AND EXISTS (
            SELECT 1 FROM unnest(v_set) mid
             WHERE NOT EXISTS (
                 SELECT 1 FROM academico_test.TMATRICULA m
                  WHERE m.PK_TMATRICULA = mid
                    AND m.ACTIVE = TRUE
                    AND (v_fk_grupo IS NULL OR m.FK_TGRUPO = v_fk_grupo)
             )
        ) THEN
            RAISE EXCEPTION 'Una o mas matriculas no existen, no estan activas o no pertenecen al grupo de la actividad'
                USING ERRCODE = '23503';
        END IF;
    END IF;

    -- Desactiva las que ya no vienen.
    UPDATE academico_test.TACTIVIDAD_ESTUDIANTE
       SET ACTIVE = FALSE, MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE FK_TACTIVIDAD = p_pk_tactividad
       AND ACTIVE = TRUE
       AND NOT (FK_TMATRICULA = ANY(v_set));

    -- Reactiva las que ya existian desactivadas (respeta UN_TACTIVIDAD_ESTUDIANTE_1).
    UPDATE academico_test.TACTIVIDAD_ESTUDIANTE ae
       SET ACTIVE = TRUE, MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
      FROM unnest(v_set) mid
     WHERE ae.FK_TACTIVIDAD = p_pk_tactividad
       AND ae.FK_TMATRICULA = mid
       AND ae.ACTIVE = FALSE;

    -- Crea las nuevas.
    INSERT INTO academico_test.TACTIVIDAD_ESTUDIANTE (
        FK_TACTIVIDAD, FK_TMATRICULA, CREATED_BY, CREATED_AT, ACTIVE
    )
    SELECT DISTINCT p_pk_tactividad, mid, p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
      FROM unnest(v_set) mid
     WHERE NOT EXISTS (
         SELECT 1 FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
          WHERE ae.FK_TACTIVIDAD = p_pk_tactividad AND ae.FK_TMATRICULA = mid
     );

    SELECT COUNT(*) INTO v_asignados
      FROM academico_test.TACTIVIDAD_ESTUDIANTE
     WHERE FK_TACTIVIDAD = p_pk_tactividad AND ACTIVE = TRUE;

    RETURN v_asignados;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_estudiantes_asignar(BIGINT, BIGINT, BIGINT[], BOOLEAN)
    IS 'Reemplazo completo del pivote TACTIVIDAD_ESTUDIANTE de una actividad. p_fk_tmatriculas NULL + p_todo_el_grupo=TRUE asigna todas las matriculas ACTIVE del FK_TGRUPO de la actividad; un array la fija a ese set exacto (valida existencia/estado/grupo, 23503). Reactiva filas previamente desactivadas en vez de duplicar. Ambos NULL/FALSE = no toca nada (fn_actividad_crear NO asigna estudiantes por defecto). Retorna el total de asignados activos. V224.';

-- La version vigente es posterior; esta solo hace falta en una base limpia (V239).
DO $guarda$
BEGIN
    IF to_regprocedure('academico_test.fn_actividad_listar(bigint,varchar,bigint,bigint,bigint,bigint,bigint,date,date,varchar[],integer,boolean,varchar,boolean,integer,integer,bigint,date)') IS NULL THEN
        EXECUTE $crear$CREATE OR REPLACE FUNCTION academico_test.fn_actividad_listar(
    p_pk_usuario_solicitante   BIGINT,
    p_search                   VARCHAR   DEFAULT NULL,
    p_fk_tasignatura           BIGINT    DEFAULT NULL,
    p_fk_tgrupo                BIGINT    DEFAULT NULL,
    p_fk_tunidad               BIGINT    DEFAULT NULL,
    p_fk_tlv_tipo_actividad    BIGINT    DEFAULT NULL,
    p_fk_tlv_instrumento       BIGINT    DEFAULT NULL,
    p_fecha_desde              DATE      DEFAULT NULL,
    p_fecha_hasta              DATE      DEFAULT NULL,
    
    
    p_estados                  VARCHAR[] DEFAULT NULL,
    p_dias_gracia              INT       DEFAULT 2,
    p_incluir_inactivas        BOOLEAN   DEFAULT FALSE,
    p_orden_por                VARCHAR   DEFAULT 'fecha_inicio',
    p_orden_asc                BOOLEAN   DEFAULT TRUE,
    p_limite                   INT       DEFAULT 20,
    p_offset                   INT       DEFAULT 0,
    
    
    
    
    
    p_fk_tfuncionario          BIGINT    DEFAULT NULL,
    
    
    
    
    
    
    
    
    p_dia                      DATE      DEFAULT NULL
)
RETURNS TABLE (
    pk_tactividad                   BIGINT,
    titulo                          VARCHAR,
    descripcion                     VARCHAR,
    fk_tasignatura                  BIGINT,
    asignatura                      VARCHAR,
    fk_tarea                        BIGINT,
    area                            VARCHAR,
    fk_tunidad                      BIGINT,
    unidad                          VARCHAR,
    fk_tgrupo                       BIGINT,
    grupo                           VARCHAR,
    
    
    
    fk_tgrado                       BIGINT,
    grado                           VARCHAR,
    grado_codigo                    VARCHAR,
    grado_grupo                     VARCHAR,
    fk_tlv_tipo_actividad           BIGINT,
    tipo_actividad                  VARCHAR,
    fk_tlv_instrumento_evaluacion   BIGINT,
    instrumento_evaluacion          VARCHAR,
    ponderacion                     NUMERIC,
    influencia                      NUMERIC,
    es_evaluativa                   VARCHAR,
    es_recuperacion                 VARCHAR,
    fecha_inicio                    DATE,
    fecha_cierre                    DATE,
    fecha_calificado                DATE,
    estado                          VARCHAR,
    estudiantes_asignados           BIGINT,
    estudiantes_evaluados           BIGINT,
    porcentaje_evaluado             NUMERIC,
    active                          BOOLEAN,
    
    
    
    
    
    dia                             DATE,
    dia_anterior                    DATE,
    dia_siguiente                   DATE,
    total_count                     BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_sedes_lectura BIGINT[];
    v_alcance_total BOOLEAN;
    v_solo_propias  BOOLEAN;
    v_fk_tfuncionario BIGINT;
    v_hoy  DATE := CURRENT_DATE;
    v_key  VARCHAR;
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'PLANEADOR', 'VER'
    );

    -- Un docente puro NO administra su sede: dentro de ella solo le tocan las
    -- actividades que DICTA (mas las huerfanas que creo el). Rector y
    -- coordinador conservan intacto su alcance territorial.
    v_solo_propias    := academico_test.fn_usuario_es_docente_puro(p_pk_usuario_solicitante);
    v_fk_tfuncionario := academico_test.fn_funcionario_actual(p_pk_usuario_solicitante);

    -- Alcance de LECTURA (V277). El criterio no se elige aqui: ya lo define el
    -- sistema de rol/menu, via fn_usuario_sedes_lectura -- nivel 0/1 todas las
    -- sedes, nivel 2 las de sus establecimientos, nivel 3 las suyas, nivel 4
    -- ninguna. Se resuelve una sola vez por llamada.
    -- Nivel 0 (super admin) y 1 (territoriales) no se acotan por alcance
    -- territorial: ven todas las sedes. Lo que NO se salta nadie, ni ellos,
    -- es el borrado logico: el ACTIVE de la sede va en el JOIN de abajo, no
    -- aqui, para que una sede desactivada quede oculta para todo el mundo.
    v_alcance_total := COALESCE(
        academico_test.fn_usuario_categoria_rol_nivel(p_pk_usuario_solicitante), 99) <= 1;
    v_sedes_lectura := ARRAY(
        SELECT sl.sede_id
          FROM academico_test.fn_usuario_sedes_lectura(p_pk_usuario_solicitante) sl);

    -- Whitelist del criterio de orden (evita ramas muertas en el ORDER BY).
    v_key := LOWER(TRIM(COALESCE(p_orden_por, 'fecha_inicio')));
    IF v_key NOT IN ('fecha_inicio','fecha_cierre','fecha_creacion','titulo','ponderacion') THEN
        v_key := 'fecha_inicio';
    END IF;

    RETURN QUERY
    -- El universo es el filtro completo MENOS el dia. De ahi salen las dos
    -- cosas que necesita la barra de dias sin escribir el filtro dos veces:
    -- la pagina (del_dia -> base) y las flechas (nav, que tienen que ver los
    -- dias que el filtro por dia justamente esconde).
    WITH universo AS (
        SELECT a.PK_TACTIVIDAD  AS pk,
               a.FECHA_INICIO   AS fi,
               a.FECHA_CIERRE   AS fc,
               a.FECHA_CREACION AS fcr,
               a.TITULO         AS titulo,
               a.PONDERACION    AS pond
          FROM academico_test.TACTIVIDAD a
         WHERE (p_incluir_inactivas OR a.ACTIVE = TRUE)
           AND (
                 EXISTS (SELECT 1
                           FROM academico_test.TGRUPO g_sc
                           JOIN academico_test.TGRADO gr_sc
                             ON gr_sc.PK_TGRADO = g_sc.FK_TGRADO
                           JOIN academico_test.TPERIODO_ACADEMICO pa_sc
                             ON pa_sc.PK_TPERIODO_ACADEMICO = gr_sc.FK_TPERIODO_ACADEMICO
                           JOIN academico_test.TSEDE s_sc
                             ON s_sc.PK_TSEDE = pa_sc.FK_TSEDE AND s_sc.ACTIVE = TRUE
                          WHERE g_sc.PK_TGRUPO = a.FK_TGRUPO
                            AND (v_alcance_total
                                 OR pa_sc.FK_TSEDE = ANY(v_sedes_lectura)))
              OR EXISTS (SELECT 1
                           FROM academico_test.TUNIDAD u_sc
                           JOIN academico_test.TGRADO gr_sc
                             ON gr_sc.PK_TGRADO = u_sc.FK_TGRADO
                           JOIN academico_test.TPERIODO_ACADEMICO pa_sc
                             ON pa_sc.PK_TPERIODO_ACADEMICO = gr_sc.FK_TPERIODO_ACADEMICO
                           JOIN academico_test.TSEDE s_sc
                             ON s_sc.PK_TSEDE = pa_sc.FK_TSEDE AND s_sc.ACTIVE = TRUE
                          WHERE u_sc.PK_TUNIDAD = a.FK_TUNIDAD
                            AND (v_alcance_total
                                 OR pa_sc.FK_TSEDE = ANY(v_sedes_lectura)))
                 -- Huerfana pura (sin grupo ni unidad): no esta en ninguna
                 -- sede, asi que solo la ve quien la creo. CREATED_BY es VARCHAR
                 -- (columna de auditoria de texto libre: en filas sembradas a mano
                 -- guarda etiquetas, no ids), por eso el cast explicito.
              OR (a.FK_TGRUPO IS NULL AND a.FK_TUNIDAD IS NULL
                  AND (v_alcance_total
                      OR a.CREATED_BY = p_pk_usuario_solicitante::VARCHAR))
               )
           AND (p_fk_tasignatura        IS NULL OR a.FK_TASIGNATURA = p_fk_tasignatura)
           AND (p_fk_tgrupo             IS NULL OR a.FK_TGRUPO = p_fk_tgrupo)
           AND (p_fk_tunidad            IS NULL OR a.FK_TUNIDAD = p_fk_tunidad)
           -- V250 -- docente que DICTA la actividad: NO es el autor de la
           -- unidad (TUNIDAD.FK_TFUNCIONARIO puede ser otro docente, o el
           -- coordinador que armo la unidad). El vinculo real
           -- docente<->asignatura<->grupo vive en TDOCENTE_ASIGNATURA
           -- (V46, ver V242/fn_docente_grupos_listar): se cruza por
           -- (FK_TGRUPO, FK_TASIGNATURA) de la actividad -- si la actividad
           -- no tiene grupo (FK_TGRUPO NULL, p.ej. un "Criterio"), no hay
           -- match posible y queda excluida cuando se filtra por docente.
           AND (p_fk_tfuncionario       IS NULL OR EXISTS (
                    SELECT 1 FROM academico_test.TDOCENTE_ASIGNATURA da
                     WHERE da.FK_TGRUPO      = a.FK_TGRUPO
                       AND da.FK_TASIGNATURA = a.FK_TASIGNATURA
                       AND da.FK_TFUNCIONARIO = p_fk_tfuncionario
                       AND da.ACTIVE = TRUE))
           -- Mismo cruce por TDOCENTE_ASIGNATURA de arriba, pero forzado por
           -- el rol en vez de por parametro: el endpoint general manda NULL
           -- en p_fk_tfuncionario, asi que sin esto el docente veia las
           -- actividades de toda su sede. Se le conservan sus huerfanas
           -- (sin grupo ni unidad), que no cruzan por TDOCENTE_ASIGNATURA.
           AND (NOT v_solo_propias
                OR EXISTS (SELECT 1 FROM academico_test.TDOCENTE_ASIGNATURA da
                            WHERE da.FK_TGRUPO       = a.FK_TGRUPO
                              AND da.FK_TASIGNATURA  = a.FK_TASIGNATURA
                              AND da.FK_TFUNCIONARIO = v_fk_tfuncionario
                              AND da.ACTIVE = TRUE)
                OR (a.FK_TGRUPO IS NULL AND a.FK_TUNIDAD IS NULL
                    AND a.CREATED_BY = p_pk_usuario_solicitante::VARCHAR))
           AND (p_fk_tlv_tipo_actividad IS NULL OR a.FK_TLV_TIPO_ACTIVIDAD = p_fk_tlv_tipo_actividad)
           AND (p_fk_tlv_instrumento    IS NULL OR a.FK_TLV_INSTRUMENTO_EVALUACION = p_fk_tlv_instrumento)
           -- Ventana de fechas: solapamiento con [desde, hasta].
           AND (p_fecha_desde IS NULL OR COALESCE(a.FECHA_CIERRE, a.FECHA_INICIO) >= p_fecha_desde)
           AND (p_fecha_hasta IS NULL OR COALESCE(a.FECHA_INICIO, a.FECHA_CIERRE) <= p_fecha_hasta)
           -- Buscador unico "nombre, nivel educativo o instrumento".
           --
           -- Rama 1 (TITULO+DESCRIPCION): la expresion es IDENTICA a la de
           -- idx_tactividad_busqueda_trgm para que el planner pueda usarlo.
           --
           -- Ramas 2 y 3 (nivel de ensenanza via la unidad -> grado ->
           -- TNIVEL_ENSENANZA, e instrumento via TLISTA_VALOR.NOMBRE): NO
           -- estan cubiertas por ese indice -- son un post-filtro por EXISTS
           -- sobre catalogos pequeños, que solo se evalua cuando p_search
           -- viene informado y siempre dentro de este mismo CTE base, ya
           -- acotado por los demas filtros (asignatura / grupo / unidad /
           -- tipo / instrumento / ventana de fechas) y por la paginacion.
           -- Honestidad de rendimiento: al ser un OR, esta rama impide el
           -- Bitmap Index Scan puro del trigram; ver COMMENT ON FUNCTION.
           AND (p_search IS NULL
                OR (COALESCE(a.TITULO,'') || ' ' || COALESCE(a.DESCRIPCION,''))
                       ILIKE '%' || p_search || '%'
                OR EXISTS (
                       SELECT 1
                         FROM academico_test.TUNIDAD u2
                         JOIN academico_test.TGRADO g2            ON g2.PK_TGRADO = u2.FK_TGRADO
                         JOIN academico_test.TNIVEL_ENSENANZA ne2 ON ne2.PK_NIVEL_ENSENANZA = g2.FK_TNIVEL_ENSENANZA
                        WHERE u2.PK_TUNIDAD = a.FK_TUNIDAD
                          AND ne2.NOMBRE ILIKE '%' || p_search || '%')
                OR EXISTS (
                       SELECT 1
                         FROM academico_test.TLISTA_VALOR lvs
                        WHERE lvs.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
                          AND lvs.NOMBRE ILIKE '%' || p_search || '%'))
           AND (p_estados IS NULL OR academico_test.fn_actividad_estado(
                    a.FECHA_INICIO, a.FECHA_CIERRE, a.FECHA_CALIFICADO, v_hoy, p_dias_gracia
                ) = ANY(p_estados))
    ),
    -- Vigentes el dia pedido: la ventana lo CUBRE (no "empieza/cierra ese
    -- dia"), con la misma tolerancia a un extremo faltante que
    -- fn_actividad_estado. Sin ninguna fecha, la actividad no esta en ningun
    -- dia y no aparece en esta vista.
    del_dia AS (
        SELECT u.*
          FROM universo u
         WHERE p_dia IS NULL
            OR ((u.fi IS NOT NULL OR u.fc IS NOT NULL)
                AND (u.fi IS NULL OR u.fi <= p_dia)
                AND (u.fc IS NULL OR u.fc >= p_dia))
    ),
    -- Las flechas < >, sobre el universo SIN filtrar por dia (si mirasen
    -- del_dia no verian nada fuera del dia actual). Para cada actividad se
    -- calcula que dia aporta a cada lado: una que ya cerro aporta su cierre;
    -- una que atraviesa el dia aporta el dia contiguo. El MAX/MIN de todas
    -- da el dia ocupado mas cercano, saltando los vacios de por medio.
    nav AS (
        SELECT MAX(CASE WHEN u.fc IS NOT NULL AND u.fc < p_dia THEN u.fc
                        WHEN u.fi IS NOT NULL AND u.fi < p_dia THEN p_dia - 1
                   END) AS anterior,
               MIN(CASE WHEN u.fi IS NOT NULL AND u.fi > p_dia THEN u.fi
                        WHEN u.fc IS NOT NULL AND u.fc > p_dia THEN p_dia + 1
                   END) AS siguiente
          FROM universo u
         WHERE p_dia IS NOT NULL
        -- HAVING (no WHERE) para controlar si nav aporta FILA: un agregado
        -- sin GROUP BY siempre devuelve una, y aqui hace falta que devuelva
        -- CERO cuando no se pidio dia. Ver el FULL OUTER JOIN de abajo.
        HAVING p_dia IS NOT NULL
    ),
    base AS (
        SELECT d.pk,
               COUNT(*) OVER() AS total
          FROM del_dia d
         ORDER BY
           CASE WHEN     p_orden_asc AND v_key = 'fecha_inicio'   THEN d.fi     END ASC  NULLS LAST,
           CASE WHEN NOT p_orden_asc AND v_key = 'fecha_inicio'   THEN d.fi     END DESC NULLS LAST,
           CASE WHEN     p_orden_asc AND v_key = 'fecha_cierre'   THEN d.fc     END ASC  NULLS LAST,
           CASE WHEN NOT p_orden_asc AND v_key = 'fecha_cierre'   THEN d.fc     END DESC NULLS LAST,
           CASE WHEN     p_orden_asc AND v_key = 'fecha_creacion' THEN d.fcr    END ASC  NULLS LAST,
           CASE WHEN NOT p_orden_asc AND v_key = 'fecha_creacion' THEN d.fcr    END DESC NULLS LAST,
           CASE WHEN     p_orden_asc AND v_key = 'titulo'         THEN d.titulo END ASC  NULLS LAST,
           CASE WHEN NOT p_orden_asc AND v_key = 'titulo'         THEN d.titulo END DESC NULLS LAST,
           CASE WHEN     p_orden_asc AND v_key = 'ponderacion'    THEN d.pond   END ASC  NULLS LAST,
           CASE WHEN NOT p_orden_asc AND v_key = 'ponderacion'    THEN d.pond   END DESC NULLS LAST,
           d.pk
         -- p_limite NULL = "sin LIMIT" (PostgreSQL trata LIMIT NULL como
         -- ausencia de clausula). Es lo que usa el reporte sin paginar de
         -- V404 (POST /planeador/actividades/export-all), igual que V130
         -- hizo con est/sed/funcionarios. OJO: no vale GREATEST(NULL, 1),
         -- que en PostgreSQL ignora el NULL y devuelve 1 -- exportaria UNA
         -- fila. Para cualquier valor no nulo el comportamiento es el mismo
         -- de siempre; la fila de GET /planeador/actividades (V246) hace
         -- COALESCE(:QUERY.SIZE, 20), asi que por ahi nunca llega NULL.
         LIMIT CASE WHEN p_limite IS NULL THEN NULL ELSE GREATEST(p_limite, 1) END
        OFFSET GREATEST(COALESCE(p_offset, 0), 0)
    )
    SELECT a.PK_TACTIVIDAD,
           a.TITULO,
           a.DESCRIPCION,
           a.FK_TASIGNATURA,
           asig.NOMBRE,
           asig.FK_TAREA,
           ar.NOMBRE,
           a.FK_TUNIDAD,
           u.NOMBRE,
           a.FK_TGRUPO,
           g.NOMBRE,
           gr.PK_TGRADO,
           gr.NOMBRE,
           gr.CODIGO,
           academico_test.fn_grado_grupo_etiqueta(gr.NOMBRE, gr.CODIGO, g.NOMBRE),
           a.FK_TLV_TIPO_ACTIVIDAD,
           lvt.NOMBRE,
           a.FK_TLV_INSTRUMENTO_EVALUACION,
           lvi.NOMBRE,
           a.PONDERACION,
           a.INFLUENCIA,
           a.ES_EVALUATIVA::VARCHAR,
            a.ES_RECUPERACION::VARCHAR,
           a.FECHA_INICIO,
           a.FECHA_CIERRE,
           a.FECHA_CALIFICADO,
           academico_test.fn_actividad_estado(a.FECHA_INICIO, a.FECHA_CIERRE, a.FECHA_CALIFICADO, v_hoy, p_dias_gracia),
           prog.asignados,
           prog.evaluados,
           CASE WHEN prog.asignados > 0
                THEN ROUND(prog.evaluados * 100.0 / prog.asignados, 2)
                ELSE 0 END,
           a.ACTIVE,
           p_dia,
           n.anterior,
           n.siguiente,
           COALESCE(b.total, 0)
      FROM base b
      -- FULL OUTER ... ON TRUE, y no CROSS JOIN, por el dia VACIO: si la
      -- pagina no tiene filas, un CROSS JOIN no devuelve nada y el cliente se
      -- queda sin dia_anterior/dia_siguiente -- justo cuando mas los necesita,
      -- porque no tiene con que salir de un dia sin actividades. Con FULL
      -- OUTER: (a) sin p_dia, nav no aporta fila y el resultado es la pagina
      -- tal cual, 0 filas incluidas -- el listado de siempre no cambia;
      -- (b) con p_dia y pagina no vacia, nav aporta su unica fila a todas;
      -- (c) con p_dia y pagina VACIA, queda UNA fila con las columnas de la
      -- actividad en NULL, total_count = 0 y las flechas informadas. El
      -- cliente reconoce ese caso por total_count = 0 (o pk_tactividad NULL).
      -- Por eso los joins de abajo pasan a LEFT: esa fila no tiene actividad
      -- que resolver y un INNER la borraria.
      FULL OUTER JOIN nav n ON TRUE
      LEFT JOIN academico_test.TACTIVIDAD a      ON a.PK_TACTIVIDAD = b.pk
      LEFT JOIN academico_test.TASIGNATURA asig  ON asig.PK_TASIGNATURA = a.FK_TASIGNATURA
      LEFT JOIN academico_test.TAREA ar          ON ar.PK_TAREA = asig.FK_TAREA
      LEFT JOIN academico_test.TUNIDAD u         ON u.PK_TUNIDAD = a.FK_TUNIDAD
      LEFT JOIN academico_test.TGRUPO g          ON g.PK_TGRUPO = a.FK_TGRUPO
      -- El grado sale del GRUPO de la actividad; si no tiene grupo (criterios,
      -- huerfanas) se cae al grado de su unidad, que es el otro sitio donde la
      -- actividad esta anclada a un grado. COALESCE de los dos caminos.
      LEFT JOIN academico_test.TGRADO gr         ON gr.PK_TGRADO = COALESCE(g.FK_TGRADO, u.FK_TGRADO)
      LEFT JOIN academico_test.TLISTA_VALOR lvt  ON lvt.PK_LISTA_VALOR = a.FK_TLV_TIPO_ACTIVIDAD
      LEFT JOIN academico_test.TLISTA_VALOR lvi  ON lvi.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
      -- Un solo LATERAL: asignados y evaluados en la misma pasada.
      LEFT JOIN LATERAL (
          SELECT COUNT(*)::BIGINT AS asignados,
                 COUNT(*) FILTER (
                     WHERE COALESCE(n.DEFINITIVA, n.CALIFICACION) IS NOT NULL
                 )::BIGINT AS evaluados
            FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
            LEFT JOIN academico_test.TACTIVIDAD_NOTA n
                   ON n.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                  AND n.ACTIVE = TRUE
           WHERE ae.FK_TACTIVIDAD = a.PK_TACTIVIDAD
             AND ae.ACTIVE = TRUE
      ) prog ON TRUE
     ORDER BY
       CASE WHEN     p_orden_asc AND v_key = 'fecha_inicio'   THEN a.FECHA_INICIO   END ASC  NULLS LAST,
       CASE WHEN NOT p_orden_asc AND v_key = 'fecha_inicio'   THEN a.FECHA_INICIO   END DESC NULLS LAST,
       CASE WHEN     p_orden_asc AND v_key = 'fecha_cierre'   THEN a.FECHA_CIERRE   END ASC  NULLS LAST,
       CASE WHEN NOT p_orden_asc AND v_key = 'fecha_cierre'   THEN a.FECHA_CIERRE   END DESC NULLS LAST,
       CASE WHEN     p_orden_asc AND v_key = 'fecha_creacion' THEN a.FECHA_CREACION END ASC  NULLS LAST,
       CASE WHEN NOT p_orden_asc AND v_key = 'fecha_creacion' THEN a.FECHA_CREACION END DESC NULLS LAST,
       CASE WHEN     p_orden_asc AND v_key = 'titulo'         THEN a.TITULO         END ASC  NULLS LAST,
       CASE WHEN NOT p_orden_asc AND v_key = 'titulo'         THEN a.TITULO         END DESC NULLS LAST,
       CASE WHEN     p_orden_asc AND v_key = 'ponderacion'    THEN a.PONDERACION    END ASC  NULLS LAST,
       CASE WHEN NOT p_orden_asc AND v_key = 'ponderacion'    THEN a.PONDERACION    END DESC NULLS LAST,
       a.PK_TACTIVIDAD;
END;
$$$crear$;
    END IF;
END $guarda$;

DROP FUNCTION IF EXISTS academico_test.fn_actividad_resumen_estados(BIGINT, BIGINT, BIGINT, BIGINT, DATE, DATE, INT);

DROP FUNCTION IF EXISTS academico_test.fn_actividad_resumen_estados(BIGINT, BIGINT, BIGINT, BIGINT, DATE, DATE, INT, BIGINT);

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_resumen_estados(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tasignatura           BIGINT DEFAULT NULL,
    p_fk_tgrupo                BIGINT DEFAULT NULL,
    p_fk_tunidad               BIGINT DEFAULT NULL,
    p_fecha_desde              DATE   DEFAULT NULL,
    p_fecha_hasta              DATE   DEFAULT NULL,
    p_dias_gracia              INT    DEFAULT 2,
    
    
    
    p_fk_tfuncionario          BIGINT DEFAULT NULL
)
RETURNS TABLE (
    pendientes_por_evaluar  BIGINT,
    en_evaluacion           BIGINT,
    finalizadas             BIGINT,
    vencidas                BIGINT,
    total                   BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_sedes_lectura BIGINT[];
    v_alcance_total BOOLEAN;
    v_hoy DATE := CURRENT_DATE;
BEGIN
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'PLANEADOR', 'VER'
    );

    -- Alcance de LECTURA (V277), mismo criterio que fn_actividad_listar: lo
    -- define el sistema de rol/menu via fn_usuario_sedes_lectura. Nivel 0/1 no
    -- se acotan por alcance, pero el ACTIVE de la sede lo respeta todo el
    -- mundo: una sede dada de baja no la ve nadie.
    v_alcance_total := COALESCE(
        academico_test.fn_usuario_categoria_rol_nivel(p_pk_usuario_solicitante), 99) <= 1;
    v_sedes_lectura := ARRAY(
        SELECT sl.sede_id
          FROM academico_test.fn_usuario_sedes_lectura(p_pk_usuario_solicitante) sl);

    RETURN QUERY
    WITH est AS (
        SELECT academico_test.fn_actividad_estado(
                   a.FECHA_INICIO, a.FECHA_CIERRE, a.FECHA_CALIFICADO, v_hoy, p_dias_gracia
               ) AS estado
          FROM academico_test.TACTIVIDAD a
         WHERE a.ACTIVE = TRUE
           AND (
                 EXISTS (SELECT 1
                           FROM academico_test.TGRUPO g_sc
                           JOIN academico_test.TGRADO gr_sc
                             ON gr_sc.PK_TGRADO = g_sc.FK_TGRADO
                           JOIN academico_test.TPERIODO_ACADEMICO pa_sc
                             ON pa_sc.PK_TPERIODO_ACADEMICO = gr_sc.FK_TPERIODO_ACADEMICO
                           JOIN academico_test.TSEDE s_sc
                             ON s_sc.PK_TSEDE = pa_sc.FK_TSEDE AND s_sc.ACTIVE = TRUE
                          WHERE g_sc.PK_TGRUPO = a.FK_TGRUPO
                            AND (v_alcance_total
                                 OR pa_sc.FK_TSEDE = ANY(v_sedes_lectura)))
              OR EXISTS (SELECT 1
                           FROM academico_test.TUNIDAD u_sc
                           JOIN academico_test.TGRADO gr_sc
                             ON gr_sc.PK_TGRADO = u_sc.FK_TGRADO
                           JOIN academico_test.TPERIODO_ACADEMICO pa_sc
                             ON pa_sc.PK_TPERIODO_ACADEMICO = gr_sc.FK_TPERIODO_ACADEMICO
                           JOIN academico_test.TSEDE s_sc
                             ON s_sc.PK_TSEDE = pa_sc.FK_TSEDE AND s_sc.ACTIVE = TRUE
                          WHERE u_sc.PK_TUNIDAD = a.FK_TUNIDAD
                            AND (v_alcance_total
                                 OR pa_sc.FK_TSEDE = ANY(v_sedes_lectura)))
              OR (a.FK_TGRUPO IS NULL AND a.FK_TUNIDAD IS NULL
                  AND (v_alcance_total
                       OR a.CREATED_BY = p_pk_usuario_solicitante::VARCHAR))
               )
           AND (p_fk_tasignatura IS NULL OR a.FK_TASIGNATURA = p_fk_tasignatura)
           AND (p_fk_tgrupo      IS NULL OR a.FK_TGRUPO = p_fk_tgrupo)
           AND (p_fk_tunidad     IS NULL OR a.FK_TUNIDAD = p_fk_tunidad)
           -- V250 -- igual que fn_actividad_listar: docente que DICTA
           -- (TDOCENTE_ASIGNATURA por grupo+asignatura), no el autor de la
           -- unidad.
           AND (p_fk_tfuncionario IS NULL OR EXISTS (
                    SELECT 1 FROM academico_test.TDOCENTE_ASIGNATURA da
                     WHERE da.FK_TGRUPO      = a.FK_TGRUPO
                       AND da.FK_TASIGNATURA = a.FK_TASIGNATURA
                       AND da.FK_TFUNCIONARIO = p_fk_tfuncionario
                       AND da.ACTIVE = TRUE))
           AND (p_fecha_desde IS NULL OR COALESCE(a.FECHA_CIERRE, a.FECHA_INICIO) >= p_fecha_desde)
           AND (p_fecha_hasta IS NULL OR COALESCE(a.FECHA_INICIO, a.FECHA_CIERRE) <= p_fecha_hasta)
    )
    SELECT COUNT(*) FILTER (WHERE estado = 'PENDIENTE_POR_EVALUAR')::BIGINT,
           COUNT(*) FILTER (WHERE estado = 'EN_EVALUACION')::BIGINT,
           COUNT(*) FILTER (WHERE estado = 'FINALIZADA')::BIGINT,
           COUNT(*) FILTER (WHERE estado = 'VENCIDA')::BIGINT,
           COUNT(*)::BIGINT
      FROM est;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_resumen_estados(BIGINT, BIGINT, BIGINT, BIGINT, DATE, DATE, INT, BIGINT)
    IS 'Contadores del tablero del Planeador (Pendientes por evaluar / En evaluacion vigentes / Finalizadas / Vencidas > p_dias_gracia dias) en UNA sola pasada con COUNT(*) FILTER sobre el estado derivado por fn_actividad_estado — no cuatro queries. Devuelve EXACTAMENTE las cuatro tarjetas mas el total: se quitaron programadas y sin_programar, que con la derivacion de cuatro estados de fn_actividad_estado quedarian siempre en 0. Filtros opcionales por asignatura, grupo, unidad, ventana de fechas y (V250) docente que DICTA la actividad (p_fk_tfuncionario, via TDOCENTE_ASIGNATURA por FK_TGRUPO+FK_TASIGNATURA -- no el autor de la unidad). Gate VER sobre PLANEADOR. V224/V250.';

CREATE OR REPLACE FUNCTION academico_test.fn_funcionario_actual(
    p_pk_usuario_solicitante   BIGINT
)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    -- U_TFUNCIONARIO_2 es UNIQUE (FK_TUSUARIO, FK_ESTABLECIMIENTO) WHERE
    -- ACTIVE, NO unico por usuario: un mismo usuario tiene UN funcionario POR
    -- ESTABLECIMIENTO, y en el esquema real hay usuarios con hasta tres. La
    -- version anterior de esta funcion no ordenaba ni acotaba, asi que para
    -- ellos devolvia una fila arbitraria -- y podia cambiar entre ejecuciones.
    --
    -- El desempate es el ALCANCE del propio usuario: de sus sedes activas
    -- (TSEDE_USUARIO -> TSEDE) sale el establecimiento en el que esta
    -- trabajando, y se prefiere el funcionario de ESE establecimiento.
    --
    -- Es una PREFERENCIA, no un filtro. Medido sobre los datos reales, el
    -- cruce por sede desambigua solo uno de los seis usuarios con varios
    -- funcionarios: en el resto, FK_ESTABLECIMIENTO del funcionario no
    -- coincide con el establecimiento de ninguna de sus sedes (y a menudo es
    -- NULL). Con un JOIN duro esos usuarios se quedarian sin funcionario y
    -- dejarian de poder crear -- peor que hoy. Por eso va como ORDER BY con
    -- NULLS LAST: el conjunto de candidatos es el mismo de antes, solo deja
    -- de ser arbitrario cual sale.
    --
    -- PREDETERMINADO se usa como criterio secundario sabiendo que la columna
    -- esta sucia: deberia ser una bandera 0/1 pero guarda valores arbitrarios
    -- (10, 100, 101...), asi que solo se trata el 1 como "sede por defecto" y
    -- no se construye nada mas encima.
    --
    -- El LIMIT 1 final es lo que garantiza que el resultado sea estable.
    SELECT f.PK_TFUNCIONARIO
      FROM academico_test.TFUNCIONARIO f
     WHERE f.FK_TUSUARIO = p_pk_usuario_solicitante
       AND f.ACTIVE = TRUE
     ORDER BY (SELECT MIN(CASE WHEN su.PREDETERMINADO = 1 THEN 0 ELSE 1 END)
                 FROM academico_test.TSEDE_USUARIO su
                 JOIN academico_test.TSEDE s
                   ON s.PK_TSEDE = su.FK_TSEDE AND s.ACTIVE = TRUE
                WHERE su.FK_TUSUARIO = p_pk_usuario_solicitante
                  AND su.ACTIVE = TRUE
                  AND s.FK_TESTABLECIMIENTO = f.FK_ESTABLECIMIENTO) NULLS LAST,
              f.PK_TFUNCIONARIO
     LIMIT 1;
$$;

COMMENT ON FUNCTION academico_test.fn_funcionario_actual(BIGINT)
    IS 'Resuelve el PK_TFUNCIONARIO del usuario autenticado a partir de TFUNCIONARIO.FK_TUSUARIO, solo entre los ACTIVE. NULL si el usuario no tiene funcionario asociado (estudiante, acudiente, o funcionario inactivo). OJO con la unicidad: U_TFUNCIONARIO_2 es UNIQUE (FK_TUSUARIO, FK_ESTABLECIMIENTO) WHERE ACTIVE, es decir un funcionario POR ESTABLECIMIENTO y NO uno por usuario -- en el esquema real hay usuarios con tres. Cuando hay varios se desempata por el ALCANCE del usuario: se prefiere el funcionario cuyo establecimiento coincide con el de alguna de sus sedes activas (TSEDE_USUARIO -> TSEDE), y dentro de esas la marcada PREDETERMINADO = 1; despues, PK_TFUNCIONARIO ascendente. Es una preferencia con NULLS LAST y no un JOIN: sobre los datos reales el cruce por sede desambigua solo uno de los seis casos, y filtrar dejaria al resto sin funcionario. El LIMIT 1 es lo que hace el resultado ESTABLE -- antes la funcion no ordenaba ni acotaba y para esos usuarios devolvia una fila arbitraria. Helper generico, no especifico del Planeador. Usado por fn_actividad_resumen_estados_docente y fn_actividad_listar_docente (V250), fn_periodo_evaluacion_listar (V254) y fn_unidad_crear (V216, para derivar el docente autor y que el cliente no tenga que mandarlo).';

DROP FUNCTION IF EXISTS academico_test.fn_actividad_resumen_estados_docente(BIGINT, BIGINT, BIGINT, BIGINT, DATE, DATE, INT);

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_resumen_estados_docente(
    p_pk_usuario_solicitante   BIGINT,
    p_fk_tasignatura           BIGINT DEFAULT NULL,
    p_fk_tgrupo                BIGINT DEFAULT NULL,
    p_fk_tunidad               BIGINT DEFAULT NULL,
    p_fecha_desde              DATE   DEFAULT NULL,
    p_fecha_hasta              DATE   DEFAULT NULL,
    p_dias_gracia              INT    DEFAULT 2
)
RETURNS TABLE (
    pendientes_por_evaluar  BIGINT,
    en_evaluacion           BIGINT,
    finalizadas             BIGINT,
    vencidas                BIGINT,
    total                   BIGINT
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_fk_tfuncionario BIGINT;
BEGIN
    -- Gate propio (ademas del que hace fn_actividad_resumen_estados por
    -- dentro): asi el 403 sale ANTES de tocar TFUNCIONARIO si el usuario
    -- no tiene ni siquiera capability de VER sobre PLANEADOR.
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'PLANEADOR', 'VER'
    );

    v_fk_tfuncionario := academico_test.fn_funcionario_actual(p_pk_usuario_solicitante);

    IF v_fk_tfuncionario IS NULL THEN
        RETURN QUERY SELECT 0::BIGINT, 0::BIGINT, 0::BIGINT, 0::BIGINT, 0::BIGINT;
        RETURN;
    END IF;

    RETURN QUERY
    SELECT * FROM academico_test.fn_actividad_resumen_estados(
        p_pk_usuario_solicitante, p_fk_tasignatura, p_fk_tgrupo, p_fk_tunidad,
        p_fecha_desde, p_fecha_hasta, p_dias_gracia, v_fk_tfuncionario
    );
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_resumen_estados_docente(BIGINT, BIGINT, BIGINT, BIGINT, DATE, DATE, INT)
    IS 'Tablero "mis actividades" del docente autenticado (las CUATRO tarjetas: Pendientes por evaluar / En evaluacion vigentes / Finalizadas / Vencidas > p_dias_gracia dias, mas el total). Wrapper delgado: resuelve el TFUNCIONARIO del caller con fn_funcionario_actual y delega el conteo en fn_actividad_resumen_estados (misma fuente de verdad que el resumen general y que fn_actividad_listar) -- no duplica la logica de fn_actividad_estado. Si el usuario autenticado no es un docente activo (fn_funcionario_actual devuelve NULL), retorna todos los contadores en 0 (no es un error: el gate PLANEADOR/VER ya se evaluo primero). Gate VER sobre PLANEADOR. V250.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_finalizacion_refrescar(
    p_pk_tactividad BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_asignados INT;
    v_resueltos INT;
BEGIN
    IF p_pk_tactividad IS NULL THEN
        RETURN;
    END IF;

    SELECT COUNT(*),
           COUNT(*) FILTER (
               WHERE n.PK_TACTIVIDAD_NOTA IS NOT NULL
                 AND ( n.CALIFICACION IS NOT NULL
                       OR (n.CALIFICABLE = 'N' AND NULLIF(TRIM(n.OBSERVACION), '') IS NOT NULL) ))
      INTO v_asignados, v_resueltos
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      LEFT JOIN academico_test.TACTIVIDAD_NOTA n
             ON n.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
            AND n.ACTIVE = TRUE
     WHERE ae.FK_TACTIVIDAD = p_pk_tactividad
       AND ae.ACTIVE = TRUE;

    IF v_asignados > 0 AND v_resueltos = v_asignados THEN
        -- Solo si no estaba: no se pisa la fecha original cada vez que se
        -- re-califica a alguien de una actividad ya cerrada.
        UPDATE academico_test.TACTIVIDAD
           SET FECHA_CALIFICADO = CURRENT_DATE
         WHERE PK_TACTIVIDAD = p_pk_tactividad
           AND FECHA_CALIFICADO IS NULL;
    ELSE
        -- Se reabre: quedo alguien sin resolver (alumno nuevo, nota borrada).
        UPDATE academico_test.TACTIVIDAD
           SET FECHA_CALIFICADO = NULL
         WHERE PK_TACTIVIDAD = p_pk_tactividad
           AND FECHA_CALIFICADO IS NOT NULL;
    END IF;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_finalizacion_refrescar(BIGINT)
    IS 'Recalcula TACTIVIDAD.FECHA_CALIFICADO de UNA actividad: la fija en CURRENT_DATE cuando todos sus estudiantes ACTIVE tienen la evaluacion resuelta, y la vuelve a NULL si alguno deja de estarlo (alumno nuevo asignado, nota borrada). "Resuelto" = CALIFICACION no nula (actividad evaluativa) u OBSERVACION con CALIFICABLE=''N'' (actividad formativa de preescolar, V243). Es lo que hace ALCANZABLE el estado FINALIZADA de fn_actividad_estado, que antes nadie podia producir porque ninguna funcion escribia esta columna. No se invoca desde las funciones de calificar: lo disparan los triggers de TACTIVIDAD_NOTA y TACTIVIDAD_ESTUDIANTE, para cubrir por construccion los ocho puntos de escritura actuales y los que se agreguen despues. V224.';

CREATE OR REPLACE FUNCTION academico_test.fn_tactividad_nota_finalizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_pk_tactividad BIGINT;
BEGIN
    SELECT ae.FK_TACTIVIDAD INTO v_pk_tactividad
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE
           = COALESCE(NEW.FK_TACTIVIDAD_ESTUDIANTE, OLD.FK_TACTIVIDAD_ESTUDIANTE);

    PERFORM academico_test.fn_actividad_finalizacion_refrescar(v_pk_tactividad);
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS tr_tactividad_nota_finalizacion ON academico_test.TACTIVIDAD_NOTA;

CREATE TRIGGER tr_tactividad_nota_finalizacion
    AFTER INSERT OR UPDATE OR DELETE ON academico_test.TACTIVIDAD_NOTA
    FOR EACH ROW EXECUTE FUNCTION academico_test.fn_tactividad_nota_finalizacion();

CREATE OR REPLACE FUNCTION academico_test.fn_tactividad_estudiante_finalizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM academico_test.fn_actividad_finalizacion_refrescar(
        COALESCE(NEW.FK_TACTIVIDAD, OLD.FK_TACTIVIDAD));
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS tr_tactividad_estudiante_finalizacion ON academico_test.TACTIVIDAD_ESTUDIANTE;

CREATE TRIGGER tr_tactividad_estudiante_finalizacion
    AFTER INSERT OR UPDATE OR DELETE ON academico_test.TACTIVIDAD_ESTUDIANTE
    FOR EACH ROW EXECUTE FUNCTION academico_test.fn_tactividad_estudiante_finalizacion();

DO $backfill$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT DISTINCT ae.FK_TACTIVIDAD AS pk
               FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
              WHERE ae.ACTIVE = TRUE
    LOOP
        PERFORM academico_test.fn_actividad_finalizacion_refrescar(r.pk);
    END LOOP;
END
$backfill$;
