-- ===========================================================================
-- V240 - Instrumento de evaluacion "Otro (personalizado)" de una actividad.
-- Quedan el catalogo TIPO_EVIDENCIA_OTRO, TACTIVIDAD_OTRO,
-- fn_actividad_instrumento_assert y fn_actividad_instrumento_definir.
-- fn_actividad_otro_definir y fn_actividad_instrumento_obtener viven en V469.
-- Depende de: V224 (catalogo INSTRUMENTO_EVALUACION), V226.
-- ===========================================================================


SET search_path TO academico_test, public;

INSERT INTO academico_test.tlista_valor (categoria, nombre, valor, created_by)
SELECT v.categoria, v.nombre, v.valor, 'V240_seed'
  FROM (VALUES
    ('TIPO_EVIDENCIA_OTRO'::VARCHAR, 'Archivo'::VARCHAR,               'ARCHIVO'::VARCHAR),
    ('TIPO_EVIDENCIA_OTRO',          'Enlace',                         'ENLACE'),
    ('TIPO_EVIDENCIA_OTRO',          'Observación directa',            'OBSERVACION_DIRECTA'),
    ('TIPO_EVIDENCIA_OTRO',          'Registro en campo',              'REGISTRO_CAMPO')
  ) AS v(categoria, nombre, valor)
 WHERE NOT EXISTS (
     SELECT 1 FROM academico_test.tlista_valor lv
      WHERE lv.categoria = v.categoria AND lv.valor = v.valor
 );

CREATE TABLE IF NOT EXISTS TACTIVIDAD_OTRO (
  PK_TACTIVIDAD_OTRO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD BIGINT NOT NULL,
  FK_TLV_TIPO_EVIDENCIA_OTRO BIGINT NOT NULL,
  FK_TLV_METODO_VALORACION BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TAC_OTRO PRIMARY KEY (PK_TACTIVIDAD_OTRO),
  CONSTRAINT UN_TAC_OTRO_1 UNIQUE (FK_TACTIVIDAD) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT FK_TAC_OTRO_1 FOREIGN KEY (FK_TACTIVIDAD) REFERENCES TACTIVIDAD (PK_TACTIVIDAD) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_OTRO_2 FOREIGN KEY (FK_TLV_TIPO_EVIDENCIA_OTRO) REFERENCES TLISTA_VALOR (PK_LISTA_VALOR),
  CONSTRAINT FK_TAC_OTRO_3 FOREIGN KEY (FK_TLV_METODO_VALORACION) REFERENCES TLISTA_VALOR (PK_LISTA_VALOR)
);

CREATE INDEX IF NOT EXISTS IDX_TAC_OTRO_1 ON TACTIVIDAD_OTRO (FK_TACTIVIDAD);

CREATE INDEX IF NOT EXISTS IDX_TAC_OTRO_2 ON TACTIVIDAD_OTRO (FK_TLV_TIPO_EVIDENCIA_OTRO);

CREATE INDEX IF NOT EXISTS IDX_TAC_OTRO_3 ON TACTIVIDAD_OTRO (FK_TLV_METODO_VALORACION);

CREATE INDEX IF NOT EXISTS IDX_TACTIVIDAD_OTRO_ACTIVE ON TACTIVIDAD_OTRO (PK_TACTIVIDAD_OTRO) WHERE ACTIVE = true;

COMMENT ON COLUMN TACTIVIDAD_OTRO.PK_TACTIVIDAD_OTRO IS 'Llave primaria de la tabla';

COMMENT ON COLUMN TACTIVIDAD_OTRO.FK_TACTIVIDAD IS 'Llave foranea a tabla TACTIVIDAD (relacion 1:1, solo aplica cuando FK_TLV_INSTRUMENTO_EVALUACION = OTRO)';

COMMENT ON COLUMN TACTIVIDAD_OTRO.FK_TLV_TIPO_EVIDENCIA_OTRO IS 'Tipo de evidencia esperada del instrumento Otro. Llave foranea de lista valor, categoria TIPO_EVIDENCIA_OTRO (distinta de TIPO_EVIDENCIA de V224)';

COMMENT ON COLUMN TACTIVIDAD_OTRO.FK_TLV_METODO_VALORACION IS 'Metodo de valoracion elegido para poder calificar el instrumento Otro. Llave foranea de lista valor, categoria INSTRUMENTO_EVALUACION reutilizada (solo RUBRICA | LISTA_COTEJO | ESCALA_VALORACION, nunca OTRO)';

COMMENT ON TABLE TACTIVIDAD_OTRO IS 'Configuracion del instrumento de evaluacion "Otro (personalizado)" de una actividad (1:1 con TACTIVIDAD cuando INSTRUMENTO = OTRO): tipo de evidencia esperada + metodo de valoracion elegido para calificar. El detalle textual/ponderacion generica (DESCRIPCION_INSTRUMENTO, REQUIERE_ARCHIVO, REQUIERE_TEXTO, PONDERACION) vive en TACTIVIDAD (V224); la estructura del metodo de valoracion vive en TACTIVIDAD_RUBRICA_*/_COTEJO_ITEM/_ESCALA* (V226), no se duplica aqui. V240.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_instrumento_assert(
    p_pk_tactividad   BIGINT,
    p_valor_esperado  VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_active BOOLEAN;
    v_valor  VARCHAR;
BEGIN
    SELECT a.ACTIVE, lv.VALOR
      INTO v_active, v_valor
      FROM academico_test.TACTIVIDAD a
      LEFT JOIN academico_test.TLISTA_VALOR lv
             ON lv.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
     WHERE a.PK_TACTIVIDAD = p_pk_tactividad;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la actividad solicitada' USING ERRCODE = 'P0002';
    END IF;
    IF v_active = FALSE THEN
        RAISE EXCEPTION 'La actividad esta inactiva; no se le puede definir el instrumento' USING ERRCODE = '22023';
    END IF;
    IF v_valor IS NULL THEN
        RAISE EXCEPTION 'La actividad no tiene instrumento de evaluacion definido; fijelo primero con fn_actividad_crear/_actualizar (FK_TLV_INSTRUMENTO_EVALUACION)'
            USING ERRCODE = '22023';
    END IF;

    IF v_valor = p_valor_esperado THEN
        RETURN;
    END IF;

    -- V240: el instrumento OTRO reutiliza rubrica/cotejo/escala como METODO
    -- DE VALORACION (TACTIVIDAD_OTRO.FK_TLV_METODO_VALORACION, fijado por
    -- fn_actividad_otro_definir). Se acepta como equivalente al instrumento
    -- estructurado esperado SOLO si ya quedo configurado ese metodo.
    IF v_valor = 'OTRO'
       AND p_valor_esperado IN ('RUBRICA', 'LISTA_COTEJO', 'ESCALA_VALORACION')
       AND EXISTS (
           SELECT 1
             FROM academico_test.TACTIVIDAD_OTRO o
             JOIN academico_test.TLISTA_VALOR lvm ON lvm.PK_LISTA_VALOR = o.FK_TLV_METODO_VALORACION
            WHERE o.FK_TACTIVIDAD = p_pk_tactividad
              AND o.ACTIVE = TRUE
              AND lvm.VALOR = p_valor_esperado
       )
    THEN
        RETURN;
    END IF;

    RAISE EXCEPTION 'El instrumento de la actividad es % y no % — cambielo antes de definirlo', v_valor, p_valor_esperado
        USING ERRCODE = '22023';
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_instrumento_assert(BIGINT, VARCHAR)
    IS 'Valida que la actividad exista, este activa y que su FK_TLV_INSTRUMENTO_EVALUACION (VALOR de TLISTA_VALOR) sea el esperado. Lanza P0002 / 22023. V240: ademas acepta como equivalente el caso instrumento OTRO con TACTIVIDAD_OTRO.FK_TLV_METODO_VALORACION ya configurado con el mismo valor esperado (RUBRICA | LISTA_COTEJO | ESCALA_VALORACION) — asi fn_actividad_rubrica_definir/_cotejo_definir/_escala_definir se pueden invocar desde fn_actividad_otro_definir sin romper. Helper de fn_actividad_*_definir. V226/V240.';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_instrumento_definir(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad            BIGINT,
    p_definicion               JSONB
)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE
    v_valor VARCHAR;
BEGIN
    SELECT lv.VALOR INTO v_valor
      FROM academico_test.TACTIVIDAD a
      LEFT JOIN academico_test.TLISTA_VALOR lv
             ON lv.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
     WHERE a.PK_TACTIVIDAD = p_pk_tactividad;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la actividad solicitada' USING ERRCODE = 'P0002';
    END IF;

    CASE v_valor
        WHEN 'RUBRICA' THEN
            PERFORM academico_test.fn_actividad_rubrica_definir(
                        p_pk_usuario_solicitante, p_pk_tactividad, p_definicion);
        WHEN 'LISTA_COTEJO' THEN
            PERFORM academico_test.fn_actividad_cotejo_definir(
                        p_pk_usuario_solicitante, p_pk_tactividad, p_definicion);
        WHEN 'ESCALA_VALORACION' THEN
            PERFORM academico_test.fn_actividad_escala_definir(
                        p_pk_usuario_solicitante, p_pk_tactividad, p_definicion);
        WHEN 'OTRO' THEN
            -- V240: p_definicion es aqui el p_config de fn_actividad_otro_definir
            -- {tipoEvidencia, metodoValoracion, definicion}.
            PERFORM academico_test.fn_actividad_otro_definir(
                        p_pk_usuario_solicitante, p_pk_tactividad, p_definicion);
        ELSE
            RAISE EXCEPTION 'La actividad no tiene un instrumento de evaluacion valido para definir (%)',
                COALESCE(v_valor, 'sin instrumento') USING ERRCODE = '22023';
    END CASE;

    RETURN v_valor;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_instrumento_definir(BIGINT, BIGINT, JSONB)
    IS 'Fachada: lee TACTIVIDAD.FK_TLV_INSTRUMENTO_EVALUACION y despacha a fn_actividad_rubrica_definir (array de criterios), fn_actividad_cotejo_definir (array de items), fn_actividad_escala_definir (objeto de config) o fn_actividad_otro_definir (objeto {tipoEvidencia, metodoValoracion, definicion} — V240). Gate EDITAR sobre PLANEADOR (via las funciones destino). Retorna el VALOR del instrumento aplicado. V226/V240.';
