-- ===========================================================================
-- V256 -- Dominio propio de PIGSE: entes territoriales, establecimientos,
-- usuarios/funcionarios y sus puentes con rol.
--
-- Hasta hoy PIGSE solo tenia schema y TARCHIVO (V148): sus funciones
-- fn_pigse_* leian academico_test.testablecimiento, sincronizado desde
-- coleval. Este DDL le da a PIGSE entidades INDEPENDIENTES para que deje de
-- depender de ese sincronismo. Nada de academico_test se toca.
--
-- Lo que NO se duplica: los catalogos geograficos / lista de valores /
-- propiedad juridica siguen en academico_test (son compartidos), el login
-- vive en public.users y los roles en public.role.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Tabla: pigse.tente
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tente (
  PK_ENTE BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NIT VARCHAR(30) NOT NULL,
  NOMBRE VARCHAR(130) NOT NULL,
  ESTADO academico_test.estado_ai DEFAULT 'A' NOT NULL,
  FK_TMUNICIPIO BIGINT NOT NULL,
  FK_TENTE_PADRE BIGINT,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TENTE PRIMARY KEY (PK_ENTE),
  CONSTRAINT FK_PIGSE_TENTE_PADRE FOREIGN KEY (FK_TENTE_PADRE) REFERENCES pigse.tente (PK_ENTE),
  CONSTRAINT FK_PIGSE_TENTE_MUNICIPIO FOREIGN KEY (FK_TMUNICIPIO) REFERENCES academico_test.tmunicipio (PK_TMUNICIPIO)
);

-- Unicidad parcial y no constraint: el borrado es logico (ACTIVE=false) y un
-- NIT/nombre liberado debe poder reusarse. Mismo criterio que V71 en coleval.
CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TENTE_NIT ON pigse.tente (NIT) WHERE ACTIVE = true;
CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TENTE_NOMBRE ON pigse.tente (NOMBRE) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_MUNICIPIO ON pigse.tente (FK_TMUNICIPIO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_PADRE ON pigse.tente (FK_TENTE_PADRE);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_ACTIVE ON pigse.tente (PK_ENTE) WHERE ACTIVE = true;

COMMENT ON TABLE pigse.tente IS 'Ente territorial de PIGSE. Jerarquico via FK_TENTE_PADRE.';

-- ---------------------------------------------------------------------------
-- Tabla: pigse.testablecimiento
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.testablecimiento (
  PK_ESTABLECIMIENTO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CODIGO VARCHAR(30),
  NOMBRE VARCHAR(130) NOT NULL,
  NIT VARCHAR(30),
  FK_TMUNICIPIO BIGINT NOT NULL,
  FK_TLISTA_VALOR_ZONA BIGINT,
  DIRECCION VARCHAR(130),
  CORREO_ELECTRONICO VARCHAR(130),
  TELEFONO VARCHAR(130),
  PAGINA_WEB VARCHAR(130),
  IDECOL VARCHAR(7),
  RESOLUCION_APROBACION VARCHAR(130),
  LICENCIA_FUNCIONAMIENTO VARCHAR(130),
  FECHA_LICENCIA DATE,
  FK_TPROPIEDAD_JURIDICA BIGINT,
  FK_TLV_CALENDARIO BIGINT,
  FK_TLV_ESTADO_ESTABLECIMIENTO BIGINT,
  -- Decide la regla PEI/PEC/PMI: S = etnoeducativo (aplica PEC, PEI no),
  -- N = aplica PEI. NULL deja los tres como PENDIENTE, nunca NO_APLICA.
  ETNIAS academico_test.bool_sn,
  ESTADO academico_test.estado_ai DEFAULT 'A' NOT NULL,
  FK_TARCHIVO BIGINT,
  -- Procedencia del backfill desde academico_test.testablecimiento (V259).
  -- Sin FK a proposito: los establecimientos de PIGSE son independientes y no
  -- deben quedar atados al ciclo de vida de los de coleval.
  FK_TESTABLECIMIENTO_ORIGEN BIGINT,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TESTABLECIMIENTO PRIMARY KEY (PK_ESTABLECIMIENTO),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_MUNICIPIO FOREIGN KEY (FK_TMUNICIPIO) REFERENCES academico_test.tmunicipio (PK_TMUNICIPIO),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_ZONA FOREIGN KEY (FK_TLISTA_VALOR_ZONA) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_PROPJUR FOREIGN KEY (FK_TPROPIEDAD_JURIDICA) REFERENCES academico_test.tpropiedad_juridica (PK_PROPIEDAD_JURIDICA),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_CALENDARIO FOREIGN KEY (FK_TLV_CALENDARIO) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_ESTADO FOREIGN KEY (FK_TLV_ESTADO_ESTABLECIMIENTO) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TESTABLECIMIENTO_ARCHIVO FOREIGN KEY (FK_TARCHIVO) REFERENCES pigse.tarchivo (pk_tarchivo)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TESTABLECIMIENTO_CODIGO ON pigse.testablecimiento (CODIGO) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_MUNICIPIO ON pigse.testablecimiento (FK_TMUNICIPIO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_ZONA ON pigse.testablecimiento (FK_TLISTA_VALOR_ZONA);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_PROPJUR ON pigse.testablecimiento (FK_TPROPIEDAD_JURIDICA);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_IDECOL ON pigse.testablecimiento (IDECOL);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_ORIGEN ON pigse.testablecimiento (FK_TESTABLECIMIENTO_ORIGEN);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TESTABLECIMIENTO_ACTIVE ON pigse.testablecimiento (PK_ESTABLECIMIENTO) WHERE ACTIVE = true;

COMMENT ON TABLE pigse.testablecimiento IS 'Establecimiento de PIGSE, independiente de academico_test.testablecimiento.';
COMMENT ON COLUMN pigse.testablecimiento.FK_TESTABLECIMIENTO_ORIGEN IS 'Trazabilidad del backfill: PK_ESTABLECIMIENTO de origen en academico_test, sin FK';

-- ---------------------------------------------------------------------------
-- Tabla: pigse.tente_establecimiento
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tente_establecimiento (
  PK_TENTE_ESTABLECIMIENTO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TENTE BIGINT NOT NULL,
  FK_TESTABLECIMIENTO BIGINT NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TENTE_ESTABLECIMIENTO PRIMARY KEY (PK_TENTE_ESTABLECIMIENTO),
  CONSTRAINT FK_PIGSE_TENTE_EST_1 FOREIGN KEY (FK_TENTE) REFERENCES pigse.tente (PK_ENTE),
  CONSTRAINT FK_PIGSE_TENTE_EST_2 FOREIGN KEY (FK_TESTABLECIMIENTO) REFERENCES pigse.testablecimiento (PK_ESTABLECIMIENTO)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TENTE_EST ON pigse.tente_establecimiento (FK_TENTE, FK_TESTABLECIMIENTO) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_EST_ENTE ON pigse.tente_establecimiento (FK_TENTE);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_EST_EST ON pigse.tente_establecimiento (FK_TESTABLECIMIENTO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_EST_ACTIVE ON pigse.tente_establecimiento (PK_TENTE_ESTABLECIMIENTO) WHERE ACTIVE = true;

-- ---------------------------------------------------------------------------
-- Tabla: pigse.tusuario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tusuario (
  PK_TUSUARIO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  -- La credencial vive en public.users; aqui solo el enlace, nullable porque
  -- un funcionario puede registrarse antes de tener cuenta en el SSO.
  FK_ID_USER BIGINT,
  CORREO_ELECTRONICO VARCHAR(120) NOT NULL,
  ESTADO academico_test.estado_ai DEFAULT 'A' NOT NULL,
  IDENTIFICACION VARCHAR(30),
  FK_TLV_TIPO_DOCUMENTO BIGINT,
  FK_TMUNICIPIO_DOCUMENTO BIGINT,
  PRIMER_NOMBRE VARCHAR(40) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(40),
  PRIMER_APELLIDO VARCHAR(40) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(40),
  FECHA_NACIMIENTO DATE,
  FK_TLV_GENERO BIGINT,
  FK_TMUNICIPIO_RESIDENCIA BIGINT,
  DIRECCION_RESIDENCIA VARCHAR(150),
  TELEFONO VARCHAR(30),
  FK_TARCHIVO BIGINT,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TUSUARIO PRIMARY KEY (PK_TUSUARIO),
  CONSTRAINT FK_PIGSE_TUSUARIO_USER FOREIGN KEY (FK_ID_USER) REFERENCES public.users (id_user),
  CONSTRAINT FK_PIGSE_TUSUARIO_TIPO_DOC FOREIGN KEY (FK_TLV_TIPO_DOCUMENTO) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TUSUARIO_MPIO_DOC FOREIGN KEY (FK_TMUNICIPIO_DOCUMENTO) REFERENCES academico_test.tmunicipio (PK_TMUNICIPIO),
  CONSTRAINT FK_PIGSE_TUSUARIO_MPIO_RES FOREIGN KEY (FK_TMUNICIPIO_RESIDENCIA) REFERENCES academico_test.tmunicipio (PK_TMUNICIPIO),
  CONSTRAINT FK_PIGSE_TUSUARIO_GENERO FOREIGN KEY (FK_TLV_GENERO) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TUSUARIO_ARCHIVO FOREIGN KEY (FK_TARCHIVO) REFERENCES pigse.tarchivo (pk_tarchivo)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TUSUARIO_CORREO ON pigse.tusuario (LOWER(CORREO_ELECTRONICO)) WHERE ACTIVE = true;
CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TUSUARIO_DOC ON pigse.tusuario (FK_TLV_TIPO_DOCUMENTO, IDENTIFICACION) WHERE ACTIVE = true;
CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TUSUARIO_ID_USER ON pigse.tusuario (FK_ID_USER) WHERE ACTIVE = true AND FK_ID_USER IS NOT NULL;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TUSUARIO_ACTIVE ON pigse.tusuario (PK_TUSUARIO) WHERE ACTIVE = true;

COMMENT ON COLUMN pigse.tusuario.FK_ID_USER IS 'Enlace a la cuenta del SSO (public.users); NULL mientras no tenga login';

-- ---------------------------------------------------------------------------
-- Tabla: pigse.tfuncionario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tfuncionario (
  PK_TFUNCIONARIO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TUSUARIO BIGINT NOT NULL,
  FK_TESTABLECIMIENTO BIGINT NOT NULL,
  FK_TLV_CARGO BIGINT,
  FK_TLV_TIPO_VINCULACION BIGINT,
  FECHA_VINCULACION DATE,
  TELEFONOS VARCHAR(100),
  AMENAZADO academico_test.bool_sn DEFAULT 'N',
  FK_TARCHIVO BIGINT,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TFUNCIONARIO PRIMARY KEY (PK_TFUNCIONARIO),
  CONSTRAINT FK_PIGSE_TFUNCIONARIO_USUARIO FOREIGN KEY (FK_TUSUARIO) REFERENCES pigse.tusuario (PK_TUSUARIO),
  CONSTRAINT FK_PIGSE_TFUNCIONARIO_EST FOREIGN KEY (FK_TESTABLECIMIENTO) REFERENCES pigse.testablecimiento (PK_ESTABLECIMIENTO),
  CONSTRAINT FK_PIGSE_TFUNCIONARIO_CARGO FOREIGN KEY (FK_TLV_CARGO) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TFUNCIONARIO_VINC FOREIGN KEY (FK_TLV_TIPO_VINCULACION) REFERENCES academico_test.tlista_valor (PK_LISTA_VALOR),
  CONSTRAINT FK_PIGSE_TFUNCIONARIO_ARCHIVO FOREIGN KEY (FK_TARCHIVO) REFERENCES pigse.tarchivo (pk_tarchivo)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TFUNCIONARIO_USUARIO ON pigse.tfuncionario (FK_TUSUARIO) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TFUNCIONARIO_EST ON pigse.tfuncionario (FK_TESTABLECIMIENTO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TFUNCIONARIO_CARGO ON pigse.tfuncionario (FK_TLV_CARGO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TFUNCIONARIO_ACTIVE ON pigse.tfuncionario (PK_TFUNCIONARIO) WHERE ACTIVE = true;

COMMENT ON TABLE pigse.tfuncionario IS 'Perfil laboral 1:1 con pigse.tusuario, ligado a un establecimiento.';

-- ---------------------------------------------------------------------------
-- Tabla: pigse.tente_usuario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tente_usuario (
  PK_TENTE_USUARIO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TENTE BIGINT NOT NULL,
  FK_TUSUARIO BIGINT NOT NULL,
  -- Rol del SSO (public.role, los PIGSE-* de V148). TROL/TROL_MENU de
  -- academico_test no aplican a esta app.
  FK_ID_ROLE BIGINT NOT NULL,
  TLV_ESTADO academico_test.estado_activo_inactivo DEFAULT 'ACTIVO' NOT NULL,
  PREDETERMINADO NUMERIC(6) DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TENTE_USUARIO PRIMARY KEY (PK_TENTE_USUARIO),
  CONSTRAINT FK_PIGSE_TENTE_USUARIO_ENTE FOREIGN KEY (FK_TENTE) REFERENCES pigse.tente (PK_ENTE),
  CONSTRAINT FK_PIGSE_TENTE_USUARIO_USUARIO FOREIGN KEY (FK_TUSUARIO) REFERENCES pigse.tusuario (PK_TUSUARIO),
  CONSTRAINT FK_PIGSE_TENTE_USUARIO_ROLE FOREIGN KEY (FK_ID_ROLE) REFERENCES public.role (id_role)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TENTE_USUARIO ON pigse.tente_usuario (FK_TENTE, FK_TUSUARIO, FK_ID_ROLE) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_USUARIO_USUARIO ON pigse.tente_usuario (FK_TUSUARIO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_USUARIO_ROLE ON pigse.tente_usuario (FK_ID_ROLE);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TENTE_USUARIO_ACTIVE ON pigse.tente_usuario (PK_TENTE_USUARIO) WHERE ACTIVE = true;

-- ---------------------------------------------------------------------------
-- Tabla: pigse.testablecimiento_usuario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.testablecimiento_usuario (
  PK_TESTABLECIMIENTO_USUARIO BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TESTABLECIMIENTO BIGINT NOT NULL,
  FK_TUSUARIO BIGINT NOT NULL,
  FK_ID_ROLE BIGINT NOT NULL,
  TLV_ESTADO academico_test.estado_activo_inactivo DEFAULT 'ACTIVO' NOT NULL,
  PREDETERMINADO NUMERIC(6) DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR(120) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(120),
  MODIFIED_AT TIMESTAMP,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PIGSE_TEST_USUARIO PRIMARY KEY (PK_TESTABLECIMIENTO_USUARIO),
  CONSTRAINT FK_PIGSE_TEST_USUARIO_EST FOREIGN KEY (FK_TESTABLECIMIENTO) REFERENCES pigse.testablecimiento (PK_ESTABLECIMIENTO),
  CONSTRAINT FK_PIGSE_TEST_USUARIO_USUARIO FOREIGN KEY (FK_TUSUARIO) REFERENCES pigse.tusuario (PK_TUSUARIO),
  CONSTRAINT FK_PIGSE_TEST_USUARIO_ROLE FOREIGN KEY (FK_ID_ROLE) REFERENCES public.role (id_role)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TEST_USUARIO ON pigse.testablecimiento_usuario (FK_TESTABLECIMIENTO, FK_TUSUARIO, FK_ID_ROLE) WHERE ACTIVE = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TEST_USUARIO_USUARIO ON pigse.testablecimiento_usuario (FK_TUSUARIO);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TEST_USUARIO_ROLE ON pigse.testablecimiento_usuario (FK_ID_ROLE);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TEST_USUARIO_ACTIVE ON pigse.testablecimiento_usuario (PK_TESTABLECIMIENTO_USUARIO) WHERE ACTIVE = true;

-- ---------------------------------------------------------------------------
-- Auditoria CDC. V26/V276 solo recorren academico_test, asi que las tablas de
-- pigse nacerian sin emitir contexto; se instala aqui la MISMA definicion.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT t.schemaname, t.tablename
          FROM pg_tables t
         WHERE t.schemaname = 'pigse'
           AND t.tablename IN ('tente', 'testablecimiento', 'tente_establecimiento',
                               'tusuario', 'tfuncionario', 'tente_usuario',
                               'testablecimiento_usuario')
           AND NOT EXISTS (
               SELECT 1
                 FROM pg_trigger tg
                 JOIN pg_class c     ON c.oid = tg.tgrelid
                 JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = t.schemaname
                  AND c.relname = t.tablename
                  AND tg.tgname = 'trg_audit_ctx'
                  AND NOT tg.tgisinternal
           )
         ORDER BY t.tablename
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_audit_ctx BEFORE INSERT OR UPDATE OR DELETE ON %I.%I
             FOR EACH STATEMENT EXECUTE FUNCTION academico_test.fn_audit_ctx()',
            r.schemaname, r.tablename
        );
        RAISE NOTICE 'trg_audit_ctx instalado en %.%', r.schemaname, r.tablename;
    END LOOP;
END $$;
