-- Mueve al schema propio de PIGSE los documentos institucionales (PEI/PEC/PMI)
-- y el monitoreo de cumplimiento, replicando el comportamiento VIGENTE de las
-- academico_test.fn_pigse_* (V149 + V152 + V196). Nada de academico_test se
-- toca: las funciones originales quedan intactas y siguen leyendo su fuente.
-- Los catalogos (tlista_valor, tmunicipio) siguen siendo los compartidos.

-- ---------------------------------------------------------------------------
-- De donde se leen los metadatos de un archivo.
--
-- fk_tarchivo NO lleva FK a proposito: la autoridad de en que schema vive un
-- archivo es public.file_reference_location, y el pk es global
-- (public.seq_pk_tarchivo, V147). Los archivos historicos de PIGSE quedaron en
-- academico_test.tarchivo (V149 apuntaba file_storage_schema ahi); los nuevos
-- caen en pigse.tarchivo (V262). Esta vista los resuelve por pk sin duplicar
-- filas ni mover blobs.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW pigse.v_archivo AS
SELECT pk_tarchivo, nombre, peso, created_at FROM pigse.tarchivo          WHERE active
UNION ALL
SELECT pk_tarchivo, nombre, peso, created_at FROM academico_test.tarchivo WHERE active;

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tdocumento_institucional (
    pk_documento_institucional BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_testablecimiento        BIGINT NOT NULL,
    tipo                       VARCHAR(10) NOT NULL,
    fk_tarchivo                BIGINT,
    created_by                 VARCHAR(120) NOT NULL,
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_by                VARCHAR(120),
    modified_at                TIMESTAMP,
    active                     BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pigse_tdocumento_institucional_pk PRIMARY KEY (pk_documento_institucional),
    CONSTRAINT pigse_tdocumento_institucional_tipo_chk CHECK (tipo IN ('PEI', 'PEC', 'PMI')),
    CONSTRAINT fk_pigse_tdocumento_inst_testablec FOREIGN KEY (fk_testablecimiento)
        REFERENCES pigse.testablecimiento (PK_ESTABLECIMIENTO)
);

-- Un documento VIGENTE por EE+tipo: reemplazar es UPDATE, no un segundo INSERT.
CREATE UNIQUE INDEX IF NOT EXISTS U_PIGSE_TDOCUMENTO_INST_EE_TIPO
    ON pigse.tdocumento_institucional (fk_testablecimiento, tipo)
    WHERE active = true;
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TDOCUMENTO_INST_ARCHIVO
    ON pigse.tdocumento_institucional (fk_tarchivo);
CREATE INDEX IF NOT EXISTS IDX_PIGSE_TDOCUMENTO_INST_ACTIVE
    ON pigse.tdocumento_institucional (pk_documento_institucional) WHERE active = true;

CREATE TABLE IF NOT EXISTS pigse.tdocumento_institucional_hist (
    pk_documento_institucional_hist BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_documento_institucional      BIGINT NOT NULL,
    fk_tarchivo                     BIGINT NOT NULL,
    reemplazado_by                  VARCHAR(120) NOT NULL,
    reemplazado_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pigse_tdoc_inst_hist_pk PRIMARY KEY (pk_documento_institucional_hist),
    CONSTRAINT fk_pigse_tdoc_inst_hist_doc FOREIGN KEY (fk_documento_institucional)
        REFERENCES pigse.tdocumento_institucional (pk_documento_institucional)
);

CREATE INDEX IF NOT EXISTS IDX_PIGSE_TDOC_INST_HIST_DOC
    ON pigse.tdocumento_institucional_hist (fk_documento_institucional);

COMMENT ON TABLE pigse.tdocumento_institucional IS
    'PIGSE -- documento institucional vigente por establecimiento y tipo (PEI/PEC/PMI). fk_tarchivo NULL = PENDIENTE.';
COMMENT ON TABLE pigse.tdocumento_institucional_hist IS
    'PIGSE -- versiones reemplazadas o retiradas de un documento institucional.';

-- ---------------------------------------------------------------------------
-- Auditoria CDC. V26/V276 solo recorren academico_test, asi que estas tablas
-- nacerian sin emitir contexto; misma definicion que instala V256.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT t.schemaname, t.tablename
          FROM pg_tables t
         WHERE t.schemaname = 'pigse'
           AND t.tablename IN ('tdocumento_institucional', 'tdocumento_institucional_hist')
           AND NOT EXISTS (
               SELECT 1
                 FROM pg_trigger tg
                 JOIN pg_class c     ON c.oid = tg.tgrelid
                 JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = t.schemaname
                  AND c.relname = t.tablename
                  AND tg.tgname = 'trg_audit_ctx'
                  AND NOT tg.tgisinternal
           )
         ORDER BY t.tablename
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_audit_ctx BEFORE INSERT OR UPDATE OR DELETE ON %I.%I
             FOR EACH STATEMENT EXECUTE FUNCTION academico_test.fn_audit_ctx()',
            r.schemaname, r.tablename
        );
        RAISE NOTICE 'trg_audit_ctx instalado en %.%', r.schemaname, r.tablename;
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Resolucion de identidad: espejo de public.fn_get_academico_usuario_id, pero
-- contra pigse.tusuario. Solo por FK_ID_USER: en pigse el enlace con el login
-- es explicito, no hay que adivinarlo por correo.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_get_pigse_usuario_id(p_id_user BIGINT)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
SET search_path TO 'public', 'pigse'
AS $$
DECLARE
    v_pk BIGINT;
BEGIN
    IF p_id_user IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT u.PK_TUSUARIO INTO v_pk
      FROM pigse.tusuario u
     WHERE u.FK_ID_USER = p_id_user
       AND u.ACTIVE = TRUE
     ORDER BY u.PK_TUSUARIO
     LIMIT 1;

    RETURN v_pk;
END;
$$;

-- ---------------------------------------------------------------------------
-- Establecimiento del usuario autenticado. El vinculo puede venir del puente
-- con rol o del perfil de funcionario; tiene que resolver a exactamente uno.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_mi_establecimiento(p_email TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_pk    BIGINT;
    v_count INT;
BEGIN
    SELECT COUNT(*), MIN(pk_establecimiento)
      INTO v_count, v_pk
      FROM (
            SELECT te.PK_ESTABLECIMIENTO AS pk_establecimiento
              FROM pigse.tusuario t
              JOIN pigse.testablecimiento_usuario eu ON eu.FK_TUSUARIO = t.PK_TUSUARIO
              JOIN pigse.testablecimiento te ON te.PK_ESTABLECIMIENTO = eu.FK_TESTABLECIMIENTO
             WHERE upper(t.CORREO_ELECTRONICO) = upper(p_email)
               AND t.ACTIVE AND eu.ACTIVE AND eu.TLV_ESTADO = 'ACTIVO' AND te.ACTIVE
            UNION
            SELECT te.PK_ESTABLECIMIENTO
              FROM pigse.tusuario t
              JOIN pigse.tfuncionario f ON f.FK_TUSUARIO = t.PK_TUSUARIO
              JOIN pigse.testablecimiento te ON te.PK_ESTABLECIMIENTO = f.FK_TESTABLECIMIENTO
             WHERE upper(t.CORREO_ELECTRONICO) = upper(p_email)
               AND t.ACTIVE AND f.ACTIVE AND te.ACTIVE
           ) x;

    IF v_count IS NULL OR v_count <> 1 THEN
        RAISE EXCEPTION 'pigse: % no esta vinculado a exactamente un establecimiento (encontrados: %)',
            p_email, COALESCE(v_count, 0);
    END IF;
    RETURN v_pk;
END;
$$;

-- ---------------------------------------------------------------------------
-- Gestion documental
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_documentos_listar(p_fk_establecimiento BIGINT)
RETURNS TABLE(
    id TEXT, type TEXT, "typeName" TEXT, status TEXT, "fileName" TEXT,
    "uploadedAt" TIMESTAMP, "sizeBytes" BIGINT, "archivoId" BIGINT,
    "downloadUrl" TEXT
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        tipos.tipo AS id,
        tipos.tipo AS "type",
        tipos.nombre AS "typeName",
        CASE
            WHEN tipos.tipo = 'PEI' AND te.ETNIAS = 'S' THEN 'NO_APLICA'
            WHEN tipos.tipo = 'PEC' AND te.ETNIAS = 'N' THEN 'NO_APLICA'
            WHEN d.fk_tarchivo IS NOT NULL THEN 'COMPLETO'
            ELSE 'PENDIENTE'
        END AS status,
        ta.nombre AS "fileName",
        ta.created_at AS "uploadedAt",
        ta.peso AS "sizeBytes",
        ta.pk_tarchivo AS "archivoId",
        CASE WHEN ta.pk_tarchivo IS NOT NULL
             THEN '/api/files/download/' || ta.pk_tarchivo
             ELSE NULL
        END AS "downloadUrl"
      FROM pigse.testablecimiento te
     CROSS JOIN (VALUES
                    ('PEI', 'Proyecto Educativo Institucional (PEI)'),
                    ('PEC', 'Proyecto Educativo Comunitario (PEC)'),
                    ('PMI', 'Plan de Mejoramiento Institucional (PMI)')
                ) AS tipos(tipo, nombre)
      LEFT JOIN pigse.tdocumento_institucional d
             ON d.fk_testablecimiento = te.PK_ESTABLECIMIENTO
            AND d.tipo = tipos.tipo
            AND d.active
      LEFT JOIN pigse.v_archivo ta ON ta.pk_tarchivo = d.fk_tarchivo
     WHERE te.PK_ESTABLECIMIENTO = p_fk_establecimiento
     ORDER BY tipos.tipo;
$$;

CREATE OR REPLACE FUNCTION pigse.fn_documento_guardar(
    p_pk_usuario  BIGINT,
    p_email       VARCHAR,
    p_tipo        VARCHAR,
    p_fk_tarchivo BIGINT
)
RETURNS TABLE(
    id TEXT, type TEXT, "typeName" TEXT, status TEXT, "fileName" TEXT,
    "uploadedAt" TIMESTAMP, "sizeBytes" BIGINT, "archivoId" BIGINT,
    "downloadUrl" TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo BIGINT;
    v_etnias             academico_test.bool_sn;
BEGIN
    IF p_fk_tarchivo IS NULL THEN
        RAISE EXCEPTION 'pigse: p_fk_tarchivo es obligatorio (archivo no subido)';
    END IF;

    v_fk_establecimiento := pigse.fn_mi_establecimiento(p_email);

    SELECT ETNIAS INTO v_etnias
      FROM pigse.testablecimiento
     WHERE PK_ESTABLECIMIENTO = v_fk_establecimiento;

    -- Mismos mensajes y ERRCODE que V152: hay clientes que ya los parsean.
    IF p_tipo = 'PEI' AND v_etnias = 'S' THEN
        RAISE EXCEPTION 'pigse: PEI no aplica a este establecimiento (etnoeducativo -- usar PEC)'
            USING ERRCODE = '23514';
    ELSIF p_tipo = 'PEC' AND v_etnias = 'N' THEN
        RAISE EXCEPTION 'pigse: PEC no aplica a este establecimiento (no etnoeducativo -- usar PEI)'
            USING ERRCODE = '23514';
    END IF;

    SELECT pk_documento_institucional, fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM pigse.tdocumento_institucional
     WHERE fk_testablecimiento = v_fk_establecimiento AND tipo = p_tipo AND active;

    IF v_pk_doc IS NULL THEN
        INSERT INTO pigse.tdocumento_institucional
            (fk_testablecimiento, tipo, fk_tarchivo, created_by)
        VALUES (v_fk_establecimiento, p_tipo, p_fk_tarchivo, p_email)
        RETURNING pk_documento_institucional INTO v_pk_doc;
    ELSE
        UPDATE pigse.tdocumento_institucional
           SET fk_tarchivo = p_fk_tarchivo, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
         WHERE pk_documento_institucional = v_pk_doc;

        IF v_fk_tarchivo_previo IS NOT NULL THEN
            INSERT INTO pigse.tdocumento_institucional_hist
                (fk_documento_institucional, fk_tarchivo, reemplazado_by)
            VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);
        END IF;
    END IF;

    RETURN QUERY
    SELECT * FROM pigse.fn_documentos_listar(v_fk_establecimiento)
     WHERE fn_documentos_listar.id = p_tipo;
END;
$$;

CREATE OR REPLACE FUNCTION pigse.fn_documento_eliminar(
    p_pk_usuario BIGINT,
    p_email      VARCHAR,
    p_tipo       VARCHAR
)
RETURNS TABLE(
    id TEXT, type TEXT, "typeName" TEXT, status TEXT, "fileName" TEXT,
    "uploadedAt" TIMESTAMP, "sizeBytes" BIGINT, "archivoId" BIGINT,
    "downloadUrl" TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo BIGINT;
BEGIN
    v_fk_establecimiento := pigse.fn_mi_establecimiento(p_email);

    SELECT pk_documento_institucional, fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM pigse.tdocumento_institucional
     WHERE fk_testablecimiento = v_fk_establecimiento AND tipo = p_tipo AND active;

    IF v_pk_doc IS NULL OR v_fk_tarchivo_previo IS NULL THEN
        RAISE EXCEPTION 'pigse: tipo % desconocido o ya esta PENDIENTE para este establecimiento', p_tipo
            USING ERRCODE = 'P0002';
    END IF;

    UPDATE pigse.tdocumento_institucional
       SET fk_tarchivo = NULL, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
     WHERE pk_documento_institucional = v_pk_doc;

    INSERT INTO pigse.tdocumento_institucional_hist
        (fk_documento_institucional, fk_tarchivo, reemplazado_by)
    VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);

    RETURN QUERY
    SELECT * FROM pigse.fn_documentos_listar(v_fk_establecimiento)
     WHERE fn_documentos_listar.id = p_tipo;
END;
$$;

-- ---------------------------------------------------------------------------
-- Monitoreo y cumplimiento
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_cumplimiento_metricas()
RETURNS TABLE("totalEstablishments" BIGINT, pei JSONB, pec JSONB, pmi JSONB)
LANGUAGE sql
STABLE
AS $$
    WITH ee AS (
        SELECT PK_ESTABLECIMIENTO AS pk_establecimiento, ETNIAS AS etnias
          FROM pigse.testablecimiento WHERE ACTIVE
    ),
    docs AS (
        SELECT ee.pk_establecimiento,
               d.tipo,
               d.fk_tarchivo IS NOT NULL AS completo
          FROM ee
          LEFT JOIN pigse.tdocumento_institucional d
                 ON d.fk_testablecimiento = ee.pk_establecimiento AND d.active
    )
    SELECT
        (SELECT count(*) FROM ee) AS "totalEstablishments",
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PEI' AND docs.completo),
            'total',     count(*) FILTER (WHERE ee.etnias = 'N'),
            'percent',   CASE WHEN count(*) FILTER (WHERE ee.etnias = 'N') = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PEI' AND docs.completo)
                                         / count(*) FILTER (WHERE ee.etnias = 'N'))
                          END
        ) AS pei,
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PEC' AND docs.completo),
            'total',     count(*) FILTER (WHERE ee.etnias = 'S'),
            'percent',   CASE WHEN count(*) FILTER (WHERE ee.etnias = 'S') = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PEC' AND docs.completo)
                                         / count(*) FILTER (WHERE ee.etnias = 'S'))
                          END
        ) AS pec,
        jsonb_build_object(
            'completed', count(*) FILTER (WHERE docs.tipo = 'PMI' AND docs.completo),
            'total',     (SELECT count(*) FROM ee),
            'percent',   CASE WHEN (SELECT count(*) FROM ee) = 0 THEN 0
                              ELSE round(100.0 * count(*) FILTER (WHERE docs.tipo = 'PMI' AND docs.completo)
                                         / (SELECT count(*) FROM ee))
                          END
        ) AS pmi
      FROM ee
      LEFT JOIN docs ON docs.pk_establecimiento = ee.pk_establecimiento;
$$;

CREATE OR REPLACE FUNCTION pigse.fn_cumplimiento_listar()
RETURNS TABLE(
    id BIGINT, "establishmentName" TEXT, pei JSONB, pec JSONB, pmi JSONB,
    "globalProgress" INTEGER
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        te.PK_ESTABLECIMIENTO AS id,
        te.NOMBRE AS "establishmentName",
        jsonb_build_object('status', d_pei.status, 'fileName', d_pei."fileName",
                            'archivoId', d_pei."archivoId", 'downloadUrl', d_pei."downloadUrl") AS pei,
        jsonb_build_object('status', d_pec.status, 'fileName', d_pec."fileName",
                            'archivoId', d_pec."archivoId", 'downloadUrl', d_pec."downloadUrl") AS pec,
        jsonb_build_object('status', d_pmi.status, 'fileName', d_pmi."fileName",
                            'archivoId', d_pmi."archivoId", 'downloadUrl', d_pmi."downloadUrl") AS pmi,
        CASE
            WHEN (CASE WHEN d_pei.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                  + CASE WHEN d_pec.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                  + CASE WHEN d_pmi.status <> 'NO_APLICA' THEN 1 ELSE 0 END) = 0 THEN 0
            ELSE round(
                100.0 * (
                    CASE WHEN d_pei.status = 'COMPLETO' THEN 1 ELSE 0 END
                    + CASE WHEN d_pec.status = 'COMPLETO' THEN 1 ELSE 0 END
                    + CASE WHEN d_pmi.status = 'COMPLETO' THEN 1 ELSE 0 END
                ) / (
                    CASE WHEN d_pei.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                    + CASE WHEN d_pec.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                    + CASE WHEN d_pmi.status <> 'NO_APLICA' THEN 1 ELSE 0 END
                )
            )
        END AS "globalProgress"
      FROM pigse.testablecimiento te
      JOIN LATERAL (
              SELECT * FROM pigse.fn_documentos_listar(te.PK_ESTABLECIMIENTO) WHERE id = 'PEI'
          ) d_pei ON true
      JOIN LATERAL (
              SELECT * FROM pigse.fn_documentos_listar(te.PK_ESTABLECIMIENTO) WHERE id = 'PEC'
          ) d_pec ON true
      JOIN LATERAL (
              SELECT * FROM pigse.fn_documentos_listar(te.PK_ESTABLECIMIENTO) WHERE id = 'PMI'
          ) d_pmi ON true
     WHERE te.ACTIVE
     ORDER BY te.NOMBRE;
$$;

CREATE OR REPLACE FUNCTION pigse.fn_cumplimiento_listar_paginado(
    p_search     VARCHAR   DEFAULT NULL,
    p_pei        VARCHAR[] DEFAULT NULL,
    p_pec        VARCHAR[] DEFAULT NULL,
    p_pmi        VARCHAR[] DEFAULT NULL,
    p_sort_campo VARCHAR   DEFAULT NULL,
    p_sort_desc  BOOLEAN   DEFAULT FALSE,
    p_page_index INTEGER   DEFAULT 0,
    p_page_size  INTEGER   DEFAULT 10
)
RETURNS TABLE(rows JSONB, total_count BIGINT, page_count INTEGER,
              page_index INTEGER, page_size INTEGER)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    -- Se acota a [1, 200]: 0 dividiria por cero al calcular page_count y un
    -- valor enorme convierte el paginado en un "traeme todo".
    v_page_size  integer := GREATEST(1, LEAST(COALESCE(p_page_size, 10), 200));
    v_page_index integer := GREATEST(0, COALESCE(p_page_index, 0));
    v_campo      varchar := COALESCE(NULLIF(p_sort_campo, ''), 'establishmentName');
    v_desc       boolean := COALESCE(p_sort_desc, false);
BEGIN
    RETURN QUERY
    WITH base AS (
        SELECT * FROM pigse.fn_cumplimiento_listar()
    ),
    filtrada AS (
        SELECT b.*
          FROM base b
         WHERE (
                 -- Insensible a mayusculas y a tildes con translate(): la
                 -- extension `unaccent` no esta instalada en el cluster.
                 NULLIF(p_search, '') IS NULL
                 OR translate(lower(b."establishmentName"), 'áéíóúüñ', 'aeiouun')
                    LIKE '%' || translate(lower(p_search), 'áéíóúüñ', 'aeiouun') || '%'
               )
           -- Un array NULL o vacio no filtra.
           AND (COALESCE(array_length(p_pei, 1), 0) = 0 OR b.pei->>'status' = ANY(p_pei))
           AND (COALESCE(array_length(p_pec, 1), 0) = 0 OR b.pec->>'status' = ANY(p_pec))
           AND (COALESCE(array_length(p_pmi, 1), 0) = 0 OR b.pmi->>'status' = ANY(p_pmi))
    ),
    numerada AS (
        SELECT f.*,
               ROW_NUMBER() OVER (
                   ORDER BY
                       CASE WHEN v_campo = 'globalProgress'    AND NOT v_desc
                            THEN f."globalProgress" END ASC,
                       CASE WHEN v_campo = 'globalProgress'    AND     v_desc
                            THEN f."globalProgress" END DESC,
                       CASE WHEN v_campo = 'establishmentName' AND     v_desc
                            THEN f."establishmentName" END DESC,
                       -- Desempate estable: sin el, dos EE con el mismo
                       -- progreso se intercambian entre paginas.
                       f."establishmentName" ASC
               ) AS rn
          FROM filtrada f
    ),
    pagina AS (
        SELECT *
          FROM numerada
         WHERE rn >  v_page_index * v_page_size
           AND rn <= (v_page_index + 1) * v_page_size
    )
    SELECT
        COALESCE(
            (SELECT jsonb_agg(to_jsonb(p) - 'rn' ORDER BY p.rn) FROM pagina p),
            '[]'::jsonb
        ),
        (SELECT COUNT(*) FROM filtrada),
        GREATEST(1, CEIL((SELECT COUNT(*) FROM filtrada)::numeric / v_page_size)::integer),
        v_page_index,
        v_page_size;
END;
$$;
