-- ===========================================================================
-- V336 - TINFORME_PERIODO_MATRICULA: metricas consolidadas del informe por
-- (matricula, periodo). fn_informe_periodo_guardar vive hoy en V490.
-- ===========================================================================


CREATE TABLE IF NOT EXISTS academico_test.TINFORME_PERIODO_MATRICULA (
    PK_TINFORME_PERIODO_MATRICULA BIGINT GENERATED BY DEFAULT AS IDENTITY,

    FK_TMATRICULA           BIGINT NOT NULL,
    FK_TPERIODO_EVALUACION  BIGINT NOT NULL,

    PROMEDIO                NUMERIC,
    ASIGNATURAS             NUMERIC,
    APROBADAS               NUMERIC,
    REPROBADAS              NUMERIC,
    SIN_DEFINIR             NUMERIC,

    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY             VARCHAR(50),
    MODIFIED_AT             TIMESTAMP,
    ACTIVE                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TINFORME_PERIODO_MATRICULA
        PRIMARY KEY (PK_TINFORME_PERIODO_MATRICULA),
    CONSTRAINT FK_TINFORME_PERIODO_MATRICULA_1
        FOREIGN KEY (FK_TMATRICULA)
        REFERENCES academico_test.TMATRICULA (PK_TMATRICULA),
    CONSTRAINT FK_TINFORME_PERIODO_MATRICULA_2
        FOREIGN KEY (FK_TPERIODO_EVALUACION)
        REFERENCES academico_test.TPERIODO_EVALUACION (PK_TPERIODO_EVALUACION)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_PERIODO_MATRICULA_1
    ON academico_test.TINFORME_PERIODO_MATRICULA (FK_TMATRICULA);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_PERIODO_MATRICULA_2
    ON academico_test.TINFORME_PERIODO_MATRICULA (FK_TPERIODO_EVALUACION);

CREATE UNIQUE INDEX IF NOT EXISTS U_TINFORME_PERIODO_MATRICULA_1
    ON academico_test.TINFORME_PERIODO_MATRICULA
       (FK_TMATRICULA, FK_TPERIODO_EVALUACION);

COMMENT ON TABLE academico_test.TINFORME_PERIODO_MATRICULA
    IS 'Metricas consolidadas de un estudiante en un periodo de evaluacion: promedio y conteos de asignaturas aprobadas / reprobadas / sin definir. Son las columnas PR, AP y RE del listado de informes, y se guardan para no recalcularlas en cada apertura de la pantalla -- el promedio obliga a recorrer todas las asignaturas de cada estudiante del grupo. Las escribe fn_informe_periodo_guardar junto con las notas; mientras no exista la fila, fn_informe_grupo_listar calcula los mismos valores al vuelo, de modo que la pantalla funciona igual antes y despues de consolidar. EL PUESTO NO ESTA AQUI Y ES DELIBERADO: no es un dato del estudiante sino de su posicion RELATIVA en el grupo -- subir la nota de uno cambia el puesto de otro que nadie toco --, asi que guardarlo obligaria a reescribir la fila de todo el grupo en cada guardado, incluidos estudiantes que el usuario no selecciono, y a ese costo ya no se gana nada frente a calcularlo al listar con un RANK() sobre un conjunto que de todas formas hay que traer entero. El promedio se guarda en PORCENTAJE, igual que TASIGNATURA_NOTA.DEFINITIVA, porque la escala del colegio depende de TCRITERIO_EVALUACION y puede cambiar.';

COMMENT ON COLUMN academico_test.TINFORME_PERIODO_MATRICULA.PROMEDIO
    IS 'Promedio del estudiante en el periodo, en PORCENTAJE (0..100). Media simple de la definitiva de cada asignatura; no se promedian notas homologadas porque mezclar escalas distintas en una media no significa nada';

COMMENT ON COLUMN academico_test.TINFORME_PERIODO_MATRICULA.APROBADAS
    IS 'Asignaturas con definitiva mayor o igual al DESEMPENHO_MINIMO del grado';

COMMENT ON COLUMN academico_test.TINFORME_PERIODO_MATRICULA.REPROBADAS
    IS 'Asignaturas con definitiva por debajo del DESEMPENHO_MINIMO del grado';

COMMENT ON COLUMN academico_test.TINFORME_PERIODO_MATRICULA.SIN_DEFINIR
    IS 'Asignaturas donde la aprobacion no se puede decidir: sin nota, o sin DESEMPENHO_MINIMO configurado en el grado. No se cuentan como reprobadas -- no se puede decir';
