-- ===========================================================================
-- V348 - historial guardado informe
-- Recortada: las funciones de informes que V535-V541 reescriben en capas
-- se quitaron de aqui y viven alli. Queda lo que sigue vivo y lo que una
-- base limpia necesita al migrar (CREATE solo si la funcion no existe).
-- ===========================================================================


CREATE TABLE IF NOT EXISTS academico_test.TINFORME_GUARDADO (
    PK_TINFORME_GUARDADO    BIGINT GENERATED BY DEFAULT AS IDENTITY,

    FK_TGRUPO               BIGINT      NOT NULL,
    
    
    FK_TASIGNATURA          BIGINT,
    FK_TPERIODO_EVALUACION  BIGINT      NOT NULL,
    
    
    FK_TUSUARIO             BIGINT      NOT NULL,

    ORIGEN                  VARCHAR(20) NOT NULL,
    ESTUDIANTES             NUMERIC     NOT NULL,

    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY             VARCHAR(50),
    MODIFIED_AT             TIMESTAMP,
    ACTIVE                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TINFORME_GUARDADO PRIMARY KEY (PK_TINFORME_GUARDADO),
    CONSTRAINT FK_TINFORME_GUARDADO_1 FOREIGN KEY (FK_TGRUPO)
        REFERENCES academico_test.TGRUPO (PK_TGRUPO),
    CONSTRAINT FK_TINFORME_GUARDADO_2 FOREIGN KEY (FK_TASIGNATURA)
        REFERENCES academico_test.TASIGNATURA (PK_TASIGNATURA),
    CONSTRAINT FK_TINFORME_GUARDADO_3 FOREIGN KEY (FK_TPERIODO_EVALUACION)
        REFERENCES academico_test.TPERIODO_EVALUACION (PK_TPERIODO_EVALUACION),
    CONSTRAINT FK_TINFORME_GUARDADO_4 FOREIGN KEY (FK_TUSUARIO)
        REFERENCES academico_test.TUSUARIO (PK_TUSUARIO)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_1
    ON academico_test.TINFORME_GUARDADO (FK_TGRUPO);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_2
    ON academico_test.TINFORME_GUARDADO (FK_TPERIODO_EVALUACION);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_3
    ON academico_test.TINFORME_GUARDADO (FK_TUSUARIO);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_FECHA
    ON academico_test.TINFORME_GUARDADO (CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS academico_test.TINFORME_GUARDADO_ESTUDIANTE (
    PK_TINFORME_GUARDADO_ESTUDIANTE BIGINT GENERATED BY DEFAULT AS IDENTITY,

    FK_TINFORME_GUARDADO    BIGINT      NOT NULL,
    FK_TMATRICULA           BIGINT      NOT NULL,
    
    PROMEDIO                NUMERIC,
    ASIGNATURAS_AFECTADAS   NUMERIC,

    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TINFORME_GUARDADO_ESTUDIANTE
        PRIMARY KEY (PK_TINFORME_GUARDADO_ESTUDIANTE),
    CONSTRAINT FK_TINFORME_GUARDADO_ESTUDIANTE_1
        FOREIGN KEY (FK_TINFORME_GUARDADO)
        REFERENCES academico_test.TINFORME_GUARDADO (PK_TINFORME_GUARDADO),
    CONSTRAINT FK_TINFORME_GUARDADO_ESTUDIANTE_2
        FOREIGN KEY (FK_TMATRICULA)
        REFERENCES academico_test.TMATRICULA (PK_TMATRICULA)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_ESTUDIANTE_1
    ON academico_test.TINFORME_GUARDADO_ESTUDIANTE (FK_TINFORME_GUARDADO);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_ESTUDIANTE_2
    ON academico_test.TINFORME_GUARDADO_ESTUDIANTE (FK_TMATRICULA);

COMMENT ON TABLE academico_test.TINFORME_GUARDADO
    IS 'Cabecera del historial de guardados del modulo de informes: un registro por operacion de guardado que efectivamente escribio algo. EL GRANO DEL CONTEO ES EL ESTUDIANTE, no la nota: la pantalla mockeada contaba calificaciones (una por asignatura escrita) y se descarto porque no aporta nada a lo que el historial responde -- quien guardo que y cuando -- y produce numeros inutilizables: un curso de 30 con 12 asignaturas daria "360 cambios". Un estudiante guardado = un cambio. FK_TASIGNATURA es NULLABLE y ahi esta la diferencia entre los dos origenes: NULL significa que se guardo el informe COMPLETO del estudiante (todas sus asignaturas, desde /informes/guardar) y con valor que se guardo esa sola desde la planilla; es mas honesto que inventar una asignatura ficticia para el caso completo. FK_TUSUARIO es quien opero el sistema, no quien dicta la asignatura, por eso apunta a TUSUARIO y no a TFUNCIONARIO. Se separa del detalle porque la tarjeta del historial solo necesita la cabecera y el detalle se abre al desplegar; con una sola tabla, listar obligaria a traer todos los estudiantes de todos los guardados solo para contarlos. Solo se crea si algun estudiante cambio de verdad: los sin_cambio y sin_proyeccion no cuentan, para que volver a pulsar guardar no deje entradas vacias en un historial que se agrupa por dia y solo muestra los dias con movimiento.';

COMMENT ON TABLE academico_test.TINFORME_GUARDADO_ESTUDIANTE
    IS 'Detalle del historial: a que estudiantes alcanzo un guardado, con el PROMEDIO del periodo tal como quedo despues de esa operacion y cuantas asignaturas se le escribieron. El promedio se COPIA y no se recalcula al consultar: el historial dice que paso ESE dia, y si manana alguien vuelve a consolidar, aquella entrada debe seguir mostrando lo que mostro entonces -- esa es la diferencia entre un historial y un listado. Solo entran los estudiantes a los que se les escribio alguna nota (resultado guardada o actualizada).';
