-- ===========================================================================
-- V348 - Historial de guardados del informe: las dos tablas, el registrador,
--        y el cableado en los dos guardados.
--
--   TINFORME_GUARDADO             cabecera: un guardado
--   TINFORME_GUARDADO_ESTUDIANTE  detalle: a quien se le guardo
--   fn_informe_historial_registrar   punto unico de escritura
--   fn_informe_periodo_guardar       (reescrita) registra al final
--   fn_informe_planilla_guardar      (reescrita) registra al final
--
--
-- (1) EL GRANO ES EL ESTUDIANTE, NO LA NOTA
--   La pantalla mockeada contaba "calificaciones": una por cada nota de
--   asignatura escrita. Se descarto a proposito.
--
--   Contar notas no aporta nada a lo que el historial responde -- "quien
--   guardo que y cuando" -- y en cambio produce numeros que no significan
--   nada: guardar el informe de un curso de 30 con 12 asignaturas daria
--   "360 cambios". Un numero grande que nadie puede verificar ni usar.
--
--   Asi que UN ESTUDIANTE GUARDADO = UN CAMBIO. Guardar el informe de 30
--   estudiantes es un guardado con 30 cambios, y el detalle dice cuales.
--
--
-- (2) SOLO SE REGISTRA LO QUE DE VERDAD CAMBIO
--   Un estudiante entra al historial unicamente si se le ESCRIBIO alguna nota
--   -- resultado 'guardada' o 'actualizada' --. Los 'sin_cambio' y
--   'sin_proyeccion' no entran, y si ningun estudiante cambio no se crea
--   cabecera.
--
--   Sin esto, volver a pulsar guardar dejaria una entrada identica a la
--   anterior pero con cero contenido, y el historial -- que se agrupa por
--   dia y solo muestra los dias con movimiento -- se llenaria de ruido que
--   haria mas dificil encontrar el cambio real.
--
--
-- (3) DOS TABLAS Y NO UNA
--   La cabecera es lo que se pinta en la tarjeta (grupo, asignatura, hora,
--   quien, cuantos) y el detalle solo se abre al desplegar "Cambios: N". Con
--   una sola tabla, listar el historial obligaria a traer todos los
--   estudiantes de todos los guardados para poder contar, que es justo lo que
--   se quiere evitar.
--
--   FK_TASIGNATURA es NULLABLE y ahi esta la diferencia entre los dos
--   origenes: NULL significa que se guardo el informe COMPLETO del estudiante
--   -- todas sus asignaturas --, y con valor significa que se guardo esa sola
--   desde la planilla. Es mas honesto que inventar una asignatura ficticia
--   para el caso completo.
--
--
-- (4) QUE SE GUARDA DE CADA ESTUDIANTE
--   El PROMEDIO del periodo tal como quedo despues de guardar, y cuantas
--   asignaturas se le escribieron. El promedio se copia y no se recalcula al
--   consultar: el historial dice que paso ESE dia, y si manana alguien vuelve
--   a consolidar, aquella entrada debe seguir mostrando lo que mostro
--   entonces. Es la diferencia entre un historial y un listado.
--
--
-- (5) NO SE GUARDA SI SUBIO O BAJO
--   El mock mostraba una flecha por tarjeta. No se implementa: un guardado
--   abarca varios estudiantes y a unos les puede subir la nota y a otros
--   bajarle, asi que una sola flecha para el conjunto seria una afirmacion
--   que los datos no sostienen.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + CREATE OR REPLACE.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Cabecera.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS academico_test.TINFORME_GUARDADO (
    PK_TINFORME_GUARDADO    BIGINT GENERATED BY DEFAULT AS IDENTITY,

    FK_TGRUPO               BIGINT      NOT NULL,
    -- NULL = se guardo el informe COMPLETO del estudiante (todas sus
    -- asignaturas). Con valor = se guardo esa sola, desde la planilla.
    FK_TASIGNATURA          BIGINT,
    FK_TPERIODO_EVALUACION  BIGINT      NOT NULL,
    -- Quien lo hizo. Es TUSUARIO y no TFUNCIONARIO porque es quien opero el
    -- sistema, no quien dicta la asignatura.
    FK_TUSUARIO             BIGINT      NOT NULL,

    ORIGEN                  VARCHAR(20) NOT NULL,
    ESTUDIANTES             NUMERIC     NOT NULL,

    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY             VARCHAR(50),
    MODIFIED_AT             TIMESTAMP,
    ACTIVE                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TINFORME_GUARDADO PRIMARY KEY (PK_TINFORME_GUARDADO),
    CONSTRAINT FK_TINFORME_GUARDADO_1 FOREIGN KEY (FK_TGRUPO)
        REFERENCES academico_test.TGRUPO (PK_TGRUPO),
    CONSTRAINT FK_TINFORME_GUARDADO_2 FOREIGN KEY (FK_TASIGNATURA)
        REFERENCES academico_test.TASIGNATURA (PK_TASIGNATURA),
    CONSTRAINT FK_TINFORME_GUARDADO_3 FOREIGN KEY (FK_TPERIODO_EVALUACION)
        REFERENCES academico_test.TPERIODO_EVALUACION (PK_TPERIODO_EVALUACION),
    CONSTRAINT FK_TINFORME_GUARDADO_4 FOREIGN KEY (FK_TUSUARIO)
        REFERENCES academico_test.TUSUARIO (PK_TUSUARIO)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_1
    ON academico_test.TINFORME_GUARDADO (FK_TGRUPO);
CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_2
    ON academico_test.TINFORME_GUARDADO (FK_TPERIODO_EVALUACION);
CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_3
    ON academico_test.TINFORME_GUARDADO (FK_TUSUARIO);
-- El historial se lee SIEMPRE por fecha descendente y agrupado por dia, asi
-- que este es el indice que realmente se usa.
CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_FECHA
    ON academico_test.TINFORME_GUARDADO (CREATED_AT DESC);


-- ---------------------------------------------------------------------------
-- 2. Detalle.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS academico_test.TINFORME_GUARDADO_ESTUDIANTE (
    PK_TINFORME_GUARDADO_ESTUDIANTE BIGINT GENERATED BY DEFAULT AS IDENTITY,

    FK_TINFORME_GUARDADO    BIGINT      NOT NULL,
    FK_TMATRICULA           BIGINT      NOT NULL,
    -- Copiados, no recalculados al consultar: ver el punto (4) de la cabecera.
    PROMEDIO                NUMERIC,
    ASIGNATURAS_AFECTADAS   NUMERIC,

    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE                  BOOLEAN     NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_TINFORME_GUARDADO_ESTUDIANTE
        PRIMARY KEY (PK_TINFORME_GUARDADO_ESTUDIANTE),
    CONSTRAINT FK_TINFORME_GUARDADO_ESTUDIANTE_1
        FOREIGN KEY (FK_TINFORME_GUARDADO)
        REFERENCES academico_test.TINFORME_GUARDADO (PK_TINFORME_GUARDADO),
    CONSTRAINT FK_TINFORME_GUARDADO_ESTUDIANTE_2
        FOREIGN KEY (FK_TMATRICULA)
        REFERENCES academico_test.TMATRICULA (PK_TMATRICULA)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_ESTUDIANTE_1
    ON academico_test.TINFORME_GUARDADO_ESTUDIANTE (FK_TINFORME_GUARDADO);
CREATE INDEX IF NOT EXISTS IDX_TINFORME_GUARDADO_ESTUDIANTE_2
    ON academico_test.TINFORME_GUARDADO_ESTUDIANTE (FK_TMATRICULA);

COMMENT ON TABLE academico_test.TINFORME_GUARDADO
    IS 'Cabecera del historial de guardados del modulo de informes: un registro por operacion de guardado que efectivamente escribio algo. EL GRANO DEL CONTEO ES EL ESTUDIANTE, no la nota: la pantalla mockeada contaba calificaciones (una por asignatura escrita) y se descarto porque no aporta nada a lo que el historial responde -- quien guardo que y cuando -- y produce numeros inutilizables: un curso de 30 con 12 asignaturas daria "360 cambios". Un estudiante guardado = un cambio. FK_TASIGNATURA es NULLABLE y ahi esta la diferencia entre los dos origenes: NULL significa que se guardo el informe COMPLETO del estudiante (todas sus asignaturas, desde /informes/guardar) y con valor que se guardo esa sola desde la planilla; es mas honesto que inventar una asignatura ficticia para el caso completo. FK_TUSUARIO es quien opero el sistema, no quien dicta la asignatura, por eso apunta a TUSUARIO y no a TFUNCIONARIO. Se separa del detalle porque la tarjeta del historial solo necesita la cabecera y el detalle se abre al desplegar; con una sola tabla, listar obligaria a traer todos los estudiantes de todos los guardados solo para contarlos. Solo se crea si algun estudiante cambio de verdad: los sin_cambio y sin_proyeccion no cuentan, para que volver a pulsar guardar no deje entradas vacias en un historial que se agrupa por dia y solo muestra los dias con movimiento.';

COMMENT ON TABLE academico_test.TINFORME_GUARDADO_ESTUDIANTE
    IS 'Detalle del historial: a que estudiantes alcanzo un guardado, con el PROMEDIO del periodo tal como quedo despues de esa operacion y cuantas asignaturas se le escribieron. El promedio se COPIA y no se recalcula al consultar: el historial dice que paso ESE dia, y si manana alguien vuelve a consolidar, aquella entrada debe seguir mostrando lo que mostro entonces -- esa es la diferencia entre un historial y un listado. Solo entran los estudiantes a los que se les escribio alguna nota (resultado guardada o actualizada).';


-- ---------------------------------------------------------------------------
-- 3. El registrador. Punto UNICO de escritura del historial.
--
--    Recibe los estudiantes como JSONB -- [{"matricula":1,"promedio":77.71,
--    "asignaturas":2}, ...] -- porque los dos guardados los acumulan dentro
--    de sus bucles y pasarlos en una sola llamada evita abrir la cabecera
--    antes de saber si hubo algo que registrar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_informe_historial_registrar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tgrupo              BIGINT,
    p_fk_tasignatura         BIGINT,
    p_fk_tperiodo_evaluacion BIGINT,
    p_origen                 VARCHAR,
    p_estudiantes            JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $function$
DECLARE
    v_pk BIGINT;
BEGIN
    -- Sin estudiantes no hay nada que registrar. Se devuelve NULL en vez de
    -- crear una cabecera en cero: ver el punto (2) de la cabecera.
    IF p_estudiantes IS NULL OR JSONB_ARRAY_LENGTH(p_estudiantes) = 0 THEN
        RETURN NULL;
    END IF;

    INSERT INTO academico_test.TINFORME_GUARDADO (
        FK_TGRUPO, FK_TASIGNATURA, FK_TPERIODO_EVALUACION, FK_TUSUARIO,
        ORIGEN, ESTUDIANTES, CREATED_BY, CREATED_AT, ACTIVE
    ) VALUES (
        p_fk_tgrupo, p_fk_tasignatura, p_fk_tperiodo_evaluacion,
        p_pk_usuario_solicitante, p_origen,
        JSONB_ARRAY_LENGTH(p_estudiantes),
        p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
    )
    RETURNING PK_TINFORME_GUARDADO INTO v_pk;

    INSERT INTO academico_test.TINFORME_GUARDADO_ESTUDIANTE (
        FK_TINFORME_GUARDADO, FK_TMATRICULA, PROMEDIO, ASIGNATURAS_AFECTADAS,
        CREATED_BY, CREATED_AT, ACTIVE
    )
    SELECT v_pk,
           (e ->> 'matricula')::BIGINT,
           NULLIF(e ->> 'promedio', '')::NUMERIC,
           NULLIF(e ->> 'asignaturas', '')::NUMERIC,
           p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
      FROM JSONB_ARRAY_ELEMENTS(p_estudiantes) e;

    RETURN v_pk;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_informe_historial_registrar(BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR, JSONB)
    IS 'Punto UNICO de escritura del historial de guardados: crea la cabecera en TINFORME_GUARDADO y una fila por estudiante en TINFORME_GUARDADO_ESTUDIANTE. Lo llaman los dos guardados -- el del informe completo y el de una asignatura desde la planilla -- para que la forma del historial no dependa de por donde se guardo. Recibe los estudiantes como JSONB ([{"matricula":1,"promedio":77.71,"asignaturas":2}]) porque ambos los acumulan dentro de su bucle, y recibirlos de una vez evita abrir la cabecera antes de saber si hubo algo que registrar. Con arreglo vacio o NULL devuelve NULL sin escribir nada: una cabecera en cero ensuciaria un historial que se agrupa por dia y solo muestra los dias con movimiento. p_fk_tasignatura NULL indica guardado del informe completo.';


-- ---------------------------------------------------------------------------
-- 4. Guardado del informe completo, ahora registrando.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS academico_test.fn_informe_periodo_guardar(BIGINT, BIGINT, BIGINT, BIGINT[]);

CREATE OR REPLACE FUNCTION academico_test.fn_informe_periodo_guardar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tgrupo              BIGINT,
    p_fk_tperiodo_evaluacion BIGINT,
    p_fk_tmatriculas         BIGINT[] DEFAULT NULL
)
RETURNS TABLE(
    fk_tmatricula   BIGINT,
    estudiante      VARCHAR,
    guardadas       BIGINT,
    actualizadas    BIGINT,
    sin_proyeccion  BIGINT,
    sin_cambio      BIGINT,
    promedio        NUMERIC,
    aprobadas       BIGINT,
    reprobadas      BIGINT,
    detalle         JSONB
)
LANGUAGE plpgsql
AS $function$
#variable_conflict use_column
DECLARE
    v_fk_sede    BIGINT;
    v_fk_jornada BIGINT;
    v_fk_ee      BIGINT;
    v_fk_peraca  BIGINT;
    v_pe_peraca  BIGINT;
    r_mat        RECORD;
    r_asig       RECORD;
    v_prev       NUMERIC;
    v_existe     BOOLEAN;
    v_g          BIGINT;
    v_a          BIGINT;
    v_s          BIGINT;
    v_n          BIGINT;
    v_det        JSONB;
    v_m          RECORD;
    v_hist       JSONB := '[]'::JSONB;
BEGIN
    SELECT s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO,
           gd.FK_TPERIODO_ACADEMICO
      INTO v_fk_sede, v_fk_jornada, v_fk_ee, v_fk_peraca
      FROM academico_test.TGRUPO gr
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE gr.PK_TGRUPO = p_fk_tgrupo
       AND gr.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el grupo solicitado'
            USING ERRCODE = 'P0002';
    END IF;

    SELECT pe.FK_TPERIODO_ACADEMICO
      INTO v_pe_peraca
      FROM academico_test.TPERIODO_EVALUACION pe
     WHERE pe.PK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
       AND pe.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el periodo de evaluacion solicitado'
            USING ERRCODE = 'P0002';
    END IF;

    IF v_pe_peraca IS DISTINCT FROM v_fk_peraca THEN
        RAISE EXCEPTION 'El periodo de evaluacion no pertenece al periodo academico del grupo'
            USING ERRCODE = '22023';
    END IF;

    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'EDITAR',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    FOR r_mat IN
        SELECT m.PK_TMATRICULA AS pk,
               NULLIF(TRIM(CONCAT_WS(' ', u.PRIMER_NOMBRE, u.PRIMER_APELLIDO)), '')::VARCHAR AS nombre
          FROM academico_test.TMATRICULA m
          LEFT JOIN academico_test.TESTUDIANTE es ON es.PK_TESTUDIANTE = m.FK_TESTUDIANTE
          LEFT JOIN academico_test.TUSUARIO u     ON u.PK_TUSUARIO     = es.FK_TUSUARIO
         WHERE m.FK_TGRUPO = p_fk_tgrupo
           AND m.ACTIVE = TRUE
           AND (p_fk_tmatriculas IS NULL
                OR CARDINALITY(p_fk_tmatriculas) = 0
                OR m.PK_TMATRICULA = ANY (p_fk_tmatriculas))
         ORDER BY 2, 1
    LOOP
        v_g := 0; v_a := 0; v_s := 0; v_n := 0; v_det := '[]'::JSONB;

        FOR r_asig IN
            SELECT d.fk_tasignatura, d.asignatura_nombre, d.nota_proyectada
              FROM academico_test.fn_informe_estudiante_asignaturas(
                       p_pk_usuario_solicitante, r_mat.pk,
                       ARRAY[p_fk_tperiodo_evaluacion]::BIGINT[]) d
        LOOP
            IF r_asig.nota_proyectada IS NULL THEN
                v_s := v_s + 1;
                v_det := v_det || JSONB_BUILD_OBJECT(
                    'asignatura', r_asig.asignatura_nombre,
                    'resultado',  'sin_proyeccion');
                CONTINUE;
            END IF;

            SELECT sn.DEFINITIVA, TRUE
              INTO v_prev, v_existe
              FROM academico_test.TASIGNATURA_NOTA sn
             WHERE sn.FK_TMATRICULA          = r_mat.pk
               AND sn.FK_TASIGNATURA         = r_asig.fk_tasignatura
               AND sn.FK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
               AND sn.ACTIVE = TRUE;

            IF COALESCE(v_existe, FALSE) AND v_prev = r_asig.nota_proyectada THEN
                v_n := v_n + 1;
                v_det := v_det || JSONB_BUILD_OBJECT(
                    'asignatura', r_asig.asignatura_nombre,
                    'resultado',  'sin_cambio',
                    'nota',       r_asig.nota_proyectada);
                v_existe := NULL;
                CONTINUE;
            END IF;

            INSERT INTO academico_test.TASIGNATURA_NOTA (
                FK_TMATRICULA, FK_TASIGNATURA, FK_TPERIODO_EVALUACION,
                CALIFICACION, DEFINITIVA, CREATED_BY, CREATED_AT, ACTIVE
            ) VALUES (
                r_mat.pk, r_asig.fk_tasignatura, p_fk_tperiodo_evaluacion,
                r_asig.nota_proyectada, r_asig.nota_proyectada,
                p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
            )
            ON CONFLICT (FK_TMATRICULA, FK_TPERIODO_EVALUACION, FK_TASIGNATURA)
                WHERE ACTIVE
            DO UPDATE SET CALIFICACION = EXCLUDED.CALIFICACION,
                          DEFINITIVA   = EXCLUDED.DEFINITIVA,
                          MODIFIED_BY  = p_pk_usuario_solicitante::VARCHAR,
                          MODIFIED_AT  = CURRENT_TIMESTAMP;

            IF COALESCE(v_existe, FALSE) THEN
                v_a := v_a + 1;
                v_det := v_det || JSONB_BUILD_OBJECT(
                    'asignatura', r_asig.asignatura_nombre,
                    'resultado',  'actualizada',
                    'nota',       r_asig.nota_proyectada,
                    'anterior',   v_prev);
            ELSE
                v_g := v_g + 1;
                v_det := v_det || JSONB_BUILD_OBJECT(
                    'asignatura', r_asig.asignatura_nombre,
                    'resultado',  'guardada',
                    'nota',       r_asig.nota_proyectada);
            END IF;

            v_existe := NULL;
        END LOOP;

        PERFORM academico_test.fn_informe_metricas_recalcular(
            p_pk_usuario_solicitante, r_mat.pk, p_fk_tperiodo_evaluacion);

        SELECT ipm.PROMEDIO, ipm.APROBADAS, ipm.REPROBADAS
          INTO v_m
          FROM academico_test.TINFORME_PERIODO_MATRICULA ipm
         WHERE ipm.FK_TMATRICULA          = r_mat.pk
           AND ipm.FK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
           AND ipm.ACTIVE = TRUE;

        -- Al historial SOLO si se escribio algo. Ver el punto (2).
        IF v_g + v_a > 0 THEN
            v_hist := v_hist || JSONB_BUILD_OBJECT(
                'matricula',   r_mat.pk,
                'promedio',    v_m.PROMEDIO,
                'asignaturas', v_g + v_a);
        END IF;

        fk_tmatricula  := r_mat.pk;
        estudiante     := r_mat.nombre;
        guardadas      := v_g;
        actualizadas   := v_a;
        sin_proyeccion := v_s;
        sin_cambio     := v_n;
        promedio       := v_m.PROMEDIO;
        aprobadas      := COALESCE(v_m.APROBADAS, 0)::BIGINT;
        reprobadas     := COALESCE(v_m.REPROBADAS, 0)::BIGINT;
        detalle        := v_det;
        RETURN NEXT;
    END LOOP;

    PERFORM academico_test.fn_informe_historial_registrar(
        p_pk_usuario_solicitante, p_fk_tgrupo, NULL,
        p_fk_tperiodo_evaluacion, 'INFORME', v_hist);
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_informe_periodo_guardar(BIGINT, BIGINT, BIGINT, BIGINT[])
    IS 'Consolida un periodo COMPLETO: congela la nota proyectada de cada asignatura en TASIGNATURA_NOTA para el grupo (o solo las matriculas indicadas; NULL o vacio = todas), deja las metricas al dia via fn_informe_metricas_recalcular y registra el guardado en el historial via fn_informe_historial_registrar con FK_TASIGNATURA NULL, que es lo que marca "informe completo". Al historial solo entran los estudiantes a los que se les ESCRIBIO alguna nota: los sin_cambio y sin_proyeccion no cuentan, y si ninguno cambio no se crea cabecera, para que volver a pulsar guardar no deje entradas vacias. Convive sin pisarse con fn_informe_planilla_guardar, que congela una sola asignatura: TASIGNATURA_NOTA es por (matricula, periodo, asignatura) y ambas terminan en el mismo recalculo y el mismo registrador, asi que son idempotentes y su efecto final no depende del orden. Lo ya guardado con el mismo valor se reporta sin_cambio y no se toca, para no borrar el MODIFIED_AT que dice cuando se consolido. DEFINITIVA se guarda en PORCENTAJE, no homologada, porque la escala depende de TCRITERIO_EVALUACION por (asignatura, grado) y puede cambiar. Preescolar no usa este endpoint: alli todo sale sin_proyeccion porque las observaciones se guardan con CALIFICABLE=N y no promedian. Gate: INFORMES/EDITAR.';


-- ---------------------------------------------------------------------------
-- 5. Guardado de una asignatura desde la planilla, ahora registrando.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS academico_test.fn_informe_planilla_guardar(BIGINT, BIGINT, BIGINT, BIGINT, BIGINT[]);

CREATE OR REPLACE FUNCTION academico_test.fn_informe_planilla_guardar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tgrupo              BIGINT,
    p_fk_tasignatura         BIGINT,
    p_fk_tperiodo_evaluacion BIGINT,
    p_fk_tmatriculas         BIGINT[] DEFAULT NULL
)
RETURNS TABLE(
    fk_tmatricula      BIGINT,
    estudiante         VARCHAR,
    resultado          VARCHAR,
    nota_anterior      NUMERIC,
    nota_guardada      NUMERIC,
    promedio_periodo   NUMERIC,
    aprobadas          BIGINT,
    reprobadas         BIGINT
)
LANGUAGE plpgsql
AS $function$
#variable_conflict use_column
DECLARE
    v_fk_grado   BIGINT;
    v_fk_peraca  BIGINT;
    v_fk_sede    BIGINT;
    v_fk_jornada BIGINT;
    v_fk_ee      BIGINT;
    v_pe_peraca  BIGINT;
    r_mat        RECORD;
    v_proy       NUMERIC;
    v_prev       NUMERIC;
    v_existe     BOOLEAN;
    v_res        VARCHAR;
    v_m          RECORD;
    v_hist       JSONB := '[]'::JSONB;
BEGIN
    SELECT gd.PK_TGRADO, gd.FK_TPERIODO_ACADEMICO,
           s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO
      INTO v_fk_grado, v_fk_peraca, v_fk_sede, v_fk_jornada, v_fk_ee
      FROM academico_test.TGRUPO gr
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE gr.PK_TGRUPO = p_fk_tgrupo
       AND gr.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el grupo solicitado'
            USING ERRCODE = 'P0002';
    END IF;

    PERFORM academico_test.fn_planilla_grupo_asignatura_assert(
        p_fk_tgrupo, p_fk_tasignatura, v_fk_grado);

    SELECT pe.FK_TPERIODO_ACADEMICO
      INTO v_pe_peraca
      FROM academico_test.TPERIODO_EVALUACION pe
     WHERE pe.PK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
       AND pe.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el periodo de evaluacion solicitado'
            USING ERRCODE = 'P0002';
    END IF;

    IF v_pe_peraca IS DISTINCT FROM v_fk_peraca THEN
        RAISE EXCEPTION 'El periodo de evaluacion no pertenece al periodo academico del grupo'
            USING ERRCODE = '22023';
    END IF;

    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'EDITAR',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    FOR r_mat IN
        SELECT m.PK_TMATRICULA AS pk,
               NULLIF(TRIM(CONCAT_WS(' ', u.PRIMER_NOMBRE, u.PRIMER_APELLIDO)), '')::VARCHAR AS nombre
          FROM academico_test.TMATRICULA m
          LEFT JOIN academico_test.TESTUDIANTE es ON es.PK_TESTUDIANTE = m.FK_TESTUDIANTE
          LEFT JOIN academico_test.TUSUARIO u     ON u.PK_TUSUARIO     = es.FK_TUSUARIO
         WHERE m.FK_TGRUPO = p_fk_tgrupo
           AND m.ACTIVE = TRUE
           AND (p_fk_tmatriculas IS NULL
                OR CARDINALITY(p_fk_tmatriculas) = 0
                OR m.PK_TMATRICULA = ANY (p_fk_tmatriculas))
         ORDER BY 2, 1
    LOOP
        v_proy := academico_test.fn_asignatura_definitiva_proyectada_periodo(
                      r_mat.pk, p_fk_tasignatura, p_fk_tperiodo_evaluacion);

        SELECT sn.DEFINITIVA, TRUE
          INTO v_prev, v_existe
          FROM academico_test.TASIGNATURA_NOTA sn
         WHERE sn.FK_TMATRICULA          = r_mat.pk
           AND sn.FK_TASIGNATURA         = p_fk_tasignatura
           AND sn.FK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
           AND sn.ACTIVE = TRUE;

        IF v_proy IS NULL THEN
            v_res := 'sin_proyeccion';
        ELSIF COALESCE(v_existe, FALSE) AND v_prev = v_proy THEN
            v_res := 'sin_cambio';
        ELSE
            INSERT INTO academico_test.TASIGNATURA_NOTA (
                FK_TMATRICULA, FK_TASIGNATURA, FK_TPERIODO_EVALUACION,
                CALIFICACION, DEFINITIVA, CREATED_BY, CREATED_AT, ACTIVE
            ) VALUES (
                r_mat.pk, p_fk_tasignatura, p_fk_tperiodo_evaluacion,
                v_proy, v_proy,
                p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
            )
            ON CONFLICT (FK_TMATRICULA, FK_TPERIODO_EVALUACION, FK_TASIGNATURA)
                WHERE ACTIVE
            DO UPDATE SET CALIFICACION = EXCLUDED.CALIFICACION,
                          DEFINITIVA   = EXCLUDED.DEFINITIVA,
                          MODIFIED_BY  = p_pk_usuario_solicitante::VARCHAR,
                          MODIFIED_AT  = CURRENT_TIMESTAMP;

            v_res := CASE WHEN COALESCE(v_existe, FALSE) THEN 'actualizada'
                          ELSE 'guardada' END;
        END IF;

        PERFORM academico_test.fn_informe_metricas_recalcular(
            p_pk_usuario_solicitante, r_mat.pk, p_fk_tperiodo_evaluacion);

        SELECT ipm.PROMEDIO, ipm.APROBADAS, ipm.REPROBADAS
          INTO v_m
          FROM academico_test.TINFORME_PERIODO_MATRICULA ipm
         WHERE ipm.FK_TMATRICULA          = r_mat.pk
           AND ipm.FK_TPERIODO_EVALUACION = p_fk_tperiodo_evaluacion
           AND ipm.ACTIVE = TRUE;

        -- Al historial SOLO si se escribio. Una asignatura por estudiante,
        -- de ahi el 1.
        IF v_res IN ('guardada', 'actualizada') THEN
            v_hist := v_hist || JSONB_BUILD_OBJECT(
                'matricula',   r_mat.pk,
                'promedio',    v_m.PROMEDIO,
                'asignaturas', 1);
        END IF;

        fk_tmatricula    := r_mat.pk;
        estudiante       := r_mat.nombre;
        resultado        := v_res;
        nota_anterior    := v_prev;
        nota_guardada    := CASE WHEN v_res IN ('guardada', 'actualizada', 'sin_cambio')
                                 THEN v_proy END;
        promedio_periodo := v_m.PROMEDIO;
        aprobadas        := COALESCE(v_m.APROBADAS, 0)::BIGINT;
        reprobadas       := COALESCE(v_m.REPROBADAS, 0)::BIGINT;
        RETURN NEXT;

        v_prev := NULL; v_existe := NULL;
    END LOOP;

    PERFORM academico_test.fn_informe_historial_registrar(
        p_pk_usuario_solicitante, p_fk_tgrupo, p_fk_tasignatura,
        p_fk_tperiodo_evaluacion, 'PLANILLA', v_hist);
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_informe_planilla_guardar(BIGINT, BIGINT, BIGINT, BIGINT, BIGINT[])
    IS 'Congela la definitiva de UNA asignatura desde la planilla de informes, para el grupo o solo las matriculas indicadas (NULL o vacio = todas), recalcula las metricas del periodo y registra el guardado en el historial con FK_TASIGNATURA puesta, que es lo que lo distingue del guardado del informe completo. Al historial solo entran los estudiantes a los que se les escribio (guardada o actualizada); sin_cambio y sin_proyeccion no cuentan, y si ninguno cambio no se crea cabecera. Es el hermano acotado de fn_informe_periodo_guardar y NO SE PISAN: TASIGNATURA_NOTA es por (matricula, periodo, asignatura), y ambas terminan llamando al mismo recalculo de metricas y al mismo registrador, de modo que el resultado no depende del orden y las dos son idempotentes. El recalculo corre SIEMPRE, incluso en sin_cambio, porque otra asignatura pudo haberse movido desde el ultimo y esa fila las agrega a todas. En sin_proyeccion lo ya guardado NO se borra: quitar un consolidado por una ausencia no es decision de un boton de guardar. Devuelve ademas el promedio y los conteos del periodo ya recalculados, para que la pantalla refresque sin volver a consultar. Gate: INFORMES/EDITAR sobre el grupo, mas el validador puro fn_planilla_grupo_asignatura_assert (V239).';
