-- ===========================================================================
-- V435 - Observacion final del ano guardable: tabla TESTUDIANTE_ANIO_OBSERVACION
-- y los endpoints de generar, guardar y eliminar.
--
--   Las funciones vigentes estan en V439 (listado y reporte del grupo) y V490
--   (observacion final); sus COMMENT, en V516.
-- ===========================================================================


CREATE TABLE IF NOT EXISTS academico_test.TESTUDIANTE_ANIO_OBSERVACION (
    PK_TESTUDIANTE_ANIO_OBSERVACION BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_TESTUDIANTE_ANIO_OBSERVACION PRIMARY KEY,
    FK_TMATRICULA                   BIGINT    NOT NULL,
    FK_TLV_ESTADO_OBSERVACION       BIGINT    NOT NULL,
    OBSERVACION                     TEXT      NOT NULL,
    OBSERVACION_IA                  TEXT      NOT NULL,
    
    
    
    PERIODOS_ORIGEN                 NUMERIC,
    CREATED_BY                      VARCHAR(100) NOT NULL,
    CREATED_AT                      TIMESTAMP    NOT NULL,
    MODIFIED_BY                     VARCHAR(100),
    MODIFIED_AT                     TIMESTAMP,
    ACTIVE                          BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT FK_TESTUDIANTE_ANIO_OBSERVACION_1
        FOREIGN KEY (FK_TMATRICULA)
        REFERENCES academico_test.TMATRICULA (PK_TMATRICULA),
    CONSTRAINT FK_TESTUDIANTE_ANIO_OBSERVACION_2
        FOREIGN KEY (FK_TLV_ESTADO_OBSERVACION)
        REFERENCES academico_test.TLISTA_VALOR (PK_LISTA_VALOR)
);

CREATE UNIQUE INDEX IF NOT EXISTS U_TESTUDIANTE_ANIO_OBSERVACION_1
    ON academico_test.TESTUDIANTE_ANIO_OBSERVACION (FK_TMATRICULA);

CREATE INDEX IF NOT EXISTS IDX_TESTUDIANTE_ANIO_OBSERVACION_1
    ON academico_test.TESTUDIANTE_ANIO_OBSERVACION (FK_TLV_ESTADO_OBSERVACION);

COMMENT ON TABLE academico_test.TESTUDIANTE_ANIO_OBSERVACION
    IS 'El comentario del AÑO de un estudiante: el equivalente de TESTUDIANTE_PERIODO_OBSERVACION para la fila Final. Mismo ciclo -- se genera, se revisa, se guarda -- y los mismos dos estados, APROBADA y MODIFICADA, sin PENDIENTE, porque generar no persiste y por lo tanto toda fila de aca es un texto que un humano ya acepto. LA LLAVE ES SOLO LA MATRICULA, sin el periodo academico: una matricula pertenece a un grupo, que pertenece a un grado, que pertenece a UN periodo academico, asi que el año ya esta determinado y agregarlo solo permitiria escribir la combinacion incoherente. ES UNA TABLA APARTE Y NO LA MISMA con el periodo en NULL por una razon concreta: OBSERVACIONES_ORIGEN contaria dos cosas distintas segun la fila -- en un periodo, las observaciones por actividad, porque eso es lo que deja viejo a ese texto; en el año, los PERIODOS CONSOLIDADOS, porque eso es lo que deja viejo a este --, con dos formulas y un solo nombre. Aca la columna se llama PERIODOS_ORIGEN y cuenta periodos. OBSERVACION_IA es el borrador original tal como se genero, se escribe al guardar y no se toca mas; OBSERVACION es lo que se muestra. Comparandolos se sabe si el docente lo reescribio, sin historial. V435.';

COMMENT ON COLUMN academico_test.TESTUDIANTE_ANIO_OBSERVACION.PERIODOS_ORIGEN
    IS 'Cuantos resumenes de periodo consolidados tenia el estudiante cuando se guardo este texto. Si hoy hay mas, el texto del año quedo viejo y la pantalla lo marca. NULL significa "no se", no "habia cero": quien lo lea debe tratarlo como desconocido y no marcar nada -- ese fue exactamente el defecto que el V433 tuvo que arreglar en la tabla de periodos.';

UPDATE public.query q
   SET detail = 'GENERA el borrador del comentario del AÑO de un estudiante -- la fila Final --, sin escribir nada. Hoy encadena los resumenes de periodo YA CONSOLIDADOS, en orden y prefijados con el nombre del periodo; cuando exista el modelo cambia lo que devuelve y nada mas, porque el contrato ya es el definitivo. NO es /informes/observacion/generar, que concatena las observaciones por ACTIVIDAD dentro de UN periodo: esas son la materia prima del resumen de periodo. Devuelve observacion_ia y periodos_origen, que se reenvian tal cual a /informes/observacion/final/guardar para que el backend deduzca si el docente lo aprobo o lo modifico. Devuelve siempre una fila; con null y cero si el estudiante no tiene ningun resumen de periodo guardado. Gate INFORMES/VER, porque no persiste.'
  FROM public.microservice m
 WHERE q.microservice_id = m.id_microservice
   AND m.serviceid       = 'eval-col'
   AND q.path_template   = '/informes/observacion/final'
   AND q.http_method     = 'POST';

INSERT INTO public.query
    (uuid, query, type, public_end, captcha, microservice_id, path_template,
     execution_mode, http_method, param_types, out_param_names, detail, action, style)
SELECT
    'eval-col-informes-observacion-final-guardar-001',
    'SELECT academico_test.fn_estudiante_anio_observacion_guardar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:BODY.FK_TMATRICULA AS BIGINT),
    CAST(:BODY.OBSERVACION AS TEXT),
    CAST(:BODY.OBSERVACION_IA AS TEXT),
    CAST(:BODY.PERIODOS_ORIGEN AS NUMERIC)
) AS pk_testudiante_anio_observacion;',
    'postgres', false, false,
    m.id_microservice,
    '/informes/observacion/final/guardar', 'SELECT', 'POST',
    '{"BODY.FK_TMATRICULA": "BIGINT", "BODY.OBSERVACION": "TEXT", "BODY.OBSERVACION_IA": "TEXT", "BODY.PERIODOS_ORIGEN": "NUMERIC"}'::jsonb,
    NULL,
    'Guarda el comentario del AÑO de un estudiante -- la fila Final --, en TESTUDIANTE_ANIO_OBSERVACION. Reemplaza: la llave unica es la matricula y no se versiona. El ESTADO no se pide: sale de comparar OBSERVACION contra OBSERVACION_IA -- iguales APROBADA, distintos MODIFICADA --, asi que reenvia el borrador que devolvio /informes/observacion/final tal como llego. Si no lo reenvias pero ya habia fila, se conserva el borrador guardado en vez de asumir que el texto nuevo es el de la IA. PERIODOS_ORIGEN es cuantos resumenes de periodo consolidados habia al generar; si no lo mandas se cuentan al guardar, para que la marca de desactualizado no quede mintiendo. Ojo: lo que deja viejo a ESTE texto es que se consolide un PERIODO nuevo, no que el docente escriba una observacion mas. Gate INFORMES/EDITAR. 400 (22023) con el texto vacio -- para quitarlo esta /informes/observacion/final/eliminar --, 404 si la matricula no existe.',
    'informes-observacion-final-guardar', 'DEFAULT'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (microservice_id, path_template, http_method)
    WHERE path_template IS NOT NULL DO NOTHING;

INSERT INTO public.query
    (uuid, query, type, public_end, captcha, microservice_id, path_template,
     execution_mode, http_method, param_types, out_param_names, detail, action, style)
SELECT
    'eval-col-informes-observacion-final-eliminar-001',
    'SELECT academico_test.fn_estudiante_anio_observacion_eliminar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:BODY.FK_TMATRICULA AS BIGINT)
) AS pk_testudiante_anio_observacion;',
    'postgres', false, false,
    m.id_microservice,
    '/informes/observacion/final/eliminar', 'SELECT', 'POST',
    '{"BODY.FK_TMATRICULA": "BIGINT"}'::jsonb,
    NULL,
    'Quita el comentario del AÑO de un estudiante. Devuelve el PK eliminado. EL BORRADO ES FISICO, no baja logica: la llave unica de TESTUDIANTE_ANIO_OBSERVACION es total sobre la matricula, de modo que una fila inactiva seguiria ocupando el lugar e impediria guardar una nueva; y no hay nada que conservar, porque el texto se vuelve a generar desde los resumenes de periodo, que son el dato original. Despues de eliminar, la fila Final de /informes/grupo vuelve a traer observacion en null. Es POST y no DELETE por coherencia con el resto del modulo. Gate INFORMES/ELIMINAR -- mas exigente que el EDITAR de guardar, porque rehacer un texto es corregir y borrarlo es deshacer. 404 si no habia nada guardado.',
    'informes-observacion-final-eliminar', 'DEFAULT'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (microservice_id, path_template, http_method)
    WHERE path_template IS NOT NULL DO NOTHING;

INSERT INTO public.role_query (query_id, role_id)
SELECT nuevo.id_query, rq.role_id
  FROM public.query nuevo
  JOIN public.query modelo ON modelo.microservice_id = nuevo.microservice_id
                          AND modelo.http_method     = 'POST'
                          AND modelo.path_template   = CASE nuevo.uuid
                              WHEN 'eval-col-informes-observacion-final-guardar-001'
                                  THEN '/informes/observacion/guardar'
                              WHEN 'eval-col-informes-observacion-final-eliminar-001'
                                  THEN '/informes/observacion/eliminar'
                          END
  JOIN public.role_query rq ON rq.query_id = modelo.id_query
 WHERE nuevo.uuid IN ('eval-col-informes-observacion-final-guardar-001',
                      'eval-col-informes-observacion-final-eliminar-001')
ON CONFLICT DO NOTHING;
