-- ===========================================================================
-- V435 - La observacion del año se genera, se edita y se guarda.
--
--   TESTUDIANTE_ANIO_OBSERVACION           tabla nueva
--   fn_estudiante_final_observacion        pasa a ser el GENERAR (borrador)
--   fn_estudiante_anio_observacion_guardar nueva
--   fn_estudiante_anio_observacion_eliminar nueva
--   fn_informe_grupo_listar                la fila Final lee lo GUARDADO
--   fn_informe_grupo_reporte               no imprime un Final vacio
--
--   POST /informes/observacion/final           (ya existia: generar)
--   POST /informes/observacion/final/guardar   nuevo
--   POST /informes/observacion/final/eliminar  nuevo
--
--
-- QUE CAMBIA RESPECTO DEL V434
--   Alli la observacion del Final era un DERIVADO: los resumenes ya
--   consolidados encadenados, calculados al mirarlos, sin guardar y sin
--   editar. Eso era correcto mientras el texto fuera una concatenacion.
--
--   Pero la concatenacion es provisional: el dia que exista el modelo, el
--   texto del año lo va a redactar la IA, y entonces alguien tiene que
--   poder leerlo, corregirlo y dejarlo aprobado -- exactamente el ciclo que
--   ya tienen los periodos. Un derivado no admite ese ciclo: no hay donde
--   poner "esto lo reviso un humano".
--
--   Asi que el concatenado pasa a ser el BORRADOR que devuelve generar, y
--   la fila Final arranca vacia como los periodos hasta que alguien guarde.
--   Cuando llegue la IA de verdad cambia lo que devuelve generar y nada mas:
--   el contrato del guardar, el estado y la pantalla quedan igual.
--
--
-- POR QUE UNA TABLA NUEVA Y NO LA MISMA CON EL PERIODO EN NULL
--   Se evaluaron las dos. La de reusar TESTUDIANTE_PERIODO_OBSERVACION
--   funciona: se le quita el NOT NULL a FK_TPERIODO_EVALUACION, NULL pasa a
--   significar "Final", y el indice unico se reemplaza por uno
--   NULLS NOT DISTINCT -- que existe desde PG15 y aca hay 16.4 -- porque si
--   no, cada guardado crearia una fila Final nueva en silencio. Es bastante
--   menos codigo.
--
--   Se eligio la tabla aparte por una razon concreta, no por prolijidad:
--   OBSERVACIONES_ORIGEN pasaria a contar DOS COSAS DISTINTAS segun la fila.
--   En un periodo cuenta las observaciones por actividad, porque lo que deja
--   viejo a ese texto es que el docente escriba una mas. En el año cuenta los
--   PERIODOS CONSOLIDADOS, porque lo que deja viejo al texto del año es que
--   se cierre un periodo nuevo. Misma columna, dos significados y dos
--   formulas: es justo la clase de cosa que despues nadie entiende. Aca la
--   columna se llama PERIODOS_ORIGEN y cuenta periodos.
--
--   De yapa: nada de lo que hoy lee la tabla de periodos se entera de esto,
--   la llave unica queda total y simple, y no queda un centinela NULL que
--   todo el que lea esa tabla de ahora en mas tenga que conocer.
--
--
-- LA LLAVE ES LA MATRICULA, SIN EL AÑO
--   Podria ser (matricula, periodo academico) por simetria con la otra
--   tabla, pero seria redundante: una matricula pertenece a un grupo, que
--   pertenece a un grado, que pertenece a UN periodo academico. El año ya
--   esta determinado. Agregarlo permitiria escribir la combinacion
--   incoherente, que es lo contrario de lo que uno quiere de una llave.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS, CREATE OR REPLACE, ON CONFLICT
-- DO NOTHING en endpoints y roles.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. La tabla.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS academico_test.TESTUDIANTE_ANIO_OBSERVACION (
    PK_TESTUDIANTE_ANIO_OBSERVACION BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_TESTUDIANTE_ANIO_OBSERVACION PRIMARY KEY,
    FK_TMATRICULA                   BIGINT    NOT NULL,
    FK_TLV_ESTADO_OBSERVACION       BIGINT    NOT NULL,
    OBSERVACION                     TEXT      NOT NULL,
    OBSERVACION_IA                  TEXT      NOT NULL,
    -- Cuantos resumenes de periodo consolidados habia cuando se guardo. Es
    -- el equivalente de OBSERVACIONES_ORIGEN pero contando PERIODOS, que es
    -- lo que deja viejo a este texto. Ver la cabecera.
    PERIODOS_ORIGEN                 NUMERIC,
    CREATED_BY                      VARCHAR(100) NOT NULL,
    CREATED_AT                      TIMESTAMP    NOT NULL,
    MODIFIED_BY                     VARCHAR(100),
    MODIFIED_AT                     TIMESTAMP,
    ACTIVE                          BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT FK_TESTUDIANTE_ANIO_OBSERVACION_1
        FOREIGN KEY (FK_TMATRICULA)
        REFERENCES academico_test.TMATRICULA (PK_TMATRICULA),
    CONSTRAINT FK_TESTUDIANTE_ANIO_OBSERVACION_2
        FOREIGN KEY (FK_TLV_ESTADO_OBSERVACION)
        REFERENCES academico_test.TLISTA_VALOR (PK_LISTA_VALOR)
);

-- Total y no parcial sobre ACTIVE, igual que en la tabla de periodos:
-- guardar REEMPLAZA y nunca conviven dos versiones del mismo texto.
CREATE UNIQUE INDEX IF NOT EXISTS U_TESTUDIANTE_ANIO_OBSERVACION_1
    ON academico_test.TESTUDIANTE_ANIO_OBSERVACION (FK_TMATRICULA);

CREATE INDEX IF NOT EXISTS IDX_TESTUDIANTE_ANIO_OBSERVACION_1
    ON academico_test.TESTUDIANTE_ANIO_OBSERVACION (FK_TLV_ESTADO_OBSERVACION);

COMMENT ON TABLE academico_test.TESTUDIANTE_ANIO_OBSERVACION
    IS 'El comentario del AÑO de un estudiante: el equivalente de TESTUDIANTE_PERIODO_OBSERVACION para la fila Final. Mismo ciclo -- se genera, se revisa, se guarda -- y los mismos dos estados, APROBADA y MODIFICADA, sin PENDIENTE, porque generar no persiste y por lo tanto toda fila de aca es un texto que un humano ya acepto. LA LLAVE ES SOLO LA MATRICULA, sin el periodo academico: una matricula pertenece a un grupo, que pertenece a un grado, que pertenece a UN periodo academico, asi que el año ya esta determinado y agregarlo solo permitiria escribir la combinacion incoherente. ES UNA TABLA APARTE Y NO LA MISMA con el periodo en NULL por una razon concreta: OBSERVACIONES_ORIGEN contaria dos cosas distintas segun la fila -- en un periodo, las observaciones por actividad, porque eso es lo que deja viejo a ese texto; en el año, los PERIODOS CONSOLIDADOS, porque eso es lo que deja viejo a este --, con dos formulas y un solo nombre. Aca la columna se llama PERIODOS_ORIGEN y cuenta periodos. OBSERVACION_IA es el borrador original tal como se genero, se escribe al guardar y no se toca mas; OBSERVACION es lo que se muestra. Comparandolos se sabe si el docente lo reescribio, sin historial. V435.';

COMMENT ON COLUMN academico_test.TESTUDIANTE_ANIO_OBSERVACION.PERIODOS_ORIGEN
    IS 'Cuantos resumenes de periodo consolidados tenia el estudiante cuando se guardo este texto. Si hoy hay mas, el texto del año quedo viejo y la pantalla lo marca. NULL significa "no se", no "habia cero": quien lo lea debe tratarlo como desconocido y no marcar nada -- ese fue exactamente el defecto que el V433 tuvo que arreglar en la tabla de periodos.';


-- ---------------------------------------------------------------------------
-- 2. Generar: el concatenado pasa a ser un BORRADOR.
--
--    Cambian los nombres de las columnas de salida para que digan lo que
--    son, en simetria con fn_estudiante_periodo_observacion_generar:
--    observacion_ia (un borrador, no un texto aprobado) y periodos_origen
--    (lo que hay que reenviar al guardar).
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS academico_test.fn_estudiante_final_observacion(BIGINT, BIGINT);

CREATE OR REPLACE FUNCTION academico_test.fn_estudiante_final_observacion(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tmatricula          BIGINT
)
RETURNS TABLE(
    observacion_ia   TEXT,
    periodos_origen  NUMERIC
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_fk_peraca  BIGINT;
    v_fk_sede    BIGINT;
    v_fk_jornada BIGINT;
    v_fk_ee      BIGINT;
BEGIN
    SELECT gd.FK_TPERIODO_ACADEMICO, s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO
      INTO v_fk_peraca, v_fk_sede, v_fk_jornada, v_fk_ee
      FROM academico_test.TMATRICULA m
      JOIN academico_test.TGRUPO gr ON gr.PK_TGRUPO = m.FK_TGRUPO
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE m.PK_TMATRICULA = p_fk_tmatricula
       AND m.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la matricula solicitada'
            USING ERRCODE = 'P0002';
    END IF;

    -- VER y no EDITAR: generar no escribe nada, igual que su gemela de
    -- periodo. Quien guarde necesitara EDITAR.
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'VER',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    RETURN QUERY
    -- -----------------------------------------------------------------
    -- *** AQUI IRA LA IA ***
    --
    -- Por ahora: encadenar los RESUMENES DE PERIODO ya consolidados, en
    -- orden y prefijados con el nombre del periodo. No las observaciones
    -- por actividad -- esas son la materia prima del resumen de PERIODO,
    -- y volver a masticarlas aca daria un texto de tres paginas.
    -- -----------------------------------------------------------------
    SELECT STRING_AGG(FORMAT('%s: %s', pe.NOMBRE, TRIM(ob.OBSERVACION)),
                      ' ' ORDER BY pe.FECHA_INICIO, pe.PK_TPERIODO_EVALUACION),
           COUNT(*)::NUMERIC
      FROM academico_test.TESTUDIANTE_PERIODO_OBSERVACION ob
      JOIN academico_test.TPERIODO_EVALUACION pe
        ON pe.PK_TPERIODO_EVALUACION = ob.FK_TPERIODO_EVALUACION
       AND pe.ACTIVE = TRUE
       AND pe.FK_TPERIODO_ACADEMICO = v_fk_peraca
     WHERE ob.FK_TMATRICULA = p_fk_tmatricula
       AND ob.ACTIVE = TRUE
       AND NULLIF(TRIM(COALESCE(ob.OBSERVACION, '')), '') IS NOT NULL;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_estudiante_final_observacion(BIGINT, BIGINT)
    IS 'GENERA el borrador del comentario del AÑO -- la fila Final --, sin escribir nada. Hoy encadena los resumenes de periodo YA CONSOLIDADOS, en orden y prefijados con el nombre del periodo; cuando exista el modelo, cambia lo que devuelve esta funcion y nada mas, porque el contrato ya es el definitivo. NO concatena las observaciones por ACTIVIDAD: esas son la materia prima del resumen de PERIODO, y volver a masticarlas aca daria un texto de tres paginas. Devuelve siempre una fila; con NULL y cero si el estudiante no tiene ningun resumen de periodo guardado. Lo que devuelve se reenvia tal cual a fn_estudiante_anio_observacion_guardar, que compara para deducir si el docente lo aprobo o lo modifico. Gate INFORMES/VER, porque no persiste. V434, V435.';


-- ---------------------------------------------------------------------------
-- 3. Guardar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_estudiante_anio_observacion_guardar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tmatricula          BIGINT,
    p_observacion            TEXT,
    p_observacion_ia         TEXT    DEFAULT NULL,
    p_periodos_origen        NUMERIC DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $function$
DECLARE
    v_fk_peraca  BIGINT;
    v_fk_sede    BIGINT;
    v_fk_jornada BIGINT;
    v_fk_ee      BIGINT;
    v_texto      TEXT;
    v_ia         TEXT;
    v_ia_previa  TEXT;
    v_origen     NUMERIC;
    v_estado     VARCHAR;
    v_pk_estado  BIGINT;
    v_pk         BIGINT;
BEGIN
    v_texto := NULLIF(TRIM(COALESCE(p_observacion, '')), '');
    IF v_texto IS NULL THEN
        RAISE EXCEPTION 'La observacion no puede quedar vacia'
            USING ERRCODE = '22023',
                  HINT    = 'Para quitar el comentario del año use fn_estudiante_anio_observacion_eliminar';
    END IF;

    SELECT gd.FK_TPERIODO_ACADEMICO, s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO
      INTO v_fk_peraca, v_fk_sede, v_fk_jornada, v_fk_ee
      FROM academico_test.TMATRICULA m
      JOIN academico_test.TGRUPO gr ON gr.PK_TGRUPO = m.FK_TGRUPO
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE m.PK_TMATRICULA = p_fk_tmatricula
       AND m.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la matricula solicitada'
            USING ERRCODE = 'P0002';
    END IF;

    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'EDITAR',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    SELECT ao.OBSERVACION_IA
      INTO v_ia_previa
      FROM academico_test.TESTUDIANTE_ANIO_OBSERVACION ao
     WHERE ao.FK_TMATRICULA = p_fk_tmatricula
       AND ao.ACTIVE = TRUE;

    -- Misma prioridad que en la tabla de periodos desde el V433: lo que
    -- reenvia el caller, luego el borrador ya guardado, y recien al final el
    -- texto mismo. Sin el escalon del medio, editar un texto ya guardado lo
    -- dejaria como APROBADA sin cambios.
    v_ia := COALESCE(
                NULLIF(TRIM(COALESCE(p_observacion_ia, '')), ''),
                NULLIF(TRIM(COALESCE(v_ia_previa,      '')), ''),
                v_texto);

    v_origen := p_periodos_origen;

    IF v_origen IS NULL THEN
        -- Si no me dicen cuantos habia, los cuento. NULL aca significa "no
        -- se", y quien lo lea no puede distinguirlo de cero: ese fue el
        -- defecto que el V433 tuvo que arreglar en la otra tabla.
        SELECT COUNT(*)
          INTO v_origen
          FROM academico_test.TESTUDIANTE_PERIODO_OBSERVACION ob
          JOIN academico_test.TPERIODO_EVALUACION pe
            ON pe.PK_TPERIODO_EVALUACION = ob.FK_TPERIODO_EVALUACION
           AND pe.ACTIVE = TRUE
           AND pe.FK_TPERIODO_ACADEMICO = v_fk_peraca
         WHERE ob.FK_TMATRICULA = p_fk_tmatricula
           AND ob.ACTIVE = TRUE
           AND NULLIF(TRIM(COALESCE(ob.OBSERVACION, '')), '') IS NOT NULL;
    END IF;

    v_estado := CASE WHEN v_texto = TRIM(v_ia) THEN 'APROBADA' ELSE 'MODIFICADA' END;

    SELECT lv.PK_LISTA_VALOR INTO v_pk_estado
      FROM academico_test.TLISTA_VALOR lv
     WHERE lv.CATEGORIA = 'ESTADO_OBSERVACION_IA'
       AND lv.VALOR     = v_estado
       AND lv.ACTIVE    = TRUE;

    IF v_pk_estado IS NULL THEN
        RAISE EXCEPTION 'Falta el estado % en el catalogo ESTADO_OBSERVACION_IA', v_estado
            USING ERRCODE = 'P0002';
    END IF;

    INSERT INTO academico_test.TESTUDIANTE_ANIO_OBSERVACION (
        FK_TMATRICULA, FK_TLV_ESTADO_OBSERVACION,
        OBSERVACION, OBSERVACION_IA, PERIODOS_ORIGEN,
        CREATED_BY, CREATED_AT, ACTIVE
    ) VALUES (
        p_fk_tmatricula, v_pk_estado,
        v_texto, v_ia, v_origen,
        p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
    )
    ON CONFLICT (FK_TMATRICULA)
    DO UPDATE SET FK_TLV_ESTADO_OBSERVACION = EXCLUDED.FK_TLV_ESTADO_OBSERVACION,
                  OBSERVACION               = EXCLUDED.OBSERVACION,
                  OBSERVACION_IA            = EXCLUDED.OBSERVACION_IA,
                  PERIODOS_ORIGEN           = EXCLUDED.PERIODOS_ORIGEN,
                  ACTIVE                    = TRUE,
                  MODIFIED_BY               = p_pk_usuario_solicitante::VARCHAR,
                  MODIFIED_AT               = CURRENT_TIMESTAMP
    RETURNING PK_TESTUDIANTE_ANIO_OBSERVACION INTO v_pk;

    RETURN v_pk;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_estudiante_anio_observacion_guardar(BIGINT, BIGINT, TEXT, TEXT, NUMERIC)
    IS 'Guarda el comentario del AÑO de un estudiante -- la fila Final --, el equivalente de fn_estudiante_periodo_observacion_guardar para TESTUDIANTE_ANIO_OBSERVACION. Reemplaza: el indice unico es total sobre la matricula y no se versiona. El ESTADO se deduce comparando el texto contra OBSERVACION_IA (iguales APROBADA, distintos MODIFICADA) y nunca se pide por parametro, para que no pueda contradecirlo. Arrastra los dos arreglos del V433 desde el dia uno: si no llega OBSERVACION_IA pero ya hay fila, se conserva el borrador guardado en vez de asumir que el texto nuevo es el de la IA -- si no, editar quedaria como APROBADA sin cambios --, y si no llega PERIODOS_ORIGEN se cuentan los resumenes de periodo consolidados en el momento de guardar, en vez de dejar la columna en NULL, que el lector no puede distinguir de cero. Gate INFORMES/EDITAR. Errores: 22023 con el texto vacio -- para quitarlo esta _eliminar --, 404 si la matricula no existe. V435.';


-- ---------------------------------------------------------------------------
-- 4. Eliminar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_estudiante_anio_observacion_eliminar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tmatricula          BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $function$
DECLARE
    v_fk_sede    BIGINT;
    v_fk_jornada BIGINT;
    v_fk_ee      BIGINT;
    v_pk         BIGINT;
BEGIN
    SELECT s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO
      INTO v_fk_sede, v_fk_jornada, v_fk_ee
      FROM academico_test.TMATRICULA m
      JOIN academico_test.TGRUPO gr ON gr.PK_TGRUPO = m.FK_TGRUPO
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE m.PK_TMATRICULA = p_fk_tmatricula
       AND m.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro la matricula solicitada'
            USING ERRCODE = 'P0002';
    END IF;

    -- ELIMINAR y no EDITAR, igual que en la tabla de periodos (V413):
    -- rehacer un texto es corregir, borrarlo es deshacer.
    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'ELIMINAR',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    -- Borrado FISICO y no baja logica, por el mismo motivo que en la otra
    -- tabla: el indice unico es total, asi que una fila inactiva seguiria
    -- ocupando el lugar e impediria guardar una nueva. Y no hay nada que
    -- conservar: el texto se vuelve a generar desde los resumenes de
    -- periodo, que son el dato original.
    DELETE FROM academico_test.TESTUDIANTE_ANIO_OBSERVACION ao
     WHERE ao.FK_TMATRICULA = p_fk_tmatricula
    RETURNING ao.PK_TESTUDIANTE_ANIO_OBSERVACION INTO v_pk;

    IF v_pk IS NULL THEN
        RAISE EXCEPTION 'El estudiante no tiene comentario del año guardado'
            USING ERRCODE = 'P0002';
    END IF;

    RETURN v_pk;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_estudiante_anio_observacion_eliminar(BIGINT, BIGINT)
    IS 'Quita el comentario del AÑO de un estudiante. Devuelve el PK eliminado. BORRADO FISICO y no baja logica, igual que su gemela de periodo (V413): el indice unico de TESTUDIANTE_ANIO_OBSERVACION es total sobre la matricula, de modo que una fila inactiva seguiria ocupando el lugar e impediria guardar una nueva; y no hay nada que conservar, porque el texto se regenera desde los resumenes de periodo, que son el dato original. Despues de eliminar, la fila Final de /informes/grupo vuelve a traer observacion en NULL. Gate INFORMES/ELIMINAR -- mas exigente que el EDITAR de guardar, porque rehacer es corregir y borrar es deshacer. 404 si no habia nada guardado. V435.';


-- ---------------------------------------------------------------------------
-- 5. El listado: la fila Final lee lo GUARDADO, no el concatenado.
--
--    DROP porque la firma no cambia pero si el cuerpo... en realidad alcanza
--    CREATE OR REPLACE: ni los parametros ni las columnas de salida cambian.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_informe_grupo_listar(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tgrupo              BIGINT,
    p_fk_periodos_evaluacion BIGINT[] DEFAULT NULL,
    p_search                 VARCHAR  DEFAULT NULL,
    p_incluir_final          BOOLEAN  DEFAULT FALSE
)
RETURNS TABLE(
    fk_tmatricula              BIGINT,
    estudiante                 VARCHAR,
    documento                  VARCHAR,
    fk_tperiodo_evaluacion     BIGINT,
    periodo_nombre             VARCHAR,
    periodo_abreviacion        VARCHAR,
    periodo_inicio             DATE,
    modo_periodo               VARCHAR,
    formato                    VARCHAR,
    es_cualitativo             BOOLEAN,
    consolidado                BOOLEAN,
    promedio_guardado          NUMERIC,
    promedio_proyectado        NUMERIC,
    puesto                     BIGINT,
    asignaturas_total          BIGINT,
    aprobadas                  BIGINT,
    reprobadas                 BIGINT,
    sin_definir                BIGINT,
    tiene_cambios_propuestos   BOOLEAN,
    asignaturas                JSONB,
    observacion                TEXT,
    observacion_estado         VARCHAR,
    observacion_desactualizada BOOLEAN,
    evidencias                 BIGINT,
    total_count                BIGINT
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_fk_sede     BIGINT;
    v_fk_jornada  BIGINT;
    v_fk_ee       BIGINT;
    v_fk_peraca   BIGINT;
    v_fk_grado    BIGINT;
    v_minimo      NUMERIC;
    v_n_periodos  INTEGER;
BEGIN
    SELECT s.PK_TSEDE, gr.FK_TLV_JORNADA, s.FK_TESTABLECIMIENTO,
           gd.FK_TPERIODO_ACADEMICO, gd.PK_TGRADO
      INTO v_fk_sede, v_fk_jornada, v_fk_ee, v_fk_peraca, v_fk_grado
      FROM academico_test.TGRUPO gr
      JOIN academico_test.TGRADO gd ON gd.PK_TGRADO = gr.FK_TGRADO
      JOIN academico_test.TPERIODO_ACADEMICO pa
        ON pa.PK_TPERIODO_ACADEMICO = gd.FK_TPERIODO_ACADEMICO
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = pa.FK_TSEDE
     WHERE gr.PK_TGRUPO = p_fk_tgrupo
       AND gr.ACTIVE = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontro el grupo solicitado'
            USING ERRCODE = 'P0002';
    END IF;

    PERFORM academico_test.fn_assert_permiso_seccion(
        p_pk_usuario_solicitante, 'INFORMES', 'VER',
        v_fk_ee, v_fk_sede, v_fk_jornada
    );

    v_minimo := academico_test.fn_grado_desempeno_minimo(v_fk_grado);

    SELECT COUNT(*)
      INTO v_n_periodos
      FROM academico_test.TPERIODO_EVALUACION pe
     WHERE pe.ACTIVE = TRUE
       AND pe.FK_TPERIODO_ACADEMICO = v_fk_peraca;

    RETURN QUERY
    WITH periodos AS (
        SELECT pe.PK_TPERIODO_EVALUACION AS pk,
               pe.NOMBRE                 AS nombre,
               pe.ABREVIACION            AS abrev,
               pe.FECHA_INICIO           AS inicio
          FROM academico_test.TPERIODO_EVALUACION pe
         WHERE pe.ACTIVE = TRUE
           AND pe.FK_TPERIODO_ACADEMICO = v_fk_peraca
           AND (p_fk_periodos_evaluacion IS NULL
                OR CARDINALITY(p_fk_periodos_evaluacion) = 0
                OR pe.PK_TPERIODO_EVALUACION = ANY (p_fk_periodos_evaluacion))
    ),
    estudiantes AS (
        SELECT m.PK_TMATRICULA AS pk,
               NULLIF(TRIM(CONCAT_WS(' ', u.PRIMER_NOMBRE, u.SEGUNDO_NOMBRE,
                                          u.PRIMER_APELLIDO, u.SEGUNDO_APELLIDO)),
                      '')::VARCHAR AS nombre,
               u.IDENTIFICACION::VARCHAR AS doc
          FROM academico_test.TMATRICULA m
          LEFT JOIN academico_test.TESTUDIANTE es ON es.PK_TESTUDIANTE = m.FK_TESTUDIANTE
          LEFT JOIN academico_test.TUSUARIO u     ON u.PK_TUSUARIO     = es.FK_TUSUARIO
         WHERE m.FK_TGRUPO = p_fk_tgrupo
           AND m.ACTIVE = TRUE
    ),
    detalle AS (
        SELECT e.pk AS mat, d.*
          FROM estudiantes e
          CROSS JOIN LATERAL academico_test.fn_informe_estudiante_asignaturas(
                         p_pk_usuario_solicitante, e.pk, p_fk_periodos_evaluacion) d
    ),
    observaciones AS (
        SELECT e.pk AS mat,
               p.pk AS pe,
               (SELECT COUNT(*)
                  FROM academico_test.TACTIVIDAD a2
                  JOIN academico_test.TACTIVIDAD_ESTUDIANTE ae2
                    ON ae2.FK_TACTIVIDAD = a2.PK_TACTIVIDAD
                   AND ae2.FK_TMATRICULA = e.pk
                   AND ae2.ACTIVE = TRUE
                  JOIN academico_test.TACTIVIDAD_NOTA n2
                    ON n2.FK_TACTIVIDAD_ESTUDIANTE = ae2.PK_TACTIVIDAD_ESTUDIANTE
                   AND n2.ACTIVE = TRUE
                 WHERE a2.ACTIVE = TRUE
                   AND NULLIF(TRIM(COALESCE(n2.OBSERVACION, '')), '') IS NOT NULL
                   AND academico_test.fn_actividad_en_periodo_eval(a2.PK_TACTIVIDAD, p.pk) = TRUE
               ) AS n
          FROM estudiantes e
          CROSS JOIN periodos p
    ),
    evidencias_periodo AS (
        SELECT e.pk AS mat,
               p.pk AS pe,
               (SELECT COUNT(*)
                  FROM academico_test.TACTIVIDAD_SOPORTE so
                  JOIN academico_test.TACTIVIDAD_ESTUDIANTE ae3
                    ON ae3.PK_TACTIVIDAD_ESTUDIANTE = so.FK_TACTIVIDAD_ESTUDIANTE
                   AND ae3.FK_TMATRICULA = e.pk
                   AND ae3.ACTIVE = TRUE
                  JOIN academico_test.TACTIVIDAD a4
                    ON a4.PK_TACTIVIDAD = ae3.FK_TACTIVIDAD
                   AND a4.ACTIVE = TRUE
                 WHERE so.ACTIVE = TRUE
                   AND so.FK_TARCHIVO IS NOT NULL
                   AND academico_test.fn_actividad_en_periodo_eval(a4.PK_TACTIVIDAD, p.pk) = TRUE
               ) AS n
          FROM estudiantes e
          CROSS JOIN periodos p
    ),
    por_periodo AS (
        SELECT e.pk   AS mat,
               e.nombre,
               e.doc,
               p.pk     AS pe,
               p.nombre AS pe_nombre,
               p.abrev  AS pe_abrev,
               p.inicio AS pe_inicio,
               COALESCE(BOOL_OR(COALESCE(d.nota_guardada, d.nota_proyectada)
                                IS NOT NULL), FALSE)             AS tiene_notas,
               COUNT(d.fk_tasignatura)                           AS calc_total,
               AVG(d.nota_guardada)                              AS calc_prom_guardado,
               AVG(COALESCE(d.nota_guardada, d.nota_proyectada)) AS calc_prom_visible,
               AVG(COALESCE(d.nota_proyectada, d.nota_guardada)) AS calc_prom_proyectado,
               COUNT(*) FILTER (WHERE d.aprobada IS TRUE)        AS calc_aprob,
               COUNT(*) FILTER (WHERE d.aprobada IS FALSE)       AS calc_reprob,
               COUNT(*) FILTER (WHERE d.fk_tasignatura IS NOT NULL
                                  AND d.aprobada IS NULL)        AS calc_sindef,
               COALESCE(BOOL_OR(d.es_numerico), FALSE)           AS hay_numerico,
               COALESCE(BOOL_OR(d.estado_nota = 'cambio_propuesto'), FALSE) AS cambios,
               COALESCE(
                   JSONB_AGG(
                       JSONB_BUILD_OBJECT(
                           'asignatura',  d.fk_tasignatura,
                           'nombre',      d.asignatura_nombre,
                           'abreviacion', asg.ABREVIACION,
                           'area',        d.area_nombre,
                           'orden',       asg.ORDEN_REPORTE,
                           'nota',        d.nota_homologada,
                           'nota_propuesta',
                               CASE WHEN d.estado_nota = 'cambio_propuesto'
                                    THEN d.nota_proyectada_homologada END,
                           'estado',      d.estado_nota,
                           'es_numerico', d.es_numerico,
                           'valoracion',  d.valoracion_nombre,
                           'simbolo',     d.valoracion_simbolo,
                           'aprobada',    d.aprobada
                       ) ORDER BY asg.ORDEN_REPORTE NULLS LAST, d.asignatura_nombre
                   ) FILTER (WHERE d.fk_tasignatura IS NOT NULL),
                   '[]'::JSONB
               ) AS asigs
          FROM estudiantes e
          CROSS JOIN periodos p
          LEFT JOIN detalle d
                 ON d.mat = e.pk
                AND d.fk_tperiodo_evaluacion = p.pk
          LEFT JOIN academico_test.TASIGNATURA asg
                 ON asg.PK_TASIGNATURA = d.fk_tasignatura
         GROUP BY e.pk, e.nombre, e.doc, p.pk, p.nombre, p.abrev, p.inicio
    ),
    base AS (
        SELECT pp.*,
               COALESCE(ob.n, 0) AS obs_hoy,
               COALESCE(ev.n, 0) AS evid
          FROM por_periodo pp
          LEFT JOIN observaciones      ob ON ob.mat = pp.mat AND ob.pe = pp.pe
          LEFT JOIN evidencias_periodo ev ON ev.mat = pp.mat AND ev.pe = pp.pe
    ),
    requeridos AS (
        SELECT b.mat,
               b.pe,
               COALESCE(BOOL_OR(r.es_numerico), FALSE) AS hay_numerico,
               COUNT(*)                                AS total,
               COALESCE(
                   JSONB_AGG(
                       JSONB_BUILD_OBJECT(
                           'asignatura',   r.fk_tasignatura,
                           'nombre',       r.asignatura_nombre,
                           'abreviacion',  r.abreviacion,
                           'area',         r.area_nombre,
                           'orden',        r.orden_reporte,
                           'nota',         r.requerido_homologado,
                           'porcentaje',   r.requerido,
                           'estado',       'requerido',
                           'es_numerico',  r.es_numerico,
                           'ya_asegurado', r.ya_asegurado,
                           'alcanzable',   r.alcanzable
                       ) ORDER BY r.orden_reporte NULLS LAST, r.asignatura_nombre
                   ),
                   '[]'::JSONB
               ) AS asigs
          FROM base b
          CROSS JOIN LATERAL academico_test.fn_informe_periodo_requerido(
                         p_pk_usuario_solicitante, b.mat, b.pe) r
         WHERE NOT b.tiene_notas
           AND b.obs_hoy = 0
         GROUP BY b.mat, b.pe
    ),
    resuelto AS (
        SELECT b.*,
               (NOT b.tiene_notas
                AND COALESCE(rq.hay_numerico, FALSE))  AS es_requerido,
               rq.total AS req_total,
               rq.asigs AS req_asigs,
               COALESCE(rq.hay_numerico, b.hay_numerico) AS es_num_final
          FROM base b
          LEFT JOIN requeridos rq ON rq.mat = b.mat AND rq.pe = b.pe
    ),
    con_metricas AS (
        SELECT rs.*,
               (ipm.PK_TINFORME_PERIODO_MATRICULA IS NOT NULL) AS esta_consolidado,
               COALESCE(ipm.PROMEDIO,    ROUND(rs.calc_prom_guardado, 2)) AS prom_guardado,
               COALESCE(ipm.ASIGNATURAS, rs.calc_total)                   AS total_asig,
               COALESCE(ipm.APROBADAS,   rs.calc_aprob)                   AS aprob,
               COALESCE(ipm.REPROBADAS,  rs.calc_reprob)                  AS reprob,
               COALESCE(ipm.SIN_DEFINIR, rs.calc_sindef)                  AS sindef,
               ob.OBSERVACION                                             AS obs,
               lv.VALOR                                                   AS obs_estado,
               CASE WHEN ob.PK_TESTUDIANTE_PERIODO_OBSERVACION IS NULL THEN NULL
                    ELSE rs.obs_hoy > COALESCE(ob.OBSERVACIONES_ORIGEN, 0)
               END                                                        AS obs_vieja
          FROM resuelto rs
          LEFT JOIN academico_test.TINFORME_PERIODO_MATRICULA ipm
                 ON ipm.FK_TMATRICULA          = rs.mat
                AND ipm.FK_TPERIODO_EVALUACION = rs.pe
                AND ipm.ACTIVE = TRUE
          LEFT JOIN academico_test.TESTUDIANTE_PERIODO_OBSERVACION ob
                 ON ob.FK_TMATRICULA          = rs.mat
                AND ob.FK_TPERIODO_EVALUACION = rs.pe
                AND ob.ACTIVE = TRUE
          LEFT JOIN academico_test.TLISTA_VALOR lv
                 ON lv.PK_LISTA_VALOR = ob.FK_TLV_ESTADO_OBSERVACION
    ),
    con_puesto AS (
        SELECT cm.*,
               CASE WHEN cm.es_requerido OR cm.calc_prom_visible IS NULL THEN NULL
                    ELSE RANK() OVER (PARTITION BY cm.pe
                                          ORDER BY cm.calc_prom_visible DESC NULLS LAST)
               END AS pos
          FROM con_metricas cm
    ),

    -- =======================================================================
    -- La fila Final (V431).
    -- =======================================================================
    estudiantes_final AS (
        SELECT e.* FROM estudiantes e WHERE COALESCE(p_incluir_final, FALSE)
    ),
    detalle_ano AS (
        SELECT e.pk AS mat, d.*
          FROM estudiantes_final e
          CROSS JOIN LATERAL academico_test.fn_informe_estudiante_asignaturas(
                         p_pk_usuario_solicitante, e.pk, NULL) d
    ),
    final_asig AS (
        SELECT d.mat                                    AS mat,
               d.fk_tasignatura                         AS asig,
               MAX(d.asignatura_nombre)                 AS nombre,
               MAX(asg.ABREVIACION)                     AS abrev,
               MAX(d.area_nombre)                       AS area,
               MAX(asg.ORDEN_REPORTE)                   AS orden,
               COALESCE(BOOL_OR(d.es_numerico), FALSE)  AS es_numerico,
               MAX(d.desempeno_minimo)                  AS minimo,
               SUM(COALESCE(d.nota_guardada, 0)) / NULLIF(v_n_periodos, 0) AS nota
          FROM detalle_ano d
          JOIN academico_test.TASIGNATURA asg ON asg.PK_TASIGNATURA = d.fk_tasignatura
         WHERE d.fk_tasignatura IS NOT NULL
         GROUP BY d.mat, d.fk_tasignatura
    ),
    final_agregado AS (
        SELECT fa.mat,
               COALESCE(BOOL_OR(fa.es_numerico), FALSE) AS hay_numerico,
               COUNT(*)                                 AS total,
               COUNT(*) FILTER (
                   WHERE fa.nota >= COALESCE(fa.minimo, v_minimo))         AS aprob,
               COUNT(*) FILTER (
                   WHERE fa.nota <  COALESCE(fa.minimo, v_minimo))         AS reprob,
               COUNT(*) FILTER (
                   WHERE fa.nota IS NULL
                      OR COALESCE(fa.minimo, v_minimo) IS NULL)            AS sindef,
               ROUND(AVG(fa.nota), 2)                   AS promedio,
               JSONB_AGG(
                   JSONB_BUILD_OBJECT(
                       'asignatura',  fa.asig,
                       'nombre',      fa.nombre,
                       'abreviacion', fa.abrev,
                       'area',        fa.area,
                       'orden',       fa.orden,
                       'nota',        h.nota_homologada,
                       'estado',      'final',
                       'es_numerico', fa.es_numerico,
                       'valoracion',  h.valoracion_nombre,
                       'simbolo',     h.valoracion_simbolo,
                       'aprobada',    CASE
                                          WHEN fa.nota IS NULL
                                            OR COALESCE(fa.minimo, v_minimo) IS NULL
                                          THEN NULL
                                          ELSE fa.nota >= COALESCE(fa.minimo, v_minimo)
                                      END
                   ) ORDER BY fa.orden NULLS LAST, fa.nombre
               )                                        AS asigs
          FROM final_asig fa
          LEFT JOIN LATERAL academico_test.fn_nota_homologar(
                        fa.nota, fa.asig, v_fk_grado) h ON TRUE
         GROUP BY fa.mat
    ),
    -- *** V435 *** Cuantos resumenes de periodo hay HOY. Es lo que se compara
    -- contra PERIODOS_ORIGEN para saber si el texto del año quedo viejo: lo
    -- que lo envejece es que se cierre un periodo nuevo, no que el docente
    -- escriba una observacion mas.
    final_periodos_hoy AS (
        SELECT e.pk AS mat,
               (SELECT COUNT(*)
                  FROM academico_test.TESTUDIANTE_PERIODO_OBSERVACION ob2
                  JOIN academico_test.TPERIODO_EVALUACION pe3
                    ON pe3.PK_TPERIODO_EVALUACION = ob2.FK_TPERIODO_EVALUACION
                   AND pe3.ACTIVE = TRUE
                   AND pe3.FK_TPERIODO_ACADEMICO = v_fk_peraca
                 WHERE ob2.FK_TMATRICULA = e.pk
                   AND ob2.ACTIVE = TRUE
                   AND NULLIF(TRIM(COALESCE(ob2.OBSERVACION, '')), '') IS NOT NULL
               ) AS n
          FROM estudiantes_final e
    ),
    final_evidencias AS (
        SELECT e.pk AS mat,
               (SELECT COUNT(*)
                  FROM academico_test.TACTIVIDAD_SOPORTE so
                  JOIN academico_test.TACTIVIDAD_ESTUDIANTE ae5
                    ON ae5.PK_TACTIVIDAD_ESTUDIANTE = so.FK_TACTIVIDAD_ESTUDIANTE
                   AND ae5.FK_TMATRICULA = e.pk
                   AND ae5.ACTIVE = TRUE
                  JOIN academico_test.TACTIVIDAD a6
                    ON a6.PK_TACTIVIDAD = ae5.FK_TACTIVIDAD
                   AND a6.ACTIVE = TRUE
                 WHERE so.ACTIVE = TRUE
                   AND so.FK_TARCHIVO IS NOT NULL
                   AND EXISTS (SELECT 1
                                 FROM academico_test.TPERIODO_EVALUACION pe2
                                WHERE pe2.ACTIVE = TRUE
                                  AND pe2.FK_TPERIODO_ACADEMICO = v_fk_peraca
                                  AND academico_test.fn_actividad_en_periodo_eval(
                                          a6.PK_TACTIVIDAD, pe2.PK_TPERIODO_EVALUACION) = TRUE)
               ) AS n
          FROM estudiantes_final e
    ),
    final_fila AS (
        SELECT e.pk AS mat,
               e.nombre,
               e.doc,
               COALESCE(fg.hay_numerico, FALSE) AS hay_numerico,
               COALESCE(fg.total,  0)           AS total,
               COALESCE(fg.aprob,  0)           AS aprob,
               COALESCE(fg.reprob, 0)           AS reprob,
               COALESCE(fg.sindef, 0)           AS sindef,
               fg.promedio,
               COALESCE(fg.asigs, '[]'::JSONB)  AS asigs,
               -- *** V435 *** Lo GUARDADO, no el concatenado. El concatenado
               -- pasa a ser el borrador que devuelve generar, asi que la fila
               -- arranca vacia como los periodos hasta que alguien lo acepte.
               ao.OBSERVACION                   AS obs,
               lva.VALOR                        AS obs_estado,
               CASE WHEN ao.PK_TESTUDIANTE_ANIO_OBSERVACION IS NULL THEN NULL
                    ELSE COALESCE(fph.n, 0) > COALESCE(ao.PERIODOS_ORIGEN, 0)
               END                              AS obs_vieja,
               COALESCE(fe.n, 0)                AS evid
          FROM estudiantes_final e
          LEFT JOIN final_agregado     fg  ON fg.mat  = e.pk
          LEFT JOIN final_evidencias   fe  ON fe.mat  = e.pk
          LEFT JOIN final_periodos_hoy fph ON fph.mat = e.pk
          LEFT JOIN academico_test.TESTUDIANTE_ANIO_OBSERVACION ao
                 ON ao.FK_TMATRICULA = e.pk
                AND ao.ACTIVE = TRUE
          LEFT JOIN academico_test.TLISTA_VALOR lva
                 ON lva.PK_LISTA_VALOR = ao.FK_TLV_ESTADO_OBSERVACION
    ),
    final_puesto AS (
        SELECT ff.*,
               CASE WHEN ff.hay_numerico IS TRUE AND ff.promedio IS NOT NULL
                    THEN RANK() OVER (ORDER BY ff.promedio DESC NULLS LAST)
               END AS pos
          FROM final_fila ff
    ),

    salida AS (
        SELECT cp.mat                    AS o_mat,
               cp.nombre                 AS o_nombre,
               cp.doc                    AS o_doc,
               cp.pe                     AS o_pe,
               cp.pe_nombre              AS o_pe_nombre,
               cp.pe_abrev               AS o_pe_abrev,
               cp.pe_inicio              AS o_pe_inicio,
               CASE WHEN cp.es_requerido THEN 'requerido' ELSE 'real' END::VARCHAR
                                         AS o_modo,
               CASE WHEN cp.es_num_final THEN 'numerico' ELSE 'cualitativo' END::VARCHAR
                                         AS o_formato,
               NOT cp.es_num_final       AS o_cualitativo,
               CASE WHEN cp.es_requerido THEN FALSE ELSE cp.esta_consolidado END
                                         AS o_consolidado,
               CASE WHEN cp.es_requerido THEN NULL ELSE cp.prom_guardado END
                                         AS o_prom_guardado,
               CASE WHEN cp.es_requerido THEN v_minimo
                    ELSE ROUND(cp.calc_prom_proyectado, 2) END
                                         AS o_prom_proyectado,
               cp.pos                    AS o_puesto,
               CASE WHEN cp.es_requerido THEN cp.req_total ELSE cp.total_asig END::BIGINT
                                         AS o_total,
               CASE WHEN cp.es_requerido THEN 0 ELSE cp.aprob  END::BIGINT AS o_aprob,
               CASE WHEN cp.es_requerido THEN 0 ELSE cp.reprob END::BIGINT AS o_reprob,
               CASE WHEN cp.es_requerido THEN cp.req_total ELSE cp.sindef END::BIGINT
                                         AS o_sindef,
               cp.cambios                AS o_cambios,
               CASE WHEN cp.es_requerido THEN cp.req_asigs ELSE cp.asigs END
                                         AS o_asigs,
               cp.obs                    AS o_obs,
               cp.obs_estado             AS o_obs_estado,
               cp.obs_vieja              AS o_obs_vieja,
               cp.evid::BIGINT           AS o_evidencias
          FROM con_puesto cp

        UNION ALL

        SELECT fp.mat,
               fp.nombre,
               fp.doc,
               (-1)::BIGINT,
               'Final'::VARCHAR,
               'FIN'::VARCHAR,
               '9999-12-31'::DATE,
               'final'::VARCHAR,
               CASE WHEN fp.hay_numerico THEN 'numerico' ELSE 'cualitativo' END::VARCHAR,
               NOT fp.hay_numerico,
               FALSE,
               CASE WHEN fp.hay_numerico THEN fp.promedio END,
               CASE WHEN fp.hay_numerico THEN fp.promedio END,
               fp.pos,
               CASE WHEN fp.hay_numerico THEN fp.total  ELSE 0 END::BIGINT,
               CASE WHEN fp.hay_numerico THEN fp.aprob  ELSE 0 END::BIGINT,
               CASE WHEN fp.hay_numerico THEN fp.reprob ELSE 0 END::BIGINT,
               CASE WHEN fp.hay_numerico THEN fp.sindef ELSE 0 END::BIGINT,
               FALSE,
               CASE WHEN fp.hay_numerico THEN fp.asigs ELSE '[]'::JSONB END,
               fp.obs,
               fp.obs_estado,
               fp.obs_vieja,
               fp.evid::BIGINT
          FROM final_puesto fp
    )
    SELECT s.o_mat,
           s.o_nombre,
           s.o_doc,
           s.o_pe,
           s.o_pe_nombre,
           s.o_pe_abrev,
           s.o_pe_inicio,
           s.o_modo,
           s.o_formato,
           s.o_cualitativo,
           s.o_consolidado,
           s.o_prom_guardado,
           s.o_prom_proyectado,
           s.o_puesto,
           s.o_total,
           s.o_aprob,
           s.o_reprob,
           s.o_sindef,
           s.o_cambios,
           s.o_asigs,
           s.o_obs,
           s.o_obs_estado,
           s.o_obs_vieja,
           s.o_evidencias,
           COUNT(*) OVER ()::BIGINT
      FROM salida s
     WHERE NULLIF(TRIM(COALESCE(p_search, '')), '') IS NULL
        OR s.o_nombre ILIKE '%' || TRIM(p_search) || '%'
        OR s.o_doc    ILIKE '%' || TRIM(p_search) || '%'
     ORDER BY s.o_nombre NULLS LAST, s.o_mat, s.o_pe_inicio;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_informe_grupo_listar(BIGINT, BIGINT, BIGINT[], VARCHAR, BOOLEAN)
    IS 'Listado principal de informes: una fila por (estudiante, periodo) del grupo. p_incluir_final agrega la fila con la nota del año -- FK_TPERIODO_EVALUACION = -1 (centinela, no un PK), modo_periodo "final", consolidado false, asignaturas con estado "final" --, calculada al vuelo sobre TODOS los periodos, con el periodo sin nota guardada valiendo cero y el promedio general sacado de esas mismas asignaturas (V431). La columna EVIDENCIAS trae cuantas imagenes adjuntas a observaciones tiene la fila, y en el Final las de todo el año (V434). V435: la observacion de la fila Final ya NO es el concatenado calculado al vuelo sino lo que este GUARDADO en TESTUDIANTE_ANIO_OBSERVACION -- el concatenado paso a ser el borrador que devuelve fn_estudiante_final_observacion --, asi que la fila arranca vacia como los periodos hasta que alguien lo acepte, y llega con su estado (APROBADA / MODIFICADA) y su marca de desactualizado. Lo que envejece ese texto es que se CONSOLIDE UN PERIODO NUEVO, no que el docente escriba una observacion mas, asi que se compara contra PERIODOS_ORIGEN y no contra OBSERVACIONES_ORIGEN. V335, V411, V412, V428, V431, V434, V435.';


-- ---------------------------------------------------------------------------
-- 6. El boletin: no imprimir un Final vacio.
--
--    Con el V434 el Final de preescolar siempre traia texto (el concatenado),
--    asi que entraba sin condiciones. Ahora puede no tener nada guardado, y
--    una fila cualitativa sin observacion y sin asignaturas es exactamente la
--    linea en blanco que el V430 vino a evitar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_informe_grupo_reporte(
    p_pk_usuario_solicitante BIGINT,
    p_fk_tgrupo              BIGINT,
    p_fk_periodos_evaluacion BIGINT[] DEFAULT NULL,
    p_search                 VARCHAR  DEFAULT NULL,
    p_incluir_final          BOOLEAN  DEFAULT FALSE,
    p_fk_matriculas          BIGINT[] DEFAULT NULL
)
RETURNS TABLE(
    estudiante   VARCHAR,
    documento    VARCHAR,
    periodo      VARCHAR,
    asignatura   VARCHAR,
    area         VARCHAR,
    nota         NUMERIC,
    desempeno    VARCHAR,
    estado       VARCHAR,
    aprobada     BOOLEAN,
    promedio     NUMERIC,
    puesto       BIGINT,
    observacion  TEXT,
    evidencias   BIGINT
)
LANGUAGE sql
STABLE
AS $function$
    WITH filas AS (
        SELECT *
          FROM academico_test.fn_informe_grupo_listar(
                   p_pk_usuario_solicitante,
                   p_fk_tgrupo,
                   p_fk_periodos_evaluacion,
                   p_search,
                   p_incluir_final)
    )
    SELECT f.estudiante,
           f.documento,
           f.periodo_nombre,
           a.nombre,
           a.area,
           a.nota,
           COALESCE(a.valoracion, a.simbolo)::VARCHAR,
           CASE a.estado
               WHEN 'guardada'         THEN 'Guardada'
               WHEN 'cambio_propuesto' THEN 'Guardada (con cambio propuesto)'
               WHEN 'final'            THEN 'Final (promedio del año)'
               ELSE a.estado
           END::VARCHAR,
           a.aprobada,
           f.promedio_guardado,
           f.puesto,
           f.observacion,
           f.evidencias
      FROM filas f
      LEFT JOIN LATERAL JSONB_TO_RECORDSET(
               CASE WHEN f.es_cualitativo IS TRUE
                     AND f.observacion_estado IS NOT NULL
                     AND NOT EXISTS (
                           SELECT 1
                             FROM JSONB_ARRAY_ELEMENTS(f.asignaturas) e
                            WHERE e->>'estado' IN ('guardada', 'cambio_propuesto'))
                    THEN '[]'::JSONB
                    ELSE f.asignaturas
               END
           ) AS a(
               asignatura   BIGINT,
               nombre       VARCHAR,
               abreviacion  VARCHAR,
               area         VARCHAR,
               orden        INTEGER,
               nota         NUMERIC,
               estado       VARCHAR,
               es_numerico  BOOLEAN,
               valoracion   VARCHAR,
               simbolo      VARCHAR,
               aprobada     BOOLEAN,
               ya_asegurado BOOLEAN,
               alcanzable   BOOLEAN
           ) ON TRUE
     WHERE (
             f.consolidado IS TRUE
             OR (f.es_cualitativo IS TRUE AND f.observacion_estado IS NOT NULL)
             -- *** V435 *** El Final entra si tiene algo que decir: notas
             -- (grupo numerico) o su comentario del año ya guardado. Sin eso
             -- seria una linea en blanco -- el mismo defecto que el V430.
             OR (f.modo_periodo = 'final'
                 AND (f.es_cualitativo IS FALSE OR f.observacion IS NOT NULL))
           )
       AND (a.estado IS NULL
            OR a.estado IN ('guardada', 'cambio_propuesto', 'final'))
       AND (p_fk_matriculas IS NULL
            OR CARDINALITY(p_fk_matriculas) = 0
            OR f.fk_tmatricula = ANY (p_fk_matriculas))
     ORDER BY f.periodo_inicio,
              f.estudiante,
              a.orden NULLS LAST,
              a.nombre;
$function$;


-- ---------------------------------------------------------------------------
-- 7. Los endpoints nuevos y el retoque del de generar.
-- ---------------------------------------------------------------------------

UPDATE public.query q
   SET detail = 'GENERA el borrador del comentario del AÑO de un estudiante -- la fila Final --, sin escribir nada. Hoy encadena los resumenes de periodo YA CONSOLIDADOS, en orden y prefijados con el nombre del periodo; cuando exista el modelo cambia lo que devuelve y nada mas, porque el contrato ya es el definitivo. NO es /informes/observacion/generar, que concatena las observaciones por ACTIVIDAD dentro de UN periodo: esas son la materia prima del resumen de periodo. Devuelve observacion_ia y periodos_origen, que se reenvian tal cual a /informes/observacion/final/guardar para que el backend deduzca si el docente lo aprobo o lo modifico. Devuelve siempre una fila; con null y cero si el estudiante no tiene ningun resumen de periodo guardado. Gate INFORMES/VER, porque no persiste.'
  FROM public.microservice m
 WHERE q.microservice_id = m.id_microservice
   AND m.serviceid       = 'eval-col'
   AND q.path_template   = '/informes/observacion/final'
   AND q.http_method     = 'POST';

INSERT INTO public.query
    (uuid, query, type, public_end, captcha, microservice_id, path_template,
     execution_mode, http_method, param_types, out_param_names, detail, action, style)
SELECT
    'eval-col-informes-observacion-final-guardar-001',
    'SELECT academico_test.fn_estudiante_anio_observacion_guardar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:BODY.FK_TMATRICULA AS BIGINT),
    CAST(:BODY.OBSERVACION AS TEXT),
    CAST(:BODY.OBSERVACION_IA AS TEXT),
    CAST(:BODY.PERIODOS_ORIGEN AS NUMERIC)
) AS pk_testudiante_anio_observacion;',
    'postgres', false, false,
    m.id_microservice,
    '/informes/observacion/final/guardar', 'SELECT', 'POST',
    '{"BODY.FK_TMATRICULA": "BIGINT", "BODY.OBSERVACION": "TEXT", "BODY.OBSERVACION_IA": "TEXT", "BODY.PERIODOS_ORIGEN": "NUMERIC"}'::jsonb,
    NULL,
    'Guarda el comentario del AÑO de un estudiante -- la fila Final --, en TESTUDIANTE_ANIO_OBSERVACION. Reemplaza: la llave unica es la matricula y no se versiona. El ESTADO no se pide: sale de comparar OBSERVACION contra OBSERVACION_IA -- iguales APROBADA, distintos MODIFICADA --, asi que reenvia el borrador que devolvio /informes/observacion/final tal como llego. Si no lo reenvias pero ya habia fila, se conserva el borrador guardado en vez de asumir que el texto nuevo es el de la IA. PERIODOS_ORIGEN es cuantos resumenes de periodo consolidados habia al generar; si no lo mandas se cuentan al guardar, para que la marca de desactualizado no quede mintiendo. Ojo: lo que deja viejo a ESTE texto es que se consolide un PERIODO nuevo, no que el docente escriba una observacion mas. Gate INFORMES/EDITAR. 400 (22023) con el texto vacio -- para quitarlo esta /informes/observacion/final/eliminar --, 404 si la matricula no existe.',
    'informes-observacion-final-guardar', 'DEFAULT'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (microservice_id, path_template, http_method)
    WHERE path_template IS NOT NULL DO NOTHING;

INSERT INTO public.query
    (uuid, query, type, public_end, captcha, microservice_id, path_template,
     execution_mode, http_method, param_types, out_param_names, detail, action, style)
SELECT
    'eval-col-informes-observacion-final-eliminar-001',
    'SELECT academico_test.fn_estudiante_anio_observacion_eliminar(
    public.fn_get_academico_usuario_id(:CONTEXT.USER_ID::BIGINT),
    CAST(:BODY.FK_TMATRICULA AS BIGINT)
) AS pk_testudiante_anio_observacion;',
    'postgres', false, false,
    m.id_microservice,
    '/informes/observacion/final/eliminar', 'SELECT', 'POST',
    '{"BODY.FK_TMATRICULA": "BIGINT"}'::jsonb,
    NULL,
    'Quita el comentario del AÑO de un estudiante. Devuelve el PK eliminado. EL BORRADO ES FISICO, no baja logica: la llave unica de TESTUDIANTE_ANIO_OBSERVACION es total sobre la matricula, de modo que una fila inactiva seguiria ocupando el lugar e impediria guardar una nueva; y no hay nada que conservar, porque el texto se vuelve a generar desde los resumenes de periodo, que son el dato original. Despues de eliminar, la fila Final de /informes/grupo vuelve a traer observacion en null. Es POST y no DELETE por coherencia con el resto del modulo. Gate INFORMES/ELIMINAR -- mas exigente que el EDITAR de guardar, porque rehacer un texto es corregir y borrarlo es deshacer. 404 si no habia nada guardado.',
    'informes-observacion-final-eliminar', 'DEFAULT'
  FROM public.microservice m
 WHERE m.serviceid = 'eval-col'
ON CONFLICT (microservice_id, path_template, http_method)
    WHERE path_template IS NOT NULL DO NOTHING;


-- ---------------------------------------------------------------------------
-- 8. Roles: se COPIAN de los equivalentes de periodo, no del listado.
--    Guardar y eliminar el comentario del año tiene que alcanzar a la misma
--    gente que guarda y elimina el del periodo, ni mas ni menos.
-- ---------------------------------------------------------------------------
INSERT INTO public.role_query (query_id, role_id)
SELECT nuevo.id_query, rq.role_id
  FROM public.query nuevo
  JOIN public.query modelo ON modelo.microservice_id = nuevo.microservice_id
                          AND modelo.http_method     = 'POST'
                          AND modelo.path_template   = CASE nuevo.uuid
                              WHEN 'eval-col-informes-observacion-final-guardar-001'
                                  THEN '/informes/observacion/guardar'
                              WHEN 'eval-col-informes-observacion-final-eliminar-001'
                                  THEN '/informes/observacion/eliminar'
                          END
  JOIN public.role_query rq ON rq.query_id = modelo.id_query
 WHERE nuevo.uuid IN ('eval-col-informes-observacion-final-guardar-001',
                      'eval-col-informes-observacion-final-eliminar-001')
ON CONFLICT DO NOTHING;
