-- ===========================================================================
-- V472 - Escala de valoracion: un criterio general, una nota cada uno.
--
--   TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (tabla nueva)
--   fn_actividad_nota_calificar_escala_criterios
--   PUT /planeador/actividades/estudiantes/:ID/calificar  (tipo ESCALA_VALORACION,
--       body nuevo: {"criterios":[{"criterioIndex":0,"valorNumerico":n} | {"criterioIndex":0,"pkNivel":n}, ...]})
--
--
-- EL PROBLEMA
--   "Criterios generales" (TACTIVIDAD_ESCALA.CRITERIOS_GENERALES) es una
--   lista de lo que se evalua en general -- pero hasta ahora la escala
--   solo admitia UNA nota por estudiante (TACTIVIDAD_ESCALA_EVALUACION,
--   UNIQUE por FK_TACTIVIDAD_ESCALA+FK_TACTIVIDAD_ESTUDIANTE), sin importar
--   cuantos criterios generales tuviera. Confirmado en vivo: dos criterios
--   ("hola", "como estas") y el popover de calificar solo mostraba UN campo
--   de nota -- el docente esperaba uno POR criterio, como ya pasa con
--   Rubrica.
--
--
-- LA SOLUCION: mismo patron que Rubrica, pero indexado por POSICION
--   CRITERIOS_GENERALES sigue siendo texto plano separado por coma (pedido
--   explicito: no se promueve a una tabla con PK propio, no hace falta
--   tocar la definicion del instrumento). Sin PK por criterio, el vinculo
--   entre "el segundo criterio general" y "la nota del segundo criterio"
--   es su POSICION (0-based) en el string partido por coma -- fragil si el
--   docente reordena/edita el texto DESPUES de calificar (la nota vieja
--   queda pegada a la posicion, no al texto), pero es la unica opcion
--   consistente con "CRITERIOS_GENERALES sigue siendo un solo campo".
--
--   Una fila por (estudiante, criterio_index): CUALITATIVA guarda
--   FK_TACTIVIDAD_ESCALA_NIVEL (mismos niveles de siempre, compartidos por
--   todos los criterios); NUMERICA guarda VALOR (mismo VALOR_MIN/VALOR_MAX
--   de la escala, compartido tambien). La nota final de la actividad es el
--   PROMEDIO simple de los % de cada criterio -- misma logica que Rubrica
--   promedia sus criterios.
--
--
-- COMPATIBILIDAD
--   Una escala con 0 o 1 criterio general sigue funcionando exactamente
--   igual que antes: {"valorNumerico":n} o {"pkNivel":n} sueltos (sin
--   "criterios") siguen yendo a fn_actividad_nota_calificar_escala, la
--   funcion de siempre, que nunca se toco. El body nuevo ({"criterios":[...]})
--   es aditivo -- se activa solo cuando el front lo manda.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. La tabla: una fila por (estudiante, criterio_index) de la escala.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (
  PK_TAC_ESCALA_CRITERIO_EVAL BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD_ESCALA        BIGINT NOT NULL,
  FK_TACTIVIDAD_ESTUDIANTE    BIGINT NOT NULL,
  CRITERIO_INDEX              INTEGER NOT NULL,
  FK_TACTIVIDAD_ESCALA_NIVEL  BIGINT,
  VALOR                       NUMERIC(5,2),
  PONDERACION                 NUMERIC(5,2),
  CREATED_BY                  VARCHAR(120) NOT NULL,
  CREATED_AT                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY                 VARCHAR(120),
  MODIFIED_AT                 TIMESTAMP,
  ACTIVE                      BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TAC_ESCALA_CRITERIO_EVAL PRIMARY KEY (PK_TAC_ESCALA_CRITERIO_EVAL),
  CONSTRAINT UN_TAC_ESCALA_CRITERIO_EVAL_1 UNIQUE (FK_TACTIVIDAD_ESTUDIANTE, CRITERIO_INDEX) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_1 FOREIGN KEY (FK_TACTIVIDAD_ESCALA) REFERENCES academico_test.TACTIVIDAD_ESCALA (PK_TACTIVIDAD_ESCALA) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_2 FOREIGN KEY (FK_TACTIVIDAD_ESTUDIANTE) REFERENCES academico_test.TACTIVIDAD_ESTUDIANTE (PK_TACTIVIDAD_ESTUDIANTE) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_3 FOREIGN KEY (FK_TACTIVIDAD_ESCALA_NIVEL) REFERENCES academico_test.TACTIVIDAD_ESCALA_NIVEL (PK_TACTIVIDAD_ESCALA_NIVEL)
);

CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_1 ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (FK_TACTIVIDAD_ESCALA);
CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_2 ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (FK_TACTIVIDAD_ESTUDIANTE);
CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_ACTIVE ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (PK_TAC_ESCALA_CRITERIO_EVAL) WHERE ACTIVE = true;

COMMENT ON TABLE academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
    IS 'Nota POR criterio general de una escala de valoracion, un estudiante puede tener varias (una por CRITERIO_INDEX -- posicion 0-based en TACTIVIDAD_ESCALA.CRITERIOS_GENERALES partido por coma). CUALITATIVA usa FK_TACTIVIDAD_ESCALA_NIVEL; NUMERICA usa VALOR; ambos comparten los mismos niveles/rango de TACTIVIDAD_ESCALA. La nota final de TACTIVIDAD_NOTA es el promedio simple de los % de cada fila. V472.';
COMMENT ON COLUMN academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION.CRITERIO_INDEX IS 'Posicion (0-based) del criterio dentro de CRITERIOS_GENERALES separado por coma -- no hay PK de criterio, CRITERIOS_GENERALES sigue siendo texto plano';


-- ---------------------------------------------------------------------------
-- 2. La funcion: recibe TODOS los criterios de una (mismo criterio que
--    Rubrica -- se exige cubrir el set completo, no permite parcial).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_calificar_escala_criterios(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad_estudiante BIGINT,
    p_criterios                JSONB,
    p_fecha                    DATE DEFAULT CURRENT_DATE
)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $function$
DECLARE
    v_pk_tactividad     BIGINT;
    v_pk_nota           BIGINT;
    v_pk_escala         BIGINT;
    v_tipo_val          VARCHAR;
    v_min               NUMERIC(5,2);
    v_max               NUMERIC(5,2);
    v_criterios_generales VARCHAR;
    v_criterios_esperados INTEGER;
    v_elem              JSONB;
    v_criterio_index    INTEGER;
    v_pk_nivel          BIGINT;
    v_valor_numerico    NUMERIC(5,2);
    v_nivel_pond        NUMERIC(5,2);
    v_max_pond          NUMERIC(5,2);
    v_pct_item          NUMERIC(5,2);
    v_valor_final       NUMERIC(5,2);
    v_pond_final        NUMERIC(5,2);
    v_nivel_final       BIGINT;
    v_pk_fila_existente BIGINT;
    v_indices_vistos    INTEGER[] := ARRAY[]::INTEGER[];
    v_pct_final         NUMERIC(5,2);
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL,
        academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante)
    );

    v_pk_tactividad := academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante);
    PERFORM academico_test.fn_actividad_nota_asistencia_assert(p_pk_tactividad_estudiante, p_fecha);
    PERFORM academico_test.fn_actividad_instrumento_assert(v_pk_tactividad, 'ESCALA_VALORACION');

    SELECT e.PK_TACTIVIDAD_ESCALA, lv.VALOR, e.VALOR_MIN, e.VALOR_MAX, e.CRITERIOS_GENERALES
      INTO v_pk_escala, v_tipo_val, v_min, v_max, v_criterios_generales
      FROM academico_test.TACTIVIDAD_ESCALA e
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = e.FK_TLV_TIPO_ESCALA
     WHERE e.FK_TACTIVIDAD = v_pk_tactividad AND e.ACTIVE = TRUE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La actividad no tiene una escala de valoracion definida (use fn_actividad_escala_definir primero)'
            USING ERRCODE = '22023';
    END IF;

    IF p_criterios IS NULL OR jsonb_typeof(p_criterios) <> 'array' OR jsonb_array_length(p_criterios) = 0 THEN
        RAISE EXCEPTION 'criterios debe ser un array con al menos un elemento {criterioIndex, pkNivel|valorNumerico}'
            USING ERRCODE = '22023';
    END IF;

    -- Cuantos criterios generales tiene la escala -- se deriva del mismo
    -- texto separado por coma que ya usa el front para armar los inputs,
    -- no de un conteo mandado por el cliente (mismo espiritu que Rubrica:
    -- "se exige cubrir el set completo", pero el "completo" real vive del
    -- lado del servidor).
    v_criterios_esperados := GREATEST(
        COALESCE(array_length(string_to_array(NULLIF(TRIM(v_criterios_generales), ''), ','), 1), 1),
        1
    );

    IF jsonb_array_length(p_criterios) <> v_criterios_esperados THEN
        RAISE EXCEPTION 'La escala tiene % criterio(s) general(es) pero se calificaron % -- deben cubrirse todos',
            v_criterios_esperados, jsonb_array_length(p_criterios)
            USING ERRCODE = '22023';
    END IF;

    v_pk_nota := academico_test.fn_actividad_nota_get_or_create(p_pk_usuario_solicitante, p_pk_tactividad_estudiante);

    v_pct_final := 0;

    FOR v_elem IN SELECT * FROM jsonb_array_elements(p_criterios)
    LOOP
        v_criterio_index := (v_elem->>'criterioIndex')::INTEGER;
        v_pk_nivel        := (v_elem->>'pkNivel')::BIGINT;
        v_valor_numerico  := (v_elem->>'valorNumerico')::NUMERIC;

        IF v_criterio_index IS NULL OR v_criterio_index < 0 OR v_criterio_index >= v_criterios_esperados THEN
            RAISE EXCEPTION 'criterioIndex (%) fuera de rango: la escala tiene % criterio(s)',
                v_criterio_index, v_criterios_esperados
                USING ERRCODE = '22023';
        END IF;
        IF v_criterio_index = ANY(v_indices_vistos) THEN
            RAISE EXCEPTION 'criterioIndex % repetido' , v_criterio_index USING ERRCODE = '22023';
        END IF;
        v_indices_vistos := v_indices_vistos || v_criterio_index;

        IF (v_pk_nivel IS NOT NULL) = (v_valor_numerico IS NOT NULL) THEN
            RAISE EXCEPTION 'criterioIndex %: debe indicarse exactamente uno de pkNivel o valorNumerico',
                v_criterio_index USING ERRCODE = '22023';
        END IF;

        IF v_tipo_val = 'CUALITATIVA' THEN
            IF v_pk_nivel IS NULL THEN
                RAISE EXCEPTION 'criterioIndex %: la escala de esta actividad es CUALITATIVA, se requiere pkNivel',
                    v_criterio_index USING ERRCODE = '22023';
            END IF;

            SELECT PONDERACION INTO v_nivel_pond
              FROM academico_test.TACTIVIDAD_ESCALA_NIVEL
             WHERE PK_TACTIVIDAD_ESCALA_NIVEL = v_pk_nivel
               AND FK_TACTIVIDAD_ESCALA = v_pk_escala AND ACTIVE = TRUE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'criterioIndex %: el nivel % no pertenece a la escala de esta actividad',
                    v_criterio_index, v_pk_nivel USING ERRCODE = '22023';
            END IF;

            SELECT MAX(PONDERACION) INTO v_max_pond
              FROM academico_test.TACTIVIDAD_ESCALA_NIVEL
             WHERE FK_TACTIVIDAD_ESCALA = v_pk_escala AND ACTIVE = TRUE;

            v_pct_item    := ROUND(v_nivel_pond / NULLIF(v_max_pond, 0) * 100, 2);
            v_nivel_final := v_pk_nivel;
            v_valor_final := v_nivel_pond;
            v_pond_final  := v_nivel_pond;
        ELSE
            IF v_valor_numerico IS NULL THEN
                RAISE EXCEPTION 'criterioIndex %: la escala de esta actividad es NUMERICA, se requiere valorNumerico',
                    v_criterio_index USING ERRCODE = '22023';
            END IF;
            IF v_min IS NULL OR v_max IS NULL THEN
                RAISE EXCEPTION 'La escala NUMERICA de esta actividad no tiene valorMin/valorMax definidos'
                    USING ERRCODE = '22023';
            END IF;
            IF v_valor_numerico < v_min OR v_valor_numerico > v_max THEN
                RAISE EXCEPTION 'criterioIndex %: valorNumerico (%) debe estar entre % y %',
                    v_criterio_index, v_valor_numerico, v_min, v_max USING ERRCODE = '22023';
            END IF;

            v_pct_item    := ROUND(v_valor_numerico / NULLIF(v_max, 0) * 100, 2);
            v_nivel_final := NULL;
            v_valor_final := v_valor_numerico;
            v_pond_final  := NULL;
        END IF;

        v_pct_final := v_pct_final + v_pct_item;

        SELECT PK_TAC_ESCALA_CRITERIO_EVAL INTO v_pk_fila_existente
          FROM academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
         WHERE FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante AND CRITERIO_INDEX = v_criterio_index;

        IF v_pk_fila_existente IS NULL THEN
            INSERT INTO academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (
                FK_TACTIVIDAD_ESCALA, FK_TACTIVIDAD_ESTUDIANTE, CRITERIO_INDEX,
                FK_TACTIVIDAD_ESCALA_NIVEL, VALOR, PONDERACION,
                CREATED_BY, CREATED_AT, ACTIVE
            ) VALUES (
                v_pk_escala, p_pk_tactividad_estudiante, v_criterio_index,
                v_nivel_final, v_valor_final, v_pond_final,
                p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
            );
        ELSE
            UPDATE academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
               SET FK_TACTIVIDAD_ESCALA_NIVEL = v_nivel_final,
                   VALOR                       = v_valor_final,
                   PONDERACION                 = v_pond_final,
                   ACTIVE                       = TRUE,
                   MODIFIED_BY                  = p_pk_usuario_solicitante::VARCHAR,
                   MODIFIED_AT                  = CURRENT_TIMESTAMP
             WHERE PK_TAC_ESCALA_CRITERIO_EVAL = v_pk_fila_existente;
        END IF;
    END LOOP;

    -- Promedio simple de los % de cada criterio -- misma logica que Rubrica.
    v_pct_final := ROUND(v_pct_final / v_criterios_esperados, 2);
    v_pct_final := academico_test.fn_actividad_nota_ajustar_por_criterio(v_pk_tactividad, v_pct_final);

    UPDATE academico_test.TACTIVIDAD_NOTA
       SET CALIFICACION = v_pct_final, CALIFICABLE = 'S',
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_NOTA = v_pk_nota;

    PERFORM academico_test.fn_actividad_recuperacion_aplicar(
                p_pk_usuario_solicitante, p_pk_tactividad_estudiante);

    RETURN v_pct_final;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_calificar_escala_criterios(BIGINT, BIGINT, JSONB, DATE)
    IS 'Califica UNA escala de valoracion con un valor POR criterio general: p_criterios = [{criterioIndex, pkNivel|valorNumerico}, ...], UNO por cada posicion de CRITERIOS_GENERALES separado por coma (se exige el set completo, igual que Rubrica). Por criterio: % = ponderacion del nivel / MAX ponderacion (CUALITATIVA) o valor / valorMax * 100 (NUMERICA, V469). Nota final = promedio simple de esos %. Upsert de TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (una fila por estudiante+criterio_index) y de TACTIVIDAD_NOTA.CALIFICACION. Exige asistencia del dia. Aditiva: una escala con 0-1 criterio sigue usando fn_actividad_nota_calificar_escala de siempre. V472.';


-- ---------------------------------------------------------------------------
-- 3. La fachada (fn_actividad_nota_calificar, V227): si el body trae
--    "criterios", despacha a la funcion nueva; si no, sigue igual que
--    siempre. Aditivo -- DROP+CREATE porque la firma no cambia (BIGINT,
--    BIGINT, JSONB, DATE), pero el CUERPO si.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_calificar(
    p_pk_usuario_solicitante    BIGINT,
    p_pk_tactividad_estudiante  BIGINT,
    p_calificacion               JSONB,
    p_fecha                      DATE DEFAULT CURRENT_DATE
)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $function$
DECLARE
    v_pk_tactividad BIGINT;
    v_valor         VARCHAR;
    v_pct           NUMERIC(5,2);
BEGIN
    v_pk_tactividad := academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante);

    SELECT lv.VALOR INTO v_valor
      FROM academico_test.TACTIVIDAD a
      LEFT JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
     WHERE a.PK_TACTIVIDAD = v_pk_tactividad;

    IF p_calificacion IS NULL OR jsonb_typeof(p_calificacion) <> 'object' THEN
        RAISE EXCEPTION 'p_calificacion debe ser un objeto JSON' USING ERRCODE = '22023';
    END IF;

    CASE v_valor
        WHEN 'RUBRICA' THEN
            v_pct := academico_test.fn_actividad_nota_calificar_rubrica(
                         p_pk_usuario_solicitante, p_pk_tactividad_estudiante, p_calificacion->'niveles', p_fecha);
        WHEN 'LISTA_COTEJO' THEN
            v_pct := academico_test.fn_actividad_nota_calificar_cotejo(
                         p_pk_usuario_solicitante, p_pk_tactividad_estudiante,
                         ARRAY(SELECT jsonb_array_elements_text(COALESCE(p_calificacion->'itemsMarcados', '[]'::jsonb))::BIGINT),
                         p_fecha);
        WHEN 'ESCALA_VALORACION' THEN
            -- V472: "criterios" (array) es UN valor por criterio general;
            -- sin ese campo, sigue el camino de siempre (un solo pkNivel/
            -- valorNumerico para toda la escala).
            IF p_calificacion ? 'criterios' THEN
                v_pct := academico_test.fn_actividad_nota_calificar_escala_criterios(
                             p_pk_usuario_solicitante, p_pk_tactividad_estudiante, p_calificacion->'criterios', p_fecha);
            ELSE
                v_pct := academico_test.fn_actividad_nota_calificar_escala(
                             p_pk_usuario_solicitante, p_pk_tactividad_estudiante,
                             (p_calificacion->>'pkNivel')::BIGINT, (p_calificacion->>'valorNumerico')::NUMERIC, p_fecha);
            END IF;
        WHEN 'OTRO' THEN
            v_pct := academico_test.fn_actividad_nota_calificar_otro(
                         p_pk_usuario_solicitante, p_pk_tactividad_estudiante,
                         (p_calificacion->>'porcentaje')::NUMERIC, p_fecha);
        ELSE
            RAISE EXCEPTION 'La actividad no tiene un instrumento de evaluacion valido para calificar (%)',
                COALESCE(v_valor, 'sin instrumento') USING ERRCODE = '22023';
    END CASE;

    RETURN v_pct;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_calificar(BIGINT, BIGINT, JSONB, DATE)
    IS 'Fachada: lee el instrumento de la actividad (via TACTIVIDAD_ESTUDIANTE.FK_TACTIVIDAD) y despacha a fn_actividad_nota_calificar_rubrica ({niveles:[{pkCriterio,pkNivel}]}), _cotejo ({itemsMarcados:[pk,...]}), _escala ({pkNivel} o {valorNumerico}) / _escala_criterios ({criterios:[{criterioIndex,pkNivel|valorNumerico}]}, V472, un valor por criterio general) u _otro ({porcentaje}), pasando p_fecha (DEFAULT CURRENT_DATE, el dia de clase que se califica; el gate de asistencia se aplica contra ella, ver cabecera). Calcula (salvo OTRO) y guarda el % (0-100) en TACTIVIDAD_NOTA.CALIFICACION. Gate EDITAR sobre PLANEADOR (via las funciones destino). V227; criterios independientes de escala en V472.';


-- ---------------------------------------------------------------------------
-- 4. Lectura: fn_actividad_nota_obtener (detalle crudo por PK) y
--    fn_actividad_nota_resultado_instrumento (con etiquetas) prefieren la
--    tabla nueva cuando tiene filas para este estudiante; si no, caen al
--    camino de siempre (compatibilidad con escalas de 0-1 criterio, que
--    nunca escriben en la tabla nueva).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_obtener(p_pk_usuario_solicitante bigint, p_pk_tactividad_estudiante bigint)
 RETURNS TABLE(instrumento character varying, calificacion numeric, calificable character, observacion character varying, detalle jsonb, evidencias jsonb, nota_homologada numeric, valoracion character varying, formato_valor character varying, resultado_instrumento jsonb)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'VER', NULL, NULL, NULL, academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante)
    );

    IF NOT EXISTS (
        SELECT 1 FROM academico_test.TACTIVIDAD_ESTUDIANTE
         WHERE PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante AND ACTIVE = TRUE
    ) THEN
        RAISE EXCEPTION 'No se encontro la asignacion actividad-estudiante solicitada' USING ERRCODE = 'P0002';
    END IF;

    RETURN QUERY
    SELECT lv.VALOR,
           n.CALIFICACION,
           n.CALIFICABLE,
           n.OBSERVACION,
           CASE lv.VALOR
               WHEN 'RUBRICA' THEN COALESCE((
                   SELECT jsonb_agg(jsonb_build_object(
                              'pkCriterio',  re.FK_TACTIVIDAD_RUBRICA_CRITERIO,
                              'pkNivel',     re.FK_TACTIVIDAD_RUBRICA_NIVEL,
                              'ponderacion', re.PONDERACION))
                     FROM academico_test.TACTIVIDAD_RUBRICA_EVALUACION re
                     JOIN academico_test.TACTIVIDAD_RUBRICA_CRITERIO c
                       ON c.PK_TACTIVIDAD_RUBRICA_CRITERIO = re.FK_TACTIVIDAD_RUBRICA_CRITERIO
                    WHERE re.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                      AND re.ACTIVE = TRUE AND c.FK_TACTIVIDAD = a.PK_TACTIVIDAD
               ), '[]'::jsonb)

               WHEN 'LISTA_COTEJO' THEN COALESCE((
                   SELECT jsonb_agg(jsonb_build_object(
                              'pkItem',   ce.FK_TACTIVIDAD_COTEJO_ITEM,
                              'cumplido', ce.CUMPLIDO))
                     FROM academico_test.TACTIVIDAD_COTEJO_EVALUACION ce
                     JOIN academico_test.TACTIVIDAD_COTEJO_ITEM i
                       ON i.PK_TACTIVIDAD_COTEJO_ITEM = ce.FK_TACTIVIDAD_COTEJO_ITEM
                    WHERE ce.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                      AND ce.ACTIVE = TRUE AND i.FK_TACTIVIDAD = a.PK_TACTIVIDAD
               ), '[]'::jsonb)

               -- V472: si hay filas por-criterio, ganan sobre la fila unica
               -- vieja -- un elemento por CRITERIO_INDEX, {criterioIndex,
               -- pkNivel, valor, ponderacion}.
               WHEN 'ESCALA_VALORACION' THEN COALESCE((
                   SELECT jsonb_agg(jsonb_build_object(
                              'criterioIndex', ce.CRITERIO_INDEX,
                              'pkNivel',       ce.FK_TACTIVIDAD_ESCALA_NIVEL,
                              'valor',         ce.VALOR,
                              'ponderacion',   ce.PONDERACION) ORDER BY ce.CRITERIO_INDEX)
                     FROM academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION ce
                     JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = ce.FK_TACTIVIDAD_ESCALA
                    WHERE ce.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                      AND ce.ACTIVE = TRUE AND e.FK_TACTIVIDAD = a.PK_TACTIVIDAD
               ), (
                   SELECT jsonb_build_object(
                              'pkNivel',      ee.FK_TACTIVIDAD_ESCALA_NIVEL,
                              'valor',        ee.VALOR,
                              'ponderacion',  ee.PONDERACION)
                     FROM academico_test.TACTIVIDAD_ESCALA_EVALUACION ee
                     JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = ee.FK_TACTIVIDAD_ESCALA
                    WHERE ee.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                      AND ee.ACTIVE = TRUE AND e.FK_TACTIVIDAD = a.PK_TACTIVIDAD
               ))

               WHEN 'OTRO' THEN (
                   CASE academico_test.fn_actividad_otro_metodo_valoracion(a.PK_TACTIVIDAD)
                       WHEN 'RUBRICA' THEN COALESCE((
                           SELECT jsonb_agg(jsonb_build_object(
                                      'pkCriterio',  re.FK_TACTIVIDAD_RUBRICA_CRITERIO,
                                      'pkNivel',     re.FK_TACTIVIDAD_RUBRICA_NIVEL,
                                      'ponderacion', re.PONDERACION))
                             FROM academico_test.TACTIVIDAD_RUBRICA_EVALUACION re
                             JOIN academico_test.TACTIVIDAD_RUBRICA_CRITERIO c
                               ON c.PK_TACTIVIDAD_RUBRICA_CRITERIO = re.FK_TACTIVIDAD_RUBRICA_CRITERIO
                            WHERE re.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                              AND re.ACTIVE = TRUE AND c.FK_TACTIVIDAD = a.PK_TACTIVIDAD
                       ), '[]'::jsonb)

                       WHEN 'LISTA_COTEJO' THEN COALESCE((
                           SELECT jsonb_agg(jsonb_build_object(
                                      'pkItem',   ce.FK_TACTIVIDAD_COTEJO_ITEM,
                                      'cumplido', ce.CUMPLIDO))
                             FROM academico_test.TACTIVIDAD_COTEJO_EVALUACION ce
                             JOIN academico_test.TACTIVIDAD_COTEJO_ITEM i
                               ON i.PK_TACTIVIDAD_COTEJO_ITEM = ce.FK_TACTIVIDAD_COTEJO_ITEM
                            WHERE ce.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                              AND ce.ACTIVE = TRUE AND i.FK_TACTIVIDAD = a.PK_TACTIVIDAD
                       ), '[]'::jsonb)

                       WHEN 'ESCALA_VALORACION' THEN (
                           SELECT jsonb_build_object(
                                      'pkNivel',      ee.FK_TACTIVIDAD_ESCALA_NIVEL,
                                      'valor',        ee.VALOR,
                                      'ponderacion',  ee.PONDERACION)
                             FROM academico_test.TACTIVIDAD_ESCALA_EVALUACION ee
                             JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = ee.FK_TACTIVIDAD_ESCALA
                            WHERE ee.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                              AND ee.ACTIVE = TRUE AND e.FK_TACTIVIDAD = a.PK_TACTIVIDAD
                       )

                       ELSE NULL
                   END
               )

               ELSE NULL
           END
           ,
           COALESCE((
               SELECT jsonb_agg(jsonb_build_object(
                          'pk',     so.PK_TACTIVIDAD_SOPORTE,
                          'fkTarchivo', so.FK_TARCHIVO,
                          'nombre', ar.NOMBRE,
                          'fecha',  so.FECHA)
                          ORDER BY so.PK_TACTIVIDAD_SOPORTE)
                 FROM academico_test.TACTIVIDAD_SOPORTE so
                 LEFT JOIN academico_test.TARCHIVO ar ON ar.PK_TARCHIVO = so.FK_TARCHIVO
                WHERE so.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE
                  AND so.ACTIVE = TRUE
                  AND so.FK_TARCHIVO IS NOT NULL
           ), '[]'::jsonb),
           h.nota_homologada,
           h.valoracion_nombre,
           h.formato_valor,
           academico_test.fn_actividad_nota_resultado_instrumento(ae.PK_TACTIVIDAD_ESTUDIANTE)
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      JOIN academico_test.TACTIVIDAD a ON a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD
      LEFT JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
      LEFT JOIN academico_test.TACTIVIDAD_NOTA n
             ON n.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE AND n.ACTIVE = TRUE
      LEFT JOIN LATERAL academico_test.fn_nota_homologar(
                    COALESCE(n.DEFINITIVA, n.CALIFICACION), a.FK_TASIGNATURA,
                    academico_test.fn_actividad_grado_resolver(a.PK_TACTIVIDAD)) h ON TRUE
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_obtener(BIGINT, BIGINT)
    IS 'Detalle de la nota de un estudiante en una actividad: instrumento, % (calificacion), calificable, observacion, detalle (captura cruda por PK -- ESCALA_VALORACION prefiere TACTIVIDAD_ESCALA_CRITERIO_EVALUACION, un array por criterio_index, V472; cae a la fila unica vieja si no hay), evidencias, nota_homologada/valoracion/formato_valor (fn_nota_homologar) y resultado_instrumento con etiquetas (fn_actividad_nota_resultado_instrumento). Gate VER sobre PLANEADOR. V227/V241/V243/V461/V469/V472.';


CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_resultado_instrumento(
    p_pk_tactividad_estudiante BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_pk_tactividad BIGINT;
    v_tipo          VARCHAR;
    v_res           JSONB;
BEGIN
    SELECT ae.FK_TACTIVIDAD, lv.VALOR
      INTO v_pk_tactividad, v_tipo
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      JOIN academico_test.TACTIVIDAD a ON a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD
      LEFT JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = a.FK_TLV_INSTRUMENTO_EVALUACION
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    IF v_tipo = 'OTRO' THEN
        v_tipo := COALESCE(academico_test.fn_actividad_otro_metodo_valoracion(v_pk_tactividad), 'OTRO');
    END IF;

    CASE v_tipo
        WHEN 'RUBRICA' THEN
            SELECT jsonb_build_object(
                       'tipo', 'RUBRICA',
                       'resumen', string_agg(c.NOMBRE || ': ' || COALESCE(n.ETIQUETA, n.DESCRIPCION), ' · ' ORDER BY c.ORDEN),
                       'detalle', jsonb_agg(jsonb_build_object(
                                      'pkCriterio', c.PK_TACTIVIDAD_RUBRICA_CRITERIO, 'criterio', c.NOMBRE,
                                      'pkNivel', n.PK_TACTIVIDAD_RUBRICA_NIVEL, 'nivel', COALESCE(n.ETIQUETA, n.DESCRIPCION),
                                      'ponderacion', re.PONDERACION) ORDER BY c.ORDEN))
              INTO v_res
              FROM academico_test.TACTIVIDAD_RUBRICA_EVALUACION re
              JOIN academico_test.TACTIVIDAD_RUBRICA_CRITERIO c ON c.PK_TACTIVIDAD_RUBRICA_CRITERIO = re.FK_TACTIVIDAD_RUBRICA_CRITERIO
              LEFT JOIN academico_test.TACTIVIDAD_RUBRICA_NIVEL n ON n.PK_TACTIVIDAD_RUBRICA_NIVEL = re.FK_TACTIVIDAD_RUBRICA_NIVEL
             WHERE re.FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante
               AND re.ACTIVE = TRUE AND c.FK_TACTIVIDAD = v_pk_tactividad AND c.ACTIVE = TRUE
            HAVING COUNT(*) > 0;

        WHEN 'LISTA_COTEJO' THEN
            SELECT jsonb_build_object(
                       'tipo', 'LISTA_COTEJO',
                       'resumen', COUNT(*) FILTER (WHERE ce.CUMPLIDO = 'S') || '/' || COUNT(*) || ' items',
                       'cumplidos', COUNT(*) FILTER (WHERE ce.CUMPLIDO = 'S'),
                       'total', COUNT(*),
                       'detalle', jsonb_agg(jsonb_build_object(
                                      'pkItem', i.PK_TACTIVIDAD_COTEJO_ITEM, 'item', i.DESCRIPCION,
                                      'cumplido', COALESCE(ce.CUMPLIDO, 'N') = 'S') ORDER BY i.ORDEN))
              INTO v_res
              FROM academico_test.TACTIVIDAD_COTEJO_ITEM i
              LEFT JOIN academico_test.TACTIVIDAD_COTEJO_EVALUACION ce
                     ON ce.FK_TACTIVIDAD_COTEJO_ITEM = i.PK_TACTIVIDAD_COTEJO_ITEM
                    AND ce.FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante AND ce.ACTIVE = TRUE
             WHERE i.FK_TACTIVIDAD = v_pk_tactividad AND i.ACTIVE = TRUE
            HAVING COUNT(ce.PK_TACTIVIDAD_COTEJO_EVAL) > 0;

        WHEN 'ESCALA_VALORACION' THEN
            -- V472: filas por-criterio ganan sobre la fila unica vieja --
            -- un resumen "Criterio 1: X · Criterio 2: Y" (1-based para
            -- pintar, aunque CRITERIO_INDEX guarde 0-based).
            SELECT jsonb_build_object(
                       'tipo', 'ESCALA_CRITERIOS',
                       'resumen', string_agg(
                                      'Criterio ' || (ce.CRITERIO_INDEX + 1) || ': ' ||
                                      COALESCE(n.ETIQUETA, n.DESCRIPCION, TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM ce.VALOR::TEXT))),
                                      ' · ' ORDER BY ce.CRITERIO_INDEX),
                       'detalle', jsonb_agg(jsonb_build_object(
                                      'criterioIndex', ce.CRITERIO_INDEX,
                                      'pkNivel', n.PK_TACTIVIDAD_ESCALA_NIVEL,
                                      'nivel', COALESCE(n.ETIQUETA, n.DESCRIPCION),
                                      'valor', ce.VALOR, 'valorMin', e.VALOR_MIN, 'valorMax', e.VALOR_MAX,
                                      'ponderacion', ce.PONDERACION) ORDER BY ce.CRITERIO_INDEX))
              INTO v_res
              FROM academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION ce
              JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = ce.FK_TACTIVIDAD_ESCALA
              LEFT JOIN academico_test.TACTIVIDAD_ESCALA_NIVEL n ON n.PK_TACTIVIDAD_ESCALA_NIVEL = ce.FK_TACTIVIDAD_ESCALA_NIVEL
             WHERE ce.FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante
               AND ce.ACTIVE = TRUE AND e.FK_TACTIVIDAD = v_pk_tactividad
            HAVING COUNT(*) > 0;

            IF v_res IS NULL THEN
                SELECT CASE WHEN ee.FK_TACTIVIDAD_ESCALA_NIVEL IS NOT NULL THEN
                           jsonb_build_object('tipo', 'ESCALA_CUALITATIVA',
                                              'resumen', COALESCE(n.ETIQUETA, n.DESCRIPCION),
                                              'pkNivel', n.PK_TACTIVIDAD_ESCALA_NIVEL,
                                              'nivel', COALESCE(n.ETIQUETA, n.DESCRIPCION),
                                              'ponderacion', ee.PONDERACION)
                       ELSE
                           jsonb_build_object('tipo', 'ESCALA_NUMERICA',
                                              'resumen', TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM ee.VALOR::TEXT)),
                                              'valor', ee.VALOR, 'valorMin', e.VALOR_MIN, 'valorMax', e.VALOR_MAX)
                       END
                  INTO v_res
                  FROM academico_test.TACTIVIDAD_ESCALA_EVALUACION ee
                  JOIN academico_test.TACTIVIDAD_ESCALA e ON e.PK_TACTIVIDAD_ESCALA = ee.FK_TACTIVIDAD_ESCALA
                  LEFT JOIN academico_test.TACTIVIDAD_ESCALA_NIVEL n ON n.PK_TACTIVIDAD_ESCALA_NIVEL = ee.FK_TACTIVIDAD_ESCALA_NIVEL
                 WHERE ee.FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante
                   AND ee.ACTIVE = TRUE AND e.FK_TACTIVIDAD = v_pk_tactividad
                 LIMIT 1;
            END IF;

        ELSE
            SELECT jsonb_build_object('tipo', 'OTRO',
                                      'resumen', n.CALIFICACION::TEXT || ' %',
                                      'porcentaje', n.CALIFICACION)
              INTO v_res
              FROM academico_test.TACTIVIDAD_NOTA n
             WHERE n.FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante
               AND n.ACTIVE = TRUE AND n.CALIFICACION IS NOT NULL;
    END CASE;

    RETURN v_res;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_resultado_instrumento(BIGINT)
    IS 'Resultado que el docente marco en el instrumento de la actividad para un estudiante, con etiquetas listas para pintar: {tipo, resumen, ...detalle}. RUBRICA: criterio: nivel por criterio; LISTA_COTEJO: cumplidos/total e items; ESCALA_CRITERIOS (V472): un valor por criterio general, gana sobre la fila unica; ESCALA cualitativa/numerica (fila unica, escalas de 0-1 criterio): el nivel o el valor digitado; OTRO con metodo configurado: igual que su metodo; OTRO libre: el porcentaje. NULL si no hay captura. No gatea permisos: helper de lectura para listados que ya gatearon. V469; ESCALA_CRITERIOS en V472.';
