-- ===========================================================================
-- V472 - Escala de valoracion: una nota por criterio general.
-- Quedan TACTIVIDAD_ESCALA_CRITERIO_EVALUACION y
-- fn_actividad_nota_calificar_escala_criterios.
-- fn_actividad_nota_calificar/_obtener viven en V473 y
-- fn_actividad_nota_resultado_instrumento en V477.
-- ===========================================================================


CREATE TABLE IF NOT EXISTS academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (
  PK_TAC_ESCALA_CRITERIO_EVAL BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  FK_TACTIVIDAD_ESCALA        BIGINT NOT NULL,
  FK_TACTIVIDAD_ESTUDIANTE    BIGINT NOT NULL,
  CRITERIO_INDEX              INTEGER NOT NULL,
  FK_TACTIVIDAD_ESCALA_NIVEL  BIGINT,
  VALOR                       NUMERIC(5,2),
  PONDERACION                 NUMERIC(5,2),
  CREATED_BY                  VARCHAR(120) NOT NULL,
  CREATED_AT                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MODIFIED_BY                 VARCHAR(120),
  MODIFIED_AT                 TIMESTAMP,
  ACTIVE                      BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_TAC_ESCALA_CRITERIO_EVAL PRIMARY KEY (PK_TAC_ESCALA_CRITERIO_EVAL),
  CONSTRAINT UN_TAC_ESCALA_CRITERIO_EVAL_1 UNIQUE (FK_TACTIVIDAD_ESTUDIANTE, CRITERIO_INDEX) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_1 FOREIGN KEY (FK_TACTIVIDAD_ESCALA) REFERENCES academico_test.TACTIVIDAD_ESCALA (PK_TACTIVIDAD_ESCALA) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_2 FOREIGN KEY (FK_TACTIVIDAD_ESTUDIANTE) REFERENCES academico_test.TACTIVIDAD_ESTUDIANTE (PK_TACTIVIDAD_ESTUDIANTE) ON DELETE CASCADE,
  CONSTRAINT FK_TAC_ESCALA_CRITERIO_EVAL_3 FOREIGN KEY (FK_TACTIVIDAD_ESCALA_NIVEL) REFERENCES academico_test.TACTIVIDAD_ESCALA_NIVEL (PK_TACTIVIDAD_ESCALA_NIVEL)
);

CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_1 ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (FK_TACTIVIDAD_ESCALA);

CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_2 ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (FK_TACTIVIDAD_ESTUDIANTE);

CREATE INDEX IF NOT EXISTS IDX_TAC_ESCALA_CRITERIO_EVAL_ACTIVE ON academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (PK_TAC_ESCALA_CRITERIO_EVAL) WHERE ACTIVE = true;

COMMENT ON TABLE academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
    IS 'Nota POR criterio general de una escala de valoracion, un estudiante puede tener varias (una por CRITERIO_INDEX -- posicion 0-based en TACTIVIDAD_ESCALA.CRITERIOS_GENERALES partido por coma). CUALITATIVA usa FK_TACTIVIDAD_ESCALA_NIVEL; NUMERICA usa VALOR; ambos comparten los mismos niveles/rango de TACTIVIDAD_ESCALA. La nota final de TACTIVIDAD_NOTA es el promedio simple de los % de cada fila. V472.';

COMMENT ON COLUMN academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION.CRITERIO_INDEX IS 'Posicion (0-based) del criterio dentro de CRITERIOS_GENERALES separado por coma -- no hay PK de criterio, CRITERIOS_GENERALES sigue siendo texto plano';

CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_calificar_escala_criterios(
    p_pk_usuario_solicitante   BIGINT,
    p_pk_tactividad_estudiante BIGINT,
    p_criterios                JSONB,
    p_fecha                    DATE DEFAULT CURRENT_DATE
)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $function$
DECLARE
    v_pk_tactividad     BIGINT;
    v_pk_nota           BIGINT;
    v_pk_escala         BIGINT;
    v_tipo_val          VARCHAR;
    v_min               NUMERIC(5,2);
    v_max               NUMERIC(5,2);
    v_criterios_generales VARCHAR;
    v_criterios_esperados INTEGER;
    v_elem              JSONB;
    v_criterio_index    INTEGER;
    v_pk_nivel          BIGINT;
    v_valor_numerico    NUMERIC(5,2);
    v_nivel_pond        NUMERIC(5,2);
    v_max_pond          NUMERIC(5,2);
    v_pct_item          NUMERIC(5,2);
    v_valor_final       NUMERIC(5,2);
    v_pond_final        NUMERIC(5,2);
    v_nivel_final       BIGINT;
    v_pk_fila_existente BIGINT;
    v_indices_vistos    INTEGER[] := ARRAY[]::INTEGER[];
    v_pct_final         NUMERIC(5,2);
BEGIN
    PERFORM academico_test.fn_planeador_assert_alcance(
        p_pk_usuario_solicitante, 'EDITAR', NULL, NULL, NULL,
        academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante)
    );

    v_pk_tactividad := academico_test.fn_actividad_estudiante_actividad(p_pk_tactividad_estudiante);
    PERFORM academico_test.fn_actividad_nota_asistencia_assert(p_pk_tactividad_estudiante, p_fecha);
    PERFORM academico_test.fn_actividad_instrumento_assert(v_pk_tactividad, 'ESCALA_VALORACION');

    SELECT e.PK_TACTIVIDAD_ESCALA, lv.VALOR, e.VALOR_MIN, e.VALOR_MAX, e.CRITERIOS_GENERALES
      INTO v_pk_escala, v_tipo_val, v_min, v_max, v_criterios_generales
      FROM academico_test.TACTIVIDAD_ESCALA e
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = e.FK_TLV_TIPO_ESCALA
     WHERE e.FK_TACTIVIDAD = v_pk_tactividad AND e.ACTIVE = TRUE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La actividad no tiene una escala de valoracion definida (use fn_actividad_escala_definir primero)'
            USING ERRCODE = '22023';
    END IF;

    IF p_criterios IS NULL OR jsonb_typeof(p_criterios) <> 'array' OR jsonb_array_length(p_criterios) = 0 THEN
        RAISE EXCEPTION 'criterios debe ser un array con al menos un elemento {criterioIndex, pkNivel|valorNumerico}'
            USING ERRCODE = '22023';
    END IF;

    -- Cuantos criterios generales tiene la escala -- se deriva del mismo
    -- texto separado por coma que ya usa el front para armar los inputs,
    -- no de un conteo mandado por el cliente (mismo espiritu que Rubrica:
    -- "se exige cubrir el set completo", pero el "completo" real vive del
    -- lado del servidor).
    v_criterios_esperados := GREATEST(
        COALESCE(array_length(string_to_array(NULLIF(TRIM(v_criterios_generales), ''), ','), 1), 1),
        1
    );

    IF jsonb_array_length(p_criterios) <> v_criterios_esperados THEN
        RAISE EXCEPTION 'La escala tiene % criterio(s) general(es) pero se calificaron % -- deben cubrirse todos',
            v_criterios_esperados, jsonb_array_length(p_criterios)
            USING ERRCODE = '22023';
    END IF;

    v_pk_nota := academico_test.fn_actividad_nota_get_or_create(p_pk_usuario_solicitante, p_pk_tactividad_estudiante);

    v_pct_final := 0;

    FOR v_elem IN SELECT * FROM jsonb_array_elements(p_criterios)
    LOOP
        v_criterio_index := (v_elem->>'criterioIndex')::INTEGER;
        v_pk_nivel        := (v_elem->>'pkNivel')::BIGINT;
        v_valor_numerico  := (v_elem->>'valorNumerico')::NUMERIC;

        IF v_criterio_index IS NULL OR v_criterio_index < 0 OR v_criterio_index >= v_criterios_esperados THEN
            RAISE EXCEPTION 'criterioIndex (%) fuera de rango: la escala tiene % criterio(s)',
                v_criterio_index, v_criterios_esperados
                USING ERRCODE = '22023';
        END IF;
        IF v_criterio_index = ANY(v_indices_vistos) THEN
            RAISE EXCEPTION 'criterioIndex % repetido' , v_criterio_index USING ERRCODE = '22023';
        END IF;
        v_indices_vistos := v_indices_vistos || v_criterio_index;

        IF (v_pk_nivel IS NOT NULL) = (v_valor_numerico IS NOT NULL) THEN
            RAISE EXCEPTION 'criterioIndex %: debe indicarse exactamente uno de pkNivel o valorNumerico',
                v_criterio_index USING ERRCODE = '22023';
        END IF;

        IF v_tipo_val = 'CUALITATIVA' THEN
            IF v_pk_nivel IS NULL THEN
                RAISE EXCEPTION 'criterioIndex %: la escala de esta actividad es CUALITATIVA, se requiere pkNivel',
                    v_criterio_index USING ERRCODE = '22023';
            END IF;

            SELECT PONDERACION INTO v_nivel_pond
              FROM academico_test.TACTIVIDAD_ESCALA_NIVEL
             WHERE PK_TACTIVIDAD_ESCALA_NIVEL = v_pk_nivel
               AND FK_TACTIVIDAD_ESCALA = v_pk_escala AND ACTIVE = TRUE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'criterioIndex %: el nivel % no pertenece a la escala de esta actividad',
                    v_criterio_index, v_pk_nivel USING ERRCODE = '22023';
            END IF;

            SELECT MAX(PONDERACION) INTO v_max_pond
              FROM academico_test.TACTIVIDAD_ESCALA_NIVEL
             WHERE FK_TACTIVIDAD_ESCALA = v_pk_escala AND ACTIVE = TRUE;

            v_pct_item    := ROUND(v_nivel_pond / NULLIF(v_max_pond, 0) * 100, 2);
            v_nivel_final := v_pk_nivel;
            v_valor_final := v_nivel_pond;
            v_pond_final  := v_nivel_pond;
        ELSE
            IF v_valor_numerico IS NULL THEN
                RAISE EXCEPTION 'criterioIndex %: la escala de esta actividad es NUMERICA, se requiere valorNumerico',
                    v_criterio_index USING ERRCODE = '22023';
            END IF;
            IF v_min IS NULL OR v_max IS NULL THEN
                RAISE EXCEPTION 'La escala NUMERICA de esta actividad no tiene valorMin/valorMax definidos'
                    USING ERRCODE = '22023';
            END IF;
            IF v_valor_numerico < v_min OR v_valor_numerico > v_max THEN
                RAISE EXCEPTION 'criterioIndex %: valorNumerico (%) debe estar entre % y %',
                    v_criterio_index, v_valor_numerico, v_min, v_max USING ERRCODE = '22023';
            END IF;

            v_pct_item    := ROUND(v_valor_numerico / NULLIF(v_max, 0) * 100, 2);
            v_nivel_final := NULL;
            v_valor_final := v_valor_numerico;
            v_pond_final  := NULL;
        END IF;

        v_pct_final := v_pct_final + v_pct_item;

        SELECT PK_TAC_ESCALA_CRITERIO_EVAL INTO v_pk_fila_existente
          FROM academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
         WHERE FK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante AND CRITERIO_INDEX = v_criterio_index;

        IF v_pk_fila_existente IS NULL THEN
            INSERT INTO academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (
                FK_TACTIVIDAD_ESCALA, FK_TACTIVIDAD_ESTUDIANTE, CRITERIO_INDEX,
                FK_TACTIVIDAD_ESCALA_NIVEL, VALOR, PONDERACION,
                CREATED_BY, CREATED_AT, ACTIVE
            ) VALUES (
                v_pk_escala, p_pk_tactividad_estudiante, v_criterio_index,
                v_nivel_final, v_valor_final, v_pond_final,
                p_pk_usuario_solicitante::VARCHAR, CURRENT_TIMESTAMP, TRUE
            );
        ELSE
            UPDATE academico_test.TACTIVIDAD_ESCALA_CRITERIO_EVALUACION
               SET FK_TACTIVIDAD_ESCALA_NIVEL = v_nivel_final,
                   VALOR                       = v_valor_final,
                   PONDERACION                 = v_pond_final,
                   ACTIVE                       = TRUE,
                   MODIFIED_BY                  = p_pk_usuario_solicitante::VARCHAR,
                   MODIFIED_AT                  = CURRENT_TIMESTAMP
             WHERE PK_TAC_ESCALA_CRITERIO_EVAL = v_pk_fila_existente;
        END IF;
    END LOOP;

    -- Promedio simple de los % de cada criterio -- misma logica que Rubrica.
    v_pct_final := ROUND(v_pct_final / v_criterios_esperados, 2);
    v_pct_final := academico_test.fn_actividad_nota_ajustar_por_criterio(v_pk_tactividad, v_pct_final);

    UPDATE academico_test.TACTIVIDAD_NOTA
       SET CALIFICACION = v_pct_final, CALIFICABLE = 'S',
           MODIFIED_BY = p_pk_usuario_solicitante::VARCHAR, MODIFIED_AT = CURRENT_TIMESTAMP
     WHERE PK_TACTIVIDAD_NOTA = v_pk_nota;

    PERFORM academico_test.fn_actividad_recuperacion_aplicar(
                p_pk_usuario_solicitante, p_pk_tactividad_estudiante);

    RETURN v_pct_final;
END;
$function$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_calificar_escala_criterios(BIGINT, BIGINT, JSONB, DATE)
    IS 'Califica UNA escala de valoracion con un valor POR criterio general: p_criterios = [{criterioIndex, pkNivel|valorNumerico}, ...], UNO por cada posicion de CRITERIOS_GENERALES separado por coma (se exige el set completo, igual que Rubrica). Por criterio: % = ponderacion del nivel / MAX ponderacion (CUALITATIVA) o valor / valorMax * 100 (NUMERICA, V469). Nota final = promedio simple de esos %. Upsert de TACTIVIDAD_ESCALA_CRITERIO_EVALUACION (una fila por estudiante+criterio_index) y de TACTIVIDAD_NOTA.CALIFICACION. Exige asistencia del dia. Aditiva: una escala con 0-1 criterio sigue usando fn_actividad_nota_calificar_escala de siempre. V472.';
