-- V496.18 - Aprobación del Coordinador (Reglas 55, 69, 70, 71, 75), capa 1 de 4:
-- helpers + validaciones. Catálogos TIPO/ESTADO_SOLICITUD_APROBACION,
-- TSOLICITUD_APROBACION y TINFORME_DESACTUALIZADO (auditadas), lecturas de
-- "cuándo se exige", sedes donde el usuario es Coordinador, valor vigente de
-- una recuperación y una validación por regla. Además el tope de recuperación
-- que rechaza en vez de recortar (Regla 31), aquí y no en V227 porque el DO de
-- V469 lo ejecuta al migrar. El redondeo (Regla 30) vive en V496.5.
-- Depende de: V22, V496.5 (redondeo), V137 (periodo por fecha),
-- V227/V239 (criterio y piso/tope), V283 (auditoría), V408.

SET search_path TO academico_test, public;

SELECT setval(pg_get_serial_sequence('academico_test.tlista_valor', 'pk_lista_valor'),
              GREATEST((SELECT COALESCE(MAX(PK_LISTA_VALOR), 0) FROM academico_test.TLISTA_VALOR), 1));

INSERT INTO academico_test.TLISTA_VALOR (CATEGORIA, NOMBRE, VALOR, CREATED_BY)
SELECT v.categoria, v.nombre, v.valor, 'V496.18_seed'
  FROM (VALUES
    ('TIPO_SOLICITUD_APROBACION', 'Recuperación - Habilitación/Nivelación', 'RECUPERACION_HABILITACION'),
    ('TIPO_SOLICITUD_APROBACION', 'Recuperación - Refuerzo', 'RECUPERACION_REFUERZO'),
    ('TIPO_SOLICITUD_APROBACION', 'Corrección de resultado', 'CORRECCION_RESULTADO'),
    ('TIPO_SOLICITUD_APROBACION', 'Corrección de asistencia', 'CORRECCION_ASISTENCIA'),
    ('ESTADO_SOLICITUD_APROBACION', 'Pendiente', 'PENDIENTE'),
    ('ESTADO_SOLICITUD_APROBACION', 'Aprobada', 'APROBADA'),
    ('ESTADO_SOLICITUD_APROBACION', 'Rechazada', 'RECHAZADA')
  ) AS v(categoria, nombre, valor)
 WHERE NOT EXISTS (SELECT 1 FROM academico_test.TLISTA_VALOR lv
                    WHERE lv.CATEGORIA = v.categoria AND lv.VALOR = v.valor);

CREATE TABLE IF NOT EXISTS academico_test.TSOLICITUD_APROBACION (
    PK_TSOLICITUD_APROBACION BIGINT GENERATED BY DEFAULT AS IDENTITY,
    FK_TLV_TIPO              BIGINT        NOT NULL,
    FK_TLV_ESTADO            BIGINT        NOT NULL,
    TABLA_OBJETO             VARCHAR(60)   NOT NULL,
    FK_OBJETO                BIGINT        NOT NULL,
    FK_TGRUPO                BIGINT        NOT NULL,
    FK_TASIGNATURA           BIGINT,
    FK_TPERIODO_EVALUACION   BIGINT,
    FK_TACTIVIDAD            BIGINT,
    VALOR_ANTERIOR           JSONB,
    VALOR_PROPUESTO          JSONB         NOT NULL,
    FK_TUSUARIO_SOLICITANTE  BIGINT,
    FK_TUSUARIO_APROBADOR    BIGINT,
    FECHA_SOLICITUD          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_RESOLUCION         TIMESTAMP,
    MOTIVO                   VARCHAR(1000),
    MOTIVO_RESOLUCION        VARCHAR(1000),
    CREATED_BY               VARCHAR(120)  NOT NULL,
    CREATED_AT               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY              VARCHAR(120),
    MODIFIED_AT              TIMESTAMP,
    ACTIVE                   BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TSOLICITUD_APROBACION PRIMARY KEY (PK_TSOLICITUD_APROBACION),
    CONSTRAINT FK_TSOLICITUD_APROBACION_1 FOREIGN KEY (FK_TLV_TIPO) REFERENCES academico_test.TLISTA_VALOR (PK_LISTA_VALOR),
    CONSTRAINT FK_TSOLICITUD_APROBACION_2 FOREIGN KEY (FK_TLV_ESTADO) REFERENCES academico_test.TLISTA_VALOR (PK_LISTA_VALOR),
    CONSTRAINT FK_TSOLICITUD_APROBACION_3 FOREIGN KEY (FK_TGRUPO) REFERENCES academico_test.TGRUPO (PK_TGRUPO),
    CONSTRAINT FK_TSOLICITUD_APROBACION_4 FOREIGN KEY (FK_TPERIODO_EVALUACION) REFERENCES academico_test.TPERIODO_EVALUACION (PK_TPERIODO_EVALUACION),
    CONSTRAINT FK_TSOLICITUD_APROBACION_5 FOREIGN KEY (FK_TUSUARIO_SOLICITANTE) REFERENCES academico_test.TUSUARIO (PK_TUSUARIO),
    CONSTRAINT FK_TSOLICITUD_APROBACION_6 FOREIGN KEY (FK_TUSUARIO_APROBADOR) REFERENCES academico_test.TUSUARIO (PK_TUSUARIO),
    CONSTRAINT CHK_TSOLICITUD_APROBACION_TABLA CHECK (TABLA_OBJETO IN ('TACTIVIDAD_ESTUDIANTE', 'TASISTENCIA'))
);

CREATE INDEX IF NOT EXISTS IDX_TSOLICITUD_APROBACION_OBJETO
    ON academico_test.TSOLICITUD_APROBACION (TABLA_OBJETO, FK_OBJETO, FK_TLV_TIPO) WHERE ACTIVE = TRUE;
CREATE INDEX IF NOT EXISTS IDX_TSOLICITUD_APROBACION_ESTADO
    ON academico_test.TSOLICITUD_APROBACION (FK_TLV_ESTADO, FK_TGRUPO) WHERE ACTIVE = TRUE;

COMMENT ON TABLE academico_test.TSOLICITUD_APROBACION
    IS 'Solicitud de aprobación del Coordinador para un cambio que no se aplica directo (Reglas 55, 69, 75). FK_OBJETO apunta a TABLA_OBJETO: TACTIVIDAD_ESTUDIANTE (recuperación y corrección de resultado) o TASISTENCIA. Mientras está PENDIENTE el valor vigente es VALOR_ANTERIOR (Regla 70). FK_TGRUPO es el ancla del alcance del aprobador.';

CREATE TABLE IF NOT EXISTS academico_test.TINFORME_DESACTUALIZADO (
    PK_TINFORME_DESACTUALIZADO BIGINT GENERATED BY DEFAULT AS IDENTITY,
    FK_TGRUPO                  BIGINT       NOT NULL,
    FK_TPERIODO_EVALUACION     BIGINT       NOT NULL,
    FK_TASIGNATURA             BIGINT,
    FK_TSOLICITUD_APROBACION   BIGINT       NOT NULL,
    CREATED_BY                 VARCHAR(120) NOT NULL,
    CREATED_AT                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY                VARCHAR(120),
    MODIFIED_AT                TIMESTAMP,
    ACTIVE                     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TINFORME_DESACTUALIZADO PRIMARY KEY (PK_TINFORME_DESACTUALIZADO),
    CONSTRAINT FK_TINFORME_DESACTUALIZADO_1 FOREIGN KEY (FK_TGRUPO) REFERENCES academico_test.TGRUPO (PK_TGRUPO),
    CONSTRAINT FK_TINFORME_DESACTUALIZADO_2 FOREIGN KEY (FK_TPERIODO_EVALUACION) REFERENCES academico_test.TPERIODO_EVALUACION (PK_TPERIODO_EVALUACION),
    CONSTRAINT FK_TINFORME_DESACTUALIZADO_3 FOREIGN KEY (FK_TSOLICITUD_APROBACION) REFERENCES academico_test.TSOLICITUD_APROBACION (PK_TSOLICITUD_APROBACION)
);

CREATE INDEX IF NOT EXISTS IDX_TINFORME_DESACTUALIZADO_GRUPO
    ON academico_test.TINFORME_DESACTUALIZADO (FK_TGRUPO, FK_TPERIODO_EVALUACION) WHERE ACTIVE = TRUE;

COMMENT ON TABLE academico_test.TINFORME_DESACTUALIZADO
    IS 'Regla 71: el informe del grupo y periodo ya se había emitido cuando una aprobación cambió un valor. ACTIVE = TRUE mientras no se reemita; el trigger sobre TINFORME_GUARDADO la apaga.';

SELECT academico_test.fn_cdc_asegurar_auditoria('academico_test', 'tsolicitud_aprobacion');
SELECT academico_test.fn_cdc_asegurar_auditoria('academico_test', 'tinforme_desactualizado');

-- ---------------------------------------------------------------------------
-- Catálogos
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_tlv_solicitud_tipo_pk(p_valor TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    -- plpgsql y no sql: una sql con FROM no se incrusta y se replanifica en
    -- cada llamada; aqui el plan queda en cache. Primera fila o NULL, como antes.
    RETURN (SELECT * FROM (
    SELECT PK_LISTA_VALOR FROM academico_test.TLISTA_VALOR
     WHERE CATEGORIA = 'TIPO_SOLICITUD_APROBACION' AND VALOR = upper(TRIM(p_valor)) AND ACTIVE = TRUE
     LIMIT 1
    ) q LIMIT 1);
END;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_tlv_solicitud_estado_pk(p_valor TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    -- plpgsql y no sql: una sql con FROM no se incrusta y se replanifica en
    -- cada llamada; aqui el plan queda en cache. Primera fila o NULL, como antes.
    RETURN (SELECT * FROM (
    SELECT PK_LISTA_VALOR FROM academico_test.TLISTA_VALOR
     WHERE CATEGORIA = 'ESTADO_SOLICITUD_APROBACION' AND VALOR = upper(TRIM(p_valor)) AND ACTIVE = TRUE
     LIMIT 1
    ) q LIMIT 1);
END;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_estado(p_pk BIGINT)
RETURNS VARCHAR
LANGUAGE sql
STABLE
AS $$
    SELECT lv.VALOR
      FROM academico_test.TSOLICITUD_APROBACION s
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = s.FK_TLV_ESTADO
     WHERE s.PK_TSOLICITUD_APROBACION = p_pk AND s.ACTIVE = TRUE;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_tipo(p_pk BIGINT)
RETURNS VARCHAR
LANGUAGE sql
STABLE
AS $$
    SELECT lv.VALOR
      FROM academico_test.TSOLICITUD_APROBACION s
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = s.FK_TLV_TIPO
     WHERE s.PK_TSOLICITUD_APROBACION = p_pk AND s.ACTIVE = TRUE;
$$;

-- ---------------------------------------------------------------------------
-- Estado del periodo de evaluación (catálogo ESTADOPERIODOEVALUACION)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_periodo_evaluacion_calificable(p_pk_tperiodo_evaluacion BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    -- VALOR '1' es "Calificable" (V339/V418); el nombre cubre un catálogo recodificado.
    SELECT lv.VALOR = '1' OR upper(TRIM(lv.NOMBRE)) = 'CALIFICABLE'
      FROM academico_test.TPERIODO_EVALUACION pe
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = pe.FK_TLV_ESTADO
     WHERE pe.PK_TPERIODO_EVALUACION = p_pk_tperiodo_evaluacion;
$$;

COMMENT ON FUNCTION academico_test.fn_periodo_evaluacion_calificable(BIGINT)
    IS 'TRUE si el periodo de evaluación está Calificable (Activo en el documento: Reglas 55, 75). NULL si el periodo no existe. La usan las reglas de "cuándo se exige aprobación".';

CREATE OR REPLACE FUNCTION academico_test.fn_periodo_evaluacion_admite_refuerzo(p_pk_tperiodo_evaluacion BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    -- "En Recuperaciones" es justamente el estado abierto para recuperar.
    SELECT academico_test.fn_periodo_evaluacion_calificable(pe.PK_TPERIODO_EVALUACION)
           OR upper(lv.NOMBRE) LIKE '%RECUPERACI%'
      FROM academico_test.TPERIODO_EVALUACION pe
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = pe.FK_TLV_ESTADO
     WHERE pe.PK_TPERIODO_EVALUACION = p_pk_tperiodo_evaluacion;
$$;

COMMENT ON FUNCTION academico_test.fn_periodo_evaluacion_admite_refuerzo(BIGINT)
    IS 'Regla 69: el periodo de la actividad original sigue vigente para un Refuerzo (Calificable o En Recuperaciones). NULL si el periodo no existe.';

-- ---------------------------------------------------------------------------
-- Cuándo se exige aprobación. Devuelven el TIPO, o NULL si se aplica directo.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_recuperacion_tipo_aprobacion(p_pk_tactividad_estudiante BIGINT)
RETURNS VARCHAR
LANGUAGE sql
STABLE
AS $$
    -- Habilitación = destino NOTA_FINAL, siempre (Regla 69); Refuerzo = destino
    -- ACTIVIDAD, solo si el periodo de la ORIGINAL ya no está vigente. Un
    -- Refuerzo sin periodo resoluble se aplica directo, como hasta ahora.
    SELECT CASE
             WHEN lv.VALOR = 'NOTA_FINAL' THEN 'RECUPERACION_HABILITACION'
             WHEN lv.VALOR = 'ACTIVIDAD'
              AND academico_test.fn_periodo_evaluacion_admite_refuerzo(
                      academico_test.fn_actividad_periodo_evaluacion(r.FK_TACTIVIDAD_RECUPERAR, ae.FK_TMATRICULA)) = FALSE
                  THEN 'RECUPERACION_REFUERZO'
           END
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      JOIN academico_test.TACTIVIDAD a ON a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD AND a.ES_RECUPERACION = 'S'
      JOIN academico_test.TACTIVIDAD_RECUPERACION r ON r.FK_TACTIVIDAD = a.PK_TACTIVIDAD AND r.ACTIVE = TRUE
      JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = r.FK_TLV_DESTINO_RECUPERACION
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_resultado_correccion_requiere_aprobacion(
    p_pk_tactividad_estudiante BIGINT,
    p_porcentaje               NUMERIC
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    -- Regla 55: solo CORREGIR un resultado ya capturado. La primera captura y
    -- las recuperaciones (que pasan por la Regla 69) no entran aquí.
    SELECT COALESCE(
             n.CALIFICACION IS NOT NULL
             AND p_porcentaje IS DISTINCT FROM n.CALIFICACION
             AND academico_test.fn_periodo_evaluacion_calificable(
                     academico_test.fn_actividad_periodo_evaluacion(ae.FK_TACTIVIDAD, ae.FK_TMATRICULA)) = FALSE,
             FALSE)
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      JOIN academico_test.TACTIVIDAD a ON a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD
      LEFT JOIN academico_test.TACTIVIDAD_NOTA n
             ON n.FK_TACTIVIDAD_ESTUDIANTE = ae.PK_TACTIVIDAD_ESTUDIANTE AND n.ACTIVE = TRUE
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante
       AND a.ES_RECUPERACION IS DISTINCT FROM 'S';
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_asistencia_fecha_requiere_aprobacion(p_fk_tgrupo BIGINT, p_fecha DATE)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    -- Regla 75: manda el periodo DE EVALUACIÓN de la fecha de la sesión. Un
    -- periodo que ya terminó por fechas también exige aprobación aunque siga
    -- Calificable. NULL si la fecha no cae en ninguno: bloqueo plano (V136).
    SELECT NOT academico_test.fn_periodo_evaluacion_calificable(pe.PK_TPERIODO_EVALUACION)
           OR pe.FECHA_FIN < CURRENT_DATE
      FROM academico_test.TPERIODO_EVALUACION pe
     WHERE pe.PK_TPERIODO_EVALUACION = academico_test.fn_asistencia_periodo_eval(p_fk_tgrupo, p_fecha);
$$;

COMMENT ON FUNCTION academico_test.fn_asistencia_fecha_requiere_aprobacion(BIGINT, DATE)
    IS 'TRUE si escribir asistencia de esa fecha exige aprobación del Coordinador (Regla 75: su periodo de evaluación no es Calificable o ya terminó por fechas); NULL si la fecha no cae en ningún periodo. La usan fn_asistencia_correccion_requiere_aprobacion y fn_asistencia_registrar_bulk.';

CREATE OR REPLACE FUNCTION academico_test.fn_asistencia_correccion_requiere_aprobacion(p_pk_tasistencia BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT academico_test.fn_asistencia_fecha_requiere_aprobacion(m.FK_TGRUPO, a.FECHA)
      FROM academico_test.TASISTENCIA a
      JOIN academico_test.TMATRICULA m ON m.PK_TMATRICULA = a.FK_TMATRICULA
     WHERE a.PK_TASISTENCIA = p_pk_tasistencia;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_asistencia_solicitud_pendiente(p_pk_tasistencia BIGINT)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT s.PK_TSOLICITUD_APROBACION
      FROM academico_test.TSOLICITUD_APROBACION s
     WHERE s.TABLA_OBJETO = 'TASISTENCIA' AND s.FK_OBJETO = p_pk_tasistencia
       AND s.FK_TLV_TIPO = academico_test.fn_tlv_solicitud_tipo_pk('CORRECCION_ASISTENCIA')
       AND s.FK_TLV_ESTADO = academico_test.fn_tlv_solicitud_estado_pk('PENDIENTE')
       AND s.ACTIVE = TRUE
     LIMIT 1;
$$;

COMMENT ON FUNCTION academico_test.fn_asistencia_solicitud_pendiente(BIGINT)
    IS 'PK de la solicitud CORRECCION_ASISTENCIA pendiente sobre un registro de TASISTENCIA (activo, o el inactivo que espera una captura tardía), o NULL. La usan el padrón de la sesión, Seguimiento y registrar.';

-- Regla 70: una recuperación ya aprobada con ESA nota se reconsolida sin pedir
-- de nuevo (cambió la base, no lo aprobado); otra nota vuelve a pedirla.
CREATE OR REPLACE FUNCTION academico_test.fn_recuperacion_aprobada_vigente(
    p_pk_tactividad_estudiante BIGINT,
    p_tipo                     VARCHAR,
    p_nota_recuperacion        NUMERIC
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE((
        SELECT lv.VALOR = 'APROBADA'
               AND (s.VALOR_PROPUESTO->>'notaRecuperacion')::NUMERIC = p_nota_recuperacion
          FROM academico_test.TSOLICITUD_APROBACION s
          JOIN academico_test.TLISTA_VALOR lv ON lv.PK_LISTA_VALOR = s.FK_TLV_ESTADO
         WHERE s.TABLA_OBJETO = 'TACTIVIDAD_ESTUDIANTE'
           AND s.FK_OBJETO = p_pk_tactividad_estudiante
           AND s.FK_TLV_TIPO = academico_test.fn_tlv_solicitud_tipo_pk(p_tipo)
           AND s.ACTIVE = TRUE
         ORDER BY s.FECHA_SOLICITUD DESC, s.PK_TSOLICITUD_APROBACION DESC
         LIMIT 1), FALSE);
$$;

-- ---------------------------------------------------------------------------
-- Validaciones de la solicitud (una por regla)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_validar_existe(p_pk BIGINT)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM academico_test.TSOLICITUD_APROBACION
                    WHERE PK_TSOLICITUD_APROBACION = p_pk AND ACTIVE = TRUE) THEN
        RAISE EXCEPTION 'La solicitud de aprobación % no existe', p_pk USING ERRCODE = 'P0002';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_validar_pendiente(p_pk BIGINT)
RETURNS VOID
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_estado VARCHAR := academico_test.fn_solicitud_aprobacion_estado(p_pk);
BEGIN
    IF v_estado IS DISTINCT FROM 'PENDIENTE' THEN
        RAISE EXCEPTION 'Esta solicitud ya fue %, así que no se puede resolver de nuevo.', COALESCE(lower(v_estado), 'resuelta')
            USING ERRCODE = '22023';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_validar_motivo(p_motivo TEXT, p_obligatorio BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF p_obligatorio AND NULLIF(TRIM(p_motivo), '') IS NULL THEN
        RAISE EXCEPTION 'Indique el motivo del rechazo' USING ERRCODE = '22023';
    END IF;
    IF length(p_motivo) > 1000 THEN
        RAISE EXCEPTION 'El motivo admite hasta 1000 caracteres (tiene %)', length(p_motivo) USING ERRCODE = '22023';
    END IF;
END;
$$;

-- Rol por TROL.CODIGO (como V489): el Coordinador no tiene CATEGORIA_ROL propia.
CREATE OR REPLACE FUNCTION academico_test.fn_usuario_sedes_por_rol(p_pk_tusuario BIGINT, p_codigos VARCHAR[])
RETURNS SETOF BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT DISTINCT su.FK_TSEDE
      FROM academico_test.TSEDE_USUARIO su
      JOIN academico_test.TSEDE s ON s.PK_TSEDE = su.FK_TSEDE AND s.ACTIVE = TRUE
      JOIN academico_test.TROL r  ON r.PK_TROL  = su.FK_TROL
     WHERE su.FK_TUSUARIO = p_pk_tusuario
       AND su.ACTIVE = TRUE
       AND UPPER(TRIM(r.CODIGO)) = ANY (p_codigos);
$$;

COMMENT ON FUNCTION academico_test.fn_usuario_sedes_por_rol(BIGINT, VARCHAR[])
    IS 'Sedes activas donde el usuario tiene un TSEDE_USUARIO activo con alguno de los roles p_codigos (TROL.CODIGO en mayúsculas). Base de fn_usuario_sedes_coordinador y fn_usuario_ee_por_rol.';

-- El Rector también se reconoce por el puntero del establecimiento, sin TSEDE_USUARIO.
CREATE OR REPLACE FUNCTION academico_test.fn_usuario_ee_por_rol(p_pk_tusuario BIGINT, p_codigos VARCHAR[])
RETURNS SETOF BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT s.FK_TESTABLECIMIENTO
      FROM academico_test.TSEDE s
     WHERE s.PK_TSEDE IN (SELECT academico_test.fn_usuario_sedes_por_rol(p_pk_tusuario, p_codigos))
    UNION
    SELECT e.PK_ESTABLECIMIENTO
      FROM academico_test.TESTABLECIMIENTO e
      JOIN academico_test.TFUNCIONARIO f ON f.PK_TFUNCIONARIO = e.FK_TFUNCIONARIO_RECTOR
     WHERE 'RECTOR' = ANY (p_codigos)
       AND e.ACTIVE = TRUE AND f.ACTIVE = TRUE AND f.FK_TUSUARIO = p_pk_tusuario;
$$;

COMMENT ON FUNCTION academico_test.fn_usuario_ee_por_rol(BIGINT, VARCHAR[])
    IS 'Establecimientos donde el usuario tiene alguno de los roles p_codigos en una sede (fn_usuario_sedes_por_rol); si p_codigos incluye RECTOR, también los que tiene por FK_TFUNCIONARIO_RECTOR.';

CREATE OR REPLACE FUNCTION academico_test.fn_usuario_sedes_coordinador(p_pk_tusuario BIGINT)
RETURNS SETOF BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT academico_test.fn_usuario_sedes_por_rol(p_pk_tusuario, ARRAY['COORDINADOR']::VARCHAR[]);
$$;

COMMENT ON FUNCTION academico_test.fn_usuario_sedes_coordinador(BIGINT)
    IS 'Sedes activas donde el usuario es Coordinador (fn_usuario_sedes_por_rol). La usa fn_mi_establecimiento_para_auditoria (claim est del JWT).';

-- Lista única de quién aprueba: para sumar o quitar un rol se edita solo esto
-- (y su role_query en V496.21).
CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_roles_sede()
RETURNS VARCHAR[]
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT ARRAY['COORDINADOR']::VARCHAR[];
$$;

COMMENT ON FUNCTION academico_test.fn_solicitud_aprobacion_roles_sede()
    IS 'TROL.CODIGO de los roles que resuelven solicitudes de aprobación solo en la sede donde los tienen.';

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_aprobacion_roles_ee()
RETURNS VARCHAR[]
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT ARRAY['RECTOR', 'JEFE_SISTEMA_ESTABLECIMIENTO', 'AUXILIAR_ADMINISTRATIVO']::VARCHAR[];
$$;

COMMENT ON FUNCTION academico_test.fn_solicitud_aprobacion_roles_ee()
    IS 'TROL.CODIGO de los roles que resuelven solicitudes de aprobación en todas las sedes de su establecimiento.';

CREATE OR REPLACE FUNCTION academico_test.fn_usuario_sedes_aprobador(p_pk_tusuario BIGINT)
RETURNS SETOF BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT academico_test.fn_usuario_sedes_por_rol(p_pk_tusuario, academico_test.fn_solicitud_aprobacion_roles_sede())
    UNION
    SELECT s.PK_TSEDE
      FROM academico_test.TSEDE s
     WHERE s.ACTIVE = TRUE
       AND s.FK_TESTABLECIMIENTO IN (
           SELECT academico_test.fn_usuario_ee_por_rol(p_pk_tusuario, academico_test.fn_solicitud_aprobacion_roles_ee()));
$$;

COMMENT ON FUNCTION academico_test.fn_usuario_sedes_aprobador(BIGINT)
    IS 'Sedes activas donde el usuario resuelve solicitudes de aprobación: donde tiene un rol de fn_solicitud_aprobacion_roles_sede, y todas las de los establecimientos donde tiene uno de fn_solicitud_aprobacion_roles_ee. La usa fn_usuario_es_aprobador_sede.';

CREATE OR REPLACE FUNCTION academico_test.fn_solicitud_valor_vigente_recuperacion(
    p_pk_tactividad_estudiante BIGINT,
    p_tipo                     VARCHAR
)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
    SELECT CASE WHEN p_tipo = 'RECUPERACION_REFUERZO' THEN
               (SELECT jsonb_build_object('calificacion', n.CALIFICACION, 'definitiva', n.DEFINITIVA)
                  FROM academico_test.TACTIVIDAD_ESTUDIANTE o
                  JOIN academico_test.TACTIVIDAD_NOTA n ON n.FK_TACTIVIDAD_ESTUDIANTE = o.PK_TACTIVIDAD_ESTUDIANTE AND n.ACTIVE = TRUE
                 WHERE o.FK_TACTIVIDAD = r.FK_TACTIVIDAD_RECUPERAR AND o.FK_TMATRICULA = ae.FK_TMATRICULA AND o.ACTIVE = TRUE)
           ELSE
               (SELECT jsonb_build_object('calificacion', sn.CALIFICACION, 'definitiva', sn.DEFINITIVA)
                  FROM academico_test.TASIGNATURA_NOTA sn
                 WHERE sn.FK_TMATRICULA = ae.FK_TMATRICULA AND sn.FK_TASIGNATURA = a.FK_TASIGNATURA AND sn.ACTIVE = TRUE
                   AND sn.FK_TPERIODO_EVALUACION = academico_test.fn_actividad_periodo_evaluacion(a.PK_TACTIVIDAD, ae.FK_TMATRICULA))
           END
      FROM academico_test.TACTIVIDAD_ESTUDIANTE ae
      JOIN academico_test.TACTIVIDAD a ON a.PK_TACTIVIDAD = ae.FK_TACTIVIDAD
      JOIN academico_test.TACTIVIDAD_RECUPERACION r ON r.FK_TACTIVIDAD = a.PK_TACTIVIDAD AND r.ACTIVE = TRUE
     WHERE ae.PK_TACTIVIDAD_ESTUDIANTE = p_pk_tactividad_estudiante;
$$;

COMMENT ON FUNCTION academico_test.fn_solicitud_valor_vigente_recuperacion(BIGINT, VARCHAR)
    IS 'Regla 70: valor que conserva el destino mientras la solicitud de recuperación está pendiente, {calificacion, definitiva}. RECUPERACION_REFUERZO: la nota del estudiante en la actividad original; otro tipo (Habilitación): su TASIGNATURA_NOTA del periodo de la actividad. NULL si no hay nota vigente. La usa fn_actividad_recuperacion_consolidar al abrir la solicitud.';

-- ---------------------------------------------------------------------------
-- Regla 31: el tope de recuperación rechaza; antes recortaba con LEAST.
-- Cuerpo de V227 con ese único cambio.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION academico_test.fn_actividad_nota_ajustar_por_criterio(
    p_pk_tactividad BIGINT,
    p_valor         NUMERIC
)
RETURNS NUMERIC
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_fk_tgrado        BIGINT;
    v_fk_tasignatura   BIGINT;
    v_es_recuperacion  CHAR(1);
    v_pk_criterio      BIGINT;
    v_piso             NUMERIC;
    v_tope             NUMERIC;
    v_valor            NUMERIC := p_valor;
BEGIN
    IF v_valor IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT a.FK_TASIGNATURA, a.ES_RECUPERACION
      INTO v_fk_tasignatura, v_es_recuperacion
      FROM academico_test.TACTIVIDAD a
     WHERE a.PK_TACTIVIDAD = p_pk_tactividad;

    v_fk_tgrado := academico_test.fn_actividad_grado_resolver(p_pk_tactividad);
    IF v_fk_tgrado IS NULL OR v_fk_tasignatura IS NULL THEN
        RETURN v_valor;
    END IF;

    v_pk_criterio := academico_test.fn_asignatura_criterio_evaluacion_vigente(v_fk_tasignatura, v_fk_tgrado);
    IF v_pk_criterio IS NULL THEN
        RETURN v_valor;
    END IF;

    IF v_es_recuperacion = 'S' THEN
        v_tope := academico_test.fn_criterio_evaluacion_porcentaje_maximo_recuperacion(v_pk_criterio);
        IF v_tope IS NOT NULL AND v_valor > v_tope THEN
            RAISE EXCEPTION 'La nota de recuperación de % (% %%) supera la nota máxima de recuperación del colegio (% %%)',
                academico_test.fn_actividad_etiqueta(p_pk_tactividad), round(v_valor, 2), v_tope
                USING ERRCODE = '22023';
        END IF;
    END IF;

    -- El piso va después: levanta también una recuperación.
    v_piso := academico_test.fn_criterio_evaluacion_porcentaje_inicial(v_pk_criterio);
    IF v_piso IS NOT NULL THEN
        v_valor := GREATEST(v_valor, v_piso);
    END IF;

    RETURN v_valor;
END;
$$;

COMMENT ON FUNCTION academico_test.fn_actividad_nota_ajustar_por_criterio(BIGINT, NUMERIC)
    IS 'Punto único de los dos límites de TCRITERIO_EVALUACION sobre una calificación (porcentaje 0-100). Regla 31: en una actividad de recuperación, un valor por encima de PORCENTAJE_MAXIMO_RECUPERACION se RECHAZA con 22023 (antes se recortaba). Después aplica el piso PORCENTAJE_INICIAL_CALIF a cualquier actividad. Sin grado, asignatura o criterio devuelve el valor intacto; NULL entra y sale NULL. No redondea. La usan los _interno de calificación (V496.6), el recálculo de V469 y la consolidación de la recuperación, que recorta antes la definitiva combinada para que el rechazo solo aplique a lo que digita el docente.';
