-- ===========================================================================
-- V514 - COMMENT de las funciones de informes cuyas migraciones de origen
-- (V334, V337, V338) se recortaron o borraron por tener el cuerpo obsoleto.
--
-- Las reescrituras posteriores (V428, V491) no traen COMMENT, asi que el
-- texto vivo seguia siendo el de V334/V337/V338; se copia literal.
--
-- Depende de: V428 (fn_informe_estudiante_asignaturas), V491 (alertas).
-- ===========================================================================

COMMENT ON FUNCTION academico_test.fn_informe_estudiante_asignaturas(BIGINT, BIGINT, BIGINT[], BOOLEAN)
    IS 'La grilla NUMERICA del informe para un estudiante: una fila por (asignatura, periodo de evaluacion) de los periodos pedidos (NULL o vacio = todos los del periodo academico de su matricula). Devuelve LAS DOS notas a la vez, que es lo que la vista necesita para pintar gris sobre negro: NOTA_GUARDADA es TASIGNATURA_NOTA.DEFINITIVA (el consolidado) y NOTA_PROYECTADA se recalcula siempre desde las actividades con fn_asignatura_definitiva_proyectada_periodo. Ya NO devuelve la observacion de la IA: la llevaba mientras el resumen era por asignatura, y al pasar a ser del estudiante y el periodo (V330) dejo de tener lugar en una grilla por asignatura -- vive en fn_informe_grupo_listar, donde el grano coincide. ESTADO_NOTA es el contrato con el front: sin_nota / proyectada (gris) / guardada (negro) / cambio_propuesto (negro + gris). cambio_propuesto es el docente que califico despues de consolidar el periodo, y por eso NO se creo ninguna tabla de "notas pendientes de aprobar": el docente nunca deja de escribir en TACTIVIDAD_NOTA, el consolidado esta en TASIGNATURA_NOTA, y la propuesta es la diferencia entre recalcular y lo guardado. INCLUYE UN CASO QUE ANTES SE ESCAPABA: si hay nota guardada y la proyectada pasa a NULL -- el docente dio de baja las actividades que la sustentaban -- eso tambien es cambio_propuesto, con NOTA_PROYECTADA en NULL y la propuesta siendo "ya no hay nota"; la version anterior lo reportaba como guardada y la bandera del listado no se encendia, de modo que el cambio pasaba en silencio. CALIFICADO_POR y CALIFICADO_EN dicen quien toco por ultima vez las notas de esa asignatura en ese periodo, desde TACTIVIDAD_NOTA.MODIFIED_BY/MODIFIED_AT; el join es defensivo porque MODIFIED_BY es VARCHAR sin FK y otros procesos escriben ahi valores que no son un id, asi que solo se resuelve cuando es numerico y la fecha se devuelve resuelva o no. p_solo_cambios reduce la salida a las filas con cambio propuesto. Lo cualitativo no se fuerza a numero: NOTA_HOMOLOGADA y la valoracion salen de fn_nota_homologar, que decide por (asignatura, grado) si el colegio califica con numero (CINCO/DIEZ/CIEN) o con valoracion (LITERAL/SIMBOLO/CARITA); ES_NUMERICO se devuelve explicito. APROBADA es NULL (desconocida) cuando el grado no tiene DESEMPENHO_MINIMO configurado, nunca FALSE. El universo de asignaturas son las que tienen nota guardada o actividades asignadas -- no el plan de estudios, que llenaria el boletin de filas vacias por configuracion incompleta. En preescolar devolvera filas en NULL o ninguna, y es correcto: alli el informe se arma con TESTUDIANTE_PERIODO_OBSERVACION. Gate: INFORMES/VER.';

COMMENT ON FUNCTION academico_test.fn_informe_cambios_pendientes(BIGINT, BIGINT[], BIGINT[])
    IS 'La alerta NARANJA del modulo de informes -- "docentes con cambios pendientes de aprobacion". Devuelve, en los grupos y periodos seleccionados, una fila por (grupo, asignatura, docente) con cuantos estudiantes quedaron afectados y cuando fue el ultimo cambio: el boton de la alerta muestra el total, el encabezado del panel cuenta los grupos distintos, y cada tarjeta lleva docente, asignatura, grupo y las tres FK que el boton "Ir" necesita para armar la ruta a la planilla. NO SALE DEL LISTADO por dos razones independientes: el grano es otro -- el listado es por (estudiante, periodo) y esto por (grupo, asignatura, docente) --, y el alcance tambien, porque la pantalla permite varios grupos en pestanas y la alerta habla de todos ellos mientras el listado es de uno solo; por eso p_fk_tgrupos es un ARREGLO, igual que en la alerta roja (V338). El cambio se detecta por COMPARACION, reutilizando fn_informe_estudiante_asignaturas con p_solo_cambios en vez de reimplementar la logica, de modo que la alerta no pueda decir 5 cambios mientras la tabla muestra 4; y solo cuentan las asignaturas YA CONSOLIDADAS, porque si el periodo nunca se guardo no hay nada que aprobar -- la nota simplemente aun no se congelo, que es el flujo normal y no una alerta. EL DOCENTE SALE DE TDOCENTE_ASIGNATURA, el asignado a esa asignatura en ese grupo. Una version anterior resolvia primero por TACTIVIDAD_NOTA.MODIFIED_BY (quien realmente digito) y solo caia a la asignacion si eso fallaba: era mas riguroso y peor, porque en la practica no califica actividades de una asignatura alguien distinto de su docente, asi que ese camino casi nunca aportaba algo distinto y a cambio metia una dependencia fragil -- MODIFIED_BY es VARCHAR sin FK donde otros procesos escriben migracion, V330 o un correo -- que obligaba a un JOIN defensivo con el guard dentro de un CASE para no reventar con 22P02. Ademas la alerta no existe para senalar culpables sino para LLEVAR A LA PLANILLA, y la planilla es de la asignatura: el destino correcto del boton siempre es el docente asignado. La FECHA del ultimo cambio si se sigue tomando de TACTIVIDAD_NOTA, porque no tiene sustituto y no depende de resolver a nadie. Gate: INFORMES/VER, verificado una vez por grupo y ANTES de leer nada -- un grupo fuera de alcance hace fallar toda la llamada con 42501 en vez de devolver una alerta incompleta que se ve completa.';

COMMENT ON FUNCTION academico_test.fn_informe_planillas_pendientes(BIGINT, BIGINT[], BIGINT[])
    IS 'La alerta ROJA del modulo de informes -- "docentes con planillas pendientes de calificar". Devuelve, en los grupos y periodos seleccionados, una fila por (grupo, asignatura, periodo) donde NO hay NADA registrado, con el docente al que hay que ir a buscar y las FK que el boton "Ir" necesita para armar la ruta a la planilla. Es la gemela de fn_informe_cambios_pendientes (V337) y comparte firma a proposito -- mismo arreglo de grupos, mismos periodos -- para que el front trate las dos alertas igual; la diferencia es que aquella busca cambios DESPUES de consolidar y esta busca ausencia de calificacion. EL GRANO INCLUYE EL PERIODO, a diferencia de la naranja: un cambio es un cambio se haya hecho cuando sea, pero "no califico el primer periodo" y "no califico el segundo" son dos planillas pendientes distintas, y colapsarlas haria mentir al conteo del boton. CUENTA COMO YA CALIFICO que exista al menos una TACTIVIDAD_NOTA activa del periodo, de una actividad activa de esa asignatura, ligada a una matricula de ese grupo, con CALIFICACION, DEFINITIVA u OBSERVACION: la observacion cuenta igual que la nota, y eso es lo que hace que sirva en preescolar, donde el docente no pone numeros sino comentarios por actividad (guardados con CALIFICABLE=N) -- mirar solo CALIFICACION habria reportado como morosos a todos esos docentes. El vinculo con el grupo se hace por TACTIVIDAD_ESTUDIANTE -> TMATRICULA -> FK_TGRUPO y no por TACTIVIDAD.FK_TGRUPO, que es NULLABLE y por lo tanto no sirve para decidir a que grupo pertenece el trabajo. EL UNIVERSO SON LAS ASIGNACIONES (TDOCENTE_ASIGNATURA del mismo periodo academico), no las asignaturas, que es lo correcto para una alerta que habla de docentes: sin asignacion no hay a quien mostrar ni a donde llevar el boton. Consecuencia a conocer: una asignatura del grupo SIN docente asignado no aparece aunque este igual de vacia -- eso es falta de asignacion academica, no de calificacion, y mezclarlo dejaria la tarjeta sin que decir. ACTIVIDADES distingue dos situaciones que la alerta trata igual pero el colegio no: 0 significa que el docente ni siquiera armo las actividades; mayor que 0, que las armo y no las califico. Se devuelve UN docente -- la asignacion mas reciente -- y tambien cuantos hay, porque en el servidor hay 397 combinaciones (grupo, asignatura) con mas de un docente activo (374 con dos, 22 con tres, una con cuatro); se emite una fila por PLANILLA y no por docente para que el conteo del boton siga siendo "planillas pendientes" y no se infle, y docentes_asignados mayor que 1 avisa que se comparte. Gate: INFORMES/VER, verificado una vez por grupo y ANTES de leer nada.';
