-- ===========================================================================
-- V516 - COMMENT de funciones cuyas migraciones de origen (V52, V53, V274,
-- V435, V474) se recortaron por tener el cuerpo obsoleto.
--
-- Las reescrituras posteriores no traen COMMENT, asi que el texto vivo seguia
-- siendo el de la migracion original; se copia literal.
-- ===========================================================================

COMMENT ON FUNCTION academico_test.fn_sed_crear(
    BIGINT, VARCHAR, VARCHAR, BIGINT, BIGINT,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR,
    VARCHAR
)
    IS 'REV4: crea una TSEDE para un TESTABLECIMIENTO activo. CODIGO/NOMBRE/FK_TLV_ZONA/p_fk_establecimiento son obligatorios (p_fk_establecimiento sin DEFAULT en la firma). El select de EE del front ahora se muestra siempre en el alta, para cualquier rol -- ya no se intenta resolver "el unico EE" del solicitante (fn_resolver_establecimiento_unico, retirado de esta funcion): ese fallback se rompia si el solicitante administraba 2+ EE a la vez. Si llega NULL => 22023 (o 42501 si ademas no es super-admin, el gate corre antes que la validacion de obligatoriedad). CONSECUTIVO se calcula automaticamente (MAX+1, padded a 2 digitos, solo entre sedes activas del mismo EE). Campos NOT NULL del DDL no obligatorios a nivel API se persisten como vacio si llegan nulos. Gate de autorizacion (CU-86e2w4xdt): una sola llamada a fn_assert_permiso_seccion(solicitante, ''SEDES_EDUCATIVAS'', ''CREAR'', EE) (helpers de V29). Ya no hay listas de FK_TROL: (0) bypass SUPER_ADMIN por categoria de rol; (1) capability -- TROL_MENU debe conceder CREAR sobre el menu SEDES_EDUCATIVAS y TUSUARIO_ROL_PERMISO no habersela recortado al usuario (fn_usuario_permisos_menu, V185); sin fila TROL_MENU => 42501 de capability; (2) scope sobre el EE recibido -- los roles de categoria territorial alcanzan cualquier EE y los de categoria establecimiento (rector, jefe de sistema, auxiliar) solo los EE de fn_usuario_ee_accesibles, que incluye los punteros FK_TFUNCIONARIO_RECTOR / FK_TFUNCIONARIO_SECRETARIA ademas de TSEDE_USUARIO; si no alcanza => 42501 con mensaje distinto al de capability. REV4: ademas, si el EE ya tiene rector y/o secretaria asignados, se les crea su permiso por defecto (rol 7/9, jornada "Completa", predeterminado=0) en la sede recien creada -- mantiene el invariante "rector/secretaria tiene permiso en TODAS las sedes de su EE" sin importar cuando se cree cada sede. fn_est_crear delega aqui para su sede por defecto, asi que este mismo comportamiento aplica ahi tambien. p_pk_usuario_solicitante va al inicio (obligatorio, mismo patron que V52 y V53).';

COMMENT ON FUNCTION academico_test.fn_sed_actualizar(
    BIGINT,
    BIGINT,
    VARCHAR, VARCHAR, BIGINT,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR,
    VARCHAR
)
    IS 'Actualizacion parcial (PATCH) de una TSEDE activa. Solo se modifican las columnas cuyos parametros llegaron con valor (NULL = no cambia). CODIGO/NOMBRE validan unicidad contra otras sedes activas (NOMBRE acotado al mismo EE por U_TSEDE_1). FK_TESTABLECIMIENTO, CONSECUTIVO, CREATED_BY/AT y ACTIVE son inmutables aqui. PATCH vacio no toca MODIFIED_BY/MODIFIED_AT. Gate de autorizacion (CU-86e2w4xdt): una sola llamada a fn_assert_permiso_seccion(solicitante, ''SEDES_EDUCATIVAS'', ''EDITAR'', EE de la sede, p_pk_sede) (helpers de V29), en vez del gate compuesto por listas de FK_TROL. (0) bypass SUPER_ADMIN; (1) capability -- TROL_MENU debe conceder EDITAR sobre SEDES_EDUCATIVAS (SOLO_LECTURA=''SI'' => 42501) y TUSUARIO_ROL_PERMISO no haberlo recortado; (2) scope -- categoria territorial alcanza cualquier EE; categoria establecimiento (rector / jefe de sistema / auxiliar, y los punteros FK_TFUNCIONARIO_RECTOR y FK_TFUNCIONARIO_SECRETARIA) solo los EE de fn_usuario_ee_accesibles. Ambos fallos son 42501, con mensajes distintos. El gate corre despues del P0002 de existencia y antes del 22023 de sede inactiva.';

COMMENT ON FUNCTION academico_test.fn_sed_soft_delete_bulk(BIGINT, BIGINT[])
    IS 'REV: baja logica en lote de sedes, una fila (pk_sede, status) por PK -- cada uno en su propio savepoint via fn_sed_soft_delete, asi que un fallo en uno no aborta ni deshace el resto (antes era todo-o-nada, devolvia un solo total_procesados). status: eliminado | error:no_encontrado (P0002) | error:sin_permiso (42501) | error:ya_inactivo (22023) | error:<mensaje> para cualquier otra excepcion. Mismo patron que fn_fun_baja_establecimiento_bulk.';

COMMENT ON FUNCTION academico_test.fn_sed_soft_delete(BIGINT, BIGINT)
    IS 'Baja logica en cascada: marca ACTIVE=FALSE en TSEDE, en sus TSEDE_USUARIO y en sus TSEDE_NIVEL. No afecta TPERIODO_ACADEMICO (modulo externo), TINF_*, TSEDE_CONVENIO (CASCADE duro en DDL), TARCHIVO ni TUSUARIO_ROL_PERMISO (ver alcance en cuerpo de la funcion). fn_est_soft_delete (V53) YA delega aqui para la cascade por EE. Solo afecta filas activas. Gate de autorizacion (CU-86e2w4xdt): una sola llamada a fn_assert_permiso_seccion(solicitante, ''SEDES_EDUCATIVAS'', ''ELIMINAR'', EE de la sede, p_pk_sede) (helpers de V29), en vez del gate compuesto por listas de FK_TROL. (0) bypass SUPER_ADMIN; (1) capability -- TROL_MENU debe conceder ELIMINAR sobre SEDES_EDUCATIVAS (SOLO_LECTURA=''SI'' => 42501) y TUSUARIO_ROL_PERMISO no haberlo recortado; (2) scope -- categoria territorial alcanza cualquier EE; categoria establecimiento (rector, JEFE DE SISTEMA -- que antes entraba por la rama FK_TROL = 8 --, auxiliar, y los punteros FK_TFUNCIONARIO_RECTOR / FK_TFUNCIONARIO_SECRETARIA) solo los EE de fn_usuario_ee_accesibles. Ambos fallos son 42501, con mensajes distintos. El gate corre despues del P0002 de existencia y del 22023 de sede ya inactiva. fn_sed_soft_delete_bulk lo hereda por fila. p_pk_usuario_solicitante va al inicio (obligatorio, mismo patron que V52 y V53).';

COMMENT ON FUNCTION academico_test.fn_est_soft_delete(BIGINT, BIGINT)
    IS 'Baja logica en cascada: marca ACTIVE=FALSE en TESTABLECIMIENTO y delega en academico_test.fn_sed_soft_delete (V52) para cada sede activa del EE. fn_sed_soft_delete se encarga a su vez de TSEDE, TSEDE_USUARIO y TSEDE_NIVEL (cuyo detalle vive en V52). Todo en una sola transaccion: si la delegation falla para cualquier sede, todo el borrado se revierte. GATE (CU-86e2w4xdt): PERFORM fn_assert_permiso_seccion(solicitante, ''ESTABLECIMIENTO'', ''ELIMINAR'', p_pk_establecimiento) (V29) -- bypass del SUPER_ADMIN (nivel 0), capability ELIMINAR sobre el menu ESTABLECIMIENTO segun TROL_MENU/TUSUARIO_ROL_PERMISO, y scope sobre el EE objetivo (nivel 1 territorial alcanza todos; nivel 2 solo los de fn_usuario_ee_accesibles). Sustituye a fn_puede_afectar_establecimiento (rol 1/2/3 fijo) y ENDURECE el comportamiento: antes no se validaba SOBRE QUE EE se actuaba. Ambos fallos siguen siendo 42501, con mensajes distintos para capability y para scope. p_pk_usuario_solicitante va primero en la firma (obligatorio, mismo patron que V52). Retorna PK_ESTABLECIMIENTO dado de baja.';

COMMENT ON FUNCTION academico_test.fn_est_soft_delete_bulk(BIGINT, BIGINT[])
    IS 'REV: baja logica en lote de establecimientos, una fila (pk_establecimiento, status) por PK -- cada uno en su propio savepoint via fn_est_soft_delete, asi que un fallo en uno no aborta ni deshace el resto (antes era todo-o-nada, devolvia un solo total_procesados, con el gate de super-admin validado una sola vez al inicio). status: eliminado | error:no_encontrado (P0002) | error:sin_permiso (42501) | error:ya_inactivo (22023) | error:<mensaje> para cualquier otra excepcion. Mismo patron que fn_fun_baja_establecimiento_bulk.';

COMMENT ON FUNCTION academico_test.fn_actividad_importar(BIGINT, JSONB, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, BOOLEAN)
    IS 'Importa actividades del planeador desde el JSON de intercambio que produce fn_actividad_exportar. Dos fases: p_solo_validar = TRUE (por defecto) devuelve el informe fila por fila sin escribir nada; FALSE aplica, y es todo o nada -- si alguna fila tiene errores no se escribe ninguna. El destino sale del bloque _identificadores del archivo y, si no viene, de los parametros p_fk_tasignatura / p_fk_tgrupo / p_fk_tgrado: nunca se resuelve por nombre, porque hay 304 nombres para 3.591 asignaturas activas. Las etiquetas que no existan en catalogo se reportan con la categoria donde se busco, sin equivalencias inventadas. Orquesta fn_unidad_crear, fn_actividad_crear y los *_definir del instrumento en vez de escribir tablas. Exige capability (PLANEADOR/CREAR) al entrar y en los DOS modos -- en validacion no se llama a ninguna funcion orquestada, asi que antes el informe se entregaba a quien no tenia permiso -- y exige que el periodo academico del destino no haya terminado (fn_planeador_periodo_vigente, V203) sin opcion de saltarselo, y comprueba el ALCANCE del destino fila por fila con fn_planeador_alcanza (V202), porque fn_actividad_crear valida capability pero no establecimiento: se midio que un docente de nivel 3 importaba en un EE ajeno. Tampoco se inventan notas: si un nivel de rubrica o de escala no trae ponderacion se rechaza la fila, y una ponderacion sobre una actividad no evaluativa tambien (el "ponderacion": 0 que pone el formato de negocio en esas si se descarta, porque no es una nota). Una adaptacion "para estudiantes concretos" solo se importa si trae PKs de matricula del grupo destino: un nombre de alumno no identifica una matricula. V274.';

COMMENT ON FUNCTION academico_test.fn_estudiante_final_observacion(BIGINT, BIGINT)
    IS 'GENERA el borrador del comentario del AÑO -- la fila Final --, sin escribir nada. Hoy encadena los resumenes de periodo YA CONSOLIDADOS, en orden y prefijados con el nombre del periodo; cuando exista el modelo, cambia lo que devuelve esta funcion y nada mas, porque el contrato ya es el definitivo. NO concatena las observaciones por ACTIVIDAD: esas son la materia prima del resumen de PERIODO, y volver a masticarlas aca daria un texto de tres paginas. Devuelve siempre una fila; con NULL y cero si el estudiante no tiene ningun resumen de periodo guardado. Lo que devuelve se reenvia tal cual a fn_estudiante_anio_observacion_guardar, que compara para deducir si el docente lo aprobo o lo modifico. Gate INFORMES/VER, porque no persiste. V434, V435.';

COMMENT ON FUNCTION academico_test.fn_estudiante_anio_observacion_guardar(BIGINT, BIGINT, TEXT, TEXT, NUMERIC)
    IS 'Guarda el comentario del AÑO de un estudiante -- la fila Final --, el equivalente de fn_estudiante_periodo_observacion_guardar para TESTUDIANTE_ANIO_OBSERVACION. Reemplaza: el indice unico es total sobre la matricula y no se versiona. El ESTADO se deduce comparando el texto contra OBSERVACION_IA (iguales APROBADA, distintos MODIFICADA) y nunca se pide por parametro, para que no pueda contradecirlo. Arrastra los dos arreglos del V433 desde el dia uno: si no llega OBSERVACION_IA pero ya hay fila, se conserva el borrador guardado en vez de asumir que el texto nuevo es el de la IA -- si no, editar quedaria como APROBADA sin cambios --, y si no llega PERIODOS_ORIGEN se cuentan los resumenes de periodo consolidados en el momento de guardar, en vez de dejar la columna en NULL, que el lector no puede distinguir de cero. Gate INFORMES/EDITAR. Errores: 22023 con el texto vacio -- para quitarlo esta _eliminar --, 404 si la matricula no existe. V435.';

COMMENT ON FUNCTION academico_test.fn_estudiante_anio_observacion_eliminar(BIGINT, BIGINT)
    IS 'Quita el comentario del AÑO de un estudiante. Devuelve el PK eliminado. BORRADO FISICO y no baja logica, igual que su gemela de periodo (V413): el indice unico de TESTUDIANTE_ANIO_OBSERVACION es total sobre la matricula, de modo que una fila inactiva seguiria ocupando el lugar e impediria guardar una nueva; y no hay nada que conservar, porque el texto se regenera desde los resumenes de periodo, que son el dato original. Despues de eliminar, la fila Final de /informes/grupo vuelve a traer observacion en NULL. Gate INFORMES/ELIMINAR -- mas exigente que el EDITAR de guardar, porque rehacer es corregir y borrar es deshacer. 404 si no habia nada guardado. V435.';

COMMENT ON FUNCTION academico_test.fn_informe_grupo_listar(BIGINT, BIGINT, BIGINT[], VARCHAR)
    IS 'Listado principal de informes: una fila por (estudiante, periodo) del grupo. EL FINAL SE PIDE METIENDO -1 EN PERIODOS (V439), que es el mismo centinela con el que esa fila viaja en FK_TPERIODO_EVALUACION; antes era el parametro p_incluir_final, que se retira. El cambio no es cosmetico: como -1 no matchea ningun periodo real, ARRAY[-1] deja la CTE de periodos vacia y por fin se puede pedir SOLO el Final -- con la bandera era imposible, porque un arreglo vacio significa (y sigue significando) TODOS los periodos reales, de modo que no habia forma de decir "ninguno". La fila Final llega con FK_TPERIODO_EVALUACION = -1, modo_periodo "final", consolidado false y asignaturas con estado "final"; su nota se calcula al vuelo sobre TODOS los periodos del año, el periodo sin nota guardada vale cero y el promedio general sale de esas mismas asignaturas (V431). EVIDENCIAS cuenta las imagenes adjuntas a observaciones de la fila, y en el Final las del año (V434). Su observacion es la que este GUARDADA en TESTUDIANTE_ANIO_OBSERVACION, con su estado y su marca de desactualizado, que se dispara cuando se CONSOLIDA UN PERIODO NUEVO y no cuando el docente escribe una observacion mas (V435). V335, V411, V412, V428, V431, V434, V435, V439. V474: PROMEDIO_GUARDADO y PROMEDIO_PROYECTADO ya NO salen en porcentaje -- se homologan con fn_promedio_homologar al formato del criterio de evaluacion GENERAL del periodo academico, el mismo con el que se pintan las asignaturas de la fila; antes la columna PR mostraba 70,0 al lado de asignaturas en 3,3. En un formato no numerico los dos vienen NULL y lo que vale son PROMEDIO_VALORACION / PROMEDIO_SIMBOLO y sus gemelas del proyectado; sin criterio configurado se sigue devolviendo el porcentaje crudo. PROMEDIO_FORMATO dice con cual se homologo. Cubre tambien el promedio de la fila Final y la nota requerida que viaja en PROMEDIO_PROYECTADO, porque la conversion esta en un solo punto de la salida. El PUESTO se sigue calculando sobre el porcentaje: la conversion es monotona y redondear antes de ordenar crearia empates que no existen.';
