-- ===========================================================================
-- V517 - COMMENT de funciones cuyas migraciones de origen (V51, V112, V227,
-- V370) se recortaron por tener el cuerpo obsoleto. Las reescrituras
-- posteriores no traen COMMENT; se copia literal.
-- ===========================================================================

SET search_path TO academico_test, public;

COMMENT ON FUNCTION academico_test.fn_fun_permisos_actualizar(BIGINT, BIGINT, JSONB)
    IS 'Procesa la lista de permisos (TSEDE_USUARIO) del funcionario segun el campo "accion" de cada elemento: crear (INSERT via fn_sede_usuario_crear), eliminar (soft-delete via fn_sede_usuario_soft_delete por id=pk_tsede_usuario), o sin accion (no-op). Reemplaza el bloque JSONB que antes vivia en fn_fun_actualizar. No soporta editar (no esta contemplado en el front). Gate (CU-86e2w4xdt, helpers de V29; reemplaza al bloque "union de EE accesibles" + coordinador de sede que estaba copiado inline): PERFORM fn_assert_permiso_funcionario(solicitante, ''EDITAR'', p_pk_funcionario) = bypass super-admin + capability ''EDITAR'' sobre el menu FUNCIONARIOS + scope sobre el funcionario objetivo + rango de rol. Capa 3 adicional: por cada elemento con accion=''crear'' se ejecuta fn_assert_rango_rol_otorgable(solicitante, fk_rol) -- no se puede otorgar un rol de categoria igual o superior a la propia; lanza 42501 y ABORTA la llamada completa (no devuelve un status por fila) porque es un intento de escalada de privilegios, no un dato invalido. La validacion por operacion contra las sedes del actor (v_sedes_plenas / v_sedes_coord -> status ''error:sin_permiso_en_sede'') se conserva, pero CU-86e2w4xdt la resuelve por CATEGORIA_ROL: v_es_super = categoria nivel <= 1; v_sedes_plenas = sedes de fn_usuario_ee_accesibles(solicitante); v_sedes_coord = sedes de fn_usuario_sedes_jornadas_accesibles(solicitante); y el permiso puntual que un coordinador puede crear/borrar en su sede se limita a roles de categoria nivel 3 (fn_rol_categoria_nivel(fk_rol) = 3) en vez de la lista FK_TROL >= 9 NOT IN (15,16). Ya no se usa fn_puede_afectar_establecimiento ni numeros de rol fijos.';

COMMENT ON FUNCTION academico_test.fn_fun_actualizar(
    BIGINT, BIGINT,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR,
    DATE, BIGINT, VARCHAR, VARCHAR, BIGINT,
    BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT,
    VARCHAR, DATE, DATE, bool_sn,
    BIGINT, BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT, BIGINT, BIGINT,
    NUMERIC, BIGINT, BIGINT, BIGINT, BIGINT,
    VARCHAR
)
    IS 'PATCH integral del funcionario: TUSUARIO + TFUNCIONARIO, en una sola transaccion. Parametros NULL no modifican su columna. Validaciones: gate (fn_puede_afectar_usuarios), existencia y actividad del TFUNCIONARIO, obligatorios no vacios, dominio estado_ai (''A''/''I''), FKs contra TLISTA_VALOR/TMUNICIPIO/TARCHIVO/TDENOMINACION activos, unicidad de CUENTA y (FK_TLV_TIPO_DOCUMENTO, IDENTIFICACION) excluyendo el propio PK. PATCH con CTE + IS DISTINCT FROM en ambas tablas: una sola sentencia UPDATE por tabla; MODIFIED_BY/MODIFIED_AT se setean UNA sola vez y SOLO si hubo cambios efectivos. p_direccion (DIRECCION, agregada en V60) va al final de la firma. Ya NO recibe p_lista_permisos ni sincroniza TSEDE_USUARIO: usar academico_test.fn_fun_permisos_actualizar para eso. Cualquier fallo hace ROLLBACK de todo. Requiere p_pk_usuario_solicitante con permiso de usuarios via fn_puede_afectar_usuarios (V50). Retorna PK_TFUNCIONARIO.';

COMMENT ON FUNCTION academico_test.fn_fun_baja_establecimiento(BIGINT, BIGINT)
    IS 'REV3 (cambio de modelo, ver header V51 REV5/REV6): ya NO depende de TFUNCIONARIO.FK_ESTABLECIMIENTO (esa columna quedo sin proposito, siempre NULL). Gate (CU-86e2w4xdt, helpers de V29; reemplaza al bloque "union de EE accesibles" + coordinador de sede copiado inline): PERFORM fn_assert_permiso_funcionario(solicitante, ''ELIMINAR'', p_pk_funcionario) = bypass super-admin + capability ''ELIMINAR'' sobre el menu FUNCIONARIOS + scope (el objetivo debe ser alcanzable en algun EE de fn_usuario_ee_accesibles, o el solicitante es territorial) + rango de rol (solo categorias estrictamente inferiores). Bloqueos previos (22023, sin excepcion por rol de quien llama, fail-fast -- nada se toca si aplican): (1) es rector de un EE activo, (2) es secretaria de un EE activo, (3) tiene responsabilidades academicas VIGENTES (TGRUPO como lider, TDOCENTE_ASIGNATURA, TUNIDAD, TTRASLADO_ESTUDIANTE o TPERIODO_PERMISO activos -- deliberadamente NO se incluyen tablas de registro historico como TACTA_GRADO/TEVALUACION_DOCENTE/TCOMPORTAMIENTO_CALIFICADO/TOBSERVADOR_ANOTACION/TFUNCIONARIO_ARCHIVO). Comportamiento por rol una vez superados los bloqueos (CU-86e2w4xdt: se decide por CATEGORIA_ROL, no por FK_TROL IN (1,2,3)): (a) categoria nivel <= 1 (SUPER_ADMIN o ADMINISTRATIVOS_TERRITORIALES) -- baja INTEGRAL: desactiva TODOS sus TSEDE_USUARIO, desactiva el TFUNCIONARIO, y si el TUSUARIO no tiene ningun otro vinculo activo en la plataforma (fn_usu_tiene_otros_vinculos -- no es tambien padre de familia, estudiante, etc.) lo desactiva tambien; (b) cualquier otra categoria -- baja PARCIAL: solo quita los TSEDE_USUARIO del funcionario en sedes de los EE de fn_usuario_ee_accesibles(solicitante), mas -- si el solicitante es de categoria ADMINISTRATIVOS_SEDES -- los permisos de rol de categoria nivel 3 en las sedes de fn_usuario_sedes_jornadas_accesibles(solicitante); si tras eso el funcionario sigue teniendo permisos en OTRO EE, el TFUNCIONARIO queda activo; si no le queda nada en ningun lado, se desactiva el TFUNCIONARIO (y, con el mismo criterio de fn_usu_tiene_otros_vinculos, el TUSUARIO). Sincroniza public.role_users al final (fn_sincronizar_rol_publico). p_pk_usuario_solicitante va al inicio (obligatorio).';

COMMENT ON FUNCTION academico_test.fn_puede_afectar_establecimiento(BIGINT)
    IS 'TRUE si el usuario tiene un TSEDE_USUARIO activo con FK_TROL IN (1,2,3) (roles de superadmin/nivel alto): ve todos los establecimientos, no solo el suyo. Baseline capturado del servidor en V112 (no existia en ninguna migracion previa del repo — ver nota de drift en el header de este archivo). Sin cambios de logica.';

COMMENT ON FUNCTION academico_test.fn_nota_homologar(NUMERIC, BIGINT, BIGINT)
    IS 'Traduce una calificacion del Planeador (porcentaje 0-100, que es como se guarda SIEMPRE en TACTIVIDAD_NOTA) a lo que el colegio muestra, resolviendo el TCRITERIO_EVALUACION vigente de (asignatura, grado) con fn_asignatura_criterio_evaluacion_vigente. Devuelve SIEMPRE una fila, incluso con p_porcentaje NULL o sin criterio configurado, para poder usarse en LEFT JOIN LATERAL desde un listado sin perder al estudiante sin calificar. nota_homologada = ROUND(% / 100 * nota_maxima, decimales) SOLO en los formatos numericos (CINCO/DIEZ/CIEN); en LITERAL/SIMBOLO/CARITA viene NULL porque ahi el colegio no califica con un numero -- devolverlo seria inventarlo, que es lo que hace el "ELSE 100" de fn_criterio_eval_obtener (V62). La valoracion (la banda Bajo/Basico/Alto/Superior de TESCALA_VALORACION) se devuelve siempre que exista, y se compara directo contra el porcentaje porque LIMITE_INFERIOR/SUPERIOR ya estan guardados en 0-100 (V97). Si el porcentaje cae en un hueco entre bandas -- las escalas reales los tienen -- la valoracion viene NULL en vez de aproximar a la mas cercana: a que lado redondear es una decision de negocio de cada colegio. NO aplica piso ni tope: de eso se encarga fn_actividad_nota_ajustar_por_criterio en la ESCRITURA, y repetirlo en la lectura lo contaria dos veces. V227.';

COMMENT ON FUNCTION pigse.fn_fun_permisos_actualizar(BIGINT, BIGINT, JSONB) IS
    'V370: mismo contrato que academico_test.fn_fun_permisos_actualizar (V297) -- JSONB array de {accion: crear|eliminar, orden, fk_rol, fk_sede, fk_jornada, fk_estado, predeterminado, id}, retorna TABLE(accion, id, status). El front que ya conoce ese contrato (dialog-manage.tsx de CEVAL) se reusa sin cambios de forma.';
