-- ============================================================================
-- V520 — Marca `ETNIAS` ('S'/'N') en `pigse.testablecimiento` para un lote de
-- 50 establecimientos puntuales, pedido explícito del cliente.
--
-- No agrega logica nueva: `ETNIAS` ya gobierna que documento institucional
-- "no aplica" (`fn_documento_categorias_listar`/`fn_cumplimiento_metricas`,
-- V149/V261/V512) — 'S' bloquea el PEI (queda NO_APLICA, solo corre PEC),
-- 'N' bloquea el PEC (solo corre PEI). Match por NOMBRE (trim+upper), no por
-- id: reproducible en cualquier ambiente que tenga estos mismos
-- establecimientos sembrados. Confirmados los 50 contra la base de test
-- antes de escribir esto (ningun nombre sin matchear).
-- ============================================================================

UPDATE pigse.testablecimiento
   SET etnias = 'S'
 WHERE active
   AND upper(trim(nombre)) = ANY (ARRAY[
    'CENTRO ETNOEDUCATIVO #16','CENTRO ETNOEDUCATIVO #19','CENTRO ETNOEDUCATIVO #4',
    'CENTRO ETNOEDUCATIVO #8','CENTRO ETNOEDUCATIVO N28 PUNTA SIERRA',
    'CENTRO ETNOEDUCATIVO NO 25 URRAICHI','CENTRO ETNOEDUCATIVO NO 27 PARULUAIN',
    'CENTRO ETNOEDUCATIVO NO. 21 ARALIA','CENTRO ETNOEDUCATIVO NO. 22 ALIJOTE',
    'CENTRO ETNOEDUCATIVO NO.23  MARIA LUISA MORENO',
    'INSTITUCION ETNODUCATIVA RURAL  EUGENIA HERRERA DE MATITAS',
    'INSTITUCION ETNOEDUCATIVA  DEL CARIBE','INSTITUCION ETNOEDUCATIVA  SIERRA NEVADA',
    'INSTITUCION ETNOEDUCATIVA # 20','INSTITUCION ETNOEDUCATIVA #1',
    'INSTITUCION ETNOEDUCATIVA #10','INSTITUCION ETNOEDUCATIVA #11',
    'INSTITUCION ETNOEDUCATIVA #13','INSTITUCION ETNOEDUCATIVA #14',
    'INSTITUCION ETNOEDUCATIVA #15','INSTITUCION ETNOEDUCATIVA #17',
    'INSTITUCION ETNOEDUCATIVA #3','INSTITUCION ETNOEDUCATIVA #7',
    'INSTITUCION ETNOEDUCATIVA JOSE CHOLES',
    'INSTITUCION ETNOEDUCATIVO # 5 ANARALITO NUEVO','INSTITUCION ETNOEDUCATIVO #12',
    'INSTITUCION ETNOEDUCATIVO #2','INSTITUCION ETNOEDUCATIVO #6 GUACHAQUERO',
    'INSTITUCION ETNOEDUCATIVO #9 MAÑATURE','INSTITUCION ETNOEDUCATIVO NO 26 WAYENETAMANA',
    'INSTITUCION ETNOEDUCATIVO NO. 24','INSTITUCION ETNOEDUCATIVO WIWA SHENZHUWIMAKU'
   ]);

UPDATE pigse.testablecimiento
   SET etnias = 'N'
 WHERE active
   AND upper(trim(nombre)) = ANY (ARRAY[
    'INSTITUCION EDUCATIVA ALMIRANTE PADILLA',
    'INSTITUCION EDUCATIVA CENTRO DE INTEGRACION POPULAR',
    'INSTITUCION EDUCATIVA CHON-KAY','INSTITUCION EDUCATIVA DENZIL ESCOLAR',
    'INSTITUCION EDUCATIVA DIOCESANA SANTA MARIA GORETTI',
    'INSTITUCION EDUCATIVA DIVINA PASTORA','INSTITUCION EDUCATIVA ECOLOGICA EL CARMEN',
    'INSTITUCION EDUCATIVA EUSEBIO SEPTIMIO MARI',
    'INSTITUCION EDUCATIVA EVARISTO ACOSTA DE MONGUI',
    'INSTITUCION EDUCATIVA FAMILIA DE NAZARET','INSTITUCION EDUCATIVA HELION PINEDO RIOS',
    'INSTITUCION EDUCATIVA ISABEL MARIA CUESTA','INSTITUCION EDUCATIVA JOSE ANTONIO GALAN',
    'INSTITUCION EDUCATIVA LIVIO REGINALDO FISCHIONE',
    'INSTITUCION EDUCATIVA LUIS ANTONIO ROBLES','INSTITUCION EDUCATIVA MARIA DORALIZA',
    'INSTITUCION EDUCATIVA SAN JUAN BAUTISTA',
    'INSTITUCION EDUCATIVA TECNICA AGROPECUARIA DE TOMARRAZON'
   ]);

DO $$
DECLARE
    v_faltantes INTEGER;
BEGIN
    SELECT count(*) INTO v_faltantes
      FROM pigse.testablecimiento
     WHERE active
       AND etnias IS NULL
       AND upper(trim(nombre)) = ANY (ARRAY[
        'CENTRO ETNOEDUCATIVO #16','CENTRO ETNOEDUCATIVO #19','CENTRO ETNOEDUCATIVO #4',
        'CENTRO ETNOEDUCATIVO #8','CENTRO ETNOEDUCATIVO N28 PUNTA SIERRA',
        'CENTRO ETNOEDUCATIVO NO 25 URRAICHI','CENTRO ETNOEDUCATIVO NO 27 PARULUAIN',
        'CENTRO ETNOEDUCATIVO NO. 21 ARALIA','CENTRO ETNOEDUCATIVO NO. 22 ALIJOTE',
        'CENTRO ETNOEDUCATIVO NO.23  MARIA LUISA MORENO',
        'INSTITUCION ETNODUCATIVA RURAL  EUGENIA HERRERA DE MATITAS',
        'INSTITUCION ETNOEDUCATIVA  DEL CARIBE','INSTITUCION ETNOEDUCATIVA  SIERRA NEVADA',
        'INSTITUCION ETNOEDUCATIVA # 20','INSTITUCION ETNOEDUCATIVA #1',
        'INSTITUCION ETNOEDUCATIVA #10','INSTITUCION ETNOEDUCATIVA #11',
        'INSTITUCION ETNOEDUCATIVA #13','INSTITUCION ETNOEDUCATIVA #14',
        'INSTITUCION ETNOEDUCATIVA #15','INSTITUCION ETNOEDUCATIVA #17',
        'INSTITUCION ETNOEDUCATIVA #3','INSTITUCION ETNOEDUCATIVA #7',
        'INSTITUCION ETNOEDUCATIVA JOSE CHOLES',
        'INSTITUCION ETNOEDUCATIVO # 5 ANARALITO NUEVO','INSTITUCION ETNOEDUCATIVO #12',
        'INSTITUCION ETNOEDUCATIVO #2','INSTITUCION ETNOEDUCATIVO #6 GUACHAQUERO',
        'INSTITUCION ETNOEDUCATIVO #9 MAÑATURE','INSTITUCION ETNOEDUCATIVO NO 26 WAYENETAMANA',
        'INSTITUCION ETNOEDUCATIVO NO. 24','INSTITUCION ETNOEDUCATIVO WIWA SHENZHUWIMAKU',
        'INSTITUCION EDUCATIVA ALMIRANTE PADILLA',
        'INSTITUCION EDUCATIVA CENTRO DE INTEGRACION POPULAR',
        'INSTITUCION EDUCATIVA CHON-KAY','INSTITUCION EDUCATIVA DENZIL ESCOLAR',
        'INSTITUCION EDUCATIVA DIOCESANA SANTA MARIA GORETTI',
        'INSTITUCION EDUCATIVA DIVINA PASTORA','INSTITUCION EDUCATIVA ECOLOGICA EL CARMEN',
        'INSTITUCION EDUCATIVA EUSEBIO SEPTIMIO MARI',
        'INSTITUCION EDUCATIVA EVARISTO ACOSTA DE MONGUI',
        'INSTITUCION EDUCATIVA FAMILIA DE NAZARET','INSTITUCION EDUCATIVA HELION PINEDO RIOS',
        'INSTITUCION EDUCATIVA ISABEL MARIA CUESTA','INSTITUCION EDUCATIVA JOSE ANTONIO GALAN',
        'INSTITUCION EDUCATIVA LIVIO REGINALDO FISCHIONE',
        'INSTITUCION EDUCATIVA LUIS ANTONIO ROBLES','INSTITUCION EDUCATIVA MARIA DORALIZA',
        'INSTITUCION EDUCATIVA SAN JUAN BAUTISTA',
        'INSTITUCION EDUCATIVA TECNICA AGROPECUARIA DE TOMARRAZON'
       ]);
    -- No es EXCEPTION: en un ambiente sin estos establecimientos sembrados
    -- (ninguno matchea) las dos UPDATE de arriba ya son no-ops seguros: esto
    -- solo deja rastro de cuantos, DE LOS QUE SI EXISTEN, quedaron sin marcar.
    RAISE NOTICE 'V520: % establecimiento(s) del lote sin ETNIAS asignado (0 = todos los presentes quedaron marcados).', v_faltantes;
END $$;
