-- ===========================================================================
-- V522 — Fecha límite de "Gestión documental": Secretaria Territorial (o
-- Administrador) fija UNA fecha global; después de esa fecha, ningún
-- establecimiento puede subir NI eliminar documentos. Admite excepciones
-- puntuales por establecimiento (su propia fecha, en vez de la global).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Config global -- una sola fila fija (pk_config = 1).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tgestion_documental_config (
    pk_config     SMALLINT NOT NULL DEFAULT 1 CHECK (pk_config = 1),
    fecha_limite  DATE,
    modified_by   VARCHAR(120),
    modified_at   TIMESTAMP,
    PRIMARY KEY (pk_config)
);

-- ---------------------------------------------------------------------------
-- 2. Excepciones por establecimiento -- a lo sumo una excepción ACTIVA por
--    establecimiento (índice único parcial, mismo patrón que
--    tdocumento_institucional).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pigse.tgestion_documental_excepcion (
    pk_excepcion         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fk_testablecimiento  BIGINT NOT NULL REFERENCES pigse.testablecimiento(pk_establecimiento),
    fecha_limite         DATE NOT NULL,
    created_by           VARCHAR(120) NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by          VARCHAR(120),
    modified_at          TIMESTAMP,
    active                BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (pk_excepcion)
);

CREATE UNIQUE INDEX IF NOT EXISTS u_pigse_gestion_doc_excepcion_establecimiento
    ON pigse.tgestion_documental_excepcion (fk_testablecimiento) WHERE active;

-- ---------------------------------------------------------------------------
-- 3. fn_gestion_documental_fecha_limite_obtener -- fecha global + lista de
--    excepciones activas, para pintar la pantalla de configuración entera
--    en un solo viaje.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_gestion_documental_fecha_limite_obtener()
RETURNS TABLE(
    "fechaLimite" DATE,
    excepciones JSONB
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        (SELECT fecha_limite FROM pigse.tgestion_documental_config WHERE pk_config = 1),
        COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
                       'establecimientoId', e.fk_testablecimiento,
                       'establecimientoNombre', te.NOMBRE,
                       'fechaLimite', e.fecha_limite
                   ) ORDER BY te.NOMBRE)
              FROM pigse.tgestion_documental_excepcion e
              JOIN pigse.testablecimiento te ON te.PK_ESTABLECIMIENTO = e.fk_testablecimiento
             WHERE e.active
        ), '[]'::jsonb);
$$;

COMMENT ON FUNCTION pigse.fn_gestion_documental_fecha_limite_obtener() IS
    'V522: fecha limite global + excepciones activas por establecimiento, para la pantalla de configuracion de Secretaria Territorial.';

-- ---------------------------------------------------------------------------
-- 4. fn_gestion_documental_fecha_limite_guardar -- upsert de la fila única.
--    p_fecha_limite NULL = sin fecha limite (des-configurar).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_gestion_documental_fecha_limite_guardar(
    p_pk_usuario   BIGINT,
    p_email        VARCHAR,
    p_fecha_limite DATE
)
RETURNS TABLE("fechaLimite" DATE)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO pigse.tgestion_documental_config (pk_config, fecha_limite, modified_by, modified_at)
    VALUES (1, p_fecha_limite, p_email, CURRENT_TIMESTAMP)
    ON CONFLICT (pk_config) DO UPDATE
        SET fecha_limite = EXCLUDED.fecha_limite,
            modified_by = EXCLUDED.modified_by,
            modified_at = EXCLUDED.modified_at;

    RETURN QUERY SELECT fecha_limite FROM pigse.tgestion_documental_config WHERE pk_config = 1;
END;
$$;

COMMENT ON FUNCTION pigse.fn_gestion_documental_fecha_limite_guardar(BIGINT, VARCHAR, DATE) IS
    'V522: fija (o quita, con NULL) la fecha limite global de Gestion Documental.';

-- ---------------------------------------------------------------------------
-- 5. fn_gestion_documental_excepcion_guardar -- upsert de la excepción de
--    UN establecimiento (si ya tenía una activa, la reemplaza).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_gestion_documental_excepcion_guardar(
    p_pk_usuario         BIGINT,
    p_email              VARCHAR,
    p_fk_establecimiento BIGINT,
    p_fecha_limite       DATE
)
RETURNS TABLE("establecimientoId" BIGINT, "establecimientoNombre" TEXT, "fechaLimite" DATE)
LANGUAGE plpgsql
AS $$
DECLARE
    v_pk_excepcion BIGINT;
BEGIN
    IF p_fecha_limite IS NULL THEN
        RAISE EXCEPTION 'pigse: la fecha limite de la excepcion es obligatoria'
            USING ERRCODE = '22023';
    END IF;

    SELECT e.pk_excepcion INTO v_pk_excepcion
      FROM pigse.tgestion_documental_excepcion e
     WHERE e.fk_testablecimiento = p_fk_establecimiento
       AND e.active;

    IF v_pk_excepcion IS NULL THEN
        INSERT INTO pigse.tgestion_documental_excepcion
            (fk_testablecimiento, fecha_limite, created_by)
        VALUES (p_fk_establecimiento, p_fecha_limite, p_email);
    ELSE
        UPDATE pigse.tgestion_documental_excepcion
           SET fecha_limite = p_fecha_limite, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
         WHERE pk_excepcion = v_pk_excepcion;
    END IF;

    RETURN QUERY
    SELECT te.PK_ESTABLECIMIENTO, te.NOMBRE::TEXT, e.fecha_limite
      FROM pigse.tgestion_documental_excepcion e
      JOIN pigse.testablecimiento te ON te.PK_ESTABLECIMIENTO = e.fk_testablecimiento
     WHERE e.fk_testablecimiento = p_fk_establecimiento
       AND e.active;
END;
$$;

COMMENT ON FUNCTION pigse.fn_gestion_documental_excepcion_guardar(BIGINT, VARCHAR, BIGINT, DATE) IS
    'V522: fija la fecha limite propia de UN establecimiento (reemplaza la global para el, no la suma).';

-- ---------------------------------------------------------------------------
-- 6. fn_gestion_documental_excepcion_eliminar -- baja logica, el
--    establecimiento vuelve a regirse por la fecha global.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_gestion_documental_excepcion_eliminar(
    p_pk_usuario         BIGINT,
    p_email              VARCHAR,
    p_fk_establecimiento BIGINT
)
RETURNS TABLE("establecimientoId" BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE pigse.tgestion_documental_excepcion
       SET active = false, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
     WHERE fk_testablecimiento = p_fk_establecimiento
       AND active;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'pigse: este establecimiento no tiene excepcion activa'
            USING ERRCODE = 'P0002';
    END IF;

    RETURN QUERY SELECT p_fk_establecimiento;
END;
$$;

COMMENT ON FUNCTION pigse.fn_gestion_documental_excepcion_eliminar(BIGINT, VARCHAR, BIGINT) IS
    'V522: saca la excepcion de un establecimiento -- vuelve a regirse por la fecha global.';

-- ---------------------------------------------------------------------------
-- 7. Gate en fn_documento_guardar/fn_documento_eliminar -- misma firma que
--    V521 dejó (CREATE OR REPLACE, no hace falta DROP). Excepción activa
--    del establecimiento gana sobre la global; sin ninguna de las dos, no
--    hay bloqueo. Bloquea TAMBIÉN eliminar, para todos los roles (ni
--    Administrador se salva) -- pedido explícito.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pigse.fn_documento_guardar(
    p_pk_usuario  BIGINT,
    p_email       VARCHAR,
    p_tipo        VARCHAR,
    p_fk_tarchivo BIGINT,
    p_categoria   VARCHAR DEFAULT NULL
)
RETURNS TABLE(
    id TEXT, type TEXT, "typeName" TEXT, categoria TEXT, "categoriaName" TEXT,
    status TEXT, "fileName" TEXT, "uploadedAt" TIMESTAMP, "sizeBytes" BIGINT,
    "archivoId" BIGINT, "downloadUrl" TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo BIGINT;
    v_etnias             pigse.bool_sn;
    v_fecha_limite       DATE;
BEGIN
    IF p_fk_tarchivo IS NULL THEN
        RAISE EXCEPTION 'pigse: p_fk_tarchivo es obligatorio (archivo no subido)';
    END IF;

    IF p_categoria IS NULL THEN
        RAISE EXCEPTION 'pigse: % requiere indicar la categoria del anexo', p_tipo
            USING ERRCODE = '22023';
    ELSIF p_categoria NOT IN ('PLAN_ESTUDIOS', 'SIEE', 'MANUAL_CONVIVENCIA',
                               'PROYECTOS_TRANSVERSALES', 'PLAN_GESTION_RIESGO',
                               'AUTOEVALUACION_INSTITUCIONAL') THEN
        RAISE EXCEPTION 'pigse: categoria invalida: %', p_categoria
            USING ERRCODE = '22023';
    ELSIF p_tipo IN ('PMI', 'PFI') AND p_categoria <> 'AUTOEVALUACION_INSTITUCIONAL' THEN
        RAISE EXCEPTION 'pigse: % solo admite la categoria AUTOEVALUACION_INSTITUCIONAL', p_tipo
            USING ERRCODE = '22023';
    ELSIF p_tipo IN ('PEI', 'PEC') AND p_categoria = 'AUTOEVALUACION_INSTITUCIONAL' THEN
        RAISE EXCEPTION 'pigse: % no admite la categoria AUTOEVALUACION_INSTITUCIONAL', p_tipo
            USING ERRCODE = '22023';
    END IF;

    v_fk_establecimiento := pigse.fn_mi_establecimiento(p_email);

    SELECT COALESCE(
               (SELECT e.fecha_limite FROM pigse.tgestion_documental_excepcion e
                 WHERE e.fk_testablecimiento = v_fk_establecimiento AND e.active),
               (SELECT c.fecha_limite FROM pigse.tgestion_documental_config c WHERE c.pk_config = 1)
           ) INTO v_fecha_limite;

    IF v_fecha_limite IS NOT NULL AND CURRENT_DATE > v_fecha_limite THEN
        RAISE EXCEPTION 'pigse: la fecha limite para Gestion Documental (%) ya paso', v_fecha_limite
            USING ERRCODE = '23514';
    END IF;

    SELECT ETNIAS INTO v_etnias
      FROM pigse.testablecimiento
     WHERE PK_ESTABLECIMIENTO = v_fk_establecimiento;

    IF p_tipo = 'PEI' AND v_etnias = 'S' THEN
        RAISE EXCEPTION 'pigse: PEI no aplica a este establecimiento (etnoeducativo -- usar PEC)'
            USING ERRCODE = '23514';
    ELSIF p_tipo = 'PEC' AND v_etnias = 'N' THEN
        RAISE EXCEPTION 'pigse: PEC no aplica a este establecimiento (no etnoeducativo -- usar PEI)'
            USING ERRCODE = '23514';
    ELSIF p_tipo = 'PMI' AND v_etnias = 'S' THEN
        RAISE EXCEPTION 'pigse: PMI no aplica a este establecimiento (etnoeducativo -- usar PFI)'
            USING ERRCODE = '23514';
    ELSIF p_tipo = 'PFI' AND v_etnias = 'N' THEN
        RAISE EXCEPTION 'pigse: PFI no aplica a este establecimiento (no etnoeducativo -- usar PMI)'
            USING ERRCODE = '23514';
    END IF;

    IF p_categoria = 'PLAN_ESTUDIOS' THEN
        INSERT INTO pigse.tdocumento_institucional
            (fk_testablecimiento, tipo, categoria, fk_tarchivo, created_by)
        VALUES (v_fk_establecimiento, p_tipo, p_categoria, p_fk_tarchivo, p_email)
        RETURNING pk_documento_institucional INTO v_pk_doc;

        RETURN QUERY
        SELECT c.id, c.type, c."typeName", c.categoria, c."categoriaName", c.status,
               c."fileName", c."uploadedAt", c."sizeBytes", c."archivoId", c."downloadUrl"
          FROM pigse.fn_documento_categorias_listar(v_fk_establecimiento, p_tipo) c
         WHERE c.id = v_pk_doc::TEXT;
        RETURN;
    END IF;

    SELECT t.pk_documento_institucional, t.fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM pigse.tdocumento_institucional t
     WHERE t.fk_testablecimiento = v_fk_establecimiento
       AND t.tipo = p_tipo
       AND t.categoria IS NOT DISTINCT FROM p_categoria
       AND t.active;

    IF v_pk_doc IS NULL THEN
        INSERT INTO pigse.tdocumento_institucional
            (fk_testablecimiento, tipo, categoria, fk_tarchivo, created_by)
        VALUES (v_fk_establecimiento, p_tipo, p_categoria, p_fk_tarchivo, p_email)
        RETURNING pk_documento_institucional INTO v_pk_doc;
    ELSE
        UPDATE pigse.tdocumento_institucional
           SET fk_tarchivo = p_fk_tarchivo, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
         WHERE pk_documento_institucional = v_pk_doc;

        IF v_fk_tarchivo_previo IS NOT NULL THEN
            INSERT INTO pigse.tdocumento_institucional_hist
                (fk_documento_institucional, fk_tarchivo, reemplazado_by)
            VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);
        END IF;
    END IF;

    RETURN QUERY
    SELECT * FROM pigse.fn_documento_categorias_listar(v_fk_establecimiento, p_tipo) c
     WHERE c.categoria = p_categoria;
END;
$$;

COMMENT ON FUNCTION pigse.fn_documento_guardar(BIGINT, VARCHAR, VARCHAR, BIGINT, VARCHAR) IS
    'V522: gana el gate de fecha limite (excepcion del establecimiento si existe, si no la global) -- rechaza el guardado si ya paso.';

CREATE OR REPLACE FUNCTION pigse.fn_documento_eliminar(
    p_pk_usuario  BIGINT,
    p_email       VARCHAR,
    p_tipo        VARCHAR,
    p_categoria   VARCHAR DEFAULT NULL,
    p_fk_tarchivo BIGINT  DEFAULT NULL
)
RETURNS TABLE(
    id TEXT, type TEXT, "typeName" TEXT, categoria TEXT, "categoriaName" TEXT,
    status TEXT, "fileName" TEXT, "uploadedAt" TIMESTAMP, "sizeBytes" BIGINT,
    "archivoId" BIGINT, "downloadUrl" TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_fk_establecimiento BIGINT;
    v_pk_doc             BIGINT;
    v_fk_tarchivo_previo BIGINT;
    v_fecha_limite       DATE;
BEGIN
    IF p_categoria IS NULL THEN
        RAISE EXCEPTION 'pigse: % requiere indicar la categoria del anexo a eliminar', p_tipo
            USING ERRCODE = '22023';
    END IF;

    IF p_categoria = 'PLAN_ESTUDIOS' AND p_fk_tarchivo IS NULL THEN
        RAISE EXCEPTION 'pigse: PLAN_ESTUDIOS admite varios archivos -- indique cual (p_fk_tarchivo)'
            USING ERRCODE = '22023';
    ELSIF (p_categoria IS DISTINCT FROM 'PLAN_ESTUDIOS') AND p_fk_tarchivo IS NOT NULL THEN
        RAISE EXCEPTION 'pigse: p_fk_tarchivo solo aplica a PLAN_ESTUDIOS'
            USING ERRCODE = '22023';
    END IF;

    v_fk_establecimiento := pigse.fn_mi_establecimiento(p_email);

    SELECT COALESCE(
               (SELECT e.fecha_limite FROM pigse.tgestion_documental_excepcion e
                 WHERE e.fk_testablecimiento = v_fk_establecimiento AND e.active),
               (SELECT c.fecha_limite FROM pigse.tgestion_documental_config c WHERE c.pk_config = 1)
           ) INTO v_fecha_limite;

    IF v_fecha_limite IS NOT NULL AND CURRENT_DATE > v_fecha_limite THEN
        RAISE EXCEPTION 'pigse: la fecha limite para Gestion Documental (%) ya paso', v_fecha_limite
            USING ERRCODE = '23514';
    END IF;

    IF p_categoria = 'PLAN_ESTUDIOS' THEN
        SELECT t.pk_documento_institucional, t.fk_tarchivo
          INTO v_pk_doc, v_fk_tarchivo_previo
          FROM pigse.tdocumento_institucional t
         WHERE t.fk_testablecimiento = v_fk_establecimiento
           AND t.tipo = p_tipo
           AND t.categoria = 'PLAN_ESTUDIOS'
           AND t.fk_tarchivo = p_fk_tarchivo
           AND t.active;

        IF v_pk_doc IS NULL THEN
            RAISE EXCEPTION 'pigse: archivo % no encontrado en PLAN_ESTUDIOS para este establecimiento', p_fk_tarchivo
                USING ERRCODE = 'P0002';
        END IF;

        UPDATE pigse.tdocumento_institucional
           SET active = false, fk_tarchivo = NULL, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
         WHERE pk_documento_institucional = v_pk_doc;

        INSERT INTO pigse.tdocumento_institucional_hist
            (fk_documento_institucional, fk_tarchivo, reemplazado_by)
        VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);

        RETURN QUERY
        SELECT p_fk_tarchivo::TEXT, p_tipo::TEXT,
               (CASE p_tipo WHEN 'PEI' THEN 'Proyecto Educativo Institucional (PEI)'
                            WHEN 'PEC' THEN 'Proyecto Educativo Comunitario (PEC)' END),
               'PLAN_ESTUDIOS'::TEXT, 'Plan de estudios'::TEXT, 'PENDIENTE'::TEXT,
               NULL::TEXT, NULL::TIMESTAMP, NULL::BIGINT, NULL::BIGINT, NULL::TEXT;
        RETURN;
    END IF;

    SELECT t.pk_documento_institucional, t.fk_tarchivo
      INTO v_pk_doc, v_fk_tarchivo_previo
      FROM pigse.tdocumento_institucional t
     WHERE t.fk_testablecimiento = v_fk_establecimiento
       AND t.tipo = p_tipo
       AND t.categoria IS NOT DISTINCT FROM p_categoria
       AND t.active;

    IF v_pk_doc IS NULL OR v_fk_tarchivo_previo IS NULL THEN
        RAISE EXCEPTION 'pigse: % % desconocido o ya esta PENDIENTE para este establecimiento',
            p_tipo, COALESCE(p_categoria, '')
            USING ERRCODE = 'P0002';
    END IF;

    UPDATE pigse.tdocumento_institucional
       SET fk_tarchivo = NULL, modified_by = p_email, modified_at = CURRENT_TIMESTAMP
     WHERE pk_documento_institucional = v_pk_doc;

    INSERT INTO pigse.tdocumento_institucional_hist
        (fk_documento_institucional, fk_tarchivo, reemplazado_by)
    VALUES (v_pk_doc, v_fk_tarchivo_previo, p_email);

    RETURN QUERY
    SELECT * FROM pigse.fn_documento_categorias_listar(v_fk_establecimiento, p_tipo) c
     WHERE c.categoria = p_categoria;
END;
$$;

COMMENT ON FUNCTION pigse.fn_documento_eliminar(BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT) IS
    'V522: gana el gate de fecha limite, igual que fn_documento_guardar -- bloquea tambien eliminar.';

-- ---------------------------------------------------------------------------
-- 8. Endpoints + permisos. Lectura para todo rol que ya interactua con
--    documentos; escritura (fijar fecha global, gestionar excepciones)
--    solo Secretaria Territorial + Administrador.
-- ---------------------------------------------------------------------------
INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                          path_template, execution_mode, http_method, param_types, detail)
SELECT 'pigse-gestion-documental-fecha-limite-obtener',
       $q$SELECT * FROM pigse.fn_gestion_documental_fecha_limite_obtener()$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/fecha-limite', 'SELECT', 'GET', '{}'::jsonb,
       'V522: fecha limite global + excepciones activas de Gestion Documental.'
  FROM public.microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM public.query WHERE uuid = 'pigse-gestion-documental-fecha-limite-obtener');

INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                          path_template, execution_mode, http_method, param_types, detail)
SELECT 'pigse-gestion-documental-fecha-limite-guardar',
       $q$SELECT * FROM pigse.fn_gestion_documental_fecha_limite_guardar(
                public.fn_get_pigse_usuario_id(:CONTEXT.USER_ID::BIGINT),
                CAST(:CONTEXT.EMAIL AS VARCHAR),
                CAST(:BODY.FECHALIMITE AS DATE)
            )$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/fecha-limite', 'SELECT', 'PATCH',
       '{"BODY.FECHALIMITE": "DATE"}'::jsonb,
       'V522: fija (o quita, con NULL) la fecha limite global.'
  FROM public.microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM public.query WHERE uuid = 'pigse-gestion-documental-fecha-limite-guardar');

INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                          path_template, execution_mode, http_method, param_types, detail)
SELECT 'pigse-gestion-documental-excepcion-guardar',
       $q$SELECT * FROM pigse.fn_gestion_documental_excepcion_guardar(
                public.fn_get_pigse_usuario_id(:CONTEXT.USER_ID::BIGINT),
                CAST(:CONTEXT.EMAIL AS VARCHAR),
                CAST(:PARAM.ESTABLECIMIENTO AS BIGINT),
                CAST(:BODY.FECHALIMITE AS DATE)
            )$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/fecha-limite/excepciones/:ESTABLECIMIENTO', 'SELECT', 'PUT',
       '{"PARAM.ESTABLECIMIENTO": "INTEGER", "BODY.FECHALIMITE": "DATE"}'::jsonb,
       'V522: fija la fecha limite propia de UN establecimiento (excepcion a la global).'
  FROM public.microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM public.query WHERE uuid = 'pigse-gestion-documental-excepcion-guardar');

INSERT INTO public.query (uuid, query, type, public_end, captcha, microservice_id,
                          path_template, execution_mode, http_method, param_types, detail)
SELECT 'pigse-gestion-documental-excepcion-eliminar',
       $q$SELECT * FROM pigse.fn_gestion_documental_excepcion_eliminar(
                public.fn_get_pigse_usuario_id(:CONTEXT.USER_ID::BIGINT),
                CAST(:CONTEXT.EMAIL AS VARCHAR),
                CAST(:PARAM.ESTABLECIMIENTO AS BIGINT)
            )$q$,
       'postgres', false, false, m.id_microservice,
       '/documentos/fecha-limite/excepciones/:ESTABLECIMIENTO', 'SELECT', 'PATCH',
       '{"PARAM.ESTABLECIMIENTO": "INTEGER"}'::jsonb,
       'V522: saca la excepcion de un establecimiento -- vuelve a regirse por la global.'
  FROM public.microservice m WHERE m.serviceid = 'pigse'
   AND NOT EXISTS (SELECT 1 FROM public.query WHERE uuid = 'pigse-gestion-documental-excepcion-eliminar');

INSERT INTO public.role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM public.query q
 CROSS JOIN public.role ro
 WHERE q.uuid = 'pigse-gestion-documental-fecha-limite-obtener'
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-RECTOR', 'PIGSE-SECRETARIO', 'PIGSE-SECRETARIA_TERRITORIAL')
   AND NOT EXISTS (SELECT 1 FROM public.role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

INSERT INTO public.role_query (query_id, role_id)
SELECT q.id_query, ro.id_role
  FROM public.query q
 CROSS JOIN public.role ro
 WHERE q.uuid IN ('pigse-gestion-documental-fecha-limite-guardar',
                   'pigse-gestion-documental-excepcion-guardar',
                   'pigse-gestion-documental-excepcion-eliminar')
   AND ro.name IN ('PIGSE-ADMINISTRADOR', 'PIGSE-SECRETARIA_TERRITORIAL')
   AND NOT EXISTS (SELECT 1 FROM public.role_query rq WHERE rq.query_id = q.id_query AND rq.role_id = ro.id_role);

-- ---------------------------------------------------------------------------
-- 9. Verificación.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    v_endpoints INTEGER;
    v_grants_lectura INTEGER;
    v_grants_escritura INTEGER;
BEGIN
    SELECT count(*) INTO v_endpoints FROM public.query
     WHERE uuid IN ('pigse-gestion-documental-fecha-limite-obtener',
                     'pigse-gestion-documental-fecha-limite-guardar',
                     'pigse-gestion-documental-excepcion-guardar',
                     'pigse-gestion-documental-excepcion-eliminar');

    SELECT count(*) INTO v_grants_lectura FROM public.role_query rq
      JOIN public.query q ON q.id_query = rq.query_id
     WHERE q.uuid = 'pigse-gestion-documental-fecha-limite-obtener';

    SELECT count(*) INTO v_grants_escritura FROM public.role_query rq
      JOIN public.query q ON q.id_query = rq.query_id
     WHERE q.uuid IN ('pigse-gestion-documental-fecha-limite-guardar',
                       'pigse-gestion-documental-excepcion-guardar',
                       'pigse-gestion-documental-excepcion-eliminar');

    IF v_endpoints <> 4 THEN
        RAISE EXCEPTION 'V522 fallo: se esperaban 4 endpoints nuevos, hay %', v_endpoints;
    END IF;
    IF v_grants_lectura <> 4 THEN
        RAISE EXCEPTION 'V522 fallo: se esperaban 4 grants de lectura, hay %', v_grants_lectura;
    END IF;
    IF v_grants_escritura <> 6 THEN
        RAISE EXCEPTION 'V522 fallo: se esperaban 6 grants de escritura (3 endpoints x 2 roles), hay %', v_grants_escritura;
    END IF;

    RAISE NOTICE 'V522 OK: % endpoints, % grants lectura, % grants escritura.', v_endpoints, v_grants_lectura, v_grants_escritura;
END $$;
