-- ===========================================================================
-- V523 - COMMENT de funciones cuyas migraciones de origen se recortaron
-- (V349, V419). Las reescrituras vigentes (V491, V490) no traen
-- COMMENT; se copia literal.
-- ===========================================================================

SET search_path TO academico_test, public;

COMMENT ON FUNCTION academico_test.fn_informe_historial_listar(BIGINT, BIGINT[], BIGINT[], INTEGER, INTEGER)
    IS 'El modal de historial del modulo de informes: una fila por GUARDADO -- la tarjeta -- de mas reciente a mas antiguo, con FECHA aparte del MOMENTO para que el front agrupe por dia ("Hoy", "Ayer", "07/08/2026") sin recalcularlo. Cada fila trae grupo, asignatura (NULL = se guardo el informe completo, con valor = una sola asignatura desde la planilla), periodo, QUIEN lo hizo y el detalle de los estudiantes en JSONB con nombre, documento, promedio y cuantas asignaturas se le escribieron. EL CONTEO ES POR ESTUDIANTE, no por nota: un estudiante guardado es un cambio, de modo que guardar un curso de 30 son 30 cambios y no 360 como habria dado contar cada calificacion. SOLO APARECEN LOS DIAS CON MOVIMIENTO y no hace falta filtrarlo: el historial solo tiene filas de guardados que escribieron algo (V348), asi que un dia sin cambios no produce filas. El PROMEDIO del detalle viene copiado del momento del guardado y NO se recalcula al consultar: el historial dice que paso ese dia, y si despues alguien vuelve a consolidar, la entrada vieja debe seguir mostrando lo que mostro entonces. Sin parametros devuelve el ano lectivo en curso dentro del alcance del usuario, que es lo que hace la pantalla al abrirse; p_fk_tgrupos y p_fk_periodos_evaluacion solo ACOTAN y son opcionales -- a diferencia de las dos alertas, donde el grupo es obligatorio porque hablan de "los grupos seleccionados", mientras el historial es una bitacora que tiene sentido ver completa. Replica el bypass de niveles 0 y 1 que fn_usuario_ee_accesibles no trae: sin eso un super admin veria el historial vacio, que se lee como "nunca se guardo nada" en vez de "no tienes permiso". NO devuelve flecha de subida o bajada: un guardado abarca varios estudiantes y a unos les puede subir la nota y a otros bajarsela, asi que una sola flecha para el conjunto seria una afirmacion que los datos no sostienen. Gate: INFORMES/VER como capability, sin alcance de objeto, porque el historial no es de un objeto concreto.';

COMMENT ON FUNCTION academico_test.fn_informe_grupos_listar(BIGINT, BIGINT, INTEGER, BIGINT, VARCHAR)
    IS 'Los grupos del periodo academico que resuelven (sede, año, jornada), para la lista de grupos de la pantalla de informes. Existe porque esa lista se llenaba con fn_docente_grupos_listar (GET /planeador/docentes/grupos), que asserta PLANEADOR/VER -- de modo que un usuario con INFORMES y sin PLANEADOR no podia abrir la pantalla -- y que ademas solo devuelve los grupos donde EL DOCENTE dicta, con lo cual un rector, una secretaria o un coordinador no veian ninguno; y los informes son sobre todo para ellos, porque el docente ya tiene su vista de calificar y los boletines no los genera el. Aqui no se filtra por quien dicta: quien puede ver que grupos lo decide el permiso INFORMES/VER con alcance de sede y jornada, que se configura por rol y por usuario. NO filtra por la jornada del grupo aunque TGRUPO tenga la suya: de los 5.339 grupos activos, 5.277 no coinciden con la del periodo academico, porque en los años viejos el periodo se creaba como "Completa" y la jornada real vivia en el grupo -- filtrar dejaria los años anteriores casi vacios. Esa jornada se devuelve como columna, que es lo util. Devuelve ademas el conteo de matriculas activas y el director de grupo cuando lo hay: son lo que permite elegir el grupo correcto sin abrirlo. El alcance y la existencia del periodo los valida fn_informe_periodo_academico_resolver (42501 / P0002). V419.';
