-- V88 — tabla de sesión web real, para reemplazar el heurístico
-- sintético de /audits/* (agrupar por gaps de 30 min sobre app_user)
-- por sesiones reales correlacionadas al `familyId` de
-- RefreshTokenStore (un UUID por login, estable a través de cada
-- rotación de refresh token — ver JsonLoginFilter/RefreshController).
--
-- NO reutiliza academico_test.TSESION: esa tabla es un vestigio del
-- esquema Oracle original (fecha_ingreso/fecha_salida DATE,
-- hora_ingreso/hora_salida VARCHAR(80) sin correlación a ningún
-- token) — nada en el código actual la escribe. Forzar el diseño de
-- sesión web ahí habría significado repurpuse-ar columnas pensadas
-- para asistencia manual.
--
-- fk_tusuario es NULLABLE a propósito: un login válido no garantiza
-- una fila en academico_test.TUSUARIO (cuentas admin/SSO puras,
-- o cuentas recién creadas antes de que su fila académica exista).
-- SessionTrackingService omite el INSERT cuando el puente
-- public.fn_get_academico_usuario_id devuelve NULL — no tiene
-- sentido una fila de sesión sin nada que correlacionar en
-- academico_test.
--
-- Vive en academico_test (no public) para heredar automáticamente
-- trg_audit_ctx vía el mismo mecanismo genérico que audita cualquier
-- otra tabla del esquema — el INSERT en login y el UPDATE en cierre
-- quedan en auditoria.audit_log sin lógica de trigger nueva.
CREATE TABLE IF NOT EXISTS academico_test.tsesion_web (
    pk_tsesion_web BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_tusuario    BIGINT REFERENCES academico_test.tusuario (pk_tusuario),
    -- UUID de RefreshTokenStore.mint(), sin guiones (mismo formato
    -- que JsonLoginFilter ya genera). Único: una fila de sesión por
    -- familia de refresh token.
    family_id      VARCHAR(64) NOT NULL,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at       TIMESTAMPTZ,
    -- 'logout' (RefreshController.logout) | 'reuse_detected'
    -- (RefreshOutcome.ReuseDetected — token robado/repetido, señal de
    -- seguridad distinta de un cierre voluntario) | 'expired'
    -- (SessionReaperService — nadie llamó a /auth/logout, el refresh
    -- token simplemente caducó en Redis a los 30 días sin que
    -- ningún código de aplicación se enterara).
    close_reason   VARCHAR(20)
        CHECK (close_reason IS NULL OR close_reason IN ('logout', 'reuse_detected', 'expired')),
    CONSTRAINT uq_tsesion_web_family UNIQUE (family_id)
);

COMMENT ON TABLE academico_test.tsesion_web IS
    'Sesión web real (login->logout/expiración), correlacionada al family_id '
    'de RefreshTokenStore. Fuente de /audits/* -- reemplaza el heurístico '
    'sintético de gaps de 30 min sobre app_user.';

-- Usado por SessionReaperService para encontrar sesiones abiertas
-- sin escanear toda la tabla.
CREATE INDEX IF NOT EXISTS idx_tsesion_web_open
    ON academico_test.tsesion_web (family_id) WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tsesion_web_usuario
    ON academico_test.tsesion_web (fk_tusuario);

-- V26 instaló trg_audit_ctx sobre las tablas que existían EN ESE
-- MOMENTO -- una tabla nueva necesita su propio CREATE TRIGGER
-- explícito, mismo patrón que V26 usa para todo academico_test.
CREATE TRIGGER trg_audit_ctx
    BEFORE INSERT OR UPDATE OR DELETE ON academico_test.tsesion_web
    FOR EACH STATEMENT EXECUTE FUNCTION academico_test.fn_audit_ctx();

-- cdc_pub NO fue creada con FOR ALL TABLES (puballtables=false,
-- confirmado en el Postgres local) -- es una lista explícita de
-- tablas que NO se actualiza sola cuando aparece una tabla nueva en
-- el esquema, a diferencia de lo que el DO block de trigger-install
-- de V26 sí hace automáticamente. Sin esta línea, trg_audit_ctx
-- sigue emitiendo el mensaje lógico con normalidad (el trigger no
-- sabe nada de publicaciones), pero Debezium nunca ve el INSERT/
-- UPDATE de esta tabla -- ni como fila propia (no tiene datos de
-- negocio que auditar por sí sola) ni, más importante, como el
-- mensaje audit_ctx que dispara. Encontrado en vivo: sin esto, la
-- fila de tsesion_web se crea perfecto en Postgres pero JAMÁS
-- aparece en auditoria.audit_log.
ALTER PUBLICATION cdc_pub ADD TABLE academico_test.tsesion_web;
